tendermint/tendermint

- docs/.vuepress/config.js
- docs/package-lock.json
- docs/package.json
docs.tendermint.com: `UA-51029217-11`
> Add GA for docs.tendermint.com

- CHANGELOG_PENDING.md
- README.md
https://github.com/tendermint/tendermint/issues/4111
> 4111 readme md white paper link

- CHANGELOG.md
- CHANGELOG_PENDING.md
- version/version.go
- update master with changelog from v0.32.8
- bump `tm-version` in `version.go`
> Update master with release/v0.32.8 details

- docs/app-dev/abci-cli.md
- change grants to funding for abci server
> docs: update wording

- abci/README.md
> Fixed typo

- CHANGELOG_PENDING.md
- Makefile
- Vagrantfile
- consensus/wal.go
- docs/spec/blockchain/blockchain.md
- rpc/swagger/swagger.yaml
- tools.mk
- types/block.go
- types/block_meta.go
- types/events.go
Fixes https://github.com/tendermint/tendermint/issues/4136
Fixes https://github.com/tendermint/tendermint/issues/4166
> Various fixes

- docs/architecture/adr-043-blockchain-riri-org.md
Bring ADR-043 up to date with links to the implementation PRs.
> [adr] ADR 043 updates

- p2p/pex/pex_reactor.go
- p2p/switch_test.go
> p2p: extract maxBackoffDurationForPeer func and remove 1 test 

- CHANGELOG_PENDING.md
- docs/tendermint-core/using-tendermint.md
https://github.com/tendermint/tendermint/pull/4205
> docs: add flag documentation

- CHANGELOG_PENDING.md
- consensus/types/round_state_test.go
> consensus/types: fix BenchmarkRoundStateDeepCopy panics

- CHANGELOG_PENDING.md
- consensus/types/round_state.go
- rpc/swagger/swagger.yaml
I have added `proposer` in `consensus_state` RPC method.
Fixes: #2741
> rpc: added proposer in consensus_state

- consensus/state.go
- types/block.go
- follow up to #4263
- when a commit is nil, then it should be counted as a missed commit
> metrics: add metric for when commit is nil

- CHANGELOG_PENDING.md
- consensus/metrics.go
- consensus/state.go
- docs/tendermint-core/metrics.md
> metrics: add metrics for specific validators

- consensus/state.go
before getting its address in recordMetrics
Refs https://github.com/tendermint/tendermint/pull/4294#discussion_r364347586
> cs: check if cs.privValidator is nil

- CHANGELOG_PENDING.md
- cmd/tendermint/commands/lite.go
- lite/doc.go
- lite2/client.go
- lite2/proxy/proxy.go
- lite2/verifier.go
Refs https://github.com/tendermint/tendermint/issues/1771
> cmd/lite: switch to new lite2 package

- CHANGELOG.md
> changelog: add 0.32.9 changelog to master

- CHANGELOG_PENDING.md
- rpc/core/blocks.go
- fixes #4319
- check if block meta is nil
> rpc: check nil blockmeta

- rpc/core/abci.go
- rpc/core/blocks.go
- rpc/core/consensus.go
- rpc/core/events.go
- rpc/core/evidence.go
- rpc/core/health.go
- rpc/core/mempool.go
- rpc/core/net.go
- rpc/core/status.go
- rpc/core/tx.go
> rpc: PR#4320 follow up

- lite2/client.go
- lite2/client_test.go
- lite2/example_test.go
- lite2/provider/mock/mock.go
> lite2: improve auto update

- lite2/client.go
> lite2: rename alternative providers to witnesses

- lite2/store/db/db.go
> lite2: batch save & delete operations in DB store

- docs/architecture/adr-053-state-sync-prototype.md
Draft ADR describing a prototype for state sync (see #828).
> ADR-053: state sync prototype

- cmd/tendermint/commands/lite.go
- lite2/client.go
- lite2/client_test.go
- lite2/example_test.go
at least one witness is required
> lite2: make witnesses mandatory

- Makefile
- README.md
- docs/guides/go-built-in.md
- docs/guides/go.md
- docs/guides/java.md
- docs/guides/kotlin.md
- update proto path of libs/kv for fetching and remove GOPATH from go guides. 
- removed items from makefile that weren't used anymore
closes #4197
> docs: update guides proto paths

- lite2/client.go
As opposed to checking a random witness, all witnesses provided should be used as a reference against the header provided by the primary node. This increases security (at the tradeoff of speed) but also gives control to the user. The more witnesses provided, the more secure the lite client can be.
> lite2: check all witnesses

- README.md
- consensus/state.go
- crypto/README.md
- docs/architecture/adr-044-lite-client-with-weak-subjectivity.md
- docs/architecture/adr-045-abci-evidence.md
- docs/interviews/tendermint-bft.md
- docs/tendermint-core/secure-p2p.md
- p2p/README.md
- types/block.go
Updates broken links to `/docs/spec/...` with https://docs.tendermint.com/master/spec/.
> Fix broken /docs/spec links

- lite2/client.go
- lite2/client_test.go
and make maxRetryAttempts an option.
> lite2: validate TrustOptions, add NewClientFromTrustedStore

- lite2/client.go
- lite2/client_test.go
> lite2: return if there are no headers in RemoveNoLongerTrustedHeaders

- abci/types/types.proto
- crypto/merkle/merkle.proto
- libs/kv/types.proto
- rpc/grpc/types.proto
- types/proto3/block.proto
- proto linting
this came about after i fetched the proto files for use in the sdk.
Co-authored-by: Anton Kaliaev <anton.kalyaev@gmail.com>
> proto: minor linting to proto files

- lite2/provider/http/http.go
- lite2/provider/mock/deadmock.go
- lite2/provider/mock/mock.go
- lite2/provider/provider.go
- rpc/client/httpclient.go
before:
&http{AFBSD743A...}
after:
http{https://127.0.0.1:26657}
> lite2: improve string output of all existing providers

- lite2/client_test.go
cleaned up lite client tests by reducing repeated assignments and other redundant code.
> refactored lite client tests

- libs/autofile/autofile.go
- libs/autofile/autofile_test.go
- libs/autofile/group.go
- libs/autofile/group_test.go
Fixes #2649. Does this warrant a changelog entry?
> autofile: resolve relative paths

- CHANGELOG.md
- CHANGELOG_PENDING.md
- CONTRIBUTING.md
- version/version.go
> release: minor release 0.33.1

- UPGRADING.md
> upgrade: update upgrade.md for protobuf changes

- cmd/tendermint/commands/lite.go
- docs/tendermint-core/light-client-protocol.md
- lite2/doc.go
> docs: update Light Client Protocol page

- docs/architecture/README.md
- docs/architecture/adr-046-light-client-implementation.md
📝 [RENDERED](https://github.com/tendermint/tendermint/blob/4faa12f5978590d7fe50e7c061e06f335e941186/docs/architecture/adr-046-light-client-implementation.md)
Closes #2133
> adr: light client implementation

- go.mod
- go.sum
> dep: maunally bump dep

- CHANGELOG_PENDING.md
- rpc/client/rpc_test.go
- rpc/core/tx.go
> rpc: fix tx_search pagination with ordered results

- rpc/client/rpc_test.go
Fixes test nits from #4437 review.
> rpc: fix TxSearch test nits

- .circleci/config.yml
- test/p2p/circleci.sh
Runs IPv4 and IPv6 P2P tests in parallel, shaves 2-3 minutes off of build times.
> circleci: run P2P IPv4 and IPv6 tests in parallel

- CHANGELOG_PENDING.md
- types/validator_set.go
> types.VerifyCommitX: early return when +2/3 sigs are verified

- docs/architecture/adr-046-light-client-implementation.md
- lite2/client.go
- lite2/client_test.go
> lite2: cross-check first header and update tests

- blockchain/v2/reactor_test.go
> blockchain (v2): comment out TestReactorTerminationScenarios

- blockchain/v2/reactor_test.go
Add some inline notes for context of why test are commented out and not deleted.
Ref. #4482
> Async testing notes

- docs/architecture/adr-046-light-client-implementation.md
- lite2/client.go
- lite2/client_test.go
> lite2: return height as 2nd return param in TrustedValidatorSet

- lite2/example_test.go
- lite2/verifier.go
- lite2/verifier_test.go
Closes: https://github.com/tendermint/tendermint/issues/4488
______
> lite2: actually run example tests + clock drift

- .mergify.yml
Updates PRs before merging, required by branch protection.
> mergify: use strict merges

- state/txindex/kv/kv_test.go
Fixes feedback in https://github.com/tendermint/tendermint/pull/4418#discussion_r385629506. But mostly tests Mergify.
> test: simplify txsearch cancellation test

- cmd/tendermint/commands/lite.go
- docs/tendermint-core/light-client-protocol.md
- lite2/client.go
- lite2/client_test.go
- better logging
- chainID as an argument
- more examples
- auto update tries to update right away after Start
Closes: #XXX
______
> lite2: fix tendermint lite sub command

- docs/tendermint-core/using-tendermint.md
> docs: `tendermint node --help` dumps all supported flags

- rpc/core/pipe.go
- state/services.go
> rpc: remove BlockStoreRPC in favor of BlockStore

- cmd/tendermint/commands/run_node.go
Closes #4303
Before:
```
TMHOME="/Users/daniel/go/src/github.com/tendermint/thome" tendermint node --proxy_app=unix:///Users/daniel/go/src/github.com/kvstore/example.sock
ERROR: 1 error(s) decoding:
* error decoding 'consensus.create_empty_blocks_interval': time: invalid duration
```
After:
```
$ TMHOME=/tmp ./build/tendermint node --proxy_app=kvstore
ERROR: failed to create node: Couldn't read GenesisDoc file: open /tmp/config/genesis.json: no such file or directory
```
______
> cmd: show useful error when tm not initialised

- docs/tendermint-core/running-in-production.md
- docs/tools/README.md
- docs/tools/debugging.md
> docs: write about debug kill and dump

- CHANGELOG_PENDING.md
- cmd/tendermint/commands/debug/dump.go
- cmd/tendermint/commands/debug/kill.go
> cmd: fix debug kill and change debug dump archive filename format

- docs/architecture/README.md
- docs/architecture/adr-047-handling-evidence-from-light-client.md
[RENDERED](https://github.com/tendermint/tendermint/blob/611c5510837b1e661f6e7f9684514f7c337f7a04/docs/architecture/adr-047-handling-evidence-from-light-client.md)
Closes https://github.com/tendermint/tendermint/issues/4213 and https://github.com/tendermint/tendermint/issues/4182
> adr-047: evidence handling

- README.md
> readme: add discord to readme

- CONTRIBUTING.md
CONTRIBUTING: include instructions for installing protobuf
> CONTRIBUTING: include instructions for installing protobuf

- CHANGELOG_PENDING.md
- libs/kv/kvpair.go
- libs/kv/result.go
- libs/kv/types.pb.go
- libs/kv/types.proto
- libs/kv/typespb_test.go
This type does not seem to be used. See also: https://github.com/tendermint/tendermint/pull/4466#discussion_r389352283
> libs/kv: remove unused type KI64Pair

- CHANGELOG.md
- CHANGELOG_PENDING.md
- version/version.go
- release candidate for 0.33.2
- will wait for tm-db to be released
> release: 0.33.2

- CHANGELOG.md
- CHANGELOG_PENDING.md
Closes: #4548
Updates the CHANGELOG with the changes from the PR
______
> p2p: Update Changelog with ban list PR - #4548

- types/evidence.go
> fix: spelling of comment

- go.sum
> deps: run go mod tidy

- CHANGELOG.md
- README.md
- docs/tools/README.md
some repos moved orgs
interchainio -> informalsystems
______
> docs: link fixing

- .github/workflows/action.yml
Closes: #4599
change the link checker to run daily instead of every pull request
______
> docs: link scheduler cron job

- CONTRIBUTING.md
- README.md
- STYLE_GUIDE.md
Took the go coding standard and shifted it to this repo, adapting it by adding the uber style guidelines and adding my own section regarding code structure.
The `STYLE_GUIDE.md` is linked to in the contribution section of the readme.
Changed the chat link from riot to Discord. 
Let me know of any other suggestions you have for this.
You can open the rendered version [here](https://github.com/tendermint/tendermint/blob/1af3bf88c3dcbd39f321916b3f3c9f1ad60c397c/STYLE_GUIDE.md)
______
> Update style guide and add it to contributors section

- CHANGELOG_PENDING.md
- docs/architecture/adr-046-light-client-implementation.md
- lite2/client.go
- lite2/verifier.go
- lite2/verifier_test.go
> lite2: make maxClockDrift an option

- CHANGELOG_PENDING.md
- abci/example/kvstore/persistent_kvstore.go
- evidence/reactor_test.go
- rpc/client/rpc_test.go
- types/evidence.go
- types/evidence_test.go
- types/protobuf_test.go
- types/vote.go
- remove Pubkey from DuplicateVoteEvidence
- this pr is meant to unblock block to proto work
ref #4580
______
> evidence: remove pubkey from DuplicateVoteEvidence

- CHANGELOG_PENDING.md
- abci/example/kvstore/persistent_kvstore.go
- crypto/README.md
- crypto/ed25519/ed25519.go
- crypto/encoding/amino/amino.go
- crypto/encoding/amino/encode_test.go
- crypto/multisig/codec.go
- crypto/multisig/threshold_pubkey.go
- crypto/multisig/threshold_pubkey_test.go
- crypto/secp256k1/secp256k1.go
- crypto/secp256k1/secp256k1_cgo.go
- crypto/secp256k1/secp256k1_cgo_test.go
- crypto/secp256k1/secp256k1_nocgo.go
- crypto/secp256k1/secp256k1_test.go
- crypto/sr25519/codec.go
- crypto/sr25519/privkey.go
- crypto/sr25519/pubkey.go
- p2p/conn/secret_connection.go
- p2p/conn/secret_connection_test.go
- privval/file_test.go
- privval/socket_listeners.go
- privval/socket_listeners_test.go
- rpc/client/rpc_test.go
- tools/tm-signer-harness/internal/test_harness.go
- tools/tm-signer-harness/main.go
- types/protobuf.go
- types/validator_set_test.go
> keys: remove suffixes

- config/config.go
> config: allow fastsync.version = v2

- lite2/provider/http/http.go
- lite2/provider/http/http_test.go
> Default to http scheme in lite2 provider.New

- .github/workflows/lint.yaml
- blockchain/v2/reactor_test.go
- lite2/client.go
- state/execution.go
- state/store_test.go
- types/validator_set_test.go
- golangci is being deprecated on the 15th, this is in perparation of that
- also seems golangci hasnt been running on the prs 🌝 
______
~ - [ ] Wrote tests ~
~ - [ ] Updated CHANGELOG_PENDING.md ~
~ - [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work. ~
~  - [ ] Updated relevant documentation (`docs/`) and code comments ~
> lint: add review dog

- CHANGELOG.md
- CHANGELOG_PENDING.md
- mempool/reactor.go
- mempool/reactor_test.go
- node/node.go
- p2p/transport.go
- p2p/transport_test.go
- version/version.go
This brings the changes from security releases 0.32.10 and 0.33.3
over to master.
> update master with security patches

- blockchain/v2/reactor.go
- blockchain/v2/reactor_test.go
Fixes an issue reported in https://github.com/tendermint/tendermint/issues/4595#issuecomment-612667441.
Not sure if this is sufficient to fully remove the reactor, but it fixes the immediate problem.
______
> blockchain/v2: allow setting nil switch, for CustomReactors()

- CHANGELOG.md
> changelog: add entries from secruity releases

- lite2/rpc/client.go
> lite2: verify ConsensusHash in rpc client

- docs/tendermint-core/using-tendermint.md
- types/params.go
> docs: mention unbonding period in MaxAgeNumBlocks/MaxAgeDuration

- SECURITY.md
Updates our Security Policy with takeaways from Security Advisory 
Lavender and the associated security releases. 
Thank you to @melekes and @alessio for reviewing earlier versions
of this document.
> revise security policy

- .github/PULL_REQUEST_TEMPLATE.md
- this pr add a check box for making sure labels are added to PRs
______
> template: add labels to pr template

- docs/package-lock.json
- docs/package.json
* Added "Edit this page" box
* Fixed link styles
* Fixed build-time errors
* Updated VuePress and dependencies
Closes: #XXX
______
> Updated docs website

- consensus/reactor_test.go
- evidence/pool_test.go
- evidence/reactor_test.go
- evidence/store_test.go
- state/execution_test.go
- state/validation_test.go
- types/block_test.go
- types/evidence.go
- types/evidence_test.go
- 1 param NewMockEvidence is entirely unused
______
> evidence: remove unused param

- proto/crypto/keys/types.pb.go
- proto/evidence/msgs.pb.go
- proto/libs/bits/types.pb.go
- proto/state/types.pb.go
- proto/types/block.pb.go
- proto/types/evidence.pb.go
- proto/types/params.pb.go
- proto/types/types.pb.go
- proto/types/validator.pb.go
- proto/version/version.pb.go
- regenerate proto using docker
- on proto breakage a different compiler is used to generate some more helper functions, on master the same one os not used, reverting back to the one used on master to undo further confusion till proto-breakage is merged
> proto: regenerate proto

- CHANGELOG_PENDING.md
- lite2/provider/http/http.go
- lite2/provider/http/http_test.go
Fixes #4739, kind of. See #4740 for the proper fix.
---
> lite: fix HTTP provider error handling

- CHANGELOG_PENDING.md
- blockchain/v2/reactor.go
- blockchain/v2/reactor_test.go
Not thoroughly tested, but seems to work. Will do further testing as this is integrated with state sync.
Fixes #4688.
> blockchain/v2: respect fast_sync option

- .github/workflows/tests.yml
check out code prior to running git diff
Closes: #XXX
> ci: checkout before git diff

- config/config.go
> linting: remove unused variable

- .github/workflows/lint.yaml
- .golangci.yml
- abci/types/application.go
- blockchain/v2/reactor.go
- blockchain/v2/routine.go
- consensus/wal.go
- crypto/ed25519/ed25519.go
- crypto/merkle/result.go
- crypto/xchacha20poly1305/xchachapoly.go
- libs/kv/result.go
- libs/pubsub/query/peg.go
- mempool/cache_test.go
- statesync/snapshots_test.go
- types/block_test.go
- enable nolintlint
- disable linting on tests
Closes: #XXX
> lint: enable nolintlinter, disable on tests

- state/validation.go
- types/block.go
- types/validator_set.go
plus make sure LastCommit is always non-nil
> types: remove extra validation in VerifyCommit

- .github/workflows/lint.yaml
- .golangci.yml
- cmd/tendermint/commands/root_test.go
- libs/cli/helper.go
- libs/tempfile/tempfile_test.go
- statesync/chunks.go
- tools/tm-signer-harness/main.go
switch to official golangci linter & fix linting issues
> ci: switch to official linter

- rpc/swagger/swagger.yaml
remove duplicate BlockID in swagger files
Closes: #XXX
> swagger: remove duplicate blockID 

- CHANGELOG_PENDING.md
- lite/proxy/proxy.go
- node/node.go
- rpc/core/abci.go
- rpc/core/blocks.go
- rpc/core/blocks_test.go
- rpc/core/consensus.go
- rpc/core/dev.go
- rpc/core/env.go
- rpc/core/env_test.go
- rpc/core/events.go
- rpc/core/evidence.go
- rpc/core/mempool.go
- rpc/core/net.go
- rpc/core/net_test.go
- rpc/core/status.go
- rpc/core/tx.go
> rpc: use a struct to wrap all the global objects

- mempool/reactor.go
- mempool/reactor_test.go
> mempool: do not launch broadcastTxRoutine if Broadcast is off

- scripts/json2wal/main.go
- scripts/wal2json/main.go
> wal2json: remove Amino imports

- .github/workflows/lint.yaml
- blockchain/v1/reactor_fsm.go
- consensus/state.go
- lite/proxy/proxy.go
- lite2/provider/http/http_test.go
- mempool/clist_mempool.go
- node/node.go
- p2p/node_info_test.go
- p2p/pex/pex_reactor.go
- rpc/client/rpc_test.go
- rpc/jsonrpc/client/ws_client.go
- state/state_test.go
- store/store.go
- store/store_test.go
> lint: various fixes

- .github/workflows/lint.yaml
- .github/workflows/proto.yml
- README.md
by adding paths the ci job wont run if the files aren't touched. this is a change from before where they would run to see if there were changes
Closes: #XXX
> ci: add paths 

- p2p/transport_test.go
Refs https://github.com/tendermint/tendermint/issues/4854
> p2p tests: TestTransportMultiplexAcceptNonBlocking and TestTransportMultiplexConnFilterTimeout

- CHANGELOG_PENDING.md
- abci/server/grpc_server.go
- abci/server/socket_server.go
> abci/server: print panic & stack trace to STDERR if logger is not set

- .circleci/config.yml
- .github/workflows/lint.yaml
- .github/workflows/net.yml
- .github/workflows/proto.yml
- .github/workflows/tests.yml
This PR moves `localnet` from circleci to github actions.
Would we like to add longer lived nets?
Closes: #XXX
> ci: migrate localnet to github actions

- test/docker/Dockerfile
> test: fix p2p test build breakage caused by Debian testing

- CHANGELOG_PENDING.md
- DOCKER/Dockerfile.build_c-amazonlinux
- Makefile
- docs/introduction/install.md
- docs/tendermint-core/running-in-production.md
> Makefile: parse TENDERMINT_BUILD_OPTIONS (#4738)

- abci/example/example_test.go
Fixes these test failures:
```
=== RUN   TestKVStore
I[2020-05-25|13:32:31.303] Starting ABCIServer service                  module=abci-server impl=ABCIServer
TestKVStore: example_test.go:48: 
Error Trace:    example_test.go:48
example_test.go:28
Error:          Received unexpected error:
listen unix test.sock: bind: address already in use
Test:           TestKVStore
Messages:       Error starting socket server
--- FAIL: TestKVStore (0.00s) 
```
> test/abci: use random socket names to avoid collisions

- CHANGELOG_PENDING.md
- blockchain/v2/reactor.go
- blockchain/v2/reactor_test.go
- blockchain/v2/routine.go
Backport of  #4761 and #4772. Single PR to save on test time, will rebase-merge.
> blockchain/v2: backport fixes

- rpc/client/rpc_test.go
Fixes the following test race condition:
```
=== RUN   TestAppCalls
TestAppCalls: rpc_test.go:216:
Error Trace:    rpc_test.go:216
Error:          Expected value not to be nil.
Test:           TestAppCalls
--- FAIL: TestAppCalls (2.20s)
```
> rpc/test: fix test race in TestAppCalls

- CHANGELOG_PENDING.md
- types/validator_set.go
- types/validator_set_test.go
in VerifyCommitTrusting
Closes #4755
> types: return an error if voting power overflows

- lite2/client.go
- lite2/client_test.go
fix bug with assigning the new pivot height during bisection
> lite2: fix pivot height during bisection (#4850)

- rpc/client/rpc_test.go
Fixes race conditions causing the following test failures:
```
=== RUN   TestUnconfirmedTxs
TestUnconfirmedTxs: rpc_test.go:342:
Error Trace:    rpc_test.go:342
Error:          Not equal:
expected: 1
actual  : 0
Test:           TestUnconfirmedTxs
TestUnconfirmedTxs: rpc_test.go:343:
Error Trace:    rpc_test.go:343
Error:          Not equal:
expected: 1
actual  : 0
Test:           TestUnconfirmedTxs
TestUnconfirmedTxs: rpc_test.go:345:
Error Trace:    rpc_test.go:345
Error:          Not equal:
expected: types.Txs{types.Tx{0x39, 0x44, 0x4d, 0x6c, 0x4b, 0x66, 0x46, 0x78, 0x3d, 0x45, 0x33, 0x33, 0x68, 0x47, 0x6e, 0x79, 0x58}}
actual  : types.Txs(nil)
Diff:
--- Expected
+++ Actual
@@ -1,4 +1,2 @@
-(types.Txs) (len=1) {
- (types.Tx) (len=17) Tx{39444D6C4B6646783D45333368476E7958}
-} …
```
> rpc/test: wait for mempool CheckTx callback

- p2p/switch.go
https://github.com/tendermint/tendermint/pull/4893#discussion_r430940912
> p2p: remove nil guard

- CHANGELOG_PENDING.md
- types/validator.go
- types/validator_set.go
- types/validator_set_test.go
- types/validator_test.go
Implemented `ValidateBasic()` functions for both Validator and ValidatorSet and corresponding tests
Closes: #4904
> types: Validator and Validator Sets have ValidateBasic() funcs

- CHANGELOG.md
- CHANGELOG_PENDING.md
- version/version.go
Final step of a point release.
> CHANGELOG: update to reflect 0.33.5

- rpc/client/event_test.go
I was able to reproduce this non-determinism locally
After increasing the timeout to 8 seconds from 5 I was not able to reproduce it
Closes: #2856
> rpc: increase waitForEventTimeout to 8 seconds

- CHANGELOG.md
> CHANGELOG: add 0.32.12 changelog entry

- CHANGELOG_PENDING.md
- light/provider/http/http.go
- light/proxy/routes.go
- light/rpc/client.go
- rpc/client/http/http.go
- rpc/client/interface.go
- rpc/client/local/local.go
- rpc/client/mock/client.go
- rpc/client/rpc_test.go
- rpc/core/consensus.go
- rpc/core/env.go
- rpc/core/env_test.go
- rpc/core/mempool.go
- rpc/core/tx.go
- rpc/swagger/swagger.yaml
Closes #4942
affected endpoints:
- /validators
- /tx_search
> rpc/core: return an error if `page=0`

- rpc/swagger/index.html
> fix swagger page

- rpc/swagger/index.html
- rpc/swagger/swagger.yaml
try to further resolve rpc docs issue
Closes: #XXX
> swagger: define version

- CHANGELOG_PENDING.md
- abci/example/kvstore/persistent_kvstore.go
- crypto/ed25519/ed25519.go
- crypto/ed25519/encoding.go
- crypto/encoding/amino/encode_test.go
- crypto/encoding/codec.go
- crypto/secp256k1/encoding.go
- crypto/secp256k1/secp256k1.go
- crypto/secp256k1/secp256k1_test.go
- crypto/sr25519/encoding.go
- crypto/sr25519/privkey.go
- crypto/sr25519/pubkey.go
- privval/file_test.go
- rpc/client/evidence_test.go
- tools/tm-signer-harness/internal/test_harness.go
- tools/tm-signer-harness/main.go
- types/block.go
- types/proto3_test.go
- types/protobuf.go
- types/protobuf_test.go
- types/validator_set_test.go
> keys: change to []bytes for keys (#4634)

- crypto/merkle/simple_proof.go
- crypto/merkle/simple_tree.go
- crypto/merkle/simple_tree_test.go
- types/block.go
- types/block_meta.go
- types/block_test.go
- types/part_set.go
- types/part_set_test.go
- types/tx_test.go
adding in some more to/from methods/functions
Closes: #XXX
> proto: add more to/from

- CHANGELOG_PENDING.md
- blockchain/v2/io.go
- blockchain/v2/reactor.go
- blockchain/v2/reactor_test.go
See: https://github.com/tendermint/tendermint/pull/4969#pullrequestreview-425298225
> blockchain/v2: correctly set block store base in status responses

- README.md
> readme: add source graph badge

- UPGRADING.md
> UPGRADING.md: write about the LastResultsHash change

- CONTRIBUTING.md
- tools.mk
Update gogoproto tools cmd to download the correct version. I still need to update the docker container and test that they generate the same
Closes: #XXX
> tools: update gogoproto get cmd

- .github/workflows/tests.yml
This pr fixes the spacing of the if statement. It was working but throwing warnings. this aims to resolve that
Closes: #XXX
> ci: fix spacing of if statement

- types/block.go
- types/canonical.go
- types/proposal.go
- types/validator_set_test.go
- types/vote.go
- types/vote_set_test.go
> types: more test cases for TestValidatorSet_VerifyCommit

- types/block.go
- types/block_test.go
> types: reject blocks w/ ConflictingHeadersEvidence

- behaviour/doc.go
add a simple doc.go to behavior module
Closes: #XXX
> behaviour: add simple doc.go

- abci/example/kvstore/persistent_kvstore.go
- networks/remote/integration.sh
> abci/example/kvstore: decrease val power by 1 upon equivocation

- types/validator_set.go
- types/validator_set_test.go
Refs https://github.com/tendermint/tendermint/pull/4764#discussion_r446488731
also, multiplication using * should be more efficient.
> types: simplify safeMul

- docs/tendermint-core/using-tendermint.md
add extra warning about chainID
Closes: #XXX
> docs: add warning for chainid

- CHANGELOG.md
> changelog: note breaking change in the 0.33.6 release

- abci/types/types.pb.go
- proto/tendermint/abci/types/types.proto
- proto/tendermint/consensus/walmsgs.pb.go
- proto/tendermint/crypto/keys/types.pb.go
> abci/types: add comment for TotalVotingPower

- .github/workflows/stale.yml
adjustment of stale action settings, making it a tad more strict
Closes: #XXX
> adjust stale action settings

- DOCKER/Dockerfile
- DOCKER/docker-entrypoint.sh
Follow https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#entrypoint or https://success.docker.com/article/use-a-script-to-initialize-stateful-container-data to resolve #5082.
Also tackles #5086.
Closes: #5086
Closes: #5082
> Rework Docker image

- .github/workflows/coverage.yml
codecov is having issues on upload so upgrade to 1.0.7 where they claim it works better and dont fail ci on failure to upload coverage file
Closes: #XXX
> ci: try to fix codecov

- .github/workflows/coverage.yml
> ci: only run tests when go files are touched

- docs/guides/java.md
- docs/guides/kotlin.md
This pr modifies the needed proto files for the java and kotlin guides. 
Closes: #5034
> docs: modify needed proto files for guides

- .github/workflows/lint.yaml
- blockchain/msgs_test.go
- consensus/replay.go
- evidence/reactor.go
- p2p/pex/addrbook.go
- state/validation_test.go
- types/block_meta_test.go
- types/evidence_test.go
linter version fix and run make format to have all ci run
Closes: #XXX
> ci: version linter fix 

- light/client.go
- light/client_test.go
- light/errors.go
> light: return if target header is invalid

- privval/errors.go
- privval/retry_signer_client.go
- privval/signer_client.go
- privval/signer_client_test.go
> privval: if remote signer errors, don't retry

- blockchain/v0/reactor_test.go
- libs/timer/throttle_timer_test.go
- p2p/conn/connection_test.go
- p2p/transport_test.go
Hi,
While working on tendermint my colleague @jinmannwong fixed a few of the unit tests that we found to be flaky in our CI. We thought that you might find this useful, see below for comments.
> add fixes for flaky tests

- types/validator_set.go
Validatebasic on FromProto for validator set not ToProto
Closes: #XXX
> types: validatebasic on from proto

- docs/.vuepress/config.js
- docs/package-lock.json
1.0.169 changes: https://github.com/cosmos/vuepress-theme-cosmos/pull/84
- update newsletter signup form: zoho → mailerlite
- disable topbar banner
> Docs update

- rpc/swagger/swagger.yaml
- types/block.go
- types/part_set.go
- types/proposal.go
- types/validator.go
- types/validator_set.go
- types/vote.go
- types/vote_set.go
> docs: add more details on Vote struct from /consensus_state

- docs/tendermint-core/using-tendermint.md
- proto/tendermint/types/params.pb.go
- proto/tendermint/types/params.proto
> docs: document ConsensusParams

- rpc/swagger/swagger.yaml
Closes #2769
Spec PR: https://github.com/tendermint/spec/pull/125
> docs: document canonical field

- rpc/client/http/http.go
> rpc/client/http: log error

- CHANGELOG.md
> changelog: add v0.33.7 release

- CHANGELOG.md
add dates to changelog
Closes: #XXX
> changelog: add dates for release

- CHANGELOG.md
> changelog: add v0.32.13 release

- CHANGELOG_PENDING.md
- node/node.go
> node: don't attempt fast sync when InitChain sets self as only validator

- CHANGELOG.md
- version/version.go
Signed-off-by: Marko Baricevic <marbar3778@yahoo.com>## Description
Add changelog entry for 0.33.8
Closes: #XXX
> changelog: rc0/33.8

- CHANGELOG.md
- version/version.go
Signed-off-by: Marko Baricevic <marbar3778@yahoo.com>## Description
Merge RC into the release branch
Closes: #XXX
> rc -> release branch

- CHANGELOG.md
- version/version.go
> release: v0.33.8

- docs/architecture/README.md
- docs/architecture/adr-014-secp-malleability.md
- docs/architecture/adr-023-ABCI-propose-tx.md
- docs/architecture/adr-044-lite-client-with-weak-subjectivity.md
- docs/architecture/adr-045-abci-evidence.md
- docs/introduction/what-is-tendermint.md
- docs/networks/docker-compose.md
- docs/tendermint-core/how-to-read-logs.md
- docs/tutorials/go-built-in.md
- docs/tutorials/go.md
- docs/tutorials/java.md
- docs/tutorials/kotlin.md
Fix a bunch of old and broken links in markdown files.
> Fix some broken links

- docs/architecture/adr-056-proving-amnesia-attacks.md
Wanted to write down the short term decision for how amnesia attacks will be handled
> docs: update ADR 56 with short term amnesia solution

- libs/cmap/cmap_test.go
- libs/pubsub/pubsub_test.go
- p2p/upnp/upnp.go
fix golang 1.15 errors. 
Closes: #XXX
> fix go 1.15 errors 

- types/proposal.go
- types/vote.go
> types: comment on need for length prefixing

- UPGRADING.md
Add block pruning information to `upgrading.md`
Closes: #XXX
> docs: add block retention to upgrading.md

- crypto/encoding/codec.go
- proto/tendermint/crypto/keys.pb.go
- proto/tendermint/crypto/keys.proto
This type was used for json but was never removed once we migrated to tmjson. 
Closes: #XXX
> crypto: remove proto privatekey

- docs/.vuepress/config.js
- Algolia docsearch config (improved full-text doc search)
Closes: https://github.com/tendermint/tendermint/issues/5289
> docs: add algolia docsearch configs

- CHANGELOG_PENDING.md
- consensus/replay.go
> consensus: fix wrong proposer schedule for `InitChain` validators

- consensus/state_test.go
Brought back the tests that were accidentally removed when removing polc in #5319
> consensus: resurrect tests

- .github/workflows/net.yml
Fix short net runs
Closes: #XXX
> ci: fix net run

- proto/tendermint/types/evidence.pb.go
- proto/tendermint/types/evidence.proto
- state/validation.go
- types/block_test.go
- types/evidence.go
- types/evidence_test.go
Changed the interface and evidence types according to [adr 59](https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-059-evidence-composition-and-lifecycle.md)
> evidence: modify evidence types

- crypto/README.md
Reword the readme of the crypto package. 
Closes: #XXX
> crypto: reword readme

- rpc/openapi/openapi.yaml
> docs: document max entries for `/blockchain` RPC

- rpc/jsonrpc/server/http_server_test.go
Fixes a couple of test data races. `testing.T` is not concurrency-safe and should not be used in goroutines at all.
> rpc: fix test data races

- CHANGELOG_PENDING.md
- DOCKER/docker-entrypoint.sh
Fixes the Docker problems discussed in #4489.
> docker: fix incorrect time_iota_ms configuration

- CHANGELOG_PENDING.md
- consensus/reactor.go
- consensus/replay_test.go
- rpc/core/blocks_test.go
- rpc/core/status.go
- state/services.go
- store/store.go
- store/store_test.go
Fixes #5377 and comments in https://github.com/tendermint/tendermint/pull/4588#pullrequestreview-492236148.
> blockstore: fix race conditions when loading data

- config/config.go
- config/toml.go
- docs/tendermint-core/configuration.md
- light/example_test.go
- state/state_test.go
also, document consensus parameters.
https://forum.cosmos.network/t/consensus-timeouts-explained/1421
Closes #4489
> config: set time_iota_ms to timeout_commit in test genesis

- CHANGELOG_PENDING.md
Clean up some inconsistent formatting and missing PR numbers.
> changelog: minor tweaks

- README.md
Cleans up the grammar, removes out-of-date information, and reduces false promises.
> README: clean up README

- abci/example/kvstore/kvstore_test.go
- consensus/replay_test.go
While going through the code I saw these 2 spelling mistakes. Not a big deal but still worth fixing.
> Fixed "Genisis" and "Iniitalize" spelling mistakes

- codecov.yml
> codecov: disable annotations

- rpc/client/http/http.go
- state/validation.go
- state/validation_test.go
- types/block.go
- types/block_test.go
> state: more test cases for block validation

- rpc/client/rpc_test.go
- rpc/core/blocks.go
- rpc/openapi/openapi.yaml
> rpc/core: more docs and a test for /blockchain endpoint

- docs/tutorials/go-built-in.md
- docs/tutorials/go.md
Closes https://github.com/tendermint/tendermint/issues/5425
> docs: specify TM version in go tutorials

- consensus/common_test.go
- consensus/state.go
- consensus/state_test.go
- types/part_set.go
- types/part_set_test.go
> consensus: check block parts don't exceed maximum block bytes

- CHANGELOG_PENDING.md
- config/toml.go
> config: set statesync.rpc_servers when generating config file

- CHANGELOG_PENDING.md
- privval/signer_dialer_endpoint.go
> privval: allow passing options to NewSignerDialerEndpoint

- consensus/common_test.go
- consensus/state.go
- consensus/state_test.go
- types/part_set.go
- types/part_set_test.go
> consensus: block bytes into rc5 (#5431)

- CHANGELOG_PENDING.md
- privval/msgs.go
- privval/msgs_test.go
> privval: fix ping message encoding

- .github/workflows/e2e.yml
- test/e2e/README.md
- test/e2e/docker/Dockerfile
- test/e2e/runner/main.go
> test: add GitHub action for end-to-end tests

- CHANGELOG_PENDING.md
- crypto/encoding/codec.go
> fix RPC blockresults return (#5459) (#5463) 

- CHANGELOG.md
> changelog: prepare changelog for RC5

- CHANGELOG.md
- CHANGELOG_PENDING.md
update changelog with updates in rc5
Closes: #XXX
> update changelog for rc5

- .github/workflows/e2e-nightly.yml
- .github/workflows/e2e.yml
- test/e2e/runner/cleanup.go
> test: clean up e2e container volumes using a container

- CHANGELOG_PENDING.md
- statesync/stateprovider.go
> statesync: check all necessary heights when adding snapshot to pool

- .circleci/config.yml
- .github/workflows/docker.yml
migrate docker deployment from circle to github actions
Closes: #XXX
> ci: docker remove circleci and add github action 

- test/e2e/run-multiple.sh
> test: run remaining E2E testnets on run-multiple.sh failure

- test/e2e/runner/cleanup.go
- test/e2e/runner/setup.go
> test: tag E2E Docker resources and autoremove them

- CHANGELOG_PENDING.md
- state/tx_filter_test.go
- types/block.go
- types/block_test.go
> block: max commit size backport

- test/e2e/generator/generate.go
- test/e2e/networks/ci.toml
- test/e2e/pkg/testnet.go
- test/e2e/runner/main.go
- test/e2e/runner/start.go
- test/e2e/runner/wait.go
> test: backport E2E fixes

- abci/client/grpc_client.go
Fixes #5540, fixes #2965. This is a hack that patches over the problem, but really the whole async handling in gRPC should be redesigned, as should ReqRes callback dispatch.
Backport of #5556.
> abci/grpc: fix ordering of sync/async callback combinations (#5556)

- light/client.go
- light/detector.go
- light/detector_test.go
- light/errors.go
Closes #5445
Backport of #5538
> light: run detector for sequentially validating light client

- CHANGELOG.md
- CHANGELOG_PENDING.md
> CHANGELOG: update for RC6

- CHANGELOG.md
> CHANGELOG: fix accidental header move

- test/e2e/generator/generate.go
> test: remove misbehaviors from e2e generator

- .github/workflows/docker.yml
- set go version to 1.15.4
- run docker action in prs (it will not be deployed)
Closes: #XXX
> ci: fix docker deployment

- libs/os/os.go
- libs/os/os_test.go
- privval/signer_listener_endpoint.go
> libs/os: add test case for TrapSignal

- CHANGELOG_PENDING.md
- config/toml.go
- libs/autofile/autofile_test.go
- libs/fail/fail.go
- libs/os/os.go
- libs/os/os_test.go
- p2p/conn/secret_connection_test.go
- proxy/multi_app_conn.go
- types/genesis.go
Remove unused ReadFile (unused) and
WriteFile (almost unused, alias of ioutil.WriteFile).
Add testcases for Must{Read,Write}File.
> libs/os: remove unused aliases, add test cases

- go.mod
- go.sum
Bumps IAVL, which pulled in some other upgrades as well. I think they should be fine though.
> go.mod: upgrade iavl and deps

- abci/types/types.pb.go
- proto/tendermint/abci/types.proto
- proto/tendermint/version/types.pb.go
- proto/tendermint/version/types.proto
App version struct might have supposedly been used in ResponseInfo and ResponseEndBlock but was never actually implemented with other variables essentially taking it's purpose. Thus I am removing it
> remove unused app version struct

- privval/signer_listener_endpoint.go
> privval: reset pingTimer to avoid sending unnecessary pings (#5642)

- CHANGELOG.md
- CHANGELOG_PENDING.md
- rpc/jsonrpc/client/http_json_client.go
Backport #5661 to v0.34.0-rc7.
/cc @tessr
> Backport v0.34.0-rc7: #5661

- .github/workflows/tests.yml
- crypto/ed25519/ed25519.go
remove disabled cmd
Closes: #XXX
> ci: remove `add-path`

- blockchain/v0/reactor.go
- blockchain/v1/reactor.go
- blockchain/v2/reactor.go
- consensus/reactor.go
- evidence/reactor.go
- mempool/reactor.go
- p2p/base_reactor.go
- p2p/pex/pex_reactor.go
- statesync/reactor.go
> docs: warn developers about calling blocking funcs in Receive

- .github/workflows/tests.yml
- abci/example/kvstore/helpers.go
- abci/example/kvstore/persistent_kvstore.go
- abci/tests/server/client.go
- abci/types/pubkey.go
- crypto/encoding/codec.go
- privval/signer_requestHandler.go
- test/e2e/app/app.go
- test/e2e/app/config.go
- test/e2e/app/main.go
- test/e2e/pkg/manifest.go
- test/e2e/pkg/testnet.go
- test/e2e/runner/setup.go
- test/e2e/tests/evidence_test.go
- test/e2e/tests/validator_test.go
backport secp e2e failure fixes
Closes: #XXX
> e2e: secp backports

- CHANGELOG_PENDING.md
- libs/math/fraction.go
- libs/math/fraction_test.go
- light/verifier_test.go
- types/validator_set.go
> light: fractions to u64 

- CHANGELOG.md
- CHANGELOG_PENDING.md
Cherry-picks 25199bdaa18d52e4e1211793c67f06cc7a02ad95 (from #5687) onto master.
> changelog: squash changelog from 0.34 RCs into one

- CONTRIBUTING.md
Yesterday was our first time actually using the new "goreleaser" tooling. This updates our release flow to match the actual flow we followed.
> CONTRIBUTING: update to match the release flow used for 0.34.0

- .github/codecov.yml
> codecov: validate codecov.yml

- .github/workflows/coverage.yml
- .github/workflows/tests.yml
- .goreleaser.yml
- libs/math/fraction.go
> ci: build for 32 bit, libs: fix overflow (#5700)

- consensus/byzantine_test.go
This fixes spurious `TestByzantinePrevoteEquivocation` failures by extending the block range and time spent waiting for evidence. I've seen many runs where the evidence isn't committed until e.g. height 27. Haven't looked into _why_ this happens, but as long as the evidence is committed eventually and the test doesn't spuriously fail I'm (mostly) happy.
> test: fix TestByzantinePrevoteEquivocation flake (#5710)

- README.md
- remove circleci badge from readme
Closes: #XXX
> readme: remover circleci badge

- CHANGELOG_PENDING.md
- consensus/msgs.go
- libs/bits/bit_array.go
- libs/bits/bit_array_test.go
- test/maverick/consensus/msgs.go
> libs/bits: validate BitArray in FromProto

- p2p/pex/pex_reactor_test.go
*testing.T.TempDir() causes test cases to fail when
it is unable to remove the temporary directory once
the test case execution terminates. This seems to
happen often with pex reactor test cases.
> p2p/pex: fix flaky tests

- CHANGELOG_PENDING.md
- UPGRADING.md
add back removed changelog entry
Closes: #XXX
> changelog: add entry back

- Makefile
- docs/tendermint-core/running-in-production.md
- when not on a tag `tendermint version` will return "unreleased-`branchName`-`commitHash`"
Closes: #XXX
> UX: version configuration

- evidence/reactor.go
Follow-up to https://github.com/tendermint/tendermint/pull/5743
> evidence: omit bytes field

- CONTRIBUTING.md
Our minor release flow has been a little bit all over the place. This updates and simplifies the process.
> contributing: simplify our minor release process

- docs/.vuepress/config.js
- docs/versions
Co-authored-by: Cyrus Goh <hello@lovincyrus.com>
add version
Closes: #XXX
> docs: add version dropdown and v0.34 docs

- docs/versions
> docs: fix link

- .goreleaser.yml
and specify files that go into an archive
> goreleaser: lowercase binary name

- CHANGELOG_PENDING.md
- blockchain/v1/peer.go
- blockchain/v1/pool.go
- blockchain/v1/reactor.go
- blockchain/v1/reactor_fsm.go
- blockchain/v1/reactor_fsm_test.go
- blockchain/v1/reactor_test.go
Backports:
- https://github.com/tendermint/tendermint/pull/5401
- https://github.com/tendermint/tendermint/pull/5701
- https://github.com/tendermint/tendermint/pull/5711
**REBASE MERGE**
> v0.32: blockchain/v1 fixes

- CHANGELOG_PENDING.md
- blockchain/v1/peer.go
- blockchain/v1/pool.go
- blockchain/v1/reactor.go
- blockchain/v1/reactor_fsm.go
- blockchain/v1/reactor_fsm_test.go
- blockchain/v1/reactor_test.go
Backports:
- https://github.com/tendermint/tendermint/pull/5401
- https://github.com/tendermint/tendermint/pull/5701
- https://github.com/tendermint/tendermint/pull/5711
**REBASE MERGE**
> v0.33: blockchain/v1 fixes

- blockchain/v0/reactor.go
- blockchain/v2/reactor.go
- consensus/reactor.go
- evidence/reactor.go
- mempool/reactor.go
- p2p/pex/pex_reactor.go
> Omit bytes from logs - 0.32.x backport 

- blockchain/v0/reactor.go
- blockchain/v2/reactor.go
- consensus/reactor.go
- evidence/reactor.go
- mempool/reactor.go
- p2p/pex/pex_reactor.go
> Omit bytes from logs - 0.33 backport

- CHANGELOG_PENDING.md
- blockchain/v2/io.go
- blockchain/v2/reactor.go
- blockchain/v2/reactor_test.go
> blockchain/v2: send status request when new peer joins

- p2p/test_util.go
- p2p/transport_mconn.go
> p2p: fix data race in MakeSwitch test helper

- docs/tutorials/go-built-in.md
- docs/tutorials/go.md
Specify master for tutorials. 
I will have a followup PR for 0.34 that specifies 0.34
Ref: #5735
> docs: specify master for tutorials

- docs/tutorials/go-built-in.md
- docs/tutorials/go.md
Specify 0.34 for tutorials. 
Closes: #5735
> docs/tutorials: specify 0.34

- .github/workflows/release.yml
- .goreleaser.yml
- run `build` when on a branch matching `RC[0-9]/**`, in accordance with contributing.md release guide.
Closes: #5695
> ci: run `goreleaser build` 

- CHANGELOG.md
- CHANGELOG_PENDING.md
> CHANGELOG: prepare v0.34.1-rc1

- consensus/byzantine_test.go
> test/consensus: improve WaitGroup handling in Byzantine tests

- blockchain/v2/reactor.go
> blockchain/v2: fix missing mutex unlock

- blockchain/v0/reactor.go
> blockchain/v0: stop tickers on poolRoutine exit

- statesync/reactor.go
> statesync: do not recover panic on peer updates

- CHANGELOG_PENDING.md
- abci/client/grpc_client.go
- blockchain/v0/reactor.go
- blockchain/v2/reactor.go
- consensus/byzantine_test.go
- libs/os/os.go
- libs/os/os_test.go
- tools/tm-signer-harness/internal/test_harness.go
Backports a bunch of recent minor bugfixes, generally too small to be mentioned in a changelog.
**Rebase-merge this**
> backport various bugfixes

- docs/tendermint-core/metrics.md
- docs/tendermint-core/validators.md
> docs: fix broken redirect links

- test/e2e/generator/generate.go
- test/e2e/networks/ci.toml
Backports #5629 and #5854. 
🎃   **DO NOT SQUASH** 🎃
> e2e backports from master to 0.34.x

- CHANGELOG.md
- CHANGELOG_PENDING.md
> changelog: update to reflect changes released in 0.34.2

- light/store/db/db.go
- light/store/db/db_test.go
Fixes deadlock during concurrent pruning
Closes: #5892
> light: fix light store deadlock

- light/store/db/db.go
I was trying to be fancy and allow pruning concurrently with other operations by taking out first a read lock and then a write lock but this just got complicated so now I've simplified this by just taking a lock out over the entire operation. This means that no write operations can occur whilst pruning. This is okay because prune operations in the light client so far only ever clip off one or two blocks
> light: patch concurrency issue with pruning in the light store

- abci/types/types.pb.go
- go.mod
- go.sum
- proto/tendermint/blockchain/types.pb.go
- proto/tendermint/consensus/types.pb.go
- proto/tendermint/consensus/wal.pb.go
- proto/tendermint/crypto/keys.pb.go
- proto/tendermint/crypto/proof.pb.go
- proto/tendermint/libs/bits/types.pb.go
- proto/tendermint/mempool/types.pb.go
- proto/tendermint/p2p/conn.pb.go
- proto/tendermint/p2p/pex.pb.go
- proto/tendermint/p2p/types.pb.go
- proto/tendermint/privval/types.pb.go
- proto/tendermint/state/types.pb.go
- proto/tendermint/statesync/types.pb.go
- proto/tendermint/types/block.pb.go
- proto/tendermint/types/canonical.pb.go
- proto/tendermint/types/events.pb.go
- proto/tendermint/types/evidence.pb.go
- proto/tendermint/types/params.pb.go
- proto/tendermint/types/types.pb.go
- proto/tendermint/types/validator.pb.go
- proto/tendermint/version/types.pb.go
- rpc/grpc/types.pb.go
- bump gogoproto (1.3.2)
- regenerate proto files
Closes: #XXX
> proto: bump gogoproto (1.3.2)

- README.md
No one knows we have this mailing list 🙈
> readme: add security mailing list

- abci/types/types.pb.go
- go.mod
- go.sum
- proto/tendermint/blockchain/types.pb.go
- proto/tendermint/consensus/types.pb.go
- proto/tendermint/consensus/wal.pb.go
- proto/tendermint/crypto/keys.pb.go
- proto/tendermint/crypto/proof.pb.go
- proto/tendermint/libs/bits/types.pb.go
- proto/tendermint/mempool/types.pb.go
- proto/tendermint/p2p/conn.pb.go
- proto/tendermint/p2p/pex.pb.go
- proto/tendermint/p2p/types.pb.go
- proto/tendermint/privval/types.pb.go
- proto/tendermint/state/types.pb.go
- proto/tendermint/statesync/types.pb.go
- proto/tendermint/store/types.pb.go
- proto/tendermint/types/block.pb.go
- proto/tendermint/types/canonical.pb.go
- proto/tendermint/types/events.pb.go
- proto/tendermint/types/evidence.pb.go
- proto/tendermint/types/params.pb.go
- proto/tendermint/types/types.pb.go
- proto/tendermint/types/validator.pb.go
- proto/tendermint/version/types.pb.go
- rpc/grpc/types.pb.go
- scripts/protocgen.sh
- bump gogoproto (1.3.2)
- regenerate proto files
Closes: #XXX
> proto: bump gogoproto (1.3.2) (#5886)

- README.md
- config/config.go
- config/toml.go
- docs/package-lock.json
- docs/package.json
Backports #5914, #5915, #1916.
> 0.34.3 backports (post-gogoproto updates)

- .github/workflows/docs.yml
- .github/workflows/e2e.yml
- .github/workflows/proto.yml
This change will add a little "run workflow" button to a few of the workflows. I've found this feature really handy for the nightlies.
> .github/workflows: enable manual dispatch for some workflows

- CHANGELOG.md
(No changelog pending updates, since we all forgot to update the changelog pending with all these changes 🤡 )
> changelog: update changelog for v0.34.3

- .github/workflows/proto-docker.yml
- tools/proto/Dockerfile
Moves the docker file from images to the tendermint repo. This allows for better tracking and updating when needed. 
Closes: #XXX
> proto: docker deployment

- p2p/shim.go
Downgrade some noisy logs to DEBUG.
> p2p: revise shim log levels

- README.md
- blockchain/v0/reactor.go
- evidence/reactor.go
- libs/sync/deadlock.go
- libs/sync/sync.go
- mempool/ids.go
- mempool/reactor.go
- mempool/reactor_test.go
- node/node.go
- proto/tendermint/blockchain/message.go
- proto/tendermint/mempool/message.go
- statesync/reactor.go
- test/maverick/node/node.go
Prepares the mempool reactor for the newly designed p2p changes per [ADR 062](https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-062-p2p-architecture.md).
ref: #5670
> mempool: p2p refactor

- docs/.vuepress/config.js
- docs/package-lock.json
- fix the world's problem, npm
Closes: #XXX
> docs: package-lock.json fix

- docs/.vuepress/config.js
- docs/.vuepress/styles/index.styl
- docs/architecture/adr-056-proving-amnesia-attacks.md
- docs/package-lock.json
- docs/package.json
bumps docs version on v0.33.x
Closes: #XXX
> docs: bump vuepress theme

- docs/versions
- change version for v0.33.x
Closes: #XXX
> docs: change v0.33 version

- consensus/replay.go
- libs/bytes/bytes.go
- libs/bytes/bytes_test.go
- libs/log/tm_logger.go
- libs/log/tm_logger_test.go
- libs/log/tmfmt_logger.go
- libs/log/tmfmt_logger_test.go
- light/client.go
- mempool/clist_mempool.go
- state/execution.go
- statesync/syncer.go
- test/maverick/consensus/replay.go
Closes: #5806 
Co-authored-by: Lanie Hei <heixx011@umn.edu>
> libs/log: format []byte as hexidecimal string (uppercased)

- blockchain/v0/reactor_test.go
> blockchain v0: skip TestReactor_BadBlockStopsPeer

- libs/sync/closer.go
- libs/sync/closer_test.go
- libs/sync/deadlock.go
- libs/sync/sync.go
> sync: move closer to separate file

- CHANGELOG_PENDING.md
- state/helpers_test.go
- state/state_test.go
- types/params.go
- types/protobuf.go
- types/protobuf_test.go
- remove unused functions
- remove a function used in tests.
Closes: #XXX
> types: cleanup protobuf.go

- .goreleaser.yml
before:
```
Tendermint_0.34.3_darwin_amd64.tar.gz
-rw-r--r--  0 runner docker 192329 Jan 19 19:30 CHANGELOG.md
-rw-r--r--  0 runner docker    321 Jan 19 19:30 CHANGELOG_PENDING.md
-rw-r--r--  0 runner docker  11382 Jan 19 19:30 LICENSE
-rw-r--r--  0 runner docker   8165 Jan 19 19:30 README.md
-rwxr-xr-x  0 runner docker 23224320 Jan 19 19:30 tendermint
```
after:
```
tendermint_0.34.3_darwin_amd64.tar.gz
-rw-r--r--  0 runner docker 192329 Jan 19 19:30 CHANGELOG.md
-rw-r--r--  0 runner docker    321 Jan 19 19:30 CHANGELOG_PENDING.md
-rw-r--r--  0 runner docker  11382 Jan 19 19:30 LICENSE
-rw-r--r--  0 runner docker   8165 Jan 19 19:30 README.md
-rwxr-xr-x  0 runner docker 23224320 Jan 19 19:30 tendermint
```
> goreleaser: downcase archive and binary names

- docs/nodes/configuration.md
- add note to recommend setting external address
> docs: external address

- docs/nodes/configuration.md
changes requested in https://github.com/tendermint/tendermint/pull/6035 but the bot merged the PR prior to applying them
> docs: reword configuration

- CHANGELOG_PENDING.md
- light/provider/http/http.go
- types/validator_set.go
> light/provider/http: fix Validators

- .github/workflows/e2e-nightly-34x.yml
- .github/workflows/e2e-nightly-master.yml
> .github/workflows: cleanup yaml for e2e nightlies

- .github/CODEOWNERS
> CODEOWNERS: remove erikgrinaker

- .github/workflows/fuzz-nightly.yml
https://stackoverflow.com/a/66073112/820520
> .github: use job ID (not step ID) inside if condition

- light/client.go
- light/detector.go
> light: remove witnesses in order of decreasing index (#6058)

- light/provider/http/http.go
https://github.com/tendermint/tendermint/pull/6054#discussion_r571149135
Also adds the functionality that a negative maxRetryAttempts value will mean that the light client will query indefinitely
> light: create provider options struct

- .github/dependabot.yml
> .github: remove erik as reviewer from dependapot

- .github/workflows/proto-docker.yml
- Makefile
- docs/tendermint-core/metrics.md
- docs/versions
- tools/proto/Dockerfile
backport tooling prs
**REBASE MERGE**
> backport: tooling PRs

- p2p/switch_test.go
Cherry-pick the following to v0.34.x:
- #6000 
- #6001
> Backport v0.34.x: 6000 & 6001

- .github/CODEOWNERS
- .github/workflows/tests.yml
- docs/package-lock.json
- docs/package.json
Backport some dependency bumps and do the codeowners update. 
***Rebase merge me, please***
> 0.34.4 tooling backports

- .github/dependabot.yml
- consensus/reactor.go
> v0.34: backport block store bug and dependabot update

- CHANGELOG.md
- CHANGELOG_PENDING.md
Updates the changelog in preparation for v0.34.4.
> changelog: update for v0.34.4

- CHANGELOG.md
> changelog: improve with suggestions from @melekes

- CHANGELOG_PENDING.md
> CHANGELOG_PENDING: update changelog for changes to American spelling

- CHANGELOG.md
> changelog: update 0.34.3 changelog with details on security vuln

- docs/tutorials/go-built-in.md
- docs/tutorials/go.md
- docs/tutorials/java.md
- docs/tutorials/kotlin.md
> docs/tutorials: fix proto file names

- cmd/tendermint/commands/root.go
- config/config.go
- consensus/state.go
- test/e2e/app/main.go
- test/maverick/consensus/misbehavior.go
- test/maverick/consensus/state.go
- test/maverick/main.go
Executed a local network using simapp and looked for logs that seemed superfluous. This isn't by any means an exhaustive grooming, but should drastically help legibility of logs.
ref: #5912
> consensus: Groom Logs (#5917)

- consensus/state.go
- test/maverick/consensus/misbehavior.go
> consensus: remove privValidator from log call

- CHANGELOG.md
> changelog: update for 0.34.5

- CHANGELOG.md
- CONTRIBUTING.md
- Makefile
- docs/app-dev/abci-cli.md
- docs/app-dev/getting-started.md
- docs/introduction/install.md
- tools.mk
> Revert PR that likely broke release tooling, and bump changelog to reflect recalled version

- .github/workflows/jepsen.yml
Adds a new GH workflow - `jepsen`, which runs a given Jepsen test.
> .github: Jepsen workflow - initial version

- .github/workflows/jepsen.yml
fixes https://github.com/tendermint/tendermint/runs/1925580432
```
No :main namespace specified in project.clj.
```
> .github: [jepsen] cd inside the container, not outside

- .github/workflows/jepsen.yml
```
bash: line 0: cd: tendermint: No such file or directory
```
> .github: [jepsen] fix directory name

- consensus/state.go
ref: https://github.com/tendermint/tendermint/pull/6140#discussion_r578635756
> consensus: log private validator address and not struct

- docs/tendermint-core/rpc.md
Add docs on how to get tendermint version into RPC version outputs
> docs: how to add tm version to RPC

- CHANGELOG_PENDING.md
> changelog: fix changelog pending version numbering

- cmd/tendermint/commands/debug/kill.go
> cmd: ignore missing wal in debug kill command

- consensus/state.go
- state/execution.go
> state executor: groom logs

- CHANGELOG_PENDING.md
- libs/cli/flags/log_level_test.go
- libs/log/filter_test.go
- libs/log/tm_json_logger.go
- libs/log/tracing_logger_test.go
> libs/log: [JSON format] include timestamp

- CHANGELOG_PENDING.md
- cmd/priv_val_server/main.go
- cmd/tendermint/commands/init.go
- cmd/tendermint/commands/reset_priv_validator.go
- cmd/tendermint/commands/show_validator.go
- cmd/tendermint/commands/testnet.go
- consensus/replay_test.go
- privval/file.go
- privval/file_test.go
- test/e2e/app/main.go
- tools/tm-signer-harness/internal/test_harness.go
- tools/tm-signer-harness/main.go
- return errors on `loadFilePv`
closes #6182
> privval: return errors on loadFilePV

- CHANGELOG.md
- CHANGELOG_PENDING.md
> changelog: update for 0.34.8

- .github/workflows/fuzz-nightly.yml
- test/fuzz/p2p/pex/reactor_receive.go
- test/fuzz/p2p/secret_connection/read_write.go
- test/fuzz/rpc/jsonrpc/server/handler.go
- ignore empty data in rpc
- provide correct IP in pex
- spawn a goroutine for Write and do multiple Read(s)
> test/fuzz: fix rpc, secret_connection and pex tests

- state/execution.go
- state/txindex/indexer_service.go
> indexer: remove info log

- test/e2e/runner/rpc.go
- test/e2e/runner/wait.go
> e2e: adjust timeouts to be dynamic to size of network

- mempool/reactor.go
- p2p/shim.go
- rpc/jsonrpc/server/http_json_handler.go
- rpc/jsonrpc/server/http_server.go
- test/e2e/runner/rpc.go
I have this set to be backported for 0.34.x. Obviously the small shim change will cause a conflict, but that'll be very easy to address.
> mempool & rpc log grooming

- consensus/state.go
- mempool/clist_mempool.go
- p2p/shim.go
- rpc/jsonrpc/server/http_json_handler.go
- state/execution.go
Cleanup logs further
This is based of test syncing a cosmos hub node. These pollute the logs but don't add value to the end user to what is going on.
> logs: cleanup

- cmd/tendermint/commands/testnet.go
> localnet: fix localnet by excluding self from persistent peers list

- .github/workflows/coverage.yml
- .github/workflows/e2e-nightly-34x.yml
- .github/workflows/e2e-nightly-master.yml
- .github/workflows/e2e.yml
- .github/workflows/fuzz-nightly.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
> build with go1.16

- CHANGELOG_PENDING.md
- rpc/jsonrpc/server/http_json_handler.go
- rpc/jsonrpc/server/http_server.go
- rpc/jsonrpc/server/http_server_test.go
- rpc/jsonrpc/server/http_uri_handler.go
instead of panicking
Closes #5529
> rpc/jsonrpc/server: return an error in WriteRPCResponseHTTP(Error)

- test/e2e/tests/app_test.go
I thought that the ABCI Query height response was the height when the key was last updated, but it instead it just returns the latest height. 
Therefore an assertion made in app_test.go is wrong.
> e2e: fix app_test.go

- consensus/state.go
> consensus: use errors.Is in checking vote error

- light/client.go
- test/e2e/app/main.go
- test/e2e/generator/generate.go
Fixes a few bugs with integrating the light client with the e2e framework. Specfically this includes a) ensuring that providers were not seed nodes, did not prune and started at the initial height and b) ensuring that ipv6 addresses are parsed correctly.
NOTE: I am no longer seeing light client based errors but I am still getting a few spurious timeouts and other errors. I have dumped them here for reference.
```
--- FAIL: TestApp_Tx (0.00s)
--- FAIL: TestApp_Tx/full01 (10.01s)
app_test.go:85: 
Error Trace:	app_test.go:85
e2e_test.go:56
Error:      	Received unexpected error:
RPC error -32603 - Internal error: timed out waiting for tx to be included in a block
Test:       	TestApp_Tx/full01
FAIL
--- FAIL: TestValidator_Propose (0.03s)
--- FAIL: TestValidator_Propose/validator05 (0.00s) …
```
> e2e: fix light client generator

- .github/workflows/lint.yaml
Please add a description of the changes that this PR introduces and the files that
are the most critical to review.
If this PR fixes an open Issue, please include "Closes #XXX" (where "XXX" is the Issue number) 
so that GitHub will automatically close the Issue when this PR is merged.
> bump linter version to 1.38

- consensus/state.go
- types/block.go
- types/vote_set.go
This is an attempt to clean up the logging message as requested in #6269.
> logging: shorten precommit log message

- p2p/metrics.go
- p2p/pqueue.go
- p2p/router.go
- p2p/wdrr_queue.go
Address remaining metrics from the legacy p2p set of metrics.
> p2p: metrics

- .github/workflows/janitor.yml
- .github/workflows/tests.yml
Cleanup old actions if a new commit is pushed
> ci: add janitor

- abci/example/kvstore/persistent_kvstore.go
- consensus/replay_test.go
- consensus/wal_generator.go
I think this is an (easy, potentially partial) fix to the issue
described in #3599.
I want to see how it does in CI, and I'm not sure we should close out
the issue, as there might be more cases we want to cover, but this
feels like a step in the right direction.
> test: clean up databases in tests

- mempool/reactor_test.go
thanks to @cmwaters for catching this!
> p2p: setup mempool reactor in tests with correct peer manager

- docs/introduction/what-is-tendermint.md
Adds small fix to the docs. Line 67 specifies "two key changes". I think this is where the second bullet point was meant to start.
> Adds missing line break

- config/config.go
- config/toml.go
- node/node.go
- p2p/peermanager.go
- p2p/pqueue.go
- p2p/router.go
- p2p/wdrr_queue.go
- test/e2e/docker/Dockerfile
- test/e2e/generator/generate.go
- test/e2e/networks/ci.toml
- test/e2e/pkg/manifest.go
- test/e2e/pkg/testnet.go
- test/e2e/runner/setup.go
This is mostly just an experiment in seeing if wiring this up will
even work.
It might make sense to back out of this a bit and just keep the
parameterization without enabling it as an axis in the tests, for now.
> p2p: extend e2e tests for new p2p framework

- CHANGELOG.md
- CHANGELOG_PENDING.md
> changelog: prepare changelog for 0.34.9 release

- CHANGELOG.md
- CHANGELOG_PENDING.md
> changelog: update to reflect 0.34.9

- SECURITY.md
Please add a description of the changes that this PR introduces and the files that
are the most critical to review.
If this PR fixes an open Issue, please include "Closes #XXX" (where "XXX" is the Issue number) 
so that GitHub will automatically close the Issue when this PR is merged.
> Minor update to security.md

- docs/package-lock.json
- docs/package.json
> docs: bump vuepress-theme-cosmos

- test/e2e/runner/load.go
- test/e2e/tests/app_test.go
> e2e: tx load to use broadcast sync instead of commit

- CHANGELOG.md
- CHANGELOG_PENDING.md
> changelog: update for 0.34.10

- node/node.go
- node/node_test.go
- test/e2e/app/main.go
> node: use db provider instead of mem db

- docs/architecture/adr-065-custom-event-indexing.md
Specify psql eventsink will not support search.
> docs: adr-65 adjustments

- mempool/bench_test.go
related to: https://github.com/tendermint/tendermint/pull/6419
@tychoish i just noticed that the parallel benchmark wasn't measuring the same thing as regular. created a pr just in case if the change wasn't intentional.
RunParallel will distribute b.N over all available cores, so in case if RunParallel*b.N benchmark won't measure the average time for checking a single transaction, but rather - average time of checking b.N transactions using all cores.
After this change numbers are somewhat more realistic:
```
BenchmarkCheckTx-16             	  409280	      3242 ns/op	    1514 B/op	      32 allocs/op
BenchmarkParallelCheckTx-16     	  235758	      4953 ns/op	    1565 B/op	      32 allocs/op
```
> mempool: fix parallel benchmark

- docs/security/vulnerability-names.md
We should really be giving our docs some more lovin
> docs: remove visibility of security page

- p2p/pex/reactor_test.go
> pex: fix test on receiving too many addresses

- p2p/router.go
this reverts the changes to router.go from https://github.com/tendermint/tendermint/pull/6467 ([see here](https://github.com/tendermint/tendermint/pull/6467/files#diff-f0904f78018bdb3a1cc16355e4d2eeb5a7313380ee9cb8cefbd3c822caf3bdb4))
> p2p: revert change to routePeer

- proto/tendermint/consensus/message_test.go
adds a test vector for hasvote in order to extra sure https://github.com/tendermint/tendermint/pull/6287 isnt breaking
> consensus: add test vector for hasvote

- README.md
Read me Introduction reframed for improving clarity
> Readme Introduction Reframed for better clarity

- .gitignore
- docs/package-lock.json
- docs/security/README.md
- docs/security/vulnerability-names.md
I have realised what I was doing wrong with my first attempt to hide the page listing security names.
I've built this locally so I'm a little more confident that this is going to work
> docs: hide security page (second attempt)

- types/block_test.go
Tag teaming with callum on debugging, wrote this to test headerHash changes from 0.34 to master. Its useful going forward as well.
> test: HeaderHash test vector

- docs/nodes/configuration.md
- docs/nodes/logging.md
- docs/nodes/running-in-production.md
- test/e2e/pkg/manifest.go
> docs: logger updates

- node/node.go
- node/node_test.go
- node/setup.go
- rpc/jsonrpc/server/http_json_handler.go
- state/state.go
- state/store.go
After observing a few failed e2e tests I realised that I missed an edge case (when genesis has no validators) for this PR: https://github.com/tendermint/tendermint/pull/6554.
> node: fix genesis on start up

- test/fuzz/oss-fuzz-build.sh
> fuzz: initial support for fuzzing

- test/fuzz/oss-fuzz-build.sh
> test/fuzz: fix wrong compile fuzzer command

- internal/p2p/queue.go
- internal/p2p/wdrr_queue.go
- internal/statesync/reactor.go
Increases defaultCapacity from 1MB to 16MB
> p2p: increase queue size to 16MB

- internal/p2p/peermanager.go
> p2p: avoid retry delay in error case

- CHANGELOG.md
- CHANGELOG_PENDING.md
- version/version.go
> release: prepare changelog for v0.34.11

- CHANGELOG.md
- version/version.go
Adds v0.34.11 updates to master
> release: update changelog and version

- internal/p2p/peermanager.go
> p2p: address audit issues with the peer manager

- light/example_test.go
- light/provider/http/http_test.go
- rpc/client/examples_test.go
- rpc/client/main_test.go
- rpc/grpc/grpc_test.go
- rpc/test/helpers.go
> rpc: use shorter path names for tests

- docs/architecture/adr-059-evidence-composition-and-lifecycle.md
- light/detector.go
- types/evidence.go
> evidence: update ADR 59 and add comments to the use of common height

- internal/consensus/state.go
- types/priv_validator.go
fixes https://github.com/tendermint/tendermint/pull/6578#discussion_r662180308
ran with `./build/runner -f networks/ci.toml` and checked the docker log message to confirm no error message
> privval: missing privval type check in SetPrivValidator

- internal/consensus/reactor.go
This reverts commit 13b95e71274e6eed250eb1b2d0afee08f79c0251.
> Revert "consensus: skip all messages during sync (#6577)"

- docs/nodes/running-in-production.md
Add sentence about windows support. 
closes #1887
> docs: add sentence about windows support

- internal/blockchain/v0/reactor.go
- internal/consensus/reactor.go
- internal/evidence/reactor.go
- internal/mempool/v0/reactor.go
- internal/mempool/v1/reactor.go
- internal/p2p/pex/reactor.go
- internal/statesync/reactor.go
> add stacktrace to panic logs

- go.mod
- scripts/keymigrate/migrate.go
remove pkg/errors since we use the provided fmt.Errorf
> deps: remove pkg errors

- .gitignore
- CHANGELOG_PENDING.md
> abci: Fix gitignore abci-cli

- internal/blockchain/v0/reactor.go
This commit extends the fix in #6518, so all other goroutine which run
concurrently with processBlockchainCh can safely send data to blockchain
out channel via a bridge channel. This helps eliminating all possible
data race with sending and closing blockchainCh.Out channel at the same
time.
Fixes #6516
> internal/blockchain/v0: prevent all possible race for blockchainCh.Out

- internal/statesync/block_queue.go
- internal/statesync/block_queue_test.go
- internal/statesync/reactor.go
- internal/statesync/reactor_test.go
Closes: https://github.com/tendermint/tendermint/issues/6703
> statesync: use initial height as a floor to backfilling

- internal/statesync/reactor.go
add an additional timeout increase for statesync to addressed a light client fetch timeout..
> statesync: increase dispatcher timeout

- internal/statesync/dispatcher_test.go
This code change amends the dispatcher tests to read from the dispatcher's `requestCh`. This ensures that a request is waiting when the test calls `dispatcher.respond`. 
addresses: #6711
> statesync: dispatcher test uses internal channel for timing

- docs/architecture/README.md
- docs/architecture/adr-042-state-sync.md
- docs/architecture/adr-044-lite-client-with-weak-subjectivity.md
- docs/architecture/adr-045-abci-evidence.md
- docs/architecture/adr-047-handling-evidence-from-light-client.md
- docs/nodes/logging.md
- docs/nodes/running-in-production.md
- docs/tendermint-core/subscription.md
- docs/tendermint-core/using-tendermint.md
> docs: fix broken links

- CHANGELOG_PENDING.md
- UPGRADING.md
- config/config.go
- config/config_test.go
- config/toml.go
- node/setup.go
> blockchain: error on v2 selection

- CHANGELOG_PENDING.md
- internal/evidence/pool.go
- internal/libs/clist/clist.go
- internal/libs/clist/clist_test.go
- internal/mempool/v0/clist_mempool.go
- internal/mempool/v1/mempool.go
This change is to help debug: #6660. Unclear if this is the source of issue but is a code change that touches highly related code.
> libs/clist: revert clear and detach changes while debugging

- internal/libs/clist/clist_test.go
> clist: add a few basic clist tests

- .github/workflows/stale.yml
Ignore issues with the stale bot
> ci: ignore issues with stale bot

- test/e2e/generator/generate.go
- test/e2e/pkg/manifest.go
- test/e2e/pkg/testnet.go
- test/e2e/runner/setup.go
> e2e: allow for both v0 and v1 mempool implementations

- internal/mempool/v1/mempool.go
- internal/mempool/v1/reactor.go
Tweak `broadcastTxRoutine` to be similar to `v0`.
ref: https://github.com/tendermint/tendermint/issues/6660
> mempool v1: tweak broadcastTxRoutine

- UPGRADING.md
This is proposed language for the upgrade process about the new custom
reactor/mempool support.
> docs: upgrade documentation for custom mempools

- CHANGELOG_PENDING.md
- UPGRADING.md
- crypto/secp256k1/secp256k1.go
- node/node.go
- rpc/core/consensus.go
- rpc/core/env.go
- rpc/core/net.go
- rpc/core/types/responses.go
- rpc/openapi/openapi.yaml
- test/e2e/tests/net_test.go
Update implementation of new p2p routes to reflect changes in the new p2p layer.
Closes: #6555
> rpc: support new p2p infrastructure

- CHANGELOG.md
- CHANGELOG_PENDING.md
Also strips some trailing whitespace :)
> changelog: update to reflect 0.34.12 release

- CHANGELOG_PENDING.md
- cmd/tendermint/commands/gen_node_key.go
- cmd/tendermint/commands/gen_validator.go
- cmd/tendermint/commands/probe_upnp.go
- cmd/tendermint/commands/replay.go
- cmd/tendermint/commands/reset_priv_validator.go
- cmd/tendermint/commands/root.go
- cmd/tendermint/commands/show_node_id.go
- cmd/tendermint/commands/show_validator.go
just following up on a deprecation.
> cmd: remove deprecated snakes

- networks/remote/ansible/inventory/digital_ocean.py
It turns out ansible has created a new set of modules that no longer rely on dopy: https://github.com/geerlingguy/ansible-for-devops/issues/229
In this PR, I update the digital_ocean.py to the newest version.
> update to newest DigitalOcean modules

- CHANGELOG.md
Fixes #6933. I forgot to update master after I did the v0.34.13 release.
> Update CHANGELOG.md for release v0.34.13.

- test/e2e/runner/load.go
This change seems to eliminate failures caused by high transaction load that occur running in the CI environment.
> e2e: reduce load pressure

- rpc/openapi/openapi.yaml
> docs: add documentation of unsafe_flush_mempool to openapi

- test/e2e/run-multiple.sh
- test/e2e/runner/main.go
I think this is closer to what we actually want.
> e2e: always preserve failed networks

- .github/workflows/coverage.yml
- test/e2e/generator/generate.go
- test/e2e/generator/generate_test.go
- test/e2e/pkg/manifest.go
These assertions just make sure that something will fail if any of the
recent configuration limitations that I've made are always true for
the test suite that we construct.
> e2e: add generator tests

- internal/statesync/reactor.go
Presently this appears to be an infinate hang, but I think we're just
not logging. Once a minute should give enough indication.
> statesync: add logging while waiting for peers

- test/e2e/generator/generate.go
- test/e2e/generator/generate_test.go
- test/e2e/generator/main.go
- test/e2e/tests/app_test.go
Contrary to what @williambanfield observes, there should not be any
mixed/hybrid nodes except when thusly configured
> e2e: generator ensure p2p modes

- scripts/authors.sh
This script is referenced from the release documentation, we should make sure it's functional. This is helpful in generating the "Special Thanks" section of the changelog.
> scripts: fix authors script to take a ref

- docs/architecture/adr-065-custom-event-indexing.md
While discussing a question about the indexing interface (#7044), we found some
confusion about the intent of the design decisions in ADR 065.
Based on discussion with the original authors of the ADR, this commit adds some
language to the Decisions section to spell out the intentions more clearly, and
to call out future work that this ADR did not explicitly decide about.
> Clarify decision record for ADR-065.

- .github/workflows/fuzz-nightly.yml
- test/fuzz/Makefile
This PR removes updates the fuzzer Makefile and github action to reflect the updated directory structure of the fuzz tests.
> fuzz: remove fuzz cases for deleted code

- docs/.vuepress/config.js
- docs/versions
This should not be merged until the release is tagged.
> Add v0.35 to the configs for building the docs website.

- rpc/jsonrpc/server/http_uri_handler.go
> rpc: fix inappropriate http request log

- docs/rfc/README.md
> Fix ToC entry for RFC 006.

- cmd/tendermint/commands/replay.go
- internal/consensus/replay.go
- internal/consensus/replay_file.go
- internal/consensus/replay_test.go
- node/node.go
- node/setup.go
This mostly just pushes more of initialization out of the node package.
> node+consensus: handshaker initialization

- Makefile
> build: update location of proto builder image

- CHANGELOG_PENDING.md
I forgot to do this before merging.
> Add pending change log entry for #7319.

- test/e2e/tests/app_test.go
This is a more clear version of the stable parts of the apphash tests.
> e2e: more clear height test

- internal/p2p/pex/reactor.go
I saw a race detected in a test here that I think would be better
handled by just wiring up these threads.
> pex: improve goroutine lifecycle

- test/e2e/app/app.go
This might be a source of non-determinism in the e2e test.
> e2e: stabilize validator update form

- .github/workflows/coverage.yml
- Makefile
> ci: move test execution to makefile (#7372)

- test/e2e/networks/ci.toml
This reverts commit b057740bd3dc92689b83901eb7cbd33758661f38.
> Revert "ci: tweak e2e configuration (#7400)"

- internal/state/execution.go
Looks like we missed a few things here.
> state: pass connected context

- internal/state/state.go
- internal/state/validation.go
- internal/state/validation_test.go
Addresses `Remove all the median time checks.` from #6942
> Remove MedianTime, set block time to Now()

- README.md
- networks/remote/README.md
> Fix links to Terraform/Ansible documentation.

- README.md
- docs/tools/docker-compose.md
A follow-up to #7416 and #7412.
> Fix broken documentation link.

- node/node.go
- node/node_test.go
- node/setup.go
This is small but a few accumulated things in the node package.
> node: minor package cleanups

- consensus/reactor.go
- p2p/pex/pex_reactor.go
> Reduce p2p log noise

- docs/introduction/architecture.md
Remove extra white space at line 64.
> Remove extra white space

- internal/consensus/common_test.go
- internal/consensus/pbts_test.go
`wb/proposer-based-timestamps` pbts tests are broken.
> Fix pbts tests

- cmd/tendermint/commands/run_node.go
- config/config.go
- test/e2e/runner/setup.go
> config: add a Deprecation annotation to P2PConfig.Seeds.

- types/block_test.go
- types/evidence_test.go
- types/light_test.go
- types/node_info_test.go
- types/proposal_test.go
- types/validation_test.go
- types/validator_set_test.go
- types/validator_test.go
- types/vote_set_test.go
- types/vote_test.go
this mostly consists of plumbing testing.T instances through test fixtures.
> types: tests should not panic

- rpc/jsonrpc/server/http_json_handler.go
No functional changes.
- Pull out a some helper code to simplify the control flow within the body of
the HTTP request handler.
- Front-load the URL path check so it does not get repeated for each request.
> rpc: refactor the HTTP POST handler

- internal/consensus/invalid_test.go
- internal/consensus/state.go
Closes `remove voteTime entirely` part of #6942
> Remove votetime

- CHANGELOG.md
> Add changelog entries from release v0.34.15.

- light/client_benchmark_test.go
- light/client_test.go
- light/detector_test.go
- light/helpers_test.go
- light/verifier_test.go
I left this in a pervious pass, because there's only one panic to
remove, but the size of the diff is obviously quite large.
> light: remove test panic

- light/client_benchmark_test.go
- light/verifier.go
These functions already handled errors, and did some input validation
without panicing, so this seems safe.
> light: convert validation panics to errors

- docs/architecture/README.md
- docs/architecture/adr-075-rpc-subscription.md
> Mark ADR 075 as "accepted".

- abci/cmd/abci-cli/abci-cli.go
- abci/version/version.go
Remove duplicate ABCIVersion const.
> version: remove duplicate ABCIVersion

- CHANGELOG_PENDING.md
- internal/consensus/pbts_test.go
- internal/consensus/state.go
- internal/consensus/state_test.go
- internal/state/state.go
- internal/state/validation.go
- rpc/client/evidence_test.go
- rpc/client/rpc_test.go
- types/proposal.go
- types/proposal_test.go
Merged to pbts branch in #7541
> Use proposer timestamp instead of genesis time for height 1 block time

- rpc/jsonrpc/server/ws_handler.go
These options are never set to anything but the defaults, so drop the options
and inline the defaults. No functional changes.
This is part of a general cleanup to minimize the surface area of the websocket handler, in preparation for work on [ADR 075](https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-075-rpc-subscription.md).
> rpc: remove unused websocket options

- internal/mempool/mempool.go
> mempool: return duplicate tx errors more consistently

- internal/consensus/peer_state.go
- internal/consensus/reactor.go
This should help address the issue described in #7729
> consensus: delay start of peer routines

- cmd/tendermint/commands/init.go
- cmd/tendermint/commands/testnet.go
> cmd: fix parameters passed to testnet

- rpc/jsonrpc/server/http_uri_handler.go
Extend the decoding rules for URL query parameters so that if the target type
implements encoding.TextUnmarshaler, the decoder will use it.
This is a non-breaking change.
> rpc: allow GET parameters that support encoding.TextUnmarshaler

- abci/client/socket_client.go
The context shipped along with the request object wasn't/shouldn't
have been meaningfully used, so it seems safe to remove.
> abci/client: remove vestigially captured context

- internal/consensus/state.go
> consensus: start the timeout ticker before replay

- docs/package-lock.json
- docs/package.json
The various package locks got out of sync, reunify them.
> docs: fix cosmos theme version.

- docs/versions
A manual cherry-pick of 926c469fcc233b6f151fb80e78811c9054ee710f.
> Restore building docs for master on docs.tendermint.com. (#7969)

- internal/consensus/reactor_test.go
I think this is arguably correct to skip this error, and this test has
been flaky for a while.
Closes #7824
> consensus: TestReactorValidatorSetChanges test fix

- spec/consensus/proposer-based-timestamp/tla/Apalache.tla
- spec/consensus/proposer-based-timestamp/tla/MC_PBT.tla
- spec/consensus/proposer-based-timestamp/tla/TendermintPBT_002_draft.tla
- spec/consensus/proposer-based-timestamp/tla/typedefs.tla
Changes to the TLA+ specifications that need to be integrated.
This recreates #8004, which I merged not realizing it was more than just a migration of files. Apologies for the noise.
> MIgrate and integrate TLA+ files from the spec repo

- internal/consensus/invalid_test.go
- internal/consensus/state.go
This includes #8027, and some additional tweaks to avoid a race
condition and intermittent failure of the InvalidState test.
> consensus: fix TestInvalidState race and reporting

- internal/p2p/pex/reactor.go
The message handling in this reactor is all under control of the reactor
itself, and does not call out to callbacks or other externally-supplied code.
It doesn't need to check for panics.
- Remove an irrelevant channel ID check.
- Remove an unnecessary panic recovery wrapper.
> p2p: remove unnecessary panic handling in PEX reactor

- README.md
Add Vocdoni under applications section on the README.
> readme: add vocdoni

- internal/consensus/reactor.go
- internal/consensus/state.go
This ports the changes from #7992 and #7994 from the v0.34.x branch to v0.35.x.
> consensus: change lock handling in reactor and handleMsg for RoundState (forward-port #7994 #7992)

- consensus/state.go
This change allows the consensus mutex to unlock in the case of panics in the `handleMsg` method call. This was pointed out by @tychoish and was updated in v0.35 and master. This adds the same logic to v0.34. 
See: https://github.com/tendermint/tendermint/pull/8138
related to: #8157
> consensus: change lock to handle panics

- CHANGELOG.md
- CHANGELOG_PENDING.md
- version/version.go
This pull request prepares the v0.34.x branch for release v0.34.17
> Update changelog for release v0.34.17

- CHANGELOG_PENDING.md
- cmd/tendermint/commands/reset.go
- cmd/tendermint/commands/reset_test.go
- internal/p2p/pex/reactor_test.go
> cli: fix reset command for v0.35

- .github/workflows/release.yml
A manual backport of #8292.
Also update actions/checkout.
> Fix release notes to match the prevailing style.

- internal/state/execution.go
minor change while reading through changes: SetEventBus was deleted, same with the NopEventBus
Feel free to ignore if not useful.
> Update outdated doc comment

- scripts/confix/confix.go
> Remove resolved TODO comments.

- CHANGELOG_PENDING.md
I forgot to add this before merging. 🙁
> Update pending changelog for #8352.

- internal/state/indexer/sink/kv/kv.go
- node/node.go
- node/node_test.go
- node/setup.go
Manual backport of #7113 to 0.35
> node: always close database engine (#7113)

- internal/p2p/conn_tracker.go
- internal/p2p/conn_tracker_test.go
(Discovered with some upram experimentation.)
> p2p: fix setting in conn-tracker

- scripts/confix/confix_test.go
- scripts/confix/testdata/diff-30-31.txt
- scripts/confix/testdata/v30-config.toml
Some additional testdata I grabbed while writing up the draft of RFC 019.
> Add confix testdata for Tendermint v0.30.

- abci/client/grpc_client.go
- abci/client/socket_client.go
It seems to me that by adding requests to the clients tracker (the
`reqSent` linked list), then there's no need to actually drain the
channel, becuase we will mark all of these requests as done/errored
(which propogates to users, as users never get future objects any
more), and then the GC can reap all of the request objects and the
channel accordingly.
> abci: avoid having untracked requests in the channel

- internal/blocksync/pool.go
What I hope are minor improvements along the road to ABCI++.
> blocksync: Honor contexts supplied to BlockPool

- privval/utils.go
Front load the protocol type check so we do not wind up creating listeners of
types that are not usable for this interface (for example, UDP).
Fixes #8647.
> privval: restrict listeners to TCP and Unix domain sockets

- test/e2e/generator/generate.go
This almost doubles the number of test suites in each nightly run. We
should backport this to 0.36.
> e2e/generator: enlarge nightly test suite

- test/e2e/generator/generate.go
This adds 30 addtional tests to the 0.35 nightly suite and runs the test with larger transaction sizes
> e2e/generator: add additional testnets (0.35)

- internal/mempool/v0/reactor.go
- internal/mempool/v1/reactor.go
Backporting this change from master
> mempool: do not log already seen txs as errors

- internal/p2p/router_test.go
Fix minor test incongruency missed earlier.
> p2p: fix mconn transport accept test

- test/fuzz/mempool/v1/checktx.go
> Make priority mempool fuzz test actually test the priority mempool.

- internal/p2p/router.go
> p2p: fix typo

- internal/p2p/peermanager.go
This is mostly an example/test PR to see how this impacts e2e tests.
>  p2p: track peers by address

- test/e2e/tests/net_test.go
Ref: https://github.com/tendermint/tendermint/issues/8848
> e2e: add tolerance to peer discovery test

- light/client.go
ctx may be canceled, causing the sender to exit and the channel to block forever. Another option is to close the sender chan, but this should work as well.
> light: fix light client select statement

- test/e2e/tests/net_test.go
Follow up on: https://github.com/tendermint/tendermint/pull/8849
> e2e: disable another network test

- .github/CODEOWNERS
To avoid @cason becoming a bottleneck
> Add @sergio-mena and @jmalicevic to list of spec reviewers

- internal/p2p/peermanager.go
> p2p: make peer gossiping coinflip safer

- CHANGELOG_PENDING.md
I neglected to do this in #8944.
> Update pending changelog.

- config/config.go
- config/toml.go
Update the queue documentation to reflect the types of queues and current default queue.
> config: update config to reflect simple-priority queue

- spec/abci++/abci++_basic_concepts.md
> Typo in basic concepts section

- go.mod
- go.sum
- mempool/v1/mempool.go
This is a manual backport of #9030.
> mempool: rework lock discipline to mitigate callback deadlocks

- .github/dependabot.yml
to try reduce noise (or at least focus it). I'd even consider to having this monthly
> git: modify dependabot to weekly

- DOCKER/Dockerfile
Fixes issues of failing docker build in #9073 
---
> DOCKER: use go 1.18

- .github/workflows/docs-toc.yml
- Makefile
- docs/architecture/README.md
- docs/presubmit.sh
Partially addresses #9096.
---
> ci: Restore ToC check for ADRs/RFCs

- consensus/metrics.gen.go
- consensus/metrics.go
- consensus/state.go
- proxy/app_conn.go
- proxy/metrics.gen.go
- proxy/metrics.go
- state/metrics.gen.go
- state/metrics.go
These issues were caught when running the Tendermint binary after applying the changes from #9178. 
---
> metrics: fixup after cherry-pick

- config/toml.go
Update to toml. Fix needed to continue testing
> Small update to toml.go for abci-responses 

- state/store.go
> Update to ABCILastResponseskey

- CHANGELOG_PENDING.md
- cmd/tendermint/commands/reindex_event.go
- rpc/core/blocks.go
- rpc/openapi/openapi.yaml
In preparation for the v0.34.21 release, I was looking through the changes and thought we could better document them.
---
> docs: Minor recommendations prior to v0.34.21 release

- CHANGELOG.md
- CHANGELOG_PENDING.md
- version/version.go
As per the release instructions
> release: prepare v0.34.21

- go.mod
> chore: add retraction notice of v0.35 to master as well

- RELEASES.md
:book: [Rendered](https://github.com/tendermint/tendermint/blob/thane/releases-docs/RELEASES.md)
---
> docs: Update RELEASES.md to reflect current process

- version/version.go
Part of task: "Cut `v0.37.x` branch" (listed in #9091)
Updated Tendermint version on  `main`
---
> Update Tendermint version in `main`

- version/version.go
Part of #9091 
Updated Tendermint version on `v0.37.x`
---
> Update Tendermint version to v0.37.0

- CHANGELOG_PENDING.md
- blocksync/reactor.go
- blocksync/reactor_test.go
- consensus/byzantine_test.go
- consensus/common_test.go
- consensus/reactor_test.go
- consensus/replay.go
- consensus/replay_file.go
- consensus/replay_test.go
- consensus/state.go
- consensus/wal_generator.go
- node/node.go
- node/node_test.go
- state/execution.go
- state/execution_test.go
- state/helpers_test.go
- state/validation_test.go
> state: move pruneBlocks from consensus/state to state/execution

- CHANGELOG_PENDING.md
- tools/tm-signer-harness/Makefile
- tools/tm-signer-harness/main.go
> tools: use os home dir to instead of the hardcoded PATH

- .github/workflows/gosec.yml
Adds a code vulnerability scanner that'll flag issues and issue advisories from cosmos/gosec https://github.com/cosmos/gosec
> .github/workflows: add cosmos/gosec vulnerability scanner for each Push/PR

- spec/abci/apps.md
> small typo fix: "later" to "latter"

- statesync/syncer.go
> statesync: convert snapshot hashes to hex strings for logging

- CHANGELOG_PENDING.md
- config/config.go
- config/toml.go
- node/node.go
For the full description, see #7930
---
> backport: add event subscription options and defaults config (#7930)

- libs/pubsub/query/query.go
- libs/pubsub/query/query_test.go
- light/rpc/client.go
- node/node.go
- rpc/core/env.go
- rpc/core/events.go
- rpc/core/routes.go
- rpc/core/types/responses.go
- types/events.go
- types/events_test.go
For the full description, see https://github.com/tendermint/tendermint/pull/7965
---
> backport: implement the ADR 075 /events method (#7965)

- CHANGELOG_PENDING.md
I forgot to add a changelog before merging #9518
---
> Add changelog entry to #9518

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
> Fix: typos

- CHANGELOG_PENDING.md
- light/proxy/routes.go
- light/rpc/client.go
- rpc/client/helpers.go
- rpc/client/http/http.go
- rpc/client/interface.go
- rpc/client/local/local.go
- rpc/client/mock/client.go
- rpc/core/events.go
- rpc/test/helpers.go
For the full description, see https://github.com/tendermint/tendermint/pull/7982
---
> backport: add Events method to the client interface (#7982)

- config/config.go
https://github.com/tendermint/tendermint/issues/8775 was resolved and backported so I think this comment is no longer applicable.
> docs: remove outdated comment

- CHANGELOG.md
- CHANGELOG_PENDING.md
- version/version.go
:book: [CHANGELOG](https://github.com/tendermint/tendermint/blob/release/v0.34.23/CHANGELOG.md#v03423)
---
> Release v0.34.23

- rpc/core/routes.go
close #9689 
Please backport it to v0.34/v0.37, thanks
> rpc: fix check_tx cache problem

- CHANGELOG.md
From #9684.
[Rendered](https://github.com/tendermint/tendermint/blob/thane/v0.34.23-changelog/CHANGELOG.md#v03423)
---
> Forward-port v0.34.23 changelog entry

- .github/workflows/pre-release.yml
> ci: Sync v0.34.x release workflows with main

- docs/tendermint-core/metrics.md
A follow up to https://github.com/tendermint/tendermint/pull/9682
Updates the documentation on metrics
> docs: add new metrics

- rpc/client/eventstream/eventstream.go
- rpc/client/eventstream/eventstream_test.go
- rpc/core/types/responses.go
For the full description, see https://github.com/tendermint/tendermint/pull/7987
---
> backport: add eventstream helper for rpc/client (#7987)

- spec/abci/abci++_methods.md
Closes #9713
Implement the decision recorded [here](https://github.com/tendermint/tendermint/issues/9713#issuecomment-1318871497)
The decision was that the spec should be adapted to match the current implementation (`ProcessProposal` is run by the consensus reactor of non-validating full nodes)
---
> Fix spec in `ProcessProposal` to align with implementation

- light/rpc/client.go
It seems the error message print the memory address of height (saw you pass height as pointer). In this PR, I update error message.
> patch: error message in light client

- spec/abci/abci++_app_requirements.md
> Fixes reference from recalled 0.36.x to 0.37.x

- .github/workflows/govulncheck.yml
- Makefile
Closes #9872. Supersedes #9873.
I'll add this as a required workflow for PRs to `main`, release and feature branches.
---
> ci: Add govulncheck workflow

- README.md
- docs/.vuepress/config.js
- docs/app-dev/abci-cli.md
- docs/tendermint-core/validators.md
updating the docs.tendermint.com site
> [fix] updating the docs.tendermint.com site

- README.md
- docs/.vuepress/config.js
- docs/app-dev/abci-cli.md
- docs/tendermint-core/validators.md
fixing inaccurate and outdated information.
> fix inaccuracies
