tendermint/tendermint

Makefile
The `proto-gen-docker` target didn't pull an updated Docker image, and would use a local image if present which could be outdated and produce wrong results.
=> Makefile: always pull image in proto-gen-docker.

p2p/pex/pex_reactor_test.go
Fixes #5941.
Not entirely sure that this will fix the problem (couldn't reproduce), but in any case this is an artifact of a hack in the P2P transport refactor to make it work with the legacy P2P stack, and will be removed when the refactor is done anyway.
=> test: fix TestPEXReactorRunning data race

.github/workflows/docker.yml
- avoid logging into docker hub when PR
- avoids breaking CI when an external contributor submits a PR
Closes: #XXX
=> docker: dont login when in PR

mempool/reactor_test.go
Update the faux router to either drop channel errors or handle them based on an argument. This prevents deadlocks in tests where we try to send an error on the mempool channel but there is no reader.
Closes: #5956
=> mempool: fix reactor tests

p2p/peer.go
Follow-up from #5947, branched off of #5954.
This simplifies the upgrade logic by adding explicit eviction requests, which can also be useful for other use-cases (e.g. if we need to ban a peer that's misbehaving). Changes:
* Add `evict` map which queues up peers to explicitly evict.
* `upgrading` now only tracks peers that we're upgrading via dialing (`DialNext` → `Dialed`/`DialFailed`).
* `Dialed` will unmark `upgrading`, and queue `evict` if still beyond capacity.
* `Accepted` will pick a random lower-scored peer to upgrade to, if appropriate, and doesn't care about `upgrading` (the dial will fail later, since it's already connected).
* `EvictNext` will return a peer scheduled in `evict` if any, otherwise if beyond capacity just evict the lowest-scored peer.
This limits all of the …
=> p2p: simplify PeerManager upgrade logic

p2p/peer.go, p2p/router.go
Adds a naïve `PeerManager.Advertise()` method that the new PEX reactor can use to fetch addresses to advertise, as well as some other `FIXME`s on address advertisement.
=> p2p: add PeerManager.Advertise()

blockchain/v0/reactor.go
Fixes the data race in usage of `WaitGroup`. Specifically, the case where we invoke `Wait` _before_ the first delta `Add` call when the current waitgroup counter is zero. See https://golang.org/pkg/sync/#WaitGroup.Add.
Still not sure how this manifests itself in a test since the reactor has to be stopped virtually immediately after being started (I think?).
Regardless, this is the appropriate fix.
closes: #5968
=> blockchain v0: fix waitgroup data race

.github/workflows/fuzz-nightly.yml
and preserve exit code.
```
2021/01/26 03:34:49 workers: 2, corpus: 4 (8m28s ago), crashers: 0, restarts: 1/9976, execs: 11013732 (21596/sec), cover: 121, uptime: 8m30s
make: *** [fuzz-mempool] Terminated
Makefile:5: recipe for target 'fuzz-mempool' failed
Error: Process completed with exit code 124.
```
https://github.com/tendermint/tendermint/runs/1766661614
`continue-on-error` should make GH ignore any error codes.
=> terminate go-fuzz gracefully (w/ SIGINT)

p2p/peer.go, p2p/pex/reactor.go, proto/tendermint/p2p/pex.go
This adds a prototype PEX reactor for the new P2P stack.
=> p2p: add prototype PEX reactor for new stack

p2p/netaddress.go, p2p/peer.go, p2p/pex/reactor.go
This changes the new prototype PEX reactor to resolve peer address URLs into IP/port PEX addresses itself. Branched off of #5974.
I've spent some time thinking about address handling in the P2P stack. We currently use `PeerAddress` URLs everywhere, except for two places: when dialing a peer, and when exchanging addresses via PEX. We had two options:
1. Resolve addresses to endpoints inside `PeerManager`. This would introduce a lot of added complexity: we would have to track connection statistics per endpoint, have goroutines that asynchronously resolve and refresh these endpoints, deal with resolve scheduling before dialing (which is trickier than it sounds since it involves multiple goroutines in the peer manager and router and messes with peer rating order), handle IP address visibility …
=> p2p: resolve PEX addresses in PEX reactor

mempool/reactor.go, mempool/reactor_test.go
Fix the timeout issue for the mempool tests by dropping mempool channel errors for _all_ reactors, not just the "primary".
closes: #5956
=> mempool: really fix mempool tests timeout

docs/nodes/state-sync.md
https://233.123.0.140:26657:26657/commit --> https://233.123.0.140:26657/commit
Closes: #XXX
=> docs: fix typo in state sync example

rpc/jsonrpc/client/http_json_client_test.go
This test relied on connecting to the external site `foo-bar.net`, and (predictably) the site went down and broke all of our CI runs. This changes it to use local HTTP servers instead.
=> test: don't use foo-bar.net in TestHTTPClientMakeHTTPDialer

p2p/switch_test.go
Fixes #5998. Sometimes the connection returns "use of closed network connection" instead, so for now we just accept any error. The switch is not long for this world anyway.
=> test: fix TestSwitchAcceptRoutine flake by ignoring error type

p2p/pex/pex_reactor_test.go
This test occasionally fails because the peer is already stopped. It is unclear to me exactly what this test is supposed to do, since calling `FlushStop()` will stop the peer, but the test asserts that the peer shouldn't have been stopped by `FlushStop()` since calling `Stop()` afterwards will error in that case.
The current PEX reactor will be removed in the new P2P stack anyway.
=> test: disable TestPEXReactorSeedModeFlushStop due to flake

p2p/transport_memory.go
This patches over a test data race where the logger would try to read struct internals via `reflect` while these were concurrently modified (specifically `MemoryTransport.closeOnce`).
=> test: fix test data race in p2p.MemoryTransport with logger

p2p/switch_test.go
Another fix for `TestSwitchAcceptRoutine` following from #6000, since the `SetDeadline()` call also errors when the connection has been closed.
=> test: fix TestSwitchAcceptRoutine by ignoring spurious error

p2p/router_test.go
Fixes #5981, which was caused by changes in Router behavior after the introduction of the peer manager, leading to a race condition that could halt the test.
This is a temporary measure, I'll start tightening up the new P2P core tomorrow and write "real" tests with better test infrastructure.
=> test: fix TestRouter to take into account PeerManager reconnects

p2p/router.go, p2p/router_test.go
Fixes #6004 by reordering test to avoid race condition. Will redesign router tests to be resistant to this later.
=> test: fix flaky router broadcast test

mempool/reactor_test.go, p2p/key.go, p2p/peer.go, p2p/router.go, p2p/router_test.go, p2p/switch.go, p2p/switch_test.go, p2p/transport.go, p2p/transport_mconn.go, p2p/transport_mconn_test.go, p2p/transport_memory.go, p2p/transport_memory_test.go, p2p/transport_test.go
This tightens up the new P2P `Transport` API and infrastructure, fixes a bunch of bugs and inconsistencies, and adds tests.
=> p2p: tighten up and test Transport API

CHANGELOG_PENDING.md, light/provider/http/http.go, rpc/client/http/http.go, rpc/client/rpc_test.go, types/validator_set.go
=> light/provider/http: fix Validators

.github/workflows/e2e-nightly.yml
This reverts commit 64961e22673a796782b0db54dab7fd06bd3aa7b4, to see if it will make the workflow dispatch trigger reappear. 
(Apologies for testing our tooling on master, but given that we're looking at branch funkiness, I think it's necessary.)
=> Revert "e2e: releases nightly (#5906)"

test/e2e/tests/validator_test.go
E2E tests often fail because validators miss signing or proposing blocks. Often this is because e.g. there's a lot of disruption in the network or it takes a long time to start up all the nodes.
This changes the test criteria to only check for 3 signed/proposed blocks, rather than a fraction of the expected blocks. This should be enough to catch most issues, apart from performance problems causing nodes to miss signing/proposing, but we may want separate tests for those sorts of things.
=> test/e2e: increase sign/propose tolerances

rpc/jsonrpc/client/http_json_client_test.go
Erik's PR: 
>This test relied on connecting to the external site `foo-bar.net`, and (predictably) the site went down and broke all of our CI runs. This changes it to use local HTTP servers instead.
Are their any other tests we should backport to `v0.34.x`?
=> tests: backport TestHTTPClientMakeHTTPDialer fix

.github/PULL_REQUEST_TEMPLATE.md
I got tired of seeing the literal phrase "Closes #XXX" left in PR bodies. 
Also, this template isn't usually viewed as rendered markdown, so I've removed the markdown formatting and the "Description" heading (which usually gets deleted anyways).
=> .github: clean up PR template

.golangci.yml
=> .golangci: set locale to US for misspell linter

docs/tendermint-core/state-sync.md
=> docs: fix typo in state sync example (#5989)

consensus/replay.go, libs/bytes/bytes.go, libs/bytes/bytes_test.go, libs/log/tm_logger.go, libs/log/tm_logger_test.go, libs/log/tmfmt_logger.go, libs/log/tmfmt_logger_test.go, light/client.go, mempool/clist_mempool.go, state/execution.go, statesync/syncer.go, test/maverick/consensus/replay.go
Cherry-picks d76add65a66635f2c97374605bb85a4f6415acff
=> Backport libs/log: format []byte as hexidecimal string (uppercased) (#5960)

.goreleaser.yml
before:
```
Tendermint_0.34.3_darwin_amd64.tar.gz
-rw-r--r--  0 runner docker 192329 Jan 19 19:30 CHANGELOG.md
-rw-r--r--  0 runner docker    321 Jan 19 19:30 CHANGELOG_PENDING.md
-rw-r--r--  0 runner docker  11382 Jan 19 19:30 LICENSE
-rw-r--r--  0 runner docker   8165 Jan 19 19:30 README.md
-rwxr-xr-x  0 runner docker 23224320 Jan 19 19:30 tendermint
```
after:
```
tendermint_0.34.3_darwin_amd64.tar.gz
-rw-r--r--  0 runner docker 192329 Jan 19 19:30 CHANGELOG.md
-rw-r--r--  0 runner docker    321 Jan 19 19:30 CHANGELOG_PENDING.md
-rw-r--r--  0 runner docker  11382 Jan 19 19:30 LICENSE
-rw-r--r--  0 runner docker   8165 Jan 19 19:30 README.md
-rwxr-xr-x  0 runner docker 23224320 Jan 19 19:30 tendermint
```
=> goreleaser: downcase archive and binary names (#6029)

Makefile
Remove mystery `tools` call, which seemed to do nothing other than change our go.mod on Linux
=> makefile: remove call to tools

rpc/jsonrpc/client/http_json_client_test.go
This test relied on connecting to the external site `foo-bar.net`, and (predictably) the site went down and broke all of our CI runs. This changes it to use local HTTP servers instead.
=> test: don't use foo-bar.net in TestHTTPClientMakeHTTPDialer (#5997)

.github/mergify.yml, CONTRIBUTING.md
Makes the label `backport-to-v0.34.x` handle auto backports
=> backports: mergify

CHANGELOG_PENDING.md, abci/client/client.go, abci/client/socket_client.go
Fixes the race condition between a callback being set and called during ReCheckTx. Note, I do not see equivalent logic in the gRPC client (anymore) as #5439 suggests, so only the socket client was updated.
closes: #5439
=> ABCI: Fix ReCheckTx for Socket Client

.goreleaser.yml, CHANGELOG.md
=> .goreleaser: remove arm64 build instructions and bump changelog again

consensus/byzantine_test.go, consensus/reactor_test.go
Missed setting the buffer size on the subscription. Note, this doesn't really "fix" this test (a la ref: https://github.com/tendermint/tendermint/pull/5710).
However, I spent a good chunk of time looking at this test with many logs and I'm pretty sure this is mainly due to the fact that none of the nodes get the conflicting vote in time.
closes: #6127
=> tests: Fix TestByzantinePrevoteEquivocation

.github/workflows/jepsen.yml
fixes https://github.com/tendermint/tendermint/runs/1924860805
```
Run docker exec -it jepsen-control 'cd tendermint && lein run test
--nemesis  --workload ' the input device is not a TTY
```
=> .github: [jepsen] fix inputs and remove TTY from docker

.github/workflows/jepsen.yml
Fixes https://github.com/tendermint/tendermint/runs/1925329781
```
OCI runtime exec failed: exec failed: container_linux.go:370: starting
container process caused: exec: "lein run test --nemesis none --workload
cas-register --concurrency 10 --tendermint-url
https://github.com/melekes/katas/releases/download/0.2.0/tendermint.tar.gz
--merkleeyes-url
https://github.com/melekes/katas/releases/download/0.2.0/merkleeyes_0.1.7.tar.gz":
stat lein run test --nemesis none --workload cas-register --concurrency
10 --tendermint-url
https://github.com/melekes/katas/releases/download/0.2.0/tendermint.tar.gz
--merkleeyes-url
https://github.com/melekes/katas/releases/download/0.2.0/merkleeyes_0.1.7.tar.gz:
no such file or directory: unknown
```
=> .github: [jepsen] use "bash -c" to execute lein run cmd

.github/workflows/jepsen.yml
fixes https://github.com/tendermint/tendermint/runs/1926771645
```
ERROR [2021-02-18 12:16:30,492] main - jepsen.cli Oh jeez, I'm sorry,
Jepsen broke. Here's why:
clojure.lang.ExceptionInfo: throw+: {:dir "/", :private-key-path nil,
:password "root", :username "root", :type :jepsen.control/session-error,
:port 22, :strict-host-key-checking false, :host nil, :sudo nil, :dummy
false, :message "Error opening SSH session. Verify username, password,
and node hostnames are correct.", :session nil}
```
=> .github: [jepsen] source .bashrc

consensus/state.go
ref: https://github.com/tendermint/tendermint/issues/5912
=> consensus: more log grooming

cmd/tendermint/commands/light.go, light/provider/http/http.go, light/rpc/client.go, rpc/jsonrpc/client/http_json_client.go
This PR makes the following changes:
- Reduces the default timeout and retry attempts from 5 seconds and 10 attempts to 3 seconds and 5 attempts. This reduces the total possible time for a light client request from 200 seconds to just over 50 seconds
- Takes advantage of the RPC error changes to only retry a request when a provider hasn't responded
- Adds a timeout to the light rpc server which is equivalent to the write timeout set in the config
=> light: improve timeout functionality

p2p/address.go, p2p/address_test.go
I'm not so well versed with regex so I used `strings.Contains()` instead. If you want a regex based solution then please let me know what I need to add.
Basically, the `reHasScheme` wasn't strict enough when deciding whether something was scheme-less or not hence it was considering scheme-less IPv6 strings (which contain `:`) as having a scheme.
Closes: #6133
=> p2p: enable scheme-less parsing of IPv6 strings

.goreleaser.yml
GoReleaser has been updated to automatically ignore darwin/arm64 for versions
of Go < 1.16, so it should be safe to add these release configurations back in.
=> goreleaser: reintroduce arm64 build instructions

CHANGELOG_PENDING.md, rpc/core/tx.go, rpc/openapi/openapi.yaml
=> rpc: change default sorting to desc for `/tx_search` results

docs/security/vulnerability-names.md
I'm also going to add the retros for all previous security incidents to this directory - I'd like to have them somewhere more central than the Cosmos Forum, where they currently live.
=> docs/security: add preallocated list of security vulnerability names

CHANGELOG_PENDING.md, rpc/client/http/http.go
```
// unbuffered
out, err := httpClient.Subscribe(ctx, "event.type=NewTx and account.name=Jack", 0)
// buffered
out, err := httpClient.Subscribe(ctx, "event.type=NewTx AND account.name=Jack", 20)
```
Before: when the `out` channel is buffered and becomes full, we drop an event (+ log the error)
After: when the `out` channel is buffered and becomes full, we block
**Before it was not apparent to the app when an event was dropped (looking at the logs is manual task). After this PR, if the user does not read from `out` on 1 subscription, all other subscriptions will be stuck too.**
Closes #6161
=> rpc/client/http: Do not drop events even if the `out` channel is full

libs/service/service.go
Fixes marshaling error in sdk
closes https://github.com/cosmos/cosmos-sdk/issues/8578
the output stays the same, we are avoiding the passing of the callback because sdk uses typed logging.
=> logging: print string instead of callback

CHANGELOG_PENDING.md, cmd/tendermint/commands/debug/dump.go, cmd/tendermint/commands/debug/kill.go, cmd/tendermint/commands/light.go, light/provider/http/http.go, light/provider/http/http_test.go, rpc/client/examples_test.go, rpc/client/http/http.go, rpc/client/http/ws.go, rpc/client/rpc_test.go, rpc/jsonrpc/client/http_json_client.go, rpc/jsonrpc/client/ws_client.go, rpc/openapi/openapi.yaml, statesync/stateprovider.go, test/e2e/pkg/testnet.go
also
- replace `MaxReconnectAttempts`, `ReadWait`, `WriteWait` and `PingPeriod` options with `WSOptions` in `WSClient` (rpc/jsonrpc/client/ws_client.go).
- set default write wait to 10s for `WSClient`(rpc/jsonrpc/client/ws_client.go)
- unexpose `WSEvents`(rpc/client/http.go)
Closes #6162
=> rpc/client/http: drop endpoint arg from New and add WSOptions

docs/tutorials/go-built-in.md
The following code in "Creating a built-in application in Go" had a small bug that prevented the application from being built, so we fixed it.
- unused import errors
- `cfg.DefaultLogLevel` is not function
=> docs/tutorials: fix sample code

CHANGELOG_PENDING.md, rpc/jsonrpc/types/types.go
i.e. without double pointer. With double pointer, it was possible to
submit `null` value, which will crash the server.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x189ddc0]
goroutine 1 [running]:
github.com/tendermint/tendermint/rpc/jsonrpc/types.(*RPCRequest).UnmarshalJSON(0xc0000147e0, 0xc00029f201, 0x4, 0x1ff, 0x883baa0, 0xc0000147e0)
/Users/anton/go/src/github.com/tendermint/tendermint/rpc/jsonrpc/types/types.go:70 +0x100
encoding/json.(*decodeState).literalStore(0xc000216bb0, 0xc00029f201, 0x4, 0x1ff, 0x1998800, 0xc0000147e0, 0x199, 0xc000231700, 0x10e0a5e, 0x197)
/usr/local/Cellar/go/1.16/libexec/src/encoding/json/decode.go:860 +0x30ce
encoding/json.(*decodeState).value(0xc000216bb0, …
```
=> rpc/jsonrpc: Unmarshal RPCRequest correctly

mempool/clist_mempool.go, mempool/clist_mempool_test.go, test/app/counter_test.sh
I have been seeing this error being logged repeatedly in the e2e tests. AFAIK, there's nothing wrong with multiple peers sending the same tx to the same node.
```
E[2021-03-03|10:04:05.373] checktx failed for tx module=mempool peer=539ffc12a0ac78970dab31ae8cdcfdd4285b2162 tx=74B08D5A229A9E907F1586DB4D7835ED20F5F9BE40042ABEF09F7AA9B11B0088 err="tx already exists in cache"
``` 
Since we track senders, I've left it to returning the error if the same sender sends the same tx, otherwise it just logs it as `Debug`.
cc: @alexanderbez, @melekes
=> mempool: don't return an error on checktx with the same tx

state/state.go
I couldn't find any references to `state.NextState(...)`. Looks like `updateState` replaced that function
=> update outdated comment in state.go

store/store.go, store/store_test.go
Closes: #5698
This is probably the least obtrusive way of making this change (the API stays the same and it's easier to revert in a later PR if need be). 
By keeping the height argument we can still theoretically have multiple seen commits but in practice we will always replace the seen commit with the canonical one meaning that we should only ever have one seen commit.
=> blockstore: save only the last seen commit

proto/tendermint/abci/types.proto, types/block.go
Since events are not hashed into the header they can be non deterministic. Changing an event is not consensus breaking. Will update docs in the spec
=> note: add nondeterministic note to events

consensus/byzantine_test.go
- wrap the body of a for-loop in a function so that the defer
os.RemoveAll cleans up after every iteration rather than at the end
of the test. I suspect this is the thing that fixes it because it
lets things go out of scope quicker, and maybe reduces numbers of
files, which was showing up in stacks. 
- some minor cleanup to the spin/wait-forever function at the end of
the test.
This could also be totally random.
=> test: cleanup consensus test

evidence/reactor_test.go
this fixes a timing-dependent assertion in the current test which is
failing inconsistently (but, I think, particularly in CI.)
=> fix: make p2p evidence_pending test not timing dependent

.golangci.yml, blockchain/v2/reactor_test.go, crypto/hash.go, crypto/merkle/proof_value.go, mempool/clist_mempool_test.go, p2p/pex/addrbook.go, statesync/snapshots.go
fixes linter to comply with golangci-lint v1.38
=> linter: fix nolintlint warning

config/config.go, node/node.go, p2p/pqueue.go, p2p/queue.go, p2p/router.go, p2p/router_init_test.go, p2p/wdrr_queue.go, p2p/wdrr_queue_test.go, test/e2e/docker/Dockerfile
This just centralizes how we construct queue instances and avoids using the fifo queue for ingestion and a different queue for outgoing messages. 
It presently defaults to FIFO unless its explicitly overridden, but we may want to use the priority algorithm.
=> Add Queue Factory function to support injecting router schedulers

node/node.go, p2p/pqueue.go, p2p/queue.go, p2p/router.go, p2p/router_init_test.go, p2p/router_test.go, p2p/wdrr_queue.go, p2p/wdrr_queue_test.go, test/e2e/docker/Dockerfile
An alternative implementation with a priority queue and dequeuing immediately after enqueueing. **Better** results compared to the WDRR scheduler.
Note: We still experience https://github.com/tendermint/tendermint/issues/6208, but it's not clear if its the scheduler implementation(s) or the consensus reactor refactor.
=> p2p: message queue alternative w/ priority queue

test/e2e/networks/ci.toml, test/e2e/runner/perturb.go
seeds nodes don't run an RPC so unfortunately when we tried to check the status of the node the testnet was panicking (because status was nil). 
This PR corrects this
=> e2e: fix perturbation of seed nodes

blockchain/v0/reactor_test.go, consensus/reactor_test.go, evidence/reactor_test.go, mempool/reactor_test.go, p2p/p2ptest/network.go, p2p/router_test.go, p2p/transport_memory.go, p2p/transport_memory_test.go
I opted to make a "p2ptest.NetworkOptions" struct to hold arguments to
"MakeNetwork" rather than pass two arguments of the same type.
=> p2p test infra: make memory network test buffers configurable

consensus/peer_state.go, consensus/types/peer_round_state.go, consensus/types/peer_round_state_test.go, libs/bits/bit_array.go, libs/bits/bit_array_test.go
I suspect this was tickled by the recent p2p change, but the underlying issue (copying structs doesn't copy the values at the other end of pointers) seems to be outstanding, and I think this change better realizes the original goal of the code at hand.
=> fix: avoid race with a deeper copy

DOCKER/README.md, docs/app-dev/getting-started.md, docs/architecture/adr-052-tendermint-mode.md, docs/introduction/install.md, docs/introduction/quick-start.md, docs/tendermint-core/using-tendermint.md
We changed the cli beforehand to use `start` instead of `node`. This just updates some of the docs to reflect that change
=> docs: use start command instead of node command

CHANGELOG_PENDING.md, p2p/peer.go
New Peers are created passing a list of static channels.
When adding a new CustomReactor to NewNode, the new channel(s) used by
that reactor were not passed to the new peers, creating an error when
peers tried to communicate.
Closes #6289
=> Fix "Unknown Channel" bug on CustomReactors

node/node.go, p2p/router.go, p2p/router_filter_test.go
Wanted to validate the approach before going to far down. 
I think the real risk here is that an application can put back pressure on the p2p layer which might not be desirable.
=> p2p: filter peers by IP address and ID

libs/clist/clist.go
This should resolve the #2209 issue. 
Since there are no callers (anymore?) of CList.Init, it seems safe to
just fold this into the constructor, obviating the problem entirely. I
might be missing something, though :)
=> fix: theoretical leak in clisit.Init

state/indexer/block/kv/kv.go
copy 🍝  bug when porting similar logic from the tx indexing code.
=> state: fix block event indexing reserved key check

p2p/router_test.go
With some tweaking, I believe that some of the router mock tests have
a timing/parallelism assumption that is causing some observed
non-deterministic behavior, which these changes help reduce.
Addresses #6119, but we should decide if it's worth closing the ticket
or not.
=> p2p: improve router test stability

evidence/reactor.go
We don't use the event bus in the evidence reactor nor do I think we will need to. This PR removes it. @alexanderbez perhaps you might have an explanation for why it is there that I've overlooked
=> evidence: remove event bus from reactor

consensus/byzantine_test.go, consensus/common_test.go, consensus/invalid_test.go, consensus/mempool_test.go, consensus/reactor_test.go, consensus/replay_test.go, consensus/state_test.go
This covers most of the shared state that seems to be causing the
effects in #4769. There are a couple of other mutable package
variables that could contribute to this effect, but I think we should
split up the change. 
Presumably the this PR won't work in its inital version because if
there are implict ordering effects that aren't being handled, then
they (and other related bugs) will become turn into consistent
failures.
I'm putting this up for review a bit early, to work on getting it through
CI. Sorry if it ends up lingering a bit.
=> consensus: reduce shared state in tests

light/detector_test.go, light/provider/mock/mock.go
adds a mutex to the mock provider so that there isn't a data race when running the tests
=> light: fix deadlock in light tests

CHANGELOG_PENDING.md, node/node.go, node/node_test.go, p2p/mock/reactor.go, p2p/node_info.go, p2p/node_info_test.go, p2p/peer.go, p2p/transport.go, p2p/transport_test.go
Previously, we were supporting custom reactors but weren't adding the channel of the custom reactor to the nodeInfo, this means nodes were not able to broadcast that they could receive messages to this custom reactor. 
#6297 attempted to fix this but in fact was replacing the peers available channels that the node received in the handshake with its own channels (thus it would think that it all its peers have the same channel that it does). Trudging through this I could see why it was confusing because `peerConfig` is actually information about the node itself not the peer. 
I tried to find a way to still allow using custom reactors without doing any breaking changes hence I'm not particularly happy with this fix but I can't really think of a better solution. 
Closes: #6338
=> p2p: fix using custom channels

CHANGELOG_PENDING.md, light/client.go
This was causing some robutness faults in the state sync and was missed out when writing up the light client security issue
=> light: handle too high errors correctly

CONTRIBUTING.md, docs/architecture/README.md, docs/architecture/adr-066-e2e-testing.md, docs/rfc/README.md
Per conversations earlier today, we'll consider all proposed implementation changes part of the ADR process rather than the RFC process (which will remain, for now, on the spec; this may get incorporated instead into the burgeoning "CIPS" process). 
This change renames RFC 1 to ADR 66, leaving space for the not-yet-merged ADR 65.
=> docs: remove RFC section and s/RFC001/ADR066

CHANGELOG_PENDING.md, light/proxy/routes.go, rpc/core/routes.go, rpc/jsonrpc/doc.go, rpc/jsonrpc/jsonrpc_test.go, rpc/jsonrpc/server/http_json_handler.go, rpc/jsonrpc/server/http_json_handler_test.go, rpc/jsonrpc/server/http_server.go, rpc/jsonrpc/server/http_server_test.go, rpc/jsonrpc/server/http_uri_handler.go, rpc/jsonrpc/server/parse_test.go, rpc/jsonrpc/server/rpc_func.go, rpc/jsonrpc/test/main.go, test/fuzz/rpc/jsonrpc/server/handler.go
This PR added the "cache-control" into the HTTP-RPC response header and set the cache expired time to one year
Closes #5764
=> Set cache control in the HTTP-RPC response header

config/config.go, config/toml.go, docs/nodes/configuration.md, node/node.go, p2p/router.go, test/e2e/generator/generate.go, test/e2e/networks/ci.toml, test/e2e/pkg/manifest.go, test/e2e/pkg/testnet.go, test/e2e/runner/setup.go
I wanted to address the point `Merge MaxNumInboundPeers and MaxNumOutboundPeers into MaxConnections.` from the p2p tracking issue, but realized we cannot remove those fields until we remove _all_ of the legacy stack.
So this PR just tweaks the current router options to use both max in and out plus some minor cleanup:
- Rename legacy flag
- Add new `MaxIncomingConnectionAttempts` config
- Add new `MaxConnections` config (will replace `MaxNumInboundPeers` and `MaxNumOutboundPeers`)
/cc @tessr
=> p2p: minor cleanup + update router options

test/e2e/runner/benchmark.go
just a small change to produce some more structured data from benchmarks for easier comparison between/among runs.
=> test/e2e: produce structured reporting from benchmarks

light/client.go, light/detector.go, light/errors.go, mempool/reactor.go, test/e2e/runner/perturb.go, test/e2e/runner/start.go, test/e2e/tests/app_test.go
Futher relaxes some timeouts that were causing failures.
This PR also removes duplicated light client error and quietens the log message for when duplicate txs are submitted
=> e2e: relax timeouts

scripts/keymigrate/migrate.go, scripts/keymigrate/migrate_test.go
This just includes the migration code and pretty extensive
tests. We'll have to integrate this into some CLI tool, or potentially
into the SDK rather than tendermint propper. I think it makes sense to
deal with the integration/operationalization questions seperate from
the migration itself.
=> db: migration script for key format change

p2p/p2ptest/network.go, p2p/p2ptest/require.go, p2p/router_test.go
The test really just needs to assert that the proper updatese are
sent, I think having extra updates in the channel when the tests are
over isn't really a problem in this case.
=> p2p: fix network update test

.github/CODEOWNERS
Expanding the list of people who can sign off on PRs. 
(And effectively backporting some changes from master.)
=> .github: make core team codeowners

statesync/snapshots_test.go
Somehow my previous attempt to fix this test was somewhat
non-deterministic. I think I misjudged how the "median" would impact
the test.
I ran the test in question 10 times without seeing a failure (which
would show up 10-30% of the time previously,) so I'm pretty sure this
is fixed.
=> statesync: fix unreliable test

.github/workflows/e2e-nightly-master.yml, test/e2e/generator/generate.go, test/e2e/generator/main.go
Added a flag to the e2e generator which specifies which p2p system to use. Then I updated the nightly workflow so that a separate job is run for each p2p system
=> e2e: split out nightly tests

statesync/snapshots_test.go
I just ran the test 10k times and it it didn't fail, so I think this
is fixed (It was failing, maybe 20 percent of the time before.)
=> statesync: peer ranking test fix

mempool/bench_test.go
This should resolve #2122, and adds a benchmark for adding a duplicate
Tx to the mempool, as described in the intial ticket. I think this
benchmark, see blow, shows that there isn't an additional overhead for
adding a duplicate transaction relative to adding a transaction in
general.
```bash 
$ go test -benchmem -bench=. -run="Bench.*" ./mempool
goos: linux                                                          
goarch: amd64
pkg: github.com/tendermint/tendermint/mempool
cpu: Intel(R) Core(TM) i7-4820K CPU @ 3.70GHz
BenchmarkReap-8                     1220           1001954 ns/op          485781 B/op      10001 allocs/op
BenchmarkCheckTx-8                262141              5363 ns/op            1553 B/op         32 allocs/op
BenchmarkCheckDuplicateTx-8       179866              6014 …
```
=> mempool: add duplicate transaction and parallel checktx benchmarks

node/node.go, rpc/client/local/local.go, rpc/client/mock/client.go, rpc/core/abci.go, rpc/core/blocks.go, rpc/core/blocks_test.go, rpc/core/consensus.go, rpc/core/dev.go, rpc/core/env.go, rpc/core/env_test.go, rpc/core/events.go, rpc/core/evidence.go, rpc/core/health.go, rpc/core/mempool.go, rpc/core/net.go, rpc/core/net_test.go, rpc/core/routes.go, rpc/core/status.go, rpc/core/tx.go, rpc/grpc/api.go, rpc/grpc/client_server.go
This is a first step in #6424, and a prerequsite for cleaning up the client tests.
=> rpc: remove global environment

libs/os/os.go, libs/os/os_test.go
This change fixes a potential exploitable vulnerability
that can cause the WAL to be consistently truncated by falsely
supplying the WAL path which would be any arbitrary dirrectory.
The problem came from CopyFile blissfully assuming that paths
passed into it would always be a regular file, assuming that os.Open
for directories would fail, but really it will always pass; it then
went ahead and truncated the destination file and then on trying
to copy failed, which wouldn't rollback any prior changes.
While here, took advantage of using (*os.File).Stat() instead of
firstly invoking os.Stat; yet *os.File has this information and
can trivially return it.
Fixes #6427
=> libs/os: avoid CopyFile truncating destination before checking if regular file

CHANGELOG_PENDING.md, consensus/reactor.go, consensus/replay.go, consensus/state.go, node/node.go, state/execution.go, state/execution_test.go, types/events.go
The current consensus reactor will stop mechanism has a chance to cause the data missing with the indexer services. Therefore we introduce a graceful stop if the consensus module is trying to commit the block. The OnStop process will wait for the block commit to finish and then continue the shutdown process.
Also, emit the index services-related events when the node replays the final block.
Closes:#5002
Might solves:#5851
=> node/state: graceful shutdown in the consensus state

DOCKER/README.md
A node type is required for `tendermint init`. I added the same mentionned on https://docs.tendermint.com/master/introduction/quick-start.html#initialization
Following the current doc on docker hub we face the following error message:
```
$ docker run -it --rm -v "/tmp:/tendermint" tendermint/tendermint init
ERROR: must specify a node type: tendermint init [validator|full|seed]
```
=> Update DOCKER/README.md to make init succeed

config/toml.go
Should give a warning in config until this is below issue is resolved
Related to https://github.com/tendermint/tendermint/issues/3055
=> config: Add private peer id /net_info expose information in default config

libs/log/tmfmt_logger.go
Noticed from profiling that the loggers are memory hungry and alas,
we were passing fmt.Sprintf strings to (*bytes.Buffer).WriteString
which defeats the purpose of using fmt.* This change fixes that and
instead directly invokes fmt.Fprintf.
The benchmarks show the improvement:
```shell
$ benchstat before.txt after.txt
name                     old time/op    new time/op    delta
TMLoggerSimple-8           1.67µs ± 4%    1.69µs ±13%     ~     (p=0.118 n=20+19)
TMLoggerContextual-8       2.01µs ± 8%    1.94µs ± 1%   -3.79%  (p=0.000 n=18+20)
TMFmtLoggerSimple-8        1.20µs ± 3%    1.16µs ± 2%   -3.39%  (p=0.000 n=20+16)
TMFmtLoggerContextual-8    1.53µs ±19%    1.43µs ±13%   -6.10%  (p=0.001 n=20+20)
name                     old alloc/op   new alloc/op   delta
TMLoggerSimple-8 …
```
=> libs/log: use fmt.Fprintf directly with *bytes.Buffer to avoid unnecessary allocations

light/proxy/routes.go
Whilst poking around the light client, I realised that the `/net_info` endpoint ends up panicking the light client rpc server. Did a sneaky git blame and it looks like this bugs been around for 2 years.
I've tested this locally to make sure that the endpoint is working now
=> light: fix net_info call on light rpc

p2p/conn/connection.go, p2p/conn/connection_test.go
Per tendermint spec, each Channel has a globally unique byte id, which
is mapped to uint8 in Go. However, the proto PacketMsg.ChannelID field
is declared as int32, and when receive the packet, we cast it to a byte
without checking for possible overflow. That leads to a malform packet
with invalid channel id is sent successfully.
To fix it, we just add a check for possible overflow, and return invalid
channel id error.
Fixed #6521
=> p2p/conn: check for channel id overflow before processing receive msg

CHANGELOG_PENDING.md, consensus/mempool_test.go, consensus/reactor_test.go, consensus/replay_stubs.go, consensus/replay_test.go, mempool/mempool.go, mempool/mock/mempool.go, mempool/tx.go, mempool/v0/bench_test.go, mempool/v0/cache_test.go, mempool/v0/clist_mempool.go, mempool/v0/clist_mempool_test.go, mempool/v0/reactor.go, mempool/v0/reactor_test.go, mempool/v1/mempool.go, mempool/v1/mempool_bench_test.go, mempool/v1/mempool_test.go, mempool/v1/reactor.go, node/node_test.go, rpc/client/rpc_test.go, rpc/core/mempool.go, test/fuzz/mempool/checktx.go
Remove `Context` from the `TxInfo` type and instead require the caller to pass a `Context` to `CheckTx` which is idiomatic.
closes: #6497
=> improvement: update TxInfo

cmd/tendermint/commands/light.go, light/client.go, light/client_test.go
This PR fixes a bug where `NewClientWithTrustedStore` will create a light client even if the trusted store is empty (we need at least one block).
This PR also cleans up a lot of the initialization logic to make it easier to follow. You either initialize with trusted options or a trusted store. Finally, I've removed the confimation function option.
=> light: clean up initialization

state/indexer/sink/psql/psql.go, state/indexer/sink/psql/psql_test.go, state/indexer/sink/psql/schema.sql
Base on the comment in PR #6535
https://github.com/tendermint/tendermint/pull/6535#issuecomment-856718249
Uses `INSERT...ON CONFLICT` in the block/tx event insert functions. If the eventsink tries to insert duplicate events to the PSQL database. the database will ignore the insert and not return an error.
=> state/indexer: use INSERT...ON CONFLICT in the psql eventsink insert functions

internal/blockchain/v0/reactor.go
There is a possible data race/panic between processBlockchainCh and
processPeerUpdates, since when we send to blockchainCh.Out in one
goroutine and close the channel in the other. The race is seen in some
Github Action runs.
This commit fix the race, by adding a peerUpdatesCh as a bridge between
processPeerUpdates and processBlockchainCh, so the former will send to
this channel, the later will listen and forward the message to
blockchainCh.Out channel.
Updates #6516
=> blockchain/v0: fix data race in blockchain channel

CHANGELOG_PENDING.md, internal/blockchain/v0/reactor.go, internal/blockchain/v0/reactor_test.go, internal/blockchain/v2/processor_context.go, internal/blockchain/v2/reactor.go, internal/blockchain/v2/reactor_test.go, internal/consensus/byzantine_test.go, internal/consensus/common_test.go, internal/consensus/reactor_test.go, internal/consensus/replay.go, internal/consensus/replay_file.go, internal/consensus/replay_test.go, internal/consensus/state.go, internal/consensus/wal_generator.go, node/node.go, node/node_test.go, state/execution.go, state/execution_test.go, state/helpers_test.go, state/validation_test.go
state: move pruneBlocks function from consensus/state to state/execution
Closes #5414
=> state: move pruneBlocks from consensus/state to state/execution

test/e2e/runner/rpc.go
`waitForHeight` can get stuck in an infinite loop because the max result gets updated when the result is equal or greater when it should be strictly greater. This means when a chain is not making progress and is stuck on the same height it will never timeout
=> e2e: fix looping problem while waiting for testnet

.golangci.yml
Enabled the ASCII check linter
https://github.com/tdakkota/asciicheck
Closes #2801
=> linter: linter checks non-ASCII identifiers

test/fuzz/oss-fuzz-build.sh
So oss-fuzz can start building and continuous fuzzing these packages.
Updates #6557
=> test/fuzz: add current fuzzing to oss-fuzz-build script

test/fuzz/oss-fuzz-build.sh
=> test/fuzz: fix wrong path for some p2p fuzzing packages

CHANGELOG_PENDING.md, config/config.go, statesync/reactor.go, statesync/syncer.go, test/e2e/generator/generate.go, test/e2e/runner/load.go, test/e2e/runner/rpc.go
This is predominantly a non-breaking backport of  #6587
=> statesync: increase chunk priority and robustness

CHANGELOG.md, version/version.go
I find it a bit repetitive to remind users of the bug bounty for every release. This PR removes all the reminders and replaces it with a single one at the top of the changelog
=> changelog: have a single friendly bug bounty reminder

CHANGELOG_PENDING.md, internal/blockchain/v0/reactor.go, internal/blockchain/v0/reactor_test.go, internal/blockchain/v2/processor.go, internal/blockchain/v2/processor_context.go, internal/blockchain/v2/reactor.go, internal/blockchain/v2/reactor_test.go, internal/consensus/metrics.go, internal/consensus/reactor.go, internal/consensus/state.go, node/node.go, node/setup.go
=> fastsync: update the metrics during fast-sync

internal/blockchain/v0/reactor.go, internal/blockchain/v2/reactor.go, internal/consensus/reactor.go, internal/evidence/reactor.go, internal/mempool/v0/reactor.go, internal/mempool/v1/reactor.go, internal/p2p/pex/reactor.go, internal/p2p/router.go, internal/statesync/reactor.go, node/setup.go
Having smaller buffers in each reactor/channel will mean that there will be fewer stale messages.
=> p2p: reduce buffering on channels

CHANGELOG_PENDING.md, crypto/batch/batch.go, crypto/crypto.go, crypto/ed25519/bench_test.go, crypto/ed25519/ed25519.go, crypto/ed25519/ed25519_test.go, crypto/sr25519/batch.go, crypto/sr25519/bench_test.go, crypto/sr25519/encoding.go, crypto/sr25519/privkey.go, crypto/sr25519/pubkey.go, crypto/sr25519/sr25519_test.go, go.mod, go.sum, internal/p2p/conn/evil_secret_connection_test.go, internal/p2p/conn/secret_connection.go, privval/secret_connection.go, types/validation.go
At Oasis we have spend some time writing a new Ed25519/X25519/sr25519 implementation called curve25519-voi.  This PR switches the import from ed25519consensus/go-schnorrkel, which should lead to performance gains on most systems.
Summary of changes:
* curve25519-voi is now used for Ed25519 operations, following the existing ZIP-215 semantics.
* curve25519-voi's public key cache is enabled (hardcoded size of 4096 entries, should be tuned, see the code comment) to accelerate repeated Ed25519 verification with the same public key(s).
* (BREAKING) curve25519-voi is now used for sr25519 operations.  This is a breaking change as the current sr25519 support does something decidedly non-standard when going from a MiniSecretKey to a SecretKey and or PublicKey (The expansion routine is called …
=> crypto: Use a different library for ed25519/sr25519

CHANGELOG_PENDING.md, internal/consensus/reactor.go, internal/consensus/state.go, libs/events/events.go, libs/pubsub/example_test.go, libs/pubsub/pubsub.go, libs/pubsub/pubsub_test.go, libs/pubsub/query/empty.go, libs/pubsub/query/empty_test.go, libs/pubsub/query/query.go, libs/pubsub/query/query_test.go, libs/pubsub/subscription.go, rpc/client/event_test.go, rpc/client/helpers.go, rpc/core/types/responses.go, types/event_bus.go, types/event_bus_test.go, types/events.go, types/events_test.go
- Remove usage of flattened events, i.e. `map[string][]string`, from the pubsub/events surface area
- Change `ResultEvent.Events` to `[]abci.Event` instead of `map[string][]string`
closes: #5133
=> Refactor Event Subscription

rpc/core/blocks.go
We altered the behavior in an earlier PR where a node returned an empty block instead of nil when the node didn't have it. This slight behavior change messed up with the e2e tests because instead of providing a nil block it was providing a block with a height of 0. This could also be a breaking change in the behavior of clients of the RPC so we've decided to revert the behavior
=> rpc: revert returning empty block

test/e2e/generator/generate.go, test/e2e/networks/ci.toml
Since https://github.com/tendermint/tendermint/pull/6124, we should re-enable grpc abci protocol in e2e tests
=> e2e: re-enable grpc abci protocol

state/indexer/sink/psql/psql.go
Closes: #6661 
Note: see another error during the events indexing, guess the raw tx size exceeds the limitation?
```
3:17PM ERR failed to index block txs err="pq: index row size 2768 exceeds btree version 4 maximum 2704 for index \"tx_results_tx_result_key\"" height=5205112 module=txindex
=> state/indexer: close row after query

test/e2e/generator/generate.go, test/e2e/pkg/manifest.go, test/e2e/pkg/testnet.go, test/e2e/runner/load.go
Closes: #5905
This also simplifies queue type to a testnet wide config and fixes a bug with using the `hybrid` p2p testnet setup
=> e2e: allow variable tx size 

CHANGELOG_PENDING.md, internal/blockchain/v0/pool.go, internal/blockchain/v0/reactor.go, internal/blockchain/v0/reactor_test.go, internal/blockchain/v2/reactor.go, internal/consensus/reactor.go, libs/sync/atomic_bool.go, libs/sync/atomic_bool_test.go, rpc/client/mock/status_test.go, rpc/core/status.go, rpc/core/types/responses.go, rpc/openapi/openapi.yaml
closes #3365 once #6619 merged
=> fastsync/rpc: add TotalSyncedTime & RemainingTime to SyncInfo in /status RPC

state/indexer/sink/psql/psql_test.go
After #6664, ran a modified version of [dgryski's semgrep rule](https://github.com/dgryski/semgrep-go/blob/master/close-sql-query-rows.yml) on the `psql` code and it found these two unclosed sql rows in tests.
=> psql: close opened rows in tests

test/e2e/runner/load.go, test/e2e/runner/main.go
In #6659, variable tx size was introduced. The frequency of txs sent to a node was adjusted to be inversely proportional to the size of the tx. However, after looking at the nightlies, I saw that in some one node testnets where the tx size was 10kb the frequency was so low that occasionally no txs were submitted and this caused a few testnets to error out. This tweaks the frequency to prevent this from happening
=> e2e: adjust tx load

rpc/client/evidence_test.go
Occasionally, the node would take longer to produce the first block and therefore the evidence_test.go would fail. This extends the wait time to 100 ms before testing to see that evidence came through
Closes: #6674
=> rpc: fix evidence test by extending wait time

internal/statesync/dispatcher.go, internal/statesync/dispatcher_test.go
It appears that a go routine was getting stuck on dispatcher.availablePeers.Pop() as this is a blocking function, so I've added a context which collapses the go routine once Backfill is finished.
Closes: #6675
=> statesync: fix leaking backfill test

internal/statesync/reactor.go
This reverts commit 50b00dff7191a31b40310cc016a9543892669d67.
This fix was determined to likely not affect correctness and other fixes should instead be pursued.
=> Revert "statesync: keep peer despite lightblock query fail (#6692)"

internal/statesync/dispatcher.go, internal/statesync/dispatcher_test.go
This change moves the dispatcher's call to Lock and Unlock the mutex in `LightBlock`. It ensures that the number of outgoing calls and number of peers does not change between the check of outgoing call length and call to the `peerlist`'s `Len` method.
An example interleaving of calls that would cause incorrect behavior exists when there is only 1 peer and it is currently making an outgoing call. If a second thread calls `dispatcher.Remove()` on this peer between `dispatcher.LightBlock`s call to `len(d.calls)` and `d.availablePeers.Len()`, we will incorrectly block in the `d.availablePeers.Pop` method, waiting for a peer that has been removed.
This change also adds tests to the `peerlist` and `dispatcher` to verify specific pieces of the API such as ensuring cancelling the context passed …
=> statesync: remove outgoingCalls race condition in dispatcher

light/client_test.go, light/detector.go, light/provider/mock/mock.go
Missed a case from https://github.com/tendermint/tendermint/pull/6687 which appeared in a e2e testnet.
I've also added some tests but I'll admit that I'm unsure if there's perhaps a better way to test context handling.
=> light: add case to catch cancelled contexts within the detector

test/e2e/runner/perturb.go
This tweaks sleeps around pertubations, based on a theory that our
tests with "kill" pertubations restart the nodes fast enough the peers
haven't marked it down when it tries to reconnect. In my local test
runs, this clears out *most* of the test failures that I've seen,
except for one evidence-related test-harness problem (which should be
handled separately.)
=> e2e: tweak sleep for pertubations

internal/p2p/router.go, internal/statesync/reactor.go, test/e2e/runner/main.go
Logs each nodes own `NodeInfo` upon startup so I can see who's trying to connect with who. I think we have a similar message within the switch.
Also moves a log in state sync to info to display which nodes are sending messages. This is to help me narrow down https://github.com/tendermint/tendermint/issues/6704 when it happens
=> router/statesync: add helpful log messages

CHANGELOG_PENDING.md, UPGRADING.md, config/config.go, config/toml.go, rpc/grpc/api.go, rpc/grpc/client_server.go
Mark gRPC as deprecated in the RPC layer. 
closes #6718
=> RPC: mark grpc as deprecated

test/e2e/generator/generate.go
This is a follow on, potentially, to #6734. 
This change key type, like other tendermint/app configuration,
something that is varried throughout all tests, but not an axsis of
systematic varriance. The key type changes the ABCI protocol, but the
changes are very isolated within tendermint itself, and I don't really
know if there are any kind of systematic interactions between this and
other dimensions.
Having said that, I might be incorrect in this assumption, and I'm
happy to retract this.
=> e2e: avoid systematic key-type variation

test/e2e/generator/generate.go
The hybrid e2e test suites are all about testing interoperability
between new and legacy p2p test suites. Single node configurations aren't meaningful in this context. 
Dropping this dimension alone lets us skip 32 test nets.
There are probably other axes that might not make sense to test with single-node confiurations and I'd like to ask you, dear reviewer, if you see any that jump out at you.
For my part, I'm a little bit suspicious of single node various plus the various initial configurations, which are necessarily tested in larger configurations.
=> e2e: drop single node hybrid configurations

CHANGELOG_PENDING.md, docs/tendermint-core/fast-sync.md, internal/consensus/reactor.go, internal/consensus/reactor_test.go, node/node.go, types/event_bus.go, types/event_bus_test.go, types/events.go
closes #2498 
solves part of #3365
Note: difficult to test the event emit in SwitchToFastSync part, might need to change `stateSyncReactor` to an interface in the `nodeImpl` struct
=> fastsync/event: emit fastsync status event when switching consensus/fastsync

test/e2e/generator/generate.go
Having looked at our network address parsing and connection code, it
really looks like we're not doing anything on top of what the standard
library is doing (both in terms using `net.ParseIP` and also
`net.Dial`,) and I don't think we need to run the tests 2x the number
of times just to run through different areas of the standard
library. I think most of our users are going to be using IPv4, and
would be down to fully remove this dimension as well, if we find it's
making noise, but for now I think it's fine.
=> e2e: remove cartesian testing of ipv6

.github/workflows/e2e-nightly-master.yml
Now that there are fewer total test cases (64 down from 288), it makes
sense to reduce the amount of seperate executions. 
Previously we all of the tests into 3 p2p-based groups (96 networks
each), and then split each of those runs into 4 groups of 24 cases
each. This means that the total run finishes in about 50 minutes,
which is nice for responsiveness. 
The downside is that because the docker images aren't fanned out to
machines, each group execution run has to build the docker image
`3x<groups>` number of times, which can become a significant portion
of the total test time. 
This patch pushes us to two groups, (e.g. about 11 tests per group)
which reduces the per-run overhead by half, and also the total runtime
should halve as well. We could go down to a single group, and maybe we …
=> e2e: run tests in fewer groups

internal/p2p/pqueue.go
In some occasions when closing a connection, if the dequeueCh was full, we'd block trying to add an envelope to that channel and thus was not able to close the connection.
=> p2p: avoid blocking on the dequeCh

CHANGELOG_PENDING.md, abci/types/messages.go, privval/signer_listener_endpoint.go, state/indexer/sink/psql/psql_test.go, state/store.go, test/e2e/runner/cleanup.go, test/e2e/runner/wait.go, test/fuzz/rpc/jsonrpc/server/handler.go, types/node_key.go
Fixes #6479 and related cases.
This is a mostly-automated fixup using Comby (https://comby.dev) to reduce lexically-obvious redundant error checks. No functional changes are intended.
Slightly ironically, the original presenting case from #6479 is now gone, but the pattern remains elsewhere in the repository.
=> cleanup: remove redundant error plumbing

crypto/merkle/proof.go, internal/p2p/peermanager.go, state/indexer/block/kv/kv.go, state/indexer/tx/kv/kv.go
The beginnings of a fix for #6780.
File list:
% staticcheck -checks SA4011 ./... | cut -d: -f-2
This change is intended to be semantics-preserving, at least for the intended
semantics of the code. It is NOT strictly behaviour-preserving, however.
Specifically: On some inputs, these loops may have run longer than they were
intended to, prior to this change.
There is one case where I was not sure how to resolve the ambiguity.
This is flagged as FIXME in the commit.
=> Fix and clarify breaks from case clauses.

UPGRADING.md
This PR fixes a typo in `UPGRADING.md`: `gaurantee` --> `guarantee`
=> UPGRADING.md: fix tiny typo

rpc/openapi/openapi.yaml
A cosmetic typo I stumbled across while reading docs.
=> docs: fix a typo in the genesis_chunked description

go.mod, go.sum, internal/libs/clist/clist_property_test.go
Adds a simple property test to the `clist` package. This test uses the [rapid](https://github.com/flyingmutant/rapid) library and works by modeling the internal clist as a simple array.
Follow up from this mornings workshop with the Regen team.
=> clist: add simple property tests

libs/bytes/bytes.go, libs/bytes/bytes_test.go
As written, the encoding step unnecessarily made and moved multiple copies of
the encoded representation. Reduce this to a single allocation and encode the
data in-place so that a shift is no longer required.
No functional changes.
=> bytes: clean up and simplify encoding of HexBytes

UPGRADING.md, cmd/tendermint/commands/key_migrate.go, cmd/tendermint/commands/run_node.go, cmd/tendermint/main.go
This adds a simple CLI around the migration key migration script to facilitate it's use.
=> commands: add key migration cli

rpc/openapi/openapi.yaml
Just a few small typos in the descriptions of the /tx_search and /tx endpoints.
=> doc: fix typos in /tx_search and /tx.

CONTRIBUTING.md
The release instructions were outdated; this updates them to better-reflect our long-lived backport branches. 
Also, closes #6072.
=> contributing: update release instructions to use backport branches

test/e2e/runner/start.go
I realized after my last commit that my change made a following line of code a bit redundant.
(alternatively my last change was redunadnt to the existing code.)
I took this oppertunity to make some minor cleanups and logging changes to the node changes which I hope will make tests a bit more clear.
=> e2e: cleanup node start function

docs/architecture/README.md, docs/architecture/adr-072-request-for-comments.md, docs/rfc/README.md, docs/rfc/rfc-template.md
This ADR proposes to restore a variation of the old Request for Comments
documentation that we previously used. The proposal differs from the original
formulation, and does not replace ADRs.
=> ADR 072: Re-instate a request-for-comments archive.

libs/time/time.go, state/state.go, state/time.go, state/time_test.go
This is a very minor change, but I was looking through the code, and
this seems like it shouldn't be exported or used more broadly, so I've
moved it out.
=> time: make median time library type private

cmd/tendermint/commands/reindex_event.go, node/setup.go, state/indexer/indexer_service_test.go, state/indexer/sink/psql/psql.go, state/indexer/sink/psql/psql_test.go, state/indexer/sink/sink.go
Add documentation comments to the psql event sink package, and simplify the
constructor function so that it does not return the SQL database handle.  The
handle is needed for testing, so expose that via a separate method on the
concrete type.
Update the tests and existing usage for the change. This change does not affect
the behaviour of the sink, so there are no functional changes, only syntactic
updates.
=> psql: add documentation and simplify constructor API

test/e2e/pkg/testnet.go, test/e2e/runner/evidence.go, test/e2e/runner/load.go
In the transaction load generator, the e2e test harness previously distributed load randomly to hosts, which was a source of test non-determinism. This change distributes the load generation to the different nodes in the set in a round robin fashion, to produce more reliable results, but does not otherwise change the behavior of the test harness.
=> e2e: more consistent node selection during tests

.golangci.yml
This is a super minor change that silences a warning when running the linter locally.
=> lint: change deprecated linter

docs/tutorials/go-built-in.md
``` go
func main() {
/* ... */
node.Start()
defer func() { // defer for graceful shutdown
node.Stop()
node.Wait()
}()
c := make(chan os.Signal, 1)
signal.Notify(c, os.Interrupt, syscall.SIGTERM)
<-c
os.Exit(0) // node.Stop() & node.Wait() aren't called, because os.Exit(0) terminates the process immediately
}
```
=> docs: fix graceful shutdown in go built-in example

internal/mempool/v0/clist_mempool.go, internal/mempool/v0/clist_mempool_test.go, internal/mempool/v1/mempool.go, types/mempool.go
This is a little change just to make things more consistent ahead of
the 0.35 release.
=> types: move mempool error for consistency

test/e2e/runner/evidence.go
In retrospect my previous implementation of this node, could get
unlucky and never find the correct node. This method is more reliable.
=> e2e: more reliable method for selecting node to inject evidence

CHANGELOG_PENDING.md, statesync/snapshots.go, statesync/snapshots_test.go, statesync/stateprovider.go, statesync/syncer.go
This PR backports some fixes that were made in #6807. Specifically this moves the fetching of AppHash so that it doesn't occur when a snapshot is added to the pool but only when we run the `Sync` method. In addition, this PR adds error handling logic to reject a snapshot and retry with a new one when the stateprovider returns an error (hopefully for greater robustness).
=> statesync: improve stateprovider handling in the syncer (backport)

test/e2e/runner/perturb.go
I believe that the restart mechanism produces inconsistent test
outcomes relative to the other pertubations, because it lacks the
intermediate sleep.
=> e2e: change restart mechanism

test/e2e/tests/app_test.go, test/e2e/tests/block_test.go, test/e2e/tests/e2e_test.go, test/e2e/tests/net_test.go, test/e2e/tests/validator_test.go
This is mostly as a proposal, I'm not neccessarily committed to the
change as such. Some of this is just centralizing "skips" more
clearly. Additionally this doesn't run application tests for light
clients, which are effectively just proxied to another node in the
network.
I think this is a fine change:
- the use case of the go light client is pretty narrow, and probably
more commonly used in its embedded form, either for statesync or as
part of an application.
- the e2e test framework makes simple calls against light client RPC
endpoints to ensure that the node has started. I think we can be
confident that the light client RPC system *works* from a "smoke
test perspective," and I don't think we should use the e2e tests to
do exhaustive testing at this level. 
- the assertions that we …
=> e2e: skip assertions for stateless nodes

networks/remote/terraform/cluster/main.tf, networks/remote/terraform/cluster/variables.tf, networks/remote/terraform/main.tf
I tried terraform with network/remote config, but got these errors:
```
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│ Error: Invalid quoted type constraints
│ 
│   on main.tf line 14, in variable "SSH_KEY_FILE":
│   14:   type = "string"
│ 
│
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider
│ hashicorp/digitalocean: provider registry registry.terraform.io does not have
│ a provider named registry.terraform.io/hashicorp/digitalocean
│ 
│ Did you intend to use digitalocean/digitalocean? If so, you must specify that
│ source address in each module which requires that provider. To see which
│ modules are currently …
```
=> Update terraform config

light/client.go
It seems the light client was erroring out when it had `<= 1` witnesses when it should be `< 1`. This corrects this.
=> light: fix early erroring

.golangci.yml
This is a cosmetic change that restores lexicographic order to the selected
linters in the CI config. No change to which linters we run, only putting them
back in order so it's easier to spot the one you care about.
=> cleanup: fix order of linters in the golangci-lint config

README.md
This change updates the Tendermint README to more accurately reflect the current Tendermint public API.
=> update readme to more accurately reflect the tendermint public api

.github/codecov.yml, .github/workflows/coverage.yml
I think what removing it did was just change the way the data got reported to the service, and what I really want to do is remove the comment on the PR, and avoid red x'es, which it looks like this patch will do.
=> ci: tweak code coverage settings

test/e2e/generator/generate.go, test/e2e/networks/ci.toml
To avoid the state provider requesting a block that a peer no longer has, I've increased the retain height to at least twice the evidence age (14)
=> e2e: increase retain height

.github/workflows/e2e-nightly-master.yml, .github/workflows/e2e.yml, test/e2e/Makefile, test/e2e/run-multiple.sh, test/e2e/runner/main.go, test/e2e/runner/test.go, test/e2e/tests/e2e_test.go
This is to avoid the situation where you're changing branches while
running tests, leading to confusing (at best) results.
I don't think this introduces any brittleness that didn't exist
previously (about from where you can run the tests/etc,) and compiling
an extra binary isn't particularly expensive in this context.
=> e2e: compile tests

.github/codecov.yml
=> ci: disable codecov patch status check

test/e2e/generator/generate.go, test/e2e/pkg/manifest.go, test/e2e/pkg/testnet.go
The previous implemention of hybrid set testing, which was entirely my
own creation, was a bit peculiar, and I think this probably clears thins up.
The previous implementation had far fewer legacy nodes in hybrid
networks, *and* also for some reason that I can't quite explain,
caused a test case to fail.
=> e2e: improve p2p mode selection

.github/workflows/coverage.yml
The spirit of my change is that we shouldn't run golang coverage tests unless go source files (outside of the test package, which are generally integration tests).
Any failures uncovered in these cases (e.g. docs, fuzzer/e2e test changes) wouldn't be appropriate to fix in the context of these PRs, and don't provide useful/actionable feedback.
=> ci: skip coverage for non-go changes

.github/workflows/coverage.yml
this is a more complete version of something I was trying to achieve last week.
=> ci: skip coverage tasks for test infrastructure

docs/rfc/README.md, docs/rfc/rfc-002-ipc-ecosystem.md
Communication in Tendermint among consensus nodes, applications, and operator tools all use different message formats and transport mechanisms.  In some cases there are multiple options. Having all these options complicates both the code and the developer experience, and hides bugs. To support a more robust, trustworthy, and usable system, we should document which communication paths are essential, which could be removed or reduced in scope, and what we can improve for the most important use cases.
=> RFC 002 Interprocess Communication in Tendermint

test/e2e/runner/evidence.go, test/e2e/runner/load.go
These are mostly the timeouts that I think we're still hitting in CI. 
At this point, the tests (on master) pass on my local machine (which is quite beefy) so I think this is just the first in (perhaps?) a sequence of changes that attempt to change timeouts and load patterns so that the tests pass in CI more reliably.
=> e2e: slow load processes with longer evidence timeouts

light/client.go, light/client_test.go, test/e2e/runner/benchmark.go, test/e2e/runner/rpc.go, test/e2e/runner/wait.go
waitForHeight waits until all nodes reach height x and then return the latest block. This latest block is what is used as the trusted block. However, not all nodes have this latest block. It would be far better that waitForHeight returns the block at the height requested and the height that we know all nodes in the network have reached. This PR makes this change
=> e2e: tweak semantics of waitForHeight

test/e2e/runner/load.go
This should address last night's failure. We've taken the perspective
of "the load generator shouldn't cause tests to fail" in recent
days/weeks, and I think this is just a next step along that line. The
e2e tests shouldn't test performance. 
I included some comments indicating the ways that this isn't ideal (it
is perhaps not), and I think that if test networks could make
assertions about the required rate, that might be a cool future
improvement (and good, perhaps, for system benchmarking.)
=> e2e: allow load generator to succed for short tests

test/e2e/runner/cleanup.go, test/e2e/runner/main.go
If the e2e tests error, they leave all of the e2e state around including containers and networks etc. 
We should clean this up when the tests shuts down, even if it exits in error.
=> e2e: cleanup on all errors if preserve not specified

docs/rfc/rfc-000-p2p-roadmap.rst
Nothing fancy. Just some super minor fixes while going through the document (typos, formatting).
=> Fix a few typos and formatting glitches in the p2p roadmap rfc

test/e2e/generator/generate.go, test/e2e/tests/app_test.go, test/e2e/tests/e2e_test.go
This patch makes several small reliability and scope reduction improvements to the e2e tests in the 0.34 branch that we've been running in master for some months.
=> e2e: backport minor reliability improvements

internal/consensus/byzantine_test.go, internal/consensus/common_test.go, internal/consensus/mempool_test.go, internal/consensus/reactor_test.go, internal/consensus/replay_test.go, internal/consensus/state_test.go
This change removes many of the panics in the `internal/consensus/*_test.go` methods. Instead, it plumbs through a `*testing.T` and makes use of `t.Fatalf` in the place of `panic`.
Using panic makes the test output more difficult to parse. Using `t.Fatal` and marking the `ensure*` and `validate*` functions as helpers using `t.Helper()` allows the testing to play a bit more nicely with tooling as well by indicating which line _in the test_ the failure originated from.
=> consensus: remove panics from test helper functions

test/e2e/runner/load.go
Historically, the workload in the e2e test suite, was inversely
proportional to the number of nodes in the network (more threads for
smaller networks,) but the generator also has a lot of sleep/rests to
ensure that the workload doesn't overwhlem the network. 
This is all somewhat complicated because the e2e tests all run on a
single system, so no only does the workload have to avoid overwhelming
the capability of a node, but it also has to avoid overwhelming the
capability of the system it's running on, which can be an issue on the
CI infrastrucure.
Also, while the e2e tests need some woarkload to validate that the
network works, the main goal of these tests is to make sure the system
_works_: proving that it's possible generate a workload that can
overwhlem the system is not particularly …
=> e2e: load should be proportional to network

internal/consensus/common_test.go, internal/consensus/state.go, internal/consensus/state_test.go, internal/test/factory/block.go, types/block.go, types/canonical.go, types/event_bus.go, types/event_bus_test.go, types/events.go, types/vote.go, types/vote_set_test.go
This change removes the logic for a validator to 'unlock' its locked block if it sees > 2/3 prevotes for nil in a round. This condition is not in the algorithm description in the Tendermint paper.
This logic was present in both `enterPrecommit` and `addVote`. The logic in `addVote` has been updated to only unlock on receipt of 2/3 prevotes for non-nil values and the logic in `enterPrecommit` has been completely removed. 
This change also updates the tests to add a new test for the unlock condition. As a cosmetic fixup, the test file was also updated to match the comments with the current names of the `Lock` suite of tests. Finally, the `Relock` test was updated to use the lock channels to ensure the unlock/lock logic remained correct despite this change. The test for the old behavior was …
=> consensus: remove logic to unlock block on 2/3 prevote for nil

.github/workflows/e2e-nightly-master.yml, test/e2e/runner/load.go, test/e2e/runner/main.go
This change: 
- halves the amount of sleep between transactions for single node test
networks. 
- increases the amount of time allowable for very short test runs (so
that, e.g. if a network runs for less than 5 seconds, up from 2s,
not landing transactions isn't an error). 
- increases the amount of parallelism in the suite as run in CI.
=> e2e: tighten timing for load generation

test/e2e/tests/app_test.go
I believe this assertion is likely redundant given that we're checking the block apphash.
=> e2e: skip validation of status apphash

test/e2e/runner/evidence.go
In the last run, there were two problems at the RPC layer returned
from light nodes' RPC end points. I think exercising the light client
proxy RPC system is something that can/should be done via unit
testing, and that likely these errors are (in production) transient
and (in CI) very likely to fail for test environment issues.
=> e2e: do not inject evidence through light proxy

.github/mergify.yml
This should make it possible to avoid needing to babysit the merge
queue by hand. [see docs](https://docs.mergify.io/actions/merge/#options). 
At some point we should probably opt into using the new(er?)
[queue](https://docs.mergify.io/actions/queue/#queue-action) feature,
but in the mean time this is a good improvement.
=> ci: use smart merges

internal/statesync/reactor.go, internal/statesync/reactor_test.go, internal/statesync/stateprovider.go, internal/statesync/syncer.go
I've been noticing that there are a number of situations where the
statesync reactor blocks waiting for peers (or similar,) I've moved
things around to improve outcomes in local tests.
=> statesync: clean up reactor/syncer lifecylce

abci/client/socket_client.go, abci/server/socket_server.go
The main effect of this change is to flush the socket client and server message
encoding buffers immediately once the message is fully and correctly encoded.
This allows us to remove the timer and some other special cases, without
changing the observed behaviour of the system.
The socket protocol client and server each use a buffered writer to encode
request and response messages onto the underlying connection. This reduces the
possibility of a single message being split across multiple writes, but has the
side-effect that a request may remain buffered for some time.
The implementation worked around this by keeping a ticker that occasionally
triggers a flush, and by flushing the writer in response to an explicit request
baked into the client/server protocol (see also #6994).
These …
=> abci: Flush socket requests and responses immediately.

test/e2e/generator/generate.go, test/e2e/generator/main.go, test/e2e/pkg/manifest.go
I observed a couple of problems with the generator in some recent tests: 
- there were a couple of hybrid test cases which did not have any
legacy nodes (randomness and all.) I change the probability to
produce more reliable results.
- added options to the generation to be able to add a max (to
compliment the earlier min) number of nodes for local testing. 
- added an option to support reversing the sort order so "more
complex" networks were first, as well as tweaked some of the point
values. 
- this refactored the generators cli parsing to be a bit more clear.
=> e2e: add limit and sort to generator

test/e2e/generator/generate.go, test/e2e/generator/random.go, test/e2e/generator/random_test.go
The goal here is to reduce the number of times that we expect
statesyncs/catchups to happen in a test network. Previously, all nodes
over quoroum of validators plus half of all full nodes, would
statesync. This says "half of all validators over qurorum or at most
two validators." Also, for nodes that are going to catch up, I've made
it far more likely to choose statesync rather than just rely on
blocksync. I think this allows us to exercise the most important parts
of the code, while also increasing the chance that networks will
succeed.
Additionally, it ensures that at least two persistent peers are
configured for nodes that have p2p statesync enabled. I think this is
roughly consistent with what our production recomendations would be.
=> e2e: reduce number of statesyncs in test networks

test/e2e/generator/generate.go
This reduces this situation where a node will get stuck block syncing,
which seemed to happen a lot in last nights run.
=> e2e: improve chances of statesyncing success

.github/workflows/coverage.yml, test/test_cover.sh
this uses the default "set" method, and avoids the more expensive
atomic counters.
=> ci: use cheaper codecov data collection

internal/p2p/pex/pex_reactor.go, internal/p2p/switch.go, libs/cmap/cmap.go, libs/cmap/cmap_test.go
Closes #7014
Fix race condition described in #7014 by implementing CMap.GetOrSet() (inspired by  [sync.Map.LoadOrStore()](https://pkg.go.dev/sync#Map.LoadOrStore))
=> p2p: fix race condition in legacy-p2p connection tracking

test/e2e/generator/generate.go
75% of the failures in the last run all ran with the 10kb
transactions. I'd like to dial it back and see if things improve more.
=> e2e: use smaller transactions

CHANGELOG.md, CHANGELOG_PENDING.md
Move items from the pending changelog.
The diff is larger than expected because I think we forgot to re-run the linkifier before the last RC tag.
=> Update changelog for v0.35.0-rc2.

CHANGELOG_PENDING.md, cmd/tendermint/commands/run_node.go, proxy/client.go, test/e2e/Makefile, test/e2e/README.md, test/e2e/app/app.go, test/e2e/app/snapshots.go, test/e2e/app/state.go, test/e2e/docker/Dockerfile, test/e2e/node/built-in.toml, test/e2e/node/config.go, test/e2e/node/main.go, test/e2e/node/socket.toml
=> e2e: allow running of single node using the e2e app (backport)

CONTRIBUTING.md, Makefile, docs/DOCS_README.md, docs/versions
Fixes #7017. The essence of the fix is to change the order of lines in `docs/versions`.
In addition:
- Update `docs/DOCS_README.md` to reflect the current state of how we publish the site.
- Fix the `build-docs` target in Makefile to not perturb the package-lock.json during the build.
Despite what the workflow configuration says, the docs repository has not been regularly
publishing updates to the site since the end of July. I will investigate fixing that up separately.
=> Make doc site index default to the latest release

internal/statesync/dispatcher.go, internal/statesync/reactor.go, internal/statesync/reactor_test.go
This test reliably gets hung up on network configuration, (which may
be a real issue,) but it's network setup is handcranked and we should
ensure that the test focuses on it's core assertions and doesn't fail for 
test architecture reasons.
=> statesync: ensure test network properly configured

.github/CODEOWNERS
with @alexanderbez's blessing, of course.
=> .github: remove tessr and bez from codeowners

internal/blocksync/v0/reactor.go
When shutting down blocksync, it is observed that the process can hang completely. A dump of running goroutines reveals that this is due to goroutines not listening on the correct shutdown signal. Namely, the `poolRoutine` goroutine does not wait on `pool.Quit`. The `poolRoutine` does not receive any other shutdown signal during `OnStop` becuase it must stop before the `r.closeCh` is closed. Currently the `poolRoutine` listens in the `closeCh` which will not close until the `poolRoutine` stops and calls `poolWG.Done()`.
This change also puts the `requestRoutine()` in the `OnStart` method to make it more visible since it does not rely on anything that is spawned in the `poolRoutine`.
```
goroutine 183 [semacquire]:
sync.runtime_Semacquire(0xc0000d3bd8)
runtime/sema.go:56 +0x45 …
```
=> blocksync: fix shutdown deadlock issue

CHANGELOG_PENDING.md, internal/p2p/conn/connection.go
The layout of struct fields means that interior fields may not be properly
aligned for 64-bit access.
Fixes #7000.
This change seems harmless and doesn't break any APIs.
=> Align atomic struct field for compatibility in 32-bit ABIs.

internal/statesync/reactor.go
This is intended to fix a test failure that occurs in the p2p state provider. The issue presents as the state provider timing out waiting for the consensus params response. 
The reason that this can occur is because the statesync reactor has the possibility of attempting to respond to the params request before the state provider is ready to read it. This results in the reactor hitting the `default` case seen here and then never sending on the channel. The stateprovider will then block waiting for a response and never receive one because the reactor opted not to send it.
=> statesync: improve rare p2p race condition

CHANGELOG_PENDING.md, node/node.go
I accidentally omitted this from the backport in #6906.
Fixes #7043.
=> Import Postgres driver support for the psql indexer (backport).

CHANGELOG.md
This reverts commits:
c16cd72c0a6ae9fe85ff7305c72aca4bcdb2b209
6ef847fdfe3af6c661622936810667f26c1771e3
We decided on another release candidate to sort out SDK merge issues.
=> Revert "Consolidate related changelog entries. (#7056)".

internal/consensus/reactor.go
backport from master to v0.35.x
=> consensus: wait until peerUpdates channel is closed to close remaining 

.github/workflows/e2e-nightly-master.yml
My earlier p2p cleanup code removed support for the p2p tests from the
e2e generator and runner, but missed removing the CI
configuration. This patch remedies that.
=> ci: fix p2p configuration for e2e tests

test/fuzz/mempool/checktx.go
We are creating a TestLogger without testing being initialized.
We could either swap to a non-test logger, or initialize testing.
This PR uses a no-op (non-test) logger.
Fixes #7189.
=> Fix spurious crasher in mempool fuzz test.

.github/CODEOWNERS
Hopefully this will keep things cleaner for the maintenance branches.
=> codeowners: backport master code owners to 0.34.x

node/node.go
This fixes an issue that lead to some e2e test failures.
=> pex: avoid starting reactor twice

CHANGELOG.md
**Note to reviewers:** Please double-check whether any of the CHANGELOG entries require further detail in the UPGRADING document.
I have _not_ incremented the ABCI protocol version, although we probably should have done so in a previous release.
=> Prepare CHANGELOG and config settings for v0.35.0 release.

internal/inspect/inspect.go, internal/state/indexer/indexer_service.go, internal/state/indexer/metrics.go, node/node.go, node/node_test.go, node/setup.go
Fixes #7249. Following the general pattern from other packages, add a Metrics type to the indexer package with some basic latencies and counters for indexing activity.
These are intentionally coarse-grained: The transaction latency, for example, is aggregated over the batches committed to storage, since that is the high-order bit of how long the indexing step takes. If later on we change indexing to index in a more granular fashion, these values can be reused with the same semantics.
=> Add basic metrics to the indexer package.

internal/consensus/peer_state.go, internal/consensus/reactor.go, types/vote_set.go
This was brought up by a user off-band. They were running nodes in debug mode and were experiencing occasional panics when the returned vote here: 
https://github.com/tendermint/tendermint/blob/c2908ef785bb5ca6e015910368e4b7a32821b9ff/consensus/reactor.go#L1056
was `nil` and the logger was trying to marshal the nil vote. 
I have added in a few extra "defensive programming" checks to try to avoid accidental nil pointer dereferencing.
=> consensus: add some more checks to vote counting

internal/rpc/core/events.go, internal/rpc/core/tx.go
As a safety measure, don't allow a query string to be unreasonably
long. The query filter is not especially efficient, so a query that
needs more than basic detail should filter coarsely in the subscriber
and refine on the client side.
=> Set a cap on the length of subscription queries.

CHANGELOG_PENDING.md, config/config.go, config/toml.go, evidence/mocks/block_store.go, libs/pubsub/subscription.go, node/node.go, proxy/mocks/app_conn_consensus.go, proxy/mocks/app_conn_mempool.go, proxy/mocks/client_creator.go, rpc/core/events.go, state/indexer/block/kv/kv_test.go, state/indexer/block/kv/util.go, state/indexer/sink/psql/psql.go, state/indexer/sink/psql/psql_test.go, state/mocks/evidence_pool.go, state/mocks/store.go, statesync/mocks/state_provider.go
Follows from #7188 and related to #6729.
The aim here is to provide a short-term workaround for #6729 in the v0.34.x series of Tendermint that allows for tuning of the internal buffer sizes relating to event subscription. The following configuration parameters are introduced in the `[rpc]` section:
```toml
[rpc]
experimental_subscription_buffer_size = 1000
#
experimental_websocket_write_buffer_size = 1000
#
experimental_close_on_slow_client = false
```
=> rpc: Add experimental config params to allow for subscription buffer size control (tm v0.34.x)

internal/evidence/reactor_test.go
The evidence test produces a set of mock evidence in the evidence pool of the 'Primary' node. The test then fills the evidence pools of secondaries with half of this mock evidence. Finally, the test waits until the secondary has an evidence pool as full as the primary. 
The assertions that are removed here were checking that the primary and secondaries' evidence channels were empty. However, nothing in the test actually ensures that the channels are empty. The test only waits for the secondaries to have received the complete set of evidence, and the secondaries already received half of the evidence at the beginning. It's more than possible that the secondaries can receive the complete set of evidence and not finish reading the duplicate evidence off the channels.
=> evidence: remove source of non-determinism from test

CHANGELOG_PENDING.md, config/config.go, config/toml.go, internal/rpc/core/events.go, libs/pubsub/subscription.go, node/node.go
As per https://github.com/tendermint/tendermint/pull/7230#issuecomment-963629146, this PR backports the changes from #7230 for Tendermint v0.35.x.
=> rpc: backport experimental buffer size control parameters from #7230 (tm v0.35.x)

internal/consensus/replay_file.go, internal/state/store.go, libs/os/os.go, rpc/jsonrpc/test/main.go
I think calling os.Exit at arbitrary points is _bad_ and is good to
delete. I think panics in the case of data courruption have a chance
of providing useful information.
=> libs/os: remove arbitrary os.Exit

RELEASES.md, docs/DOCS_README.md
Since the doc site is built from the backport branches, the config changes for
a new major release also need to be replicated into the backport branch as well
as master. Update the release docs to mention that specifically, since I missed
it during the v0.35 release.
=> docs: clarify where doc site config settings must land

Makefile
This is a manual backport of the changes to how we build and run the protobuf
toolchain images in Docker. The main effect here is to point to the new image
from ghcr.io/tendermint/docker-proto-builder, but to make that work it is also
necessary to update some of the branch pointers.
This change does NOT include the changes from #7269 and #7291 to point to the
proto files in the spec repo. To do that, we will need to create a branch or
tag on the spec that has the released version, which does not exist in the spec
history as it currently stands.
Updates #7272.
=> Partial backport of protobuf generation changes.

internal/blocksync/v0/reactor_test.go, internal/blocksync/v2/reactor_test.go, internal/consensus/byzantine_test.go, internal/consensus/common_test.go, internal/consensus/invalid_test.go, internal/consensus/mempool_test.go, internal/consensus/reactor_test.go, internal/consensus/replay_test.go, internal/consensus/state_test.go, internal/consensus/types/height_vote_set_test.go, internal/evidence/pool_test.go, internal/evidence/verify_test.go, internal/statesync/block_queue_test.go, internal/statesync/reactor_test.go, internal/test/factory/genesis.go, internal/test/factory/validator.go, light/client_test.go, light/store/db/db_test.go, node/node_test.go, state/helpers_test.go, state/store_test.go, test/e2e/runner/evidence.go
This pull requests makes a few changes that will be helpful for writing the proposer-based timestamps tests. It simplifies a few of the existing test helpers and allows the addition of needed parameters. 
First, the `Validator` constructors in the `test/factory` package took a `bool` parameter that indicated if a random amount of voting power should be added to the passed in `minPower`. This `bool` was set to `true` at very few call sites, but was threaded all the way through the helper functions that used  the `Validator` constructor. This change removes the `bool` parameter and instead updates the few places where a random amount of voting power is required to generate a random number. 
Additionally, the `Genesis` consuctor has been updated to take a `time.Time` to be used as the …
=> factory: simplify validator and genesis factory functions

internal/consensus/common_test.go, internal/consensus/replay_test.go, internal/consensus/state_test.go
Mild refactor of the state tests. This refactor performs two things:
The `validatorStub` objects now are created with a clock source that they use when signing votes. The goal of this is to be able to control the timestamps that votes are signed with for future testing with proposer based timestamps.
The vote signing helper functions have been altered slightly. They now take a `types.BlockID` instead of the constituent pieces of a `BlockID` this seems a bit cleaner and aids readability. They also no longer take a `Config` object and instead take the one piece of configuration information that they need, the `ChainID`. This helps the test harness I'm working on by making it not need to keep track of so many disparate pieces of state.
=> consensus: refactor the fake validator to take a clock source

CHANGELOG_PENDING.md, libs/pubsub/pubsub.go
If a subscriber arrives while the pubsub service is shutting down, the existing
code will return a nil subscription without error. With unlucky timing, this
may lead to a nil indirection panic in the RPC service.
To avoid that problem, make sure that when a subscription fails for this
reason, we report a non-nil error so that the client will detect it and give up
gracefully.
Fixes #7306.
=> pubsub: Report a non-nil error when shutting down.

internal/consensus/pbts_test.go, internal/consensus/state.go, internal/consensus/state_test.go, types/proposal.go
This pull requests implements helper functions to for calculating sleep durations during the propose phase.
For more information on the inequalities in these functions, please see the proposer-based timestamps ADR. Specifically, this pull requests implements the [proposer waits](https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-071-proposer-based-timestamps.md#proposer-waits) and [changes to propose step timeout](https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-071-proposer-based-timestamps.md#changes-to-the-propose-step-timeout) calculations.
Related to: #6942
=> consensus: add calculation for proposal step waits from pbts 

rpc/openapi/openapi.yaml
The event examples for the query filter language were not updated after the
change of key and value types from []byte to string. Also, the attributes need
to be a slice not a bare value.
=> Update example code in OpenAPI docs.

docs/tutorials/go.md
Fixes Go Application tutorial described in https://github.com/tendermint/tendermint/issues/7329
=> docs: go tutorial fixed for 0.35.0 version (#7329)

internal/consensus/common_test.go, internal/consensus/pbts_test.go, internal/consensus/state.go, internal/consensus/state_test.go
This pull request implements the [Propose Step Timeout](https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-071-proposer-based-timestamps.md#changes-to-the-propose-step-timeout) changes described in ADR 71. 
This code change implements this by taking the max of the recently added `proposalStepWaitingTime(...)` method and the configured `timeout-propose` value and changes the scheduled [RoundStepPropose timeout](https://github.com/tendermint/tendermint/blob/afaa43447711f9f300be8bd8993bc42d0b03da3b/internal/consensus/state.go#L1121) to occur after this maximum waiting time.
This change also adds a small test harness for the ongoing proposer-based timestamp work. The [test harness](https://github.com/tendermint/tendermint/pull/7307/files#diff-66d310611ce9e18493d9622384c …
=> consensus: ensure proposal receipt waits for maxWaitingTime

libs/pubsub/pubsub.go
Prior to this change, shutting down the pubsub server could cause
any laggard publishers to race with the shutdown plumbing.
Fix that race condition, and plumb in the service context to the
runner so that it will respect the external signal directly.
=> pubsub: Make the queue unwritable after shutdown.

docs/nodes/metrics.md, internal/blocksync/v0/reactor_test.go, internal/blocksync/v2/reactor_test.go, internal/consensus/metrics.go, internal/consensus/replay_file.go, internal/consensus/replay_stubs.go, internal/consensus/replay_test.go, internal/consensus/wal_generator.go, internal/proxy/app_conn.go, internal/proxy/metrics.go, internal/proxy/multi_app_conn.go, internal/proxy/multi_app_conn_test.go, internal/state/execution_test.go, internal/state/helpers_test.go, node/node.go, node/node_test.go, node/setup.go
This PR adds an initial set of metrics for use ABCI. The initial metrics enable the calculation of timing histograms and call counts for each of the ABCI methods. The metrics are also labeled as either 'sync' or 'async' to determine if the method call was performed using ABCI's `*Async` methods.
An example of these metrics is included here for reference:
```
tendermint_abci_connection_method_timing_bucket{chain_id="ci",method="commit",type="sync",le="0.0001"} 0
tendermint_abci_connection_method_timing_bucket{chain_id="ci",method="commit",type="sync",le="0.0004"} 5
tendermint_abci_connection_method_timing_bucket{chain_id="ci",method="commit",type="sync",le="0.002"} 12
tendermint_abci_connection_method_timing_bucket{chain_id="ci",method="commit",type="sync",le="0.009"} 13 …
```
=> internal/proxy: add initial set of abci metrics backport

types/params.go
This parameter no longer shows up at the code level and therefore should be deleted.
=> types: remove accuracy from timestamp params

test/e2e/app/app.go
This is probably belt and suspenders, but might help the apphash clarity.
=> e2e: control access to state in Info calls

cmd/tendermint/commands/reindex_event_test.go, internal/state/indexer/sink/psql/psql.go, node/node_test.go
Some of our tests were creating a psql event sink and expecting
it to report (or not report) certain kinds of errors. These tests
were ill-founded in a couple of ways:
1. Tests that required the Postgres driver were not loading it.
This led to spurious successes on tests that wanted "some error"
from the sink constructor, but didn't exercise the right path.
2. Tests that wanted a Postgres sink to succeed without a database.
These tests "passed" because they weren't actually establishing a
connection to the database, but if they had would have failed for
the lack of one.
To fix this:
- Load the postgres driver in tests that need it.
- Verify connectivity before reporting successful creation of a PSQL event sink.
- Remove tests that wanted a psql sink without a database, since that case
is …
=> Fix incorrect tests using the PSQL sink.

test/e2e/generator/generate.go
This is a little bit of a shot in the dark, but it seems odd that there'd be a usecase for v0.35 users who would be using the legacy P2P stack and also statesync using the new p2p state provider. This is a configuration that is not available in 0.34 *nor* in versions of tendermint after 0.35. 
In the end this affects about 7 nodes total across all hybrid cases.
I think this really gets to the heart of "what's the legacy p2p stack for" in v0.35, given that the new stack is deeply compatible with the legacy stack for most cases. In my estimation keeping the legacy stack around is good as a migration strategy and as a fallback for existing operators if there's a problem (that we haven't yet seen) with the new system, we have an easy operational strategy and workaround already in the bag. I …
=> e2e: limit legacyp2p and statesyncp2p

.github/workflows/coverage.yml, Makefile
This moves a bit of irritating CI orchestration into the makefile for
better local repoducabiliy, and also slims down what runs in tests (to
avoid noop cases where we try and run tests that don't exist.)
=> ci: move test execution to makefile

Makefile
I increased this while messing around with another PR, and
forgot to remove it before merging.
=> Revert CI test timeout.

.github/mergify.yml
Per https://blog.mergify.com/strict-mode-deprecation/, the strict mode
has been deprecated and will be turned off on 10-Jan-2022. This updates
the config to use the new, approved thing instead of the old thing.
=> Update mergify configuration.

.github/workflows/docker.yml
These can take 8 mins and don't provide meaningful signal on top of
whatever we're doing in the corresponding make target.
=> ci: skip docker image builds during PRs

internal/blocksync/reactor.go, internal/consensus/reactor.go, internal/evidence/reactor.go, internal/statesync/dispatcher.go, internal/statesync/reactor.go, internal/statesync/reactor_test.go, internal/statesync/syncer.go, internal/statesync/syncer_test.go
This is another (large) chunk of #7384 (and a follow up to #7392), but
omits the troublesome mempool case.
=> service: cleanup close channel in reactors

CHANGELOG_PENDING.md, internal/consensus/common_test.go, internal/consensus/pbts_test.go, internal/consensus/state.go
This change introduces the logic to have the proposer wait until the previous block time has passed before attempting to propose the next block. 
The change achieves this by by adding a new clause into the `enterPropose` state machine method. The method now checks if the validator is the proposer and if the validator's clock is behind the previous block's time. If the validator's clock is behind the previous block time, it schedules a timeout to re-enter the enter propose method after enough time has passed.
This change also introduces a mild refactor to the `pbts_test.go` file. It updates the test harness to include a channel of `time.Time`, `pubsub.Message` pairs. This timestamped events channel provides a slightly more generalizable way to collect events from the observed validator …
=> internal/consensus: proposer waits for previous block time

internal/consensus/pbts_test.go, internal/consensus/state.go
This logic has been removed from the spec and should similarly be reverted out of the code.
related to: #6942
=> internal/consensus: remove proposal wait time

CHANGELOG_PENDING.md, internal/libs/protoio/writer.go, internal/libs/protoio/writer_test.go, types/vote_test.go
Noticed in profiles that invoking *VoteSignBytes always created a
bytes.Buffer, then discarded it inside protoio.MarshalDelimited.
I dug further and examined the call paths and noticed that we
unconditionally create the bytes.Buffer, even though we might
have proto messages (in the common case) that implement
MarshalTo([]byte), and invoked varintWriter. Instead by inlining
this case, we skip a bunch of allocations and CPU cycles,
which then reflects properly on all calling functions. Here
are the benchmark results:
```shell
$ benchstat before.txt after.txt
name                                        old time/op    new time/op    delta
types.VoteSignBytes-8                       705ns ± 3%     573ns ± 6%       -18.74% (p=0.000 n=18+20)
types.CommitVoteSignBytes-8                 8.15µs ± …
```
=> internal/libs/protoio: optimize MarshalDelimited by plain byteslice allocations+sync.Pool

CHANGELOG_PENDING.md, internal/state/indexer/indexer_service_test.go
The test service was starting up without a logger and crashing while trying to log. We changed the defaults in #7288, and I missed this case during review.
=> Fix a panic in the indexer service test.

CHANGELOG_PENDING.md, internal/consensus/byzantine_test.go, internal/consensus/common_test.go, internal/consensus/pbts_test.go, internal/consensus/replay_test.go, internal/consensus/state.go, internal/consensus/state_test.go, internal/state/state.go, internal/state/validation.go, internal/state/validation_test.go, types/proposal.go, types/proposal_test.go
This change updates the proposal logic to use the block's timestamp in the proposal message. It adds an additional piece of validation logic to the prevote step to check that the block's timestamp matches the proposal message's timestamp.
This change also adds two tests that ensure that 1. if the proposal message timestamp does match, we prevote the proposal, 2. if the proposal message does not match we prevote nil.
related to: #6942
=> internal/consensus: prevote nil if proposal timestamp does not match

internal/statesync/reactor_test.go, internal/statesync/syncer.go, internal/statesync/syncer_test.go
Ref: https://github.com/tendermint/tendermint/issues/7461
For state sync verification, we call `Info` on the application and check that the app hash matches. We also take the app version from the application and use that to set the app version in Tendermint's state. However, we already have the verified app version in the header. We should assert that these two are the same and error if they are not. This PR makes these changes.
For further context: There is potentially a bug in the SDK which is causing the `Info` to always return a 0 app version which means applications with non-zero app versions are currently unable to state sync.
=> statesync: assert app version matches

libs/bits/bit_array.go, libs/events/events_test.go, libs/rand/random.go
Saw this minimally used custom random wrapper, which I think is not
useful (and could potentially panic.)
=> libs/rand: remove custom seed function

cmd/tendermint/commands/init.go, cmd/tendermint/commands/reset_priv_validator.go, internal/consensus/common_test.go, internal/consensus/replay_test.go, privval/file.go, privval/file_test.go, privval/grpc/client_test.go, privval/secret_connection.go, privval/signer_listener_endpoint_test.go, privval/socket_dialers_test.go, privval/socket_listeners_test.go, privval/utils.go, test/e2e/runner/setup.go
This converts a collection of panics to errors, and leaves two panics: 
- a "must" function for message wrapping, which is clear, and I think
passes the standard of "this should be a compile assertion if the
type system were more extensible"
- in `CheckHRS` we panic in a logical data curruption bug. I'd
inclined to remove this, but I don't know enough about the
surrounding code to know if this would be totally safe.
=> privval: remove panics in privval implementation

internal/consensus/state.go
Response to debugging with @ancazamfir. Proposal can be nil if not sent.
=> consensus: check that proposal is non-nil before voting

types/node_key_test.go
(this is a minor cleanup, no functionality is changed)
These tests use a deterministic and unseeded random source to generate
non-colliding filenames for testing. When testing locally, this means tests are
not hermetic from one run to the next.
Use proper temp directories, and clean up after they're done.
=> types: fix path handling in node key tests

privval/signer_client_test.go
I have seem a few tests where the service not shutting down triggers
the race detector and/or the log-after-test-completion. Calling Wait
on the service in a cleanup is a great fix for this. Adding the
leaktest detector seems decent as well.
=> privval: improve test hygine

libs/rand/random.go, test/e2e/generator/generate.go, test/e2e/pkg/manifest.go, test/e2e/pkg/testnet.go, test/e2e/runner/load.go
(cherry picked from commit 8564c5079f7f8a11bcae7cc16db29caea5feac69)
=> e2e: use more simple strings for generated transactions (#7513)

test/e2e/tests/app_test.go
- produce random transaction value more likely to be safe.
- remove test parallelism in test that seems to be a bit flaky.
=> e2e: make tx test more stable

internal/consensus/reactor.go, internal/consensus/reactor_test.go, node/setup.go
There's no compelling reason to have variadic options to reactor
construction like this, given that these components are internal.
=> consensus: remove reactor options

internal/consensus/byzantine_test.go, internal/consensus/reactor.go, internal/consensus/reactor_test.go, internal/p2p/router.go, node/setup.go
This is an internal detail of the way that reactors (and therefore
nodes) are constructed, and is part of the larger project of pushing
initialization code out of the node package and into constructors for
reactors.
THis patch serves as a prototype for making a similar change for the
remaining reactors.
=> consensus+p2p: change how consensus reactor is constructed

internal/consensus/peer_state.go, internal/consensus/state.go, internal/consensus/types/height_vote_set.go, internal/consensus/types/peer_round_state.go, privval/file.go, privval/file_test.go, types/part_set.go, types/vote_set.go
This is a small step toward confining and eventually removing the custom JSON encoding package. Future changes will dig into more complex cases, but I wanted to get the trivial and safe steps out of the way first.
Where possible, replace uses of the custom JSON library with the standard
library. The custom library treats interface and unnamed lteral types
differently, so this change avoids those even where it would probably be safe
to switch them.
=> Replace uses of libs/json with encoding/json.

config/config.go, config/toml.go
This addresses a problem with rerunning tests within a single process. 
I think the real solution to this problem would be to clean up and avoid the use of go-kit.
=> test: uniquify prom IDs

abci/cmd/abci-cli/abci-cli.go, cmd/priv_val_server/main.go, cmd/tendermint/commands/debug/debug.go, cmd/tendermint/commands/light.go, cmd/tendermint/commands/root.go, internal/statesync/reactor_test.go, libs/log/default.go, libs/log/default_test.go, libs/log/nop.go, libs/log/testing.go, light/example_test.go, rpc/jsonrpc/jsonrpc_test.go, rpc/jsonrpc/test/main.go, rpc/test/helpers.go, test/e2e/app/app.go, test/e2e/generator/main.go, test/e2e/node/main.go, test/e2e/runner/main.go, test/fuzz/rpc/jsonrpc/server/handler.go
Seems like we were only using this facility for the test logger with
verbose, and it wasn't providing a lot of value.
=> log: remove support for traces

rpc/jsonrpc/client/ws_client.go, rpc/jsonrpc/jsonrpc_test.go, rpc/jsonrpc/types/types.go
Apart from the tests for the websocket client, positional parameters are not
used by RPC clients. The server supports both arrays and objects, but the
client only needs to provide one or the other.
=> rpc: remove positional parameter encoding from clients

rpc/jsonrpc/client/http_json_client.go, rpc/jsonrpc/jsonrpc_test.go
These two interfaces are identical, and besides HTTPClient being confusingly
named, all but one location uses Caller. Update that one location, and drop the
redundant interface.
=> rpc: collapse Caller and HTTPClient interfaces.

internal/statesync/reactor_test.go
This will help clarify the testing logger for the statesync package,
and hopefully make it easier to tracedown an infrequent test failure
in the test suite for this package.
=> statesync: use specific testing.T logger for tests

rpc/client/http/http.go, rpc/jsonrpc/client/decode.go, rpc/jsonrpc/client/http_json_client.go, rpc/jsonrpc/client/ws_client.go, rpc/jsonrpc/jsonrpc_test.go, rpc/jsonrpc/server/ws_handler_test.go, rpc/jsonrpc/types/types.go, rpc/test/helpers.go
The old interface returned the result as well as populating it.  Nothing was using this, so drop the duplicated value from the return signature. Clarify the documentation on the Caller type.
This has some pass-along effects on some of the other unexported decoder plumbing. None of the callers was using the result return value, so this was otherwise mostly cosmetic.
Take an arbitrary value instead of only a map. This is groundwork for getting rid of the custom marshaling code. For now, however, the implementation preserves the existing behaviour for the map, until we can replace those.
=> rpc: simplify the JSON-RPC client Caller interface

CHANGELOG_PENDING.md, node/node.go, node/node_test.go
Defines a different concrete struct for the seed node that satisfies the service interface.
Fixes #6775
Closes #6775
=> node: new concrete type for seed node implementation

rpc/client/http/http.go, rpc/client/http/request.go
Instead of using anonymous maps, define tagged struct types for JSON argument
encoding. This allows us to have the encoding rules we want without tmjson.
This commit handles the "easy" cases. BroadcastEvidence is omitted here,
because it depends on the interface encoding rules from tmjson. I will address
that in a forthcoming change.
=> rpc: replace anonymous arguments with structured types

internal/rpc/core/abci.go, internal/rpc/core/blocks.go, internal/rpc/core/blocks_test.go, internal/rpc/core/consensus.go, internal/rpc/core/dev.go, internal/rpc/core/events.go, internal/rpc/core/evidence.go, internal/rpc/core/health.go, internal/rpc/core/mempool.go, internal/rpc/core/net.go, internal/rpc/core/status.go, internal/rpc/core/tx.go, light/proxy/routes.go, light/rpc/client.go, rpc/client/local/local.go, rpc/client/mock/client.go, rpc/jsonrpc/jsonrpc_test.go, rpc/jsonrpc/server/http_json_handler.go, rpc/jsonrpc/server/http_json_handler_test.go, rpc/jsonrpc/server/http_uri_handler.go, rpc/jsonrpc/server/parse_test.go, rpc/jsonrpc/server/ws_handler.go, rpc/jsonrpc/server/ws_handler_test.go, rpc/jsonrpc/test/main.go, rpc/jsonrpc/types/types.go
This is a large but uncomplicated refactoring of the RPC method handler interface. No functional changes are intended. The main effects are:
1. Rename the RPC `Context` type to `CallInfo`, and add helpers to attach and recover values of that type on a context.
2. Update all the RPC method handlers to accept a `context` context.
3. Update usage of the original type to use `CallInfo`.
Part (3) is the most "interesting" part of this change (relatively speaking), the rest is mostly macro-scriptable.
=> rpc: replace custom context-like argument with context.Context

internal/consensus/byzantine_test.go, internal/consensus/invalid_test.go, internal/consensus/mempool_test.go, internal/consensus/replay_test.go, internal/p2p/pex/reactor_test.go, privval/signer_client_test.go, privval/signer_endpoint.go, privval/signer_listener_endpoint_test.go
Logging in tests is largely unusable so pulling out these messages
which aren't presently providing value is useful.
=> tests: remove in-test logging

rpc/client/mock/abci_test.go
In two cases, we check for the content of an error right after asserting that
no error occurs. Fix the sense of those checks.
In one case, we check that there is no error with the diagnostic "expected
error". It's not clear whether this means "an error was expected" (which is
what I believe) or "we got the expected error". However, given the way the mock
plumbing is set up, the first interpretation seems right.
=> rpc: fix mock test cases

CHANGELOG_PENDING.md, rpc/jsonrpc/server/http_json_handler.go, rpc/jsonrpc/server/http_server.go, rpc/jsonrpc/server/http_server_test.go, rpc/jsonrpc/server/http_uri_handler.go, rpc/jsonrpc/server/ws_handler.go, test/app/kvstore_test.sh
Add writeRPCResponse and writeHTTPResponse helpers, that handle the way RPC
responses are written to HTTP replies. These replace the exported helpers.
In particular:
- When writing a response to a URL (GET) request, do not marshal the whole
JSON-RPC object into the body, only encode the result or the error object.
This is a user-visible change.
- Do not change the HTTP status code for RPC errors. The RPC error already
reports what went wrong, the HTTP status should only report problems with the
HTTP transaction itself. This is a user-visible change.
- Encode JSON without indentation in response bodies. This is mainly cosmetic
but saves quite a bit of response data. Users on the command line can pipe
through jq to get indented output, the server doesn't need to do it.
- Log less …
=> rpc: rework how responses are written back via HTTP

rpc/jsonrpc/server/http_server.go
Rather than installing two separate panic handlers, defer the bookkeeping separately from recovery, and lift the delegated handler call out to the top level of the wrapper.
Also, regularize the server middleware wrappers. Some of the wrappers use constructors, others are explicitly written out as composite literals. To improve legibility, give all of them constructors and add documentation.
No functional changes.
=> rpc: simplify panic recovery in the server middleware

internal/inspect/rpc/rpc.go, internal/rpc/core/routes.go, rpc/jsonrpc/doc.go, rpc/jsonrpc/server/http_json_handler_test.go, rpc/jsonrpc/server/parse_test.go, rpc/jsonrpc/server/rpc_func.go, rpc/jsonrpc/server/ws_handler_test.go, rpc/jsonrpc/test/main.go, test/fuzz/rpc/jsonrpc/server/handler.go
Instead of taking a comma-separated string of parameter names, take each
parameter name as a separate argument. Now that we no longer have an extra flag
for caching, this fits nicely into a variadic trailer.
=> rpc: clean up the RPCFunc constructor signature

rpc/jsonrpc/server/parse_test.go, rpc/jsonrpc/server/rpc_func.go
Require that RPC functions take a context as their first argument, and return
an error as either their only result, or the second of two results.
This does not change how functions are dispatched, but will make it a little
easier to make more invasive changes in the near future.
=> rpc: check RPC service functions more carefully

test/fuzz/rpc/jsonrpc/server/handler.go
I missed this during my previous pass.
Requirements for handlers:
- First argument is context.Context.
- Last of two results is error.
=> rpc: update fuzz criteria to match the implementation

rpc/jsonrpc/server/http_uri_handler.go, rpc/jsonrpc/server/parse_test.go, test/e2e/docker/Dockerfile
The parameters for RPC GET requests are parsed from query arguments in the
request URL. Rework this code to remove the need for tmjson. The structure of a
call still requires reflection, and still works the same way as before, but the
code structure has been simplified and cleaned up a bit.
Points of note:
- Consolidate handling of pointer types, so we only need to dereference once.
- Reduce the number of allocations of reflective types.
- Report errors for unsupported types rather than returning untyped nil.
Update the tests as well. There was one test case that checked for an error on
a behaviour the OpenAPI docs explicitly demonstrates as supported, so I fixed
that test case, and also added some new ones for cases that weren't checked.
=> rpc: remove dependency of URL (GET) requests on tmjson

crypto/crypto.go, crypto/ed25519/ed25519.go, crypto/secp256k1/secp256k1.go, crypto/sr25519/encoding.go, crypto/sr25519/privkey.go, crypto/sr25519/pubkey.go, internal/jsontypes/jsontypes.go, internal/jsontypes/jsontypes_test.go, internal/p2p/conn/secret_connection_test.go, privval/file.go, rpc/client/http/http.go, rpc/client/http/request.go, types/block.go, types/evidence.go, types/genesis.go, types/node_key.go, types/validator.go, types/vote.go, version/version.go
Add a new package `internal/jsontypes` that implements a subset of the behaviour defined in the custom `libs/json` (a.k.a. `tmjson`) package. Specifically, this new package implements the tag type registry used to map concrete types to interfaces, but omits all the recursive reflection. The new package handles only the packaging and decoding of "type wrapper" objects, using the same format as the original code.
Apply this package to encode the parameters to the `broadcast_evidence` call in the JSON-RPC client. This case was explicitly skipped in #7552.
For now, this change only affects the "encoding" side. The server decoding code is still using `tmjson`, but I will update that in future PRs by applying similar treatment to the handful of other types (e.g., GenesisDoc) that traffic in …
=> rpc: simplify the encoding of interface-typed arguments in JSON

internal/libs/protoio/io_test.go
After writing and then reading a bunch of random messages, the test was
checking that it did not read the same number of messages that it wrote.
The sense of this check was inverted; they should match.
Introduced by accident in #7522. I'm not sure why this did not show up in CI.
Edit: I now know why it didn't show up in ci: #7608.
=> protoio: fix incorrect test assertion

internal/statesync/dispatcher.go, light/provider/errors.go, light/provider/http/http.go, light/provider/http/http_test.go
The custom error types in the provider package did not propagate their wrapped
underlying reasons, making it difficult for the test to check that the correct
error was observed.
- Fix the custom errors to have a true underlying error (not just a string).
- Add Unwrap methods to support inspection by errors.Is.
- Update usage in a few places.
- Fix the test to check for acceptable variation.
Fixes #7609.
=> light: fix provider error plumbing

CHANGELOG_PENDING.md, internal/rpc/core/mempool.go, internal/rpc/core/routes.go, light/rpc/client.go, rpc/client/http/http.go, rpc/client/http/request.go, rpc/client/interface.go, rpc/client/local/local.go, rpc/client/rpc_test.go, rpc/openapi/openapi.yaml
This commit changes the behavior of the /unconfirmed_txs endpoint by replacing `limit` with a `page` and `perPage` parameter for pagination.
The test case for unconfirmed_txs has been modified to properly test this change and the documentation for the API as well.
fixes #7500
Closes #7500
=> rpc: paginate mempool /unconfirmed_txs endpoint

privval/signer_client_test.go, privval/signer_listener_endpoint_test.go, rpc/jsonrpc/client/ws_client_test.go, rpc/jsonrpc/jsonrpc_test.go, rpc/jsonrpc/server/http_server_test.go, rpc/jsonrpc/server/ws_handler_test.go
Switch to the testing logger in more places, but also add in the leak
test detector to explicitly catche the cases that would have been
caught by log-after-test panics.
=> testing: use noop loger with leakteset in more places

internal/p2p/pex/reactor.go
I believe it is possible that a channel may be closed after reporting `true` from its `Next` method, but before the caller retrieves the value of its current item (by calling `Envelope`).
This appears to lead to an occasional nil-indirection panic in the PEX reactor, which pushes envelopes from the iterator concurrently with context cancellation.
=> pex: do not send nil envelopes to the reactor

internal/p2p/pex/reactor.go
Reverts and improves on #7622. The problem turns out not to be on the PEX
channel side, but on the pass-through (Go) channel.
=> pex: improve handling of closed channels

internal/libs/autofile/autofile.go, internal/libs/autofile/autofile_test.go, internal/libs/autofile/group.go
During file rotation and WAL shutdown, there was a race condition between users
of an autofile and its termination. To fix this, ensure operations on an
autofile are properly synchronized, and report errors when attempting to use an
autofile after it was closed.
Notably:
- Simplify the cancellation protocol between signal and Close.
- Exclude writers to an autofile during rotation.
- Add documentation about what is going on.
There is a lot more that could be improved here, but this addresses the more
obvious races that have been panicking unit tests.
Please add a description of the changes that this PR introduces and the files that
are the most critical to review.
Updates #7624.
=> autofile: ensure files are not reopened after closing

privval/signer_client_test.go
The interaction between defers and t.Cleanup can be delicate.
For this case, which regularly flakes in CI, be explicit:
Defer the closes and waits before making any attempt to leaktest.
=> privval: synchronize leak check with shutdown

internal/consensus/state.go
Noticed spurious panic in test related to the `Proposal` being nil here. 
The other fields being used here, `Votes` and `Validators` should not be nil.
`Votes` is set at the beginning of each round, and `Validators` is initialized from the genesis file.
=> consensus: check proposal non-nil in prevote message delay metric

Makefile, internal/p2p/pex/reactor_test.go
I figured out why we weren't seeing some local test failures in CI.
This will need some fixes to land before it can be merged, including:
The test filter was looking for "TestGoFiles", which does not include tests in
a separate package (e.g., "package foo_test" for "package foo").
This caused several packages not to be tested in CI, including:
```
github.com/tendermint/tendermint/abci/client
github.com/tendermint/tendermint/crypto
github.com/tendermint/tendermint/crypto/tmhash
github.com/tendermint/tendermint/internal/eventbus
github.com/tendermint/tendermint/internal/evidence
github.com/tendermint/tendermint/internal/inspect
github.com/tendermint/tendermint/internal/jsontypes
github.com/tendermint/tendermint/internal/libs/protoio
github.com/tendermint/tendermint/internal/libs/sync …
```
=> build: Make sure to test packages with external tests

.github/workflows/tests.yml
Decrease the likelihood that two flaky tests will hit
the same batch.
Account for the increase in test load from #7608.
=> Increase test splits from 4 to 6.

abci/client/socket_client_test.go
This averts a log-after-close issue. We should probably also chase the shutdown
issues, but since ABCI clients should generally only shut down once per process
I don't think this is a real priority, and the trace is hairy.
=> abci/client: use a no-op logger in the test

privval/file.go, privval/file_test.go
After #7592, @cmwaters noticed that the logic for re-using old timestamps for proposals may not work with proposer-based timestamps. This change removes the logic to re-use old proposal timestamps since it is no longer correct. Two proposals with different timestamps can no longer be treated as equivalent. Signing a proposal that only differs by timestamp in the new algorithm can be thought of as roughly equivalent to signing a proposal that only differs by `BlockID` in the old scheme. 
I also investigated the codebase and checked for any place we updated a timestamp using the pattern `(Timestamp = |Timestamp: )` and saw no additional places where we are updating the timestamp of a proposal message. 
Here is the output of that search:
```
privval/file.go:372:			vote.Timestamp = timestamp …
```
=> privval: do not use old proposal timestamp

CHANGELOG_PENDING.md, internal/p2p/peermanager.go, internal/p2p/peermanager_test.go, node/setup.go
Fixes #7593
this is the same as #7594 but backported to branch `v0.35.x`
=> p2p: always advertise self, to enable mutual address discovery (v0.35.x)

abci/client/client.go, abci/client/grpc_client.go, abci/client/local_client.go, abci/client/mocks/client.go, abci/client/socket_client.go, abci/client/socket_client_test.go, abci/cmd/abci-cli/abci-cli.go, abci/example/example_test.go, abci/example/kvstore/kvstore_test.go, abci/tests/server/client.go, internal/consensus/replay.go, internal/consensus/replay_test.go, internal/mempool/mempool.go, internal/proxy/app_conn.go, internal/proxy/app_conn_test.go, internal/proxy/mocks/app_conn_consensus.go, internal/proxy/mocks/app_conn_mempool.go, internal/proxy/mocks/app_conn_query.go, internal/proxy/mocks/app_conn_snapshot.go, internal/rpc/core/abci.go, internal/rpc/core/mempool.go, internal/state/execution.go, internal/statesync/reactor.go, internal/statesync/reactor_test.go, internal/statesync/syncer.go, internal/statesync/syncer_test.go, node/node.go
As we discussed at the ABCI++ meeting, the rollout in v0.36 is an ideal time to clean up some  infelicities in the original implementation. This is a first step toward that cleanup. We will still have to address Flush, CommitTx, and DeliverTx separately, but getting the easy cases out of the way will help keep those diffs smaller.
N.B.: The diff in `grpc_client.go` is large, but less complicated than it looks. It folds the sync/async versions back together, strips out the unnecessary support code, and updates the names. The rename makes the diff look hairier than it should be.
This change has two main effects:
1. Remove most of the Async methods from the abci.Client interface.
Remaining are FlushAsync, CommitTxAsync, and DeliverTxAsync.
2. Rename the synchronous methods to remove the …
=> abci/client: simplify client interface

privval/file.go
It seems sign procedure is always performed when RHS and signbytes are equal
=> privval: avoid re-signing vote when RHS and signbytes are equal

internal/consensus/wal_test.go, internal/libs/autofile/group.go, internal/libs/autofile/group_test.go
I think rotate-file might still race because the operations on `Head`
take and release the lock more than once.
=> autofile: avoid shutdown race

internal/consensus/common_test.go, internal/consensus/state_test.go
The problem with the `TestStateFullRound1` is that the state that we are observeing, `cs`, can advance to the next height before we query its data. Specifically, on line `388`, when we called `validatePrevote`, the `cs` State had already advanced to height 2, so querying that State for the votes of height 1 either yielded nil or an erroneous value. This change adds a `ensurePrevoteMatch` function that checks that the prevote occurred and checks that it is for the expected block at the same time. If this change looks reasonable I can just apply the same fix to all of the places where we perform `ensurePrevote` followed by `validatePrevote` to use this function instead.
=> consensus: fix height advances in test state

light/rpc/client.go
- if ABCI query against the latest state needs to be done, perform query against latestHeight-1 instead 
- similar thing is done for `BlockResults`.
Closes #7641.
=> light: Fix query against the latest state in light client

CHANGELOG_PENDING.md
Despite leaving myself a TODO to update the changelog before merging #7607, I forgot to actually do it.
=> Update pending changelog from #7607.

internal/mempool/reactor_test.go
Despite the useful-seeming name this isn't a particularly high value
test, and it mostly just serves to smoke out potential panics due to
poorly handled concurrency. It may also detect race conditions, though
the placement of the mutexes make this unlikely. The mutexes as used
also make it unlikely that there is much meaningful concurrent
execution.
While it does run the reactors, and it does have a parallel workload,
it's also *not really* a test of reactor concurrency as the test
operations mostly deal with the mempool rather than the reactor, which
is a bit confusing.
Unfortunitley the test does fail sometimes, which makes it something
of a bother. Looking at it's history, it's a regression test for the
previous implementation, so while it may be worth keeping around, the
way that it's …
=> mempool: reactor concurrency test tweaks

internal/jsontypes/jsontypes.go, internal/jsontypes/jsontypes_test.go
Avert panics for corner cases (e.g., nil pointers) and for implementations that
reside only on the pointer type. Add documentation and tests.
**Note to reviewers:** This is a self-contained piece of an ongoing series of changes intended to eliminate our dependency on the custom JSON encoding library. It is not very interesting in itself, but it is needed for later parts and is easier to review in isolation.
=> jsontypes: improve tests and error diagnostics

internal/consensus/state_test.go, internal/eventbus/event_bus.go, internal/eventbus/event_bus_test.go, internal/pubsub/pubsub.go, internal/pubsub/pubsub_test.go, internal/pubsub/query/bench_test.go, internal/pubsub/query/query.go, internal/pubsub/query/query_test.go, internal/pubsub/subindex.go, types/events.go
- Remove the pubsub.Query interface and instead use the concrete query type. Nothing uses any other implementation but pubsub/query.
- Update the Matches method to drop the error return. The signature of this method is a holdover from when queries were compiled and executed lazily. Now that queries are always precompiled, the error is always nil and is no longer needed.
=> pubsub: use concrete queries instead of an interface

.github/workflows/linter.yml
The latest point release includes https://github.com/github/super-linter/pull/2295
which enables a bunch of checks that break existing use.
=> Pin super-linter to a less noisy version.

types/params.go
This is being done to prevent flaky failures of the `TestReactorValidatorSetChanges`
=> params: increase default synchrony params

internal/consensus/metrics.go, internal/consensus/state.go
This change adds a histogram that tracks the difference between the proposal timestamp and the local time of the validator. This metric aims to help validators determine, in aggregate, how far away their local time is from the the times proposed by the rest of the network.
The metrics added take the following form:
```
tendermint_consensus_proposal_timestamp_difference_bucket{chain_id="test-chain-aZbwF1",is_timely="true",le="-15"} 0
tendermint_consensus_proposal_timestamp_difference_bucket{chain_id="test-chain-aZbwF1",is_timely="true",le="-3"} 0
tendermint_consensus_proposal_timestamp_difference_bucket{chain_id="test-chain-aZbwF1",is_timely="true",le="-1"} 0
tendermint_consensus_proposal_timestamp_difference_bucket{chain_id="test-chain-aZbwF1",is_timely="true",le="-0.5"} 0 …
```
=> metrics: add metric for proposal timestamp difference

internal/consensus/metrics.go, internal/consensus/state.go
Moving this over from the proposer-based timestamps branch #7550.
=> metrics: add metric for proposal timestamp difference 

CHANGELOG_PENDING.md, rpc/client/http/http.go, rpc/client/http/ws.go, rpc/jsonrpc/client/http_json_client.go, rpc/jsonrpc/client/ws_client.go, rpc/jsonrpc/client/ws_client_test.go, rpc/jsonrpc/jsonrpc_test.go
Unexport and/or remove the WSOptions types, which were never used with non-default values except in our own tests. Fix up the tests to not require the options.
Searches of cs.github.com reveal no non-default use.
=> rpc: clean up unused non-default websocket options

rpc/jsonrpc/server/http_uri_handler.go, rpc/jsonrpc/server/rpc_func.go
This doesn't actually change the behaviour, it just simplifies the handler logic a bit.
=> rpc: don't route websocket-only methods on GET requests

rpc/jsonrpc/types/types.go
Instead of having the exported Request and Response type expose the version
directly, delegate version injection to an unexported shim.  We already had the
shim; this just boosts it to the top level and does a bit more checking.
=> rpc: clean up encoding of request and response messages

internal/rpc/core/events.go, light/provider/http/http_test.go, light/rpc/client.go, rpc/jsonrpc/server/http_json_handler.go, rpc/jsonrpc/server/http_json_handler_test.go, rpc/jsonrpc/server/http_server_test.go, rpc/jsonrpc/server/http_uri_handler.go, rpc/jsonrpc/server/ws_handler.go, rpc/jsonrpc/types/types.go, rpc/jsonrpc/types/types_test.go
Rework the way JSON-RPC responses are constructed to simplify the plumbing of request IDs, reduce the surface area of the `rpc/jsonrpc/types` package, and eliminate duplication of error introspection logic across the three RPC flavours (HTTP GET, HTTP POST, and websocket).
- remove the top-level response constructors
- add code constants and response methods
- update usage
- update test cases
This change affects the Go package API, but does not change the behaviour of the RPCs.
=> rpc: simplify and consolidate response construction

rpc/jsonrpc/client/decode.go, rpc/jsonrpc/client/http_json_client.go
Update the interface of the batch decoder to match the type signature of the
single-response case. The caller provides the outputs, so there is no need to
return them as well.
No functional changes.
=> rpc: clean up unmarshaling of batch-valued responses

abci/cmd/abci-cli/abci-cli.go, cmd/priv_val_server/main.go, cmd/tendermint/commands/gen_validator.go, cmd/tendermint/commands/init.go, cmd/tendermint/commands/inspect.go, cmd/tendermint/commands/key_migrate.go, cmd/tendermint/commands/light.go, cmd/tendermint/commands/reindex_event.go, cmd/tendermint/commands/reindex_event_test.go, cmd/tendermint/commands/replay.go, cmd/tendermint/commands/reset_priv_validator.go, cmd/tendermint/commands/rollback.go, cmd/tendermint/commands/root.go, cmd/tendermint/commands/root_test.go, cmd/tendermint/commands/run_node.go, cmd/tendermint/commands/show_node_id.go, cmd/tendermint/commands/show_validator.go, cmd/tendermint/commands/testnet.go, cmd/tendermint/main.go, docs/tutorials/go.md, libs/cli/setup.go, libs/log/default_test.go
This began as an attempt to remove a single panic in
`libs/log/default.go` but removes a bunch of package state in the
command package.
=> cmd: avoid package state in cli constructors

internal/consensus/peer_state.go, internal/consensus/reactor.go
This is clearly a cob-web in the code, and may predict a solution to #7729, though this is difficult to backport because we don't have contexts in 0.35
=> consensus: remove unused closer construct

rpc/jsonrpc/client/decode.go, rpc/jsonrpc/client/http_json_client.go, rpc/jsonrpc/client/ws_client.go, rpc/jsonrpc/client/ws_client_test.go, rpc/jsonrpc/server/http_json_handler.go, rpc/jsonrpc/server/http_json_handler_test.go, rpc/jsonrpc/server/http_server_test.go, rpc/jsonrpc/server/http_uri_handler.go, rpc/jsonrpc/server/ws_handler.go, rpc/jsonrpc/server/ws_handler_test.go, rpc/jsonrpc/types/types.go, rpc/jsonrpc/types/types_test.go
Replace the ID wrapper interface with plain JSON. Internally, the client
libraries use only integer IDs, and the server does not care about the ID
structure apart from checking its validity.
Basic structure of this change:
- Remove the jsonrpcid interface and its helpers.
- Unexport the ID field of request and response.
- Add helpers for constructing requests and responses.
- Fix up usage and tests.
=> rpc: simplify the handling of JSON-RPC request and response IDs

rpc/jsonrpc/server/http_json_handler.go
The output of the default endpoint-list query was not correctly segregating
methods with and without arguments. Fix this, and also clean up the output to
be easier to read (both in code and in generated source).
Fixes #3618.
Results:
```html
<html>
<head><title>List of RPC Endpoints</title></head>
<body>
<h1>Available RPC endpoints:</h1>
<hr />
<h2>Endpoints with no arguments:</h2>
<ul>
<li><a href="//localhost:26657/abci_info">//localhost:26657/abci_info</a></li>
<li><a href="//localhost:26657/consensus_state">//localhost:26657/consensus_state</a></li>
<li><a href="//localhost:26657/dump_consensus_state">//localhost:26657/dump_consensus_state</a></li>
<li><a href="//localhost:26657/genesis">//localhost:26657/genesis</a></li>
<li><a …
```
=> rpc: fix layout of endpoint list

rpc/jsonrpc/server/http_json_handler.go
A manual backport of #7742 into v0.35.x.
The output of the default endpoint-list query was not correctly segregating
methods with and without arguments. Fix this, and also clean up the output to
be easier to read (both in code and in generated source).
=> rpc: fix layout of endpoint list (#7742)

light/rpc/client.go, rpc/client/helpers.go, rpc/client/http/ws.go, rpc/client/interface.go, rpc/client/mocks/client.go, rpc/client/rpc_test.go, rpc/jsonrpc/client/integration_test.go, rpc/jsonrpc/client/ws_client.go, rpc/jsonrpc/client/ws_client_test.go, rpc/jsonrpc/server/ws_handler.go
I added the RunState type in #6971 to disconnect clients from the service
plumbing, which they do not need. Now that we have more complete context
plumbing, the lifecycle of a client no longer depends on this type: It serves
as a carrier for a logger, and a Boolean flag for "running" status, neither of
which is used outside of tests.
Logging in particular is defaulted to a no-op logger in all production use.
Arguably we could just remove the logging calls, since they are never invoked
except in tests. To defer the question of whether we should do that or make the
logging go somewhere more productive, I've preserved the existing use here.
Remove use of the IsRunning method that was provided by the RunState, and use
the Start method and context to govern client lifecycle.
Remove the one …
=> rpc: remove the placeholder RunState type.

.github/workflows/tests.yml
(a manual backport of #7630)
We need the number of splits to match across branches so that the required checks will line up.
=> Increase test splits from 4 to 6. (#7630)

docs/architecture/adr-071-proposer-based-timestamps.md
closes: #7758 
This change performs the following:
* Removes the description of the non-proposers waiting
* Removes descriptions of the `Accuracy` parameter that no longer exists
* Corrects the inequality to properly reflect the `timely` check.
* Renames the consensus params to `SynchronyParams`
* Minor cosmetic fixes.
=> ADR: synchronize PBTS ADR with spec

rpc/coretypes/responses.go, types/block_meta.go, types/events.go
This picks up a few remaining cases that I missed during my previous round of
adding these tags.
=> types: add string format to 64-bit integer JSON fields

internal/mempool/reactor.go
The incidence of this message increased a bunch in recent days because
we're returning this error in more cases now. There's no real need to
log it in any case, but particularly this one.
=> mempool: remove duplicate tx message from reactor logs

docs/app-dev/getting-started.md, docs/tendermint-core/subscription.md, docs/tendermint-core/using-tendermint.md, docs/tutorials/go-built-in.md, docs/tutorials/go.md
Remove JSON-RPC wrappers from GET output, since they are no longer printed.
Also format examples with jq so they look a little neater.
Fixes #7779.
=> docs: fix RPC output examples for GET queries

go.mod, go.sum, rpc/jsonrpc/client/ws_client.go, rpc/jsonrpc/client/ws_client_test.go
We have this one solitary metric from the go-metrics package.  In principle
this statistic could be useful, but the way we have it hooked up, nothing can
observe the value: We don't export it, we don't log it, and it does not auto
publish anywhere.
Given that this state of affairs has not changed since the metric was first
added in 2017 (c08618f), I think we can safely discard it. No one is now or has
ever gotten any data out of this metric.
=> rpc: remove unused latency metric

crypto/secp256k1/secp256k1.go
There was a nolint directive on this deprecated import, which golangci-lint
complains about being unnecessary. However, removing it angers staticcheck,
which enforces deprecation warnings.
Use the right syntax to make both equally unhappy.
=> Silence a staticcheck warning.

internal/state/indexer/indexer_service_test.go, internal/state/indexer/sink/psql/psql_test.go
To simplify local testing, do not report failures for tests that require Docker
when Docker is not avaliable. Instead, log a warning and skip the tests.
This has no effect in CI, where Docker is installed.
=> indexer: skip Docker tests when Docker is not available

internal/pubsub/pubsub.go
This check was correctly handled in Unsubscribe, but not UnsubscribeAll.
=> pubsub: check for termination in UnsubscribeAll

docs/architecture/adr-071-proposer-based-timestamps.md
We should probably make the markdown link checker required at some point, since it keeps failing silently in the backgound.
=> Fix broken links in ADR 071.

docs/rfc/README.md, docs/rfc/rfc-011-custom-indexing.md, docs/rfc/rfc-012-custom-indexing.md
{[rendered](https://github.com/tendermint/tendermint/blob/mjf/rfc-custom-index/docs/rfc/rfc-012-custom-indexing.md)}
The original Tendermint implementation provided a fixed, built-in event
indexer, but users would like to plug in different indexing backends.  Although
ADR-065 was a good first step toward customization of indexing, its
implementation model does not satisfy all the user requirements.  Moreover,
this approach leaves some existing technical issues with indexing unsolved.
This RFC documents these concerns, and discusses some potential approaches to
solving them.  It does _not_ propose a specific technical decision. It is meant
to unify and focus some of the disparate discussions of the topic.
=> RFC 012: Event Indexing Revisited

docs/README.md, docs/architecture/adr-001-logging.md, docs/architecture/adr-044-lite-client-with-weak-subjectivity.md, docs/architecture/adr-069-flexible-node-intitalization.md, docs/nodes/running-in-production.md, docs/tendermint-core/rpc.md
For most cases I was able to find a new target. In one case the branch was
deleted, so I removed the link.
=> docs: fix broken markdown links (cherry-pick of #7847)

docs/README.md, docs/architecture/adr-001-logging.md, docs/architecture/adr-044-lite-client-with-weak-subjectivity.md, docs/architecture/adr-069-flexible-node-intitalization.md, docs/architecture/adr-073-libp2p.md, docs/architecture/adr-078-nonzero-genesis.md, docs/nodes/running-in-production.md, docs/tendermint-core/rpc.md
For most cases I was able to find a new target. In one case the branch was
deleted, so I removed the link.
Updates #7675.
```sh
find docs -type f -name '*.md' -print0 | \
xargs -0 -n1 -t docker run -v ${PWD}:/tmp:ro --rm -i --workdir /tmp \
-a stderr -a stdout ghcr.io/tcort/markdown-link-check:stable |& \
grep -A1 -E '(FILE|ERROR):'
```
=> docs: fix broken markdown links

docs/tutorials/go.md
The main function defers some things that do not run in the "normal" exit case
because we call os.Exit(0) explicitly. Since falling off the end of main does
the same thing, and also permits defers to run, let's do that.
Fixes #7852.
=> docs: remove unnecessary os.Exit calls at the end of main

docs/app-dev/getting-started.md
Minor PR to fix a typo with outdated command after release v35:
previously it was:
`tendermint unsafe_reset_all` 
and now:
`tendermint unsafe-reset-all`
=> Update unsafe-reset-all command to match release v35

docs/app-dev/abci-cli.md, docs/networks/docker-compose.md, docs/nodes/logging.md, docs/tendermint-core/rpc.md, docs/tendermint-core/using-tendermint.md
Updates #7675.
Repro:
linkpatch -recur -target v0.35.x -skip-path docs/README.md,docs/DOCS_README.md \
-skip-match 'docs/(rfc|architecture)/' docs
=> Update absolute links in v0.35.x to reference that branch.

docs/post.sh, docs/pre.sh
Previously we cloned the spec repository and attached the markdown files to the docs site we host. This PR removes the spec section because:
1. It refers to the master version of the spec and thus could lead to confusion
2. Users should first rely on the externally facing documentation provided and only when necessary referto the more technical spec which they can see in github
=> docs: remove spec section from v0.35 docs

docs/app-dev/abci-cli.md, docs/networks/docker-compose.md, docs/tendermint-core/how-to-read-logs.md, docs/tendermint-core/rpc.md, docs/tendermint-core/using-tendermint.md
Updates #7675.
Repro:
linkpatch -recur -target v0.33.x -skip-path docs/README.md,docs/DOCS_README.md \
-skip-match 'docs/architecture/' docs
=> Update absolute links in v0.33.x to reference that branch.

docs/.vuepress/config.js, docs/versions
~We might want to do this for v0.33 also.~
Per the below we'll keep v0.33 for now.
=> Remove master from the docs site version config.

docs/.vuepress/config.js
This is a temporary workaround for #7908.
=> docs: Pin the RPC docs to v0.35 instead of master

docs/.vuepress/config.js
A manual cherry-pick of 3b20931da335fe9bbe707adc37313bccbe613192.
=> docs: Pin the RPC docs to v0.35 instead of master (#7909)

docs/architecture/adr-075-rpc-subscription.md, internal/eventlog/cursor/cursor.go, internal/eventlog/cursor/cursor_test.go, internal/eventlog/eventlog.go, internal/eventlog/eventlog_test.go, internal/eventlog/item.go, internal/eventlog/metrics.go, internal/eventlog/prune.go
Implement the basic cursor and eventlog types described in ADR 075.  Handle
encoding and decoding as strings for compatibility with JSON.
- Add unit tests for the required order and synchronization properties.
- Add hooks for metrics, with one value to be expanded later.
- Update ADR language so align names with the implementation.
This is the largest single unit of the implementation. This PR does not include the plumbing to make the ADR 075 events interface usable. That will follow in subsequent PRs.
There are two packages here to consider: [internal/eventlog](../blob/mjf/adr075-eventlog/internal/eventlog) and [internal/eventlog/cursor](../blob/mjf/adr075-eventlog/internal/eventlog/cursor). The latter is a subsidiary of the former, so I recommend starting with internal/eventlog.
[Design …
=> rpc: implement the eventlog defined by ADR 075

CHANGELOG_PENDING.md, config/config.go, config/toml.go, internal/rpc/core/env.go
This is part of the implementation of ADR-075. This change adds the configuration settings that will be used by the event log, and hooks up an experimental switch to disable websocket export.
See specifically the [Discussion section](https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-075-rpc-subscription.md#discussion) for background on these config settings.
=> config: add event subscription options and defaults

docs/versions
There are a lot of existing links to the master section of the site, and my
attempts to get a redirector working have so far not succeeded. While it still
makes sense to not publish docs for unreleased code, a 404 is almost certainly
more disruptive than seeing docs for unreleased stuff.
This includes the docs in the build again, but does not add them back to the
selector menu. That allows URLs to resolve but encourages folks to use the
released versions when they have a choice.
I left the redirect for the RPC link in place, since that's still useful.
Updates #7935.
=> Restore building docs for master on docs.tendermint.com.

Makefile, docs/versions
We originally tried to disable building docs for the master branch, but a lot of existing links pointed to that, so we reverted that change.
This is a different tactic, suggested by @cmwaters, where we point docs/master to the same data as the latest (default) release branch (the one listed "last" in the `versions` file).
=> docs: point docs/master to the same content as the latest release

internal/rpc/core/env.go, internal/rpc/core/events.go, internal/rpc/core/routes.go, light/proxy/routes.go, rpc/coretypes/responses.go, types/events.go, types/events_test.go
This change implements the new method on the RPC environment, and adds data types for the parameters and results of that method.
It also updates the event data types that have ABCI events to expose them to the event log.
=> rpc: implement the ADR 075 /events method

node/node.go
This change connects the ADR 075 /events implementation to node setup.
=> node: hook up eventlog and eventlog metrics

CHANGELOG_PENDING.md, light/proxy/routes.go, light/rpc/client.go, rpc/client/helpers.go, rpc/client/http/http.go, rpc/client/http/ws.go, rpc/client/interface.go, rpc/client/local/local.go, rpc/test/helpers.go
- Update documentation to deprecate the old methods.
- Add Events methods to HTTP, WS, and Local clients.
- Add Events method to the light client wrapper.
- Rename legacy events client to SubscriptionClient.
- Update pending changelog.
=> rpc/client: add Events method to the client interface

rpc/client/event_test.go, rpc/client/helpers.go, rpc/client/rpc_test.go
This is part of the implementation of ADR 075. This change updates an existing client helper function, used by tests, to use the new Events API instead of subscriptions.
=> rpc/client: rewrite the WaitForOneEvent helper

UPGRADING.md, internal/rpc/core/env.go, internal/rpc/core/events.go
Also add deprecation logs when websocket is enabled
As promised in ADR 075, this causes the node to log (without error) when
websocket transport is enabled, and also when subscribers connect.
=> Add upgrading notes for the new Events RPC interface.

abci/example/example_test.go
This averts a rare but annoying log-after-test race condition.
=> abci: use no-op loggers in the examples

internal/statesync/syncer_test.go
the perfectly 2-second sleep setup in line 176  let the `syncer.fetchChunks` has a small chance to refetch the chunk index1 
before the `syncer.applyChunks` returns the RETRY_SNAPSHOT error. it will let the fetchCtx be canceled and then make the goroutine cannot request the chunk.
the syncer.Sync might need a bit of refactor to tackle this case.
close #7644
=> statesync: fix SyncAny test

.github/workflows/e2e-manual.yml
We can't trigger this manually from the workflow in master unless the workflow also exists in the base of whichever branch we're targeting (per GitHub).
=> Add manual e2e workflow to v0.34.x.

.github/workflows/e2e-manual.yml
We can't trigger this manually from the workflow in master unless the workflow also exists in the base of whichever branch we're targeting (per GitHub).
=> Add manual e2e workflow to v0.35.x.

scripts/estream/estream.go
**Note to reviewers:** This is an optional tool that may be useful, but is not necessary for any specific production task. I'm offering it because it was helpful during development, but if we don't want to keep it around it's not going to impede use of the API.
---
This tool is an aid to debugging, and demonstrates the API of the eventstream
helper package. It subscribes to the event stream of a running node with the
ADR 075 event log enabled, and writes matching events to stdout as JSON.
=> Add command-line tool to manually subscribe to an event stream.

abci/client/socket_client.go
This change fixes the issue where requests through the socket client would fail if the buffer is full. This is a backport of the same change applied to master with slight alteration. 
The reproduction script was run with this change added and the errors writing to the socket were not observed.
=> abci: revert buffer limit change

internal/proxy/app_conn.go
Noticed this issue while working on the abci buffer problem. Merging here so that the fix can be part of v0.35.2
=> proxy: fix endblock metric

docs/architecture/adr-044-lite-client-with-weak-subjectivity.md, docs/architecture/adr-045-abci-evidence.md, docs/roadmap/roadmap.md, docs/tutorials/go-built-in.md, docs/tutorials/go.md
Found by the link checker.
There are still some links that aren't fixed, because it's not clear where they _should_ point. I just hit the obvious ones.
=> docs: fix some broken markdown links

.github/workflows/lint.yml
This reverts commit e4dced243727da5db4190741aa49a816ced41ada.
Caused inconsistent results, likely due to a caching problem.
=> Revert "build(deps): Bump golangci/golangci-lint-action from 2.5.2 to 3.1.0 (#8026)"

.github/workflows/lint.yml, internal/p2p/p2ptest/network.go, internal/p2p/p2ptest/require.go, internal/p2p/peermanager.go, internal/p2p/peermanager_test.go, internal/p2p/router.go, internal/statesync/reactor.go, internal/statesync/reactor_test.go
This is a little coarse, but the idea is that we'll send information
about the channels a peer has upon the peer-up event that we send to
reactors that we can then use to reject peers (if neeeded) from reactors.
This solves the problem where statesync would hang in test networks
(and presumably real) where we would attempt to statesync from seed
nodes, thereby hanging silently forever.
=> p2p: plumb rudamentary service discovery to rectors and update statesync

internal/statesync/reactor_test.go, internal/statesync/stateprovider.go
We're waiting between trying witnesses (which shouldn't be neccessary
because the witnesses shouldn't depend on each other,) and also
between *attempts*, and really the outer sleep should be enough.
=> statesync: avoid compounding retry logic for fetching consensus parameters

internal/consensus/reactor_test.go
This is mostly an extremely small change where I double a somewhat
arbitrarly set timeout from 1m to 2m for an entire test. When I put
these timeouts in the test, they were arbitrary based on my local
performance (which is quite fact,) and I expected that they'd need to
be tweaked in the future.
A big chunk of this PR is reworking a collection of helper functions
that produce somewhat intractable messages when a test fails, so that
the error messages take up less vertical space, hopefully without
losing any debugability.
=> consensus: validator set changes test cleanup

docs/architecture/adr-075-rpc-subscription.md, internal/rpc/core/events.go, rpc/client/eventstream/eventstream_test.go
Since the goal of reading events at the head of the event log is to satisfy a
subscription style interface, there is no point in allowing head polling with
no wait interval. The pagination case already bypasses long polling, so the
extra option is unneessary.
Set a minimum default long-polling interval for the head case.
=> rpc: set a minimum long-polling interval for Events

Makefile, docs/versions
This reverts commit f939f962b19d87e7f23ec912e388ac9165fb1ff4.
A lot of inbound links are still broken, so we will need to find a different
approach to suppressing unreleased docs.
Updates #8052.
=> Revert "Remove master from versions and copy it from the latest."

internal/rpc/core/env.go, internal/rpc/core/net.go, internal/rpc/core/status.go, node/node.go
This is another small (and perhaps unintuitive) cut toward #6777, to
make the dependency on `types.NodeInfo` a start-time rather than
construction-time requirement.
=> node: excise node handle within rpc env

internal/blocksync/reactor.go, internal/blocksync/reactor_test.go, internal/consensus/byzantine_test.go, internal/consensus/common_test.go, internal/consensus/reactor_test.go, internal/consensus/replay_file.go, internal/consensus/state.go, internal/consensus/wal_generator.go, internal/mempool/mempool.go, internal/mempool/mempool_test.go, internal/state/execution.go, internal/state/tx_filter.go, internal/state/tx_filter_test.go, node/node.go, node/node_test.go, node/setup.go, test/fuzz/mempool/checktx.go
This is in persuit of #6777, but sort of backs into the solution, by
removing the construction-time dependency on a state object and uses
the state store and reorganizes reactor construction to interact with
the during startup.
=> node: nodes should fetch state on startup

abci/tests/test_cli/ex1.abci.out, abci/tests/test_cli/ex2.abci.out
the `abci/tests/test_cli/test.sh` test that runs during CI relies on the contents of this file matching the output of the commands that it runs. This PR updates the contents of the output files to contain the output for using `finalize_block`
related to: #7658
=> update abci cli test output

internal/consensus/mempool_test.go, internal/libs/queue/queue_test.go, internal/p2p/conn/secret_connection_test.go, internal/pubsub/query/syntax/syntax_test.go, types/vote_set_test.go
The %w syntax is a fmt.Errorf thing, not supported by the testing package.
=> Fix govet errors for %w use in test errors.

docs/tendermint-core/consensus/proposer-based-timestamps.md
Fixes #8052 again. Ideally we would have some way of detecting that this
happens before merging, but the way we build docs right now is kind of
complicated.
=> Fix YAML front matter.

libs/service/service.go, node/node.go
closes: #8088 
This change allows the `service.Service` list in `node.go` to start Nop versions of the listed services. An alternate approach would be to build the services list up throughout the course of the `makeNode` function and assign it to the field in the node at the end instead of using a literal of the list. I somewhat like the aesthetics of the literal, but am happy to change to the appending style if this seems off.
=> service: add NopService and use for PexReactor

internal/consensus/common_test.go
Original repro:
go test -run TestStateFullRound1 -race -count=500 ./internal/consensus
=> Fix data race.

internal/p2p/pex/reactor.go, internal/p2p/pex/reactor_test.go
This change looks fairly complicated, but it makes relatively small changes to the existing behaviour. A network will now poll a bit more frequently early in its lifecycle, but the intervals selected by the new code are approximately the same as previously, modulo pinning to the minimum interval.
The PEX reactor has a simple feedback control mechanism to decide how often to
poll peers for peer address updates. The idea is to poll more frequently when
knowledge of the network is less, and decrease frequency as knowledge grows.
This change solves two problems:
1. It is possible in some cases we may poll a peer "too often" and get dropped
by that peer for spamming (cf. #8087).
2. The first successful peer update with any content resets the polling timer
to a very long time (10m), meaning if …
=> p2p: update polling interval calculation for PEX requests

internal/consensus/common_test.go, internal/consensus/reactor_test.go, internal/consensus/state.go, internal/libs/autofile/autofile.go
Updates #8077. The panic handler for consensus currently attempts to effect a
clean shutdown, but this can leave a failed node running in an unknown state
for an arbitrary amount of time after the failure.
Since a panic at this point means consensus is already irrecoverably broken, we
should not allow the node to continue executing. After making a best effort to
shut down the writeahead log, re-panic to ensure the node will terminate before
any further state transitions are processed.
Even with this change, it is possible some transitions may occur while the
cleanup is happening. It might be preferable to abort unconditionally without
any attempt at cleanup.
=> consensus: ensure the node terminates on consensus failure

spec/abci++/abci++_basic_concepts_002_draft.md
=> Typo Fix in abci++_basic_concepts_002_draft.md

proto/tendermint/abci/types.proto, spec/abci++/abci++_methods_002_draft.md
This field is no longer used. Previous discussion on the various bits of VoteExtensions clarified that this should no longer be included in the block or the `ResponsePrepareProposal`.
This change was never part of a released version of Tendermint so we should not be worried about removing and reusing the field tag.
=> abci++: remove app_signed_updates

internal/consensus/reactor.go, libs/events/events.go, libs/events/events_test.go
The events switch code is largely vestigal and is responsible for
wiring between the consensus state machine and the consensus
reactor. While there might have been a need, historicallly to managed
these subscriptions at runtime, it's nolonger used: subscriptions are
registered during startup, and then the switch shuts down at at the
end. 
Eventually the EventSwitch should be replaced by a much smaller
implementation of an eventloop in the consensus state machine, but
cutting down on the scope of the event switch will help clarify the
requirements from the consensus side.
=> libs/events: remove unneccessary unsubscription code

internal/mempool/mempool_bench_test.go, internal/mempool/mempool_test.go, internal/mempool/reactor_test.go
This is minor, but I was trying to write a test and realized that the
application reference in the harness isn't actually used, which is
quite confusing.
=> mempool: test harness should expose application

internal/consensus/common_test.go, internal/consensus/replay_test.go, internal/consensus/wal_generator.go
While I've made moves to reduce the use of the persistent KV store app
in the past, I had left it here before because I imagined that the
replay and WAL tests used the persistent kv store in tests that
started and stopped nodes and then let them handle the replay. 
This does not seem to be the case. 
In all of these tests WAL entries are generated and applied out of
band (which is probably good,) and the applications in question are
never stopped during the test and a new application object never
restarts with access to the files of a previously existing application. 
If this is the case, then the applications can just use ephemeral
storage, which makes for a much more reliable test execution plan.
=> consensus: avoid persistent kvstore in tests

internal/mempool/reactor_test.go
This is failing intermittently, but it's a really simple test, and I
suspect that we're just running into thread scheduling issues on CI
nodes. I don't think making the test smaller reduces the utility of
this test.
=> mempool: reduce size of test

internal/consensus/state.go
I see this panic in tests occasionally, and I don't think there's any
need to close this channel:
- it's only sent to in one place which has a select case with a
default clause, so there's no chance of deadlocks.
- the only place we recieve from it thas a timeout.
=> consensus: skip channel close during shutdown

internal/consensus/invalid_test.go, internal/consensus/reactor_test.go, internal/consensus/state_test.go
We can reduce the size of test fixtures (which will improve test
reliability) without impacting these tests' primary role (which is
correctness.)
Also reducing these test logging will make the tests easier to read,
which whill be a good quality of life improvement for devs.
=> consensus: reduce size of test fixtures and logging rate

internal/consensus/replay_test.go
Ususally this file is cleaned up normally, but being explicit might be
helpful in preventing the "tmpdir not empty during cleanup" errors
which still crop up sometimes.
=> consensus: cleanup tempfile explictly

config/config.go, config/toml.go, internal/blocksync/reactor_test.go, internal/consensus/byzantine_test.go, internal/consensus/common_test.go, internal/consensus/mempool_test.go, internal/consensus/pbts_test.go, internal/consensus/reactor_test.go, internal/consensus/state.go, internal/consensus/state_test.go, internal/test/factory/params.go, node/node_test.go, types/params.go
closes: #8178 
* Add a new set of methods to the `Timeout` consensus params type that enable the calculation of the timeout for voting, proposing, and committing.
* Uses these new methods within the `./internal/consensus/state.go` code in all places where the old local parameters were used.
* Adds a `factory.ConsensusParams` function for fetching consensus params that are more suitable for testing. The default production values are hundreds of milliseconds, which makes sense for live networks, but not in tests. In tests, these values make the tests run incredibly slowly.
* A few places in the consensus code did not calculate the timeout using the base value + delta, i.e., `Vote+VoteDelta`, to calculate a timeout. [Example](https://github.com/tendermint/tendermint/compare/wb/issue-8178?expa …
=> consensus: update state machine to use the new consensus params

spec/abci++/abci++_app_requirements_002_draft.md, spec/abci++/abci++_basic_concepts_002_draft.md, spec/abci++/abci++_methods_002_draft.md, spec/abci++/abci++_tmint_expected_behavior_002_draft.md
There were two decisions taken in ABCI++ bi-weekly meeting on 2022-03-23:
* vote extensions: (1) they are mandatory, (2) then can be of length 0
* configure the size of txs passed to `PrepareProposal`: solution agreed will use a parameter in `config.toml`. This is compatible with current API, but spec needs to allow the case where Tendermint sends too many txs in `RequestPrepareProposal`
This PR:
Partially addresses #8174 (spec side, we need to modify #8141)
Partially addresses #7750 (spec side is now prepared for the implementation, which could be done before or after v0.36)
=> Update ABCI++ spec with decisions taken in the bi-weekly meeting

config/config.go, config/config_test.go, config/toml.go, internal/consensus/state.go, internal/consensus/state_test.go, types/params.go, types/params_test.go
Closes: #7761 
* Replaces the set of timeout parameters in the `config.toml` file with `unsafe-*override` versions of the corresponding `ConsensusParams.Timeout` field. These fields can be used for the duration of v0.36 to override the consensus param in case of emergency.
* Adds a set to the `./internal/consensus/State` type for correctly calculating the value of each timeout based on the set of overrides specified. 
* Should these overrides be documented directly in the auto-generated `config.toml` file? This PR adds them to the `config.toml` that is generated with a comment explaining that they are unsafe, but perhaps it's better to keep them even more hidden to prevent use of them except for in the most extreme cases?
* Are there suggestions for testing this mechanism better? There …
=> consensus: timeout params in toml used as overrides

internal/consensus/state.go, internal/rpc/core/consensus.go, types/params.go
closes: #8156 
* Continues the work of [ADR-74](https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-074-timeout-params.md)
* Adds a set of `*OrDefault()` methods to the new `Timeout` and `Synchrony` `ConsensusParams`. These types return the consensus parameters with any 0 values filled in with the default value for the field.
* Uses these new methods in both the `consensus` and `rpc` code.
This change does not write the new parameters into the database. The new values will not written into the data base until the application issues a change to the consensus parameters. There is no issue with using these default values for historical blocks that were created before these parameters existed because these are timing parameters.
=> timeout parameters take the default if not set

CHANGELOG_PENDING.md, UPGRADING.md, config/config.go, config/toml.go, test/app/test.sh, test/docker/config-template.toml, test/e2e/runner/setup.go
After this change, new nodes will not have indexing enabled by default.
Test configurations will still use "kv".
Update pending changelog.
Updates #8221.
=> config: default indexer configuration to null

test/e2e/app/snapshots.go, test/e2e/app/state.go, test/e2e/tests/app_test.go
This PR addressed two issues:
1. the hashing algorithm for the application used in e2e test only takes into account the keys and values. Therefore, if a block has no txs, the app hash doesn't change. This is problematic in an App used for testing, since it might hide off-by-1 problems
2. TestApp_Hash is comparing the (height, app hash) pair obtained via `Info` ABCI call, with the contents of the block corresponding to that height. This is incorrect in _next-block_ exection mode (the only one currently supported)
To show that this addresses the problem seen in #8141, I did the following tests:
* e2e tests with only the first commit of this PR applied --> e2e tests fail on TestApp_Hash
* e2e tests (several times) with both commits in this PR applied --> all e2e tests pass
=> e2e: Fix hashing for app + Fix logic of TestApp_Hash

crypto/xchacha20poly1305/xchachapoly_test.go
govet complains about using the "%w" format in `t.Errorf` statements. This updates invocations of `t.Errorf` using the `%w` directive to use `%v` instead to fix the govet error.
=> stop using %w in testing errors

types/tx.go, types/tx_test.go
while reviewing https://github.com/tendermint/tendermint/pull/8210, I realized that we may not be properly accounting for the `MaxBytes` per the spec. We only want `MaxBytes` to be checked against the _added_ / _unmodified_ transactions. We were checking against _all_ tx in the `ResponsePrepareProposal`. This pull request fixes the validation logic.
=> abci++: correct max-size check to only operate on added and unmodified

.github/workflows/lint.yml, go.mod
I'm not sure why this wasn't updated automatically, but it appears to be causing heartache in Dependabot PRs.
=> Update golangci-lint-action and golang-ci versions.

CHANGELOG.md, DOCKER/README.md, UPGRADING.md, crypto/README.md, internal/p2p/README.md, networks/local/README.md, spec/p2p/messages/pex.md, test/e2e/README.md
Found during attempts to upgrade the link checker.
Note: In a couple cases the link no longer exists, even at a new location. In those cases I've "commented out" the link by marking it as plain text.
=> Fix more broken Markdown links.

internal/consensus/replay.go, internal/consensus/replay_test.go
There's no case where we recieve an error during handshake and don't
just return/continue, and it's at a point during startup where not
much is going on in the process, so having some classes of errors
return errors and some return panics is confusing and doesn't protect
anything.
=> consensus: avoid panics during handshake

cmd/tendermint/commands/reset.go, privval/file.go
Upstream consumers of Tendermint's commands that use them directly as opposed to using the `root` command will fail because `config` is a **private global**. This forces the upstream user to manually parse the config or having each command do it. This PR takes the latter approach.
=> fix: fix reset commands

CHANGELOG_PENDING.md, go.mod, go.sum, scripts/keymigrate/migrate.go, scripts/keymigrate/migrate_test.go, scripts/scmigrate/migrate.go, scripts/scmigrate/migrate_test.go
Prior to v0.35, the keys for seen-commit records included the applicable
height.  In v0.35 and beyond, we only keep the record for the latest height,
and its key does not include the height.
Update the seen-commit migration to ensure that the record we retain after
migration is correctly renamed to omit the height from its key.
- Update the test cases to check for this condition after migrating.
- Simplify concurrency in the baseline key migration script.
=> scmigrate: ensure target key is correctly renamed

.github/workflows/release.yml
Our release notes are intended to point to the CHANGELOG section for that
release, rather than the default commit log summary.
This still works correctly in v0.34, but v0.35 et seq. dropped that.  Restore
that change, while preserving other improvements to the config.
This averts the need to manually edit the release notes after goreleaser is finished running.
I will backport this into v0.35 too.
=> Fix release notes to match the prevailing style.

CHANGELOG_PENDING.md, UPGRADING.md, go.mod, go.sum, scripts/confix/confix.go, scripts/confix/confix_test.go, scripts/confix/testdata/non-config.toml, scripts/confix/testdata/v31-config.toml, scripts/confix/testdata/v32-config.toml, scripts/confix/testdata/v33-config.toml, scripts/confix/testdata/v34-config.toml, scripts/confix/testdata/v35-config.toml, scripts/confix/testdata/v36-config.toml
This is a beginning attempt at a tool to help users migrate existing Tendermint configuration settings to newer versions. It is inspired by the [go fix command](https://pkg.go.dev/cmd/fix). 
At the moment the only fixes it knows how to do are from v0.34 to v0.35 and v0.36. This limitation is simply pragmatic: Our upgrading instructions mention config changes at a high level, but the precise changes are not clearly spelled out anywhere. With some further archaeology, we should be able to extend this to at least handle v0.33 and maybe v0.32. Before that, we made more substantial changes.
The edits this tool makes are intended to be idempotent, so it should be safe to reapply it. As a safety measure, the tool checks the config file for shibboleths of its version, and will not modify the file …
=> Add a tool to update old config files to the latest version

CHANGELOG_PENDING.md, scripts/keymigrate/migrate.go, scripts/keymigrate/migrate_test.go
The suffix of BH: (block hash) row keys in v0.34.x is hexadecimal, but we were
parsing it as a plain integer.
=> keymigrate: fix decoding of block-hash row keys

test/fuzz/oss-fuzz-build.sh
p2p/pex and p2p/addrbook were deleted in 03ad7d6f20d9fd8fe83d31db168f433480552e94,
secret_connection was renamed to secretconnection in dd97ac6e1c8810a115e53a61c9a91dd40275b3fe.
=> test/fuzz: update oss-fuzz build script to match reality

.github/workflows/fuzz-nightly.yml, Makefile, docs/nodes/remote-signer.md, docs/tools/terraform-and-ansible.md
`go get` for binaries was deprecated in 1.17 and removed in 1.18 in favor of `go install`. https://go.dev/doc/go-get-install-deprecation
=> build: use `go install` instead of `go get`

go.mod, go.sum, scripts/confix/confix.go
Right now the confix tool works up to v0.35. This change is preparation for
extending the tool to handle additional changes in v0.36.
Mostly this is adding documentation. The one functional change is to fix the
name of the moved "fast-sync" parameter, which was renamed "enable".
- Document the origin of each transformation step.
- Update fast-sync target name.
=> confix: clean up and document transformations

.github/workflows/lint.yml, CHANGELOG_PENDING.md, UPGRADING.md, go.mod, go.sum, scripts/confix/confix.go, scripts/confix/confix_test.go, scripts/confix/testdata/non-config.toml, scripts/confix/testdata/v31-config.toml, scripts/confix/testdata/v32-config.toml, scripts/confix/testdata/v33-config.toml, scripts/confix/testdata/v34-config.toml, scripts/confix/testdata/v35-config.toml, scripts/confix/testdata/v36-config.toml
A manual backport of #8281, adjusted to stop at v0.35.
Since a lot of users are not yet updated to v0.35, it seems worthwhile to backport this tool. The changes in the version at master are only those up to v0.35 at present anyway.
The idea here is that building the tool at a particular version should be able to upgrade older configs _to_ that version. Once we have this backported, we can start adding additional changes on master targeting v0.36. I left those out of the initial implementation.
(I will hold off merging this till I can include the fixes from ~#8301~ and #8298)
=> Add a tool to update old config files to the latest version.

.github/workflows/lint.yml
The caches for golangci-lint failed to update correctly causing spurious
failures on #8300. To work around this, I disabled caching temporarily.
This change removes that override, restoring the default.
=> Revert CI cache override.

abci/client/client.go, abci/client/grpc_client.go, abci/client/local_client.go, abci/client/socket_client_test.go
closes: #8320
This code change ensures that the callback is always invoked by the socket client, even when set late. Previously, because `SetDone` was not called as part of the socket client's execution, invocations of `SetCallback` that occurred after the client request had executed would never trigger the callback to be called. This code fixes that by updating the previously named `done` variable when the callback is invoked.
=> invoke callbacks when set late in socket client

.github/workflows/markdown-links.yml
This averts a harmless but confusing actions plumbing issue.
A better fix would be on the link-checker side, but development there is not active.
=> Only run the markdown link checker if markdown was touched.

.github/workflows/markdown-links.yml
Work around markdown-link-check issues.
This PR works around two issues causing the markdown link check to fail in CI.
1. https://github.com/actions/checkout/pull/760. A git permissions issue,
apparently triggered by a combination of a git change and the behaviour of
actions/checkout.
2. https://github.com/gaurav-nelson/github-action-markdown-link-check/pull/129.
Merging an updated version of the underlying package that fixes a bug in the
handling of local #anchors.
The workaround is a temporary patched fork of the link-checker action.  This
should be removed once the upstream issues are addressed.
=> Work around a permissions bug in actions/checkout.

scripts/keymigrate/migrate.go, scripts/keymigrate/migrate_test.go
In the legacy database format, keys were generally stored with a string prefix
to partition the key space. Transaction hashes, however, were not prefixed: The
hash of a transaction was the entire key for its record.
When the key migration script reads scans its input, it checks the format of
each key to determine whether it has already been converted, so that it is safe
to run the script over an already-converted database.
After checking for known prefixes, the migration script used two heuristics to
distinguish ABCI events and transaction hashes: For ABCI events, whose keys
used the form "name/value/height/index", it checked for the right number of
separators. For hashes, it checked that the length is exactly 32 bytes (the
length of a SHA-256 digest) AND that the value does not contain a …
=> keymigrate: fix conversion of transaction hash keys

Makefile
Fixes #8362. We already made this fix on master so this is notionally a backport, but only for part of the much larger changes at tip.
=> build: clean up an unnecessary dependency

docs/rfc/README.md, docs/rfc/rfc-019-config-version.md
This RFC discusses issues in how we migrate configuration data across
Tendermint versions, and some options for how to improve the experience for
node operators in the future.
{[rendered](https://github.com/tendermint/tendermint/blob/mjf/rfc-conversion/docs/rfc/rfc-019-config-version.md)}
=> RFC 019: Configuration File Versioning

libs/bytes/bytes.go, libs/bytes/bytes_test.go
The HexBytes wrapper type handles decoding byte strings from JSON.  In the RPC
API, hashes are encoded as hex digits rather than the standard base64.
Simplify the implementation of this wrapper using the TextMarshaler interface,
which the encoding/json package uses for values (like these) that are meant to
be wrapped in JSON strings.
In addition, allow HexBytes values to be decoded from either hex OR base64
input. This preserves all existing use, but will allow us to remove some
reflection special cases in the RPC decoder plumbing.
=> Make encoding of HexBytes values more robust.

abci/client/client.go
Clients and applications need not duplicate method definitions.
=> abci: remove redundant methods in client

.github/workflows/build.yml, .github/workflows/docker.yml, .github/workflows/e2e-manual.yml, .github/workflows/e2e-nightly-34x.yml, .github/workflows/e2e-nightly-master.yml, .github/workflows/e2e.yml, .github/workflows/fuzz-nightly.yml, .github/workflows/jepsen.yml, .github/workflows/linkchecker.yml, .github/workflows/lint.yml, .github/workflows/linter.yml, .github/workflows/proto-docker.yml, .github/workflows/proto.yml, .github/workflows/release.yml, .github/workflows/tests.yml
- actions/checkout to v3
- actions/setup-go to v3
- technote-space/get-diff-action to v6
- actions/download-artifact and actions/upload-artifact to v3
=> Update common actions versions on v0.35.x to match master.

abci/client/local_client.go
We were just doing the compiler's work for it. Removing these
implementations just removes the chance that we get something wrong.
=> abci: remove unneccessary implementations

config/config.go, internal/p2p/router.go, internal/p2p/router_test.go, node/node.go
This is a really simple/small PR mostly to mark the initial work on
the libp2p project. I thought adding a feature flag would be a good
place to start. 
While I do **not** intend to ship a version of tendermint with this as
a feature flag that users can take, I think doing *development* with
the flag will let us continue to leverage the existing test
infrastructure until we can migrate those tests over. 
This also marks the creation of the `main/libp2p` topic branch, which
I would like to inaugurate with the following rules of engagement:
- I will merge `master` into this branch regularly and without
review. 
- We will never rebase this branch. (In situations that might warrant
a rebase, we will create a new branch (e.g. `main/libp2p/0`,
`main/libp2p/1` etc.))
- All merges into the topic …
=> p2p: add libp2p feature flag

test/fuzz/tests/mempool_test.go
In the conversion to Go 1.18 fuzzing in e4991fd862c8300254417360feb2d66c5861aa54,
a `return 0` was converted to a panic. A `return 0` is a hint to the fuzzer, not
a failing testcase.
While here, clean up the test by folding setup code into it.
CC @odeke-em
=> fuzz: don't panic on expected errors

node/node.go
This avoids situations where insuffiently configered nodes can attempt
to service RPC requests.
=> node: start rpc service after reactors

.github/workflows/linkchecker.yml
In #8339 we pointed the markdown link checker action to a patched version that
has the up-to-date version of the underlying check tool. In doing so, I missed
the periodic cron job that runs the same workflow. Update it to use the patched
version also.
**Alternatively:** We could probably just delete this cron workflow. I'm not sure it's really buying us much over running the check during PRs, which we now do.
=> Use patched link-checker for periodic checks.

internal/consensus/common_test.go, internal/consensus/msgs.go, internal/test/factory/vote.go, privval/file.go, types/block.go, types/evidence.go, types/priv_validator.go, types/vote.go, types/vote_set.go, types/vote_test.go
Follows from #8141. Relates to #8272, but does not close it.
I realized that we're signing prevotes' vote extensions too, which is incorrect (we should only be signing and verifying/validating precommits' vote extensions).
After trying to work with #8375 and discussion with @tychoish, we realized that we should rather expose different validation methods than introduce a boolean flag into the `ValidateBasic` method for `Vote`.
I'll be submitting several separate PRs that build on this one and each other (eventually including some commits from #8375) in order to implement RFC 017 (#8317).
=> abci++: Vote extension cleanup

internal/p2p/p2ptest/network.go, internal/p2p/router.go, internal/p2p/router_init_test.go, internal/p2p/router_test.go, node/setup.go
This will make it possible to add new options for the new transport
layer into the existing router witout changing the function siguature
of the constructor.
=> p2p: move transport options into struct

rpc/jsonrpc/server/http_json_handler.go, rpc/jsonrpc/server/http_uri_handler.go, rpc/jsonrpc/server/parse_test.go, rpc/jsonrpc/server/rpc_func.go
In #8397 I tried to remove all the cases where we needed to keep track of the
target type of parameters for JSON encoding, but there is one case still left:
When decoding parameters from URL query terms, there is no way to tell whether
or not we need base64 encoding without knowing whether the underlying type of
the target is string or []byte.
To fix this, keep track of parameters that are []byte valued when RPCFunc is
compiling its argument map, and use that when parsing URL query terms.  Update
the tests accordingly.
=> rpc: fix byte string decoding for URL parameters

cmd/priv_val_server/main.go, privval/grpc/client_test.go, privval/grpc/server.go, privval/grpc/server_test.go, test/e2e/node/main.go
Minor irksome tweaks: some awkwardly wrapped function signatures and
putting the logger argument in last rather than first (which has
become our convention in other parts.)
=> privval/grpc: normalize function signature

internal/blocksync/reactor.go, internal/consensus/reactor.go, internal/evidence/reactor.go, internal/mempool/reactor.go, internal/p2p/p2ptest/require.go, internal/p2p/pex/reactor.go, internal/statesync/reactor.go
I wanted to land this on mainline before doing something similar in
the libp2p branch to reduce the churn between the branches and avoid
undue backport friction.
(The accompanying libp2p change is to make the channel an interface
and swap out an alternate implemenation for a while. When its safe to
delete the legacy plumbing, the channel can go back to being a
concrete type.)
=> p2p: avoid using p2p.Channel internals

internal/blocksync/reactor.go, internal/blocksync/reactor_test.go, internal/consensus/invalid_test.go, internal/consensus/reactor.go, internal/consensus/reactor_test.go, internal/evidence/reactor.go, internal/evidence/reactor_test.go, internal/mempool/reactor.go, internal/mempool/reactor_test.go, internal/p2p/channel.go, internal/p2p/channel_test.go, internal/p2p/p2ptest/network.go, internal/p2p/p2ptest/require.go, internal/p2p/pex/reactor.go, internal/p2p/pex/reactor_test.go, internal/p2p/router.go, internal/p2p/router_test.go, internal/statesync/dispatcher.go, internal/statesync/dispatcher_test.go, internal/statesync/reactor.go, internal/statesync/reactor_test.go, internal/statesync/stateprovider.go, internal/statesync/syncer.go
I don't think this is the final state of things, but this will make it
possible to shim in the connection with the new p2p without changing
the reactors or the tests, which seems liek a good incremental step.
=> p2p: make p2p.Channel an interface

UPGRADING.md, scripts/keymigrate/migrate.go, scripts/keymigrate/migrate_test.go
This is a follow-up to #8352. The check for legacy evidence keys is only based
on the prefix of the key. Hashes, which are unprefixed, could easily have this
form and be misdiagnosed.
Because the conversion for evidence checks the key structure, this should not
cause corruption. The probability that a hash is a syntactically valid evidence
key is negligible.  The tool will report an error rather than storing bad data.
But this does mean that such transaction hashes could cause the migration to
stop and report an error before it is complete.
To ensure we convert all the data, refine the legacy key check to filter these
keys more precisely. Update the test cases to exercise this condition.
Also, update the upgrading instructions to recommend testing out migration on
a copy of the database …
=> keymigrate: improve filtering for legacy transaction hashes

light/verifier.go
Fixes #8472.
I didn't see any other obvious cases of us doing this (although we do return zeroes in other places alongside errors, which is fine).
=> Convert explicit zero comparison to a method.

.github/workflows/docs-deployment.yml, Makefile, docs/package.json
**Note to reviewers:** It is safe to merge this PR as-is. It will trigger on the main repo, but it is publishing to a Pages branch that does not yet connect to docs.tendermint.com. The latter we must do as a follow-up to update the domain pointer.
Updates #7297. Fixes https://github.com/tendermint/docs/issues/20.
Per https://github.com/tendermint/docs/issues/20, it is no longer necessary to build the static documentation out of a separate repository.
This change:
- Adds an actions workflow to build and deploy the docs to GitHub Pages.
- Updates some build settings in a compatible manner.
This change does not affect the existing site deployment. To complete this change, we will need to update the custom domain pointer and disable the corresponding workflow in the tendermint/docs …
=> Reintegrate docs deployment into the main TM repo

internal/p2p/channel.go, internal/p2p/router.go
This is some initial scafolding that I've been working on, and think
would be good to land so other people can help out or just as a basis
of doing more work (and letting me defer thinking about the p2p
branch) on the point to point protocol.
This model minimizes the entire action between the p2p later and the
reactor into the channel interface, and makes it much more synchronous
than it currently is. I think this is mostly ok, but I think it's
reasonable to have marshaling messages slightly less synchronous. In
any case, that's a thing we can polish off later.
=> p2p: base implementation of libp2p channel

internal/consensus/state.go, internal/consensus/state_test.go
=> abci++: Disable VerifyVoteExtension call on nil precommits

internal/blocksync/reactor.go
In consensus, we always validate a block before voting and thereby before we persist it, however in blocksync it's possible to persist an invalid block as we only validate it afterwards (in `ApplyBlock`). This potentially puts the node in a bad state where it can't simply rollback the previous execution.
=> blocksync: validate block before persisting it

spec/abci++/abci++_app_requirements_002_draft.md
ABCI++ application requirements section was using Latex-like math expressions which are rendered well in VSCode, but GitHub does not render them properly.
This PR refactors that section by using alternatives that are rendered properly on GitHub.
[Rendered version](https://github.com/tendermint/tendermint/blob/sergio/fix_abci%2B%2B_requirements_notation/spec/abci%2B%2B/abci%2B%2B_app_requirements_002_draft.md)
=> Fixed math notation in ABCI++ app requirements

internal/p2p/channel.go
This is an initial sketch of how this might work. We should definitely
validate this patch (and indeed the whole channel implementation) with
someone who knows more about libp2p implementations, but this is at
least "feature complete" in the sense that we can begin: 
- resolving TODOs left in this PR
- constructing p2p tools in the node package so we can begin the p2p
testing. 
- bridging tendermint metrics systems with libp2p's
- connecting and collecting peer (heartbeats? for heights and
connectiveness and scoring?) from peers which is used by reactors at
various I fully suspect that a bunch of this code in the channel
implementation will end up being replaced or reorganized, but I still
think this is a good place to iterate from. 
In addition, I think its a good move right now to begin …
=> p2p: simple request and response framework

internal/state/indexer/block/kv/kv.go, types/events.go
Although we index block.height for blocks in the KV indexer, this reserved
attribute was not previously exposed to the event subscription API. Despite
being advertised in the OpenAPI spec, neither the old (websocket) nor new
(events) query interface could see it.  This change exposes block.height to the
/events API.
In addition: Remove a non-public constant from types (finalize_block). This
value is used only as an internal tag by the indexer, and should not be exposed
to users of the public interface. (We could probably drop it entirely, as it
was previously a disambiguator for BeginBlock vs. EndBlock events, but keeping
a tag here simplifies the cleanup).
=> rpc: make block.height visible to event subscription

docs/tendermint-core/subscription.md, rpc/openapi/openapi.yaml
Update the static documentation about event subscription to include the new /events API, and to add more details about how queries work. Mention that the streaming API is deprecated.
=> docs: update event subscription documentation for new API

abci/types/types.pb.go, proto/tendermint/blocksync/types.pb.go, proto/tendermint/consensus/types.pb.go, proto/tendermint/consensus/wal.pb.go, proto/tendermint/crypto/keys.pb.go, proto/tendermint/crypto/proof.pb.go, proto/tendermint/libs/bits/types.pb.go, proto/tendermint/mempool/types.pb.go, proto/tendermint/p2p/conn.pb.go, proto/tendermint/p2p/pex.pb.go, proto/tendermint/p2p/types.pb.go, proto/tendermint/privval/types.pb.go, proto/tendermint/state/types.pb.go, proto/tendermint/statesync/types.pb.go, proto/tendermint/types/block.pb.go, proto/tendermint/types/canonical.pb.go, proto/tendermint/types/events.pb.go, proto/tendermint/types/evidence.pb.go, proto/tendermint/types/params.pb.go, proto/tendermint/types/types.pb.go, proto/tendermint/types/validator.pb.go, proto/tendermint/version/types.pb.go, scripts/proto-gen.sh
- Revert "update protos (#8515)"
It appears that #8515 may have been generated with an out-of-date version of
either buf or the gogo plugin. using the latest versions (buf 1.4.0 and gogo
1.3.2) reverts those changes.
- Add a script to re-generate protos with the latest tools.
This script is just a wrapper for the Make rule, but it runs the build inside a
container with the latest versions of buf and gogo installed. This reduces the
chance that an out-of-date ambient installation on a developer machine will get
us outdated output.
=> Fix protobuf generated code.

.github/workflows/check-generated.yml
Add an actions workflow that verifies that generated files are up-to-date during a pull request. If not, give the reader instructions about what to do to update the PR.
Checks are included for protobuf and mockery.
We might also want to add a check for the generated metrics.
=> build: add CI check that generated files are up-to-date

internal/mempool/reactor.go
Found this while working on p2p, and think it would be good to have in mainline.
=> mempool: do not continue checking transactions if context was canceled

internal/p2p/channel.go
Mostly (entirely?) cribbed from
[this](https://github.com/ElrondNetwork/elrond-go/blob/2a92e671ad845a9773257fb80cd5a596e16201d6/p2p/libp2p/directSender.go#L154),
but should let us:
- reuse existing streams. 
- send messages delimited.
=> p2p: cache libp2p streams

internal/mempool/reactor.go, internal/mempool/reactor_test.go, internal/p2p/peermanager.go, internal/p2p/peermanager_test.go, node/node.go, node/setup.go
I was poking around today, and I've realized that while we have this
potential in the mempool reactor to spin and wait for peers to catch
up (in 100ms batches,) nothing ever updates the peer height in the
peer store, so this check is (almost certianly) useless and never hit.
=> p2p: remove unused get height methods

CHANGELOG_PENDING.md, internal/rpc/core/routes.go, rpc/jsonrpc/server/http_server.go, rpc/jsonrpc/server/rpc_func.go
~**Question:** Does this deserve a changelog?~ (answer: yes)
Prior to this change, we set a 10-second global timeout for all RPC methods using the net/http Server type's WriteTimeout. This meant that any request whose handler did not return within that period would simply drop the connection to the client.
This timeout is too short for a default, as evidenced by issues like [1] and [2].  More importantly, various methods have diffent constraints: Some should be able to return quickly, others may need to adjust based on the application workload.
This is a first step toward supporting configurable timeouts. This change:
- Removes the server-wide default global timeout, and instead:
- Wires up a default context timeout for all RPC handlers.
- Increases the default timeout from 10s to 60s.
- …
=> rpc: rework timeouts to be per-method instead of global

config/config.go
Since we are deprecating the stream-based event subscription in v0.36, we should ensure that new nodes enable the replacement by default.  For now, just set a baseline 30-second window.
We already have a changelog entry for the ADR 075 interface, that should be sufficient to cover this as well.
=> rpc: enable the ADR 075 event log by default in new configs

abci/client/socket_client.go
I believe this will make the socket client (e.g. tendermint's access
to abci apps over the socket protocol.) more serial/sequential, and
get us out of the situation where requests are sent out of order
relative to how they're returned. Callers can still get asynchronicity
by wrapping synchronous calls in threads, so I think this ok.
=> abci: serialize semantics of abci client

abci/client/socket_client.go, internal/proxy/client_test.go
It is not safe to check base service state (IsRunning) while holding the lock
for the client state. If we do, then during shutdown we may deadlock with the
invocation of the OnStop handler, which the base service executes while holding
the service lock.
Fortunately we only have one case of this.
=> Fix lock sequencing in socket client request tracking.

internal/consensus/reactor.go, internal/consensus/state.go
Closes: #8575
This PR aims to fix the `LastCommitRound can only be negative for initial height 0` issue we see in the e2e tests by initializing the `state` object before starting the receive routines in the consensus reactor. This is somewhat inelegant, but it should fix the issue.
=> consensus: update state from store before use in reactor

abci/types/types.go, rpc/coretypes/responses_test.go
Fixes #8583.
The block results include validator updates in ABCI protobuf format, which does
not encode "correctly" according to the expected Amino style RPC clients expect.
- Write a regression test for this issue.
- Add JSON marshaling overrides for ABCI ValidatorUpdate messages.
This should be backported into v0.35.x, but I will handle that manually because a lot of this plumbing has changed at tip and Mergify will make a dog's breakfast of it.
=> rpc: fix encoding of block_results responses

internal/p2p/host.go, node/node.go, node/node_test.go, node/public.go, node/seed.go, node/setup.go
This is an initial bit of scafodling to outline structure of the
design, but there's more work, noticably:
- using some kind of default constructor, as for the database, to make
it possible for users to hand us pre-made libp2p components, and
changing the public interface of the node constructors accordingly. 
- implementing the host and pubsub constructors in the p2p package. I
think that the pubsub constructor might need access to the host
object, so the current interface might need to change a bit
=> p2p: libp2p constructor scafolding

CHANGELOG_PENDING.md, abci/types/result.go, rpc/coretypes/responses_test.go
Updates #8583.
The block results include validator updates in ABCI protobuf format, which does not encode "correctly" according to the expected Amino style RPC clients use.
- Write a regression test for this issue.
- Add JSON marshaling overrides for ABCI ValidatorUpdate messages.
Patches for v0.35.x:
- Replace jsontypes with tmjson (removed in v0.36)
- Regress test data for BeginBlock / EndBlock
=> rpc: fix encoding of block_results responses (backport #8593)

.github/workflows/check-generated.yml, scripts/proto-gen.sh
Since we now use buf from a tools dependency, we can use the Go tool to install the version we expected without having to curl a tarball.
=> build: simplify the proto generated check in CI

internal/consensus/reactor.go
Seems like there were cases in this that would cause the loop to run
very tight loop gossiping old catchup messages, which may starve out
other workloads.
=> consensus: restructure peer catchup sleep

internal/p2p/pex/params.go, internal/p2p/pex/pex_reactor.go, internal/p2p/pex/reactor.go
The two pex reactors use different values to define what the maximum amount of addresses it should send (and expect to receive). This can cause nodes to occasionally be unnecessary punished. This PR fixes this by setting everything to 100 addresses at a time
=> pex: align max address thresholds

.github/workflows/build.yml, .github/workflows/check-generated.yml, .github/workflows/e2e-manual.yml, .github/workflows/e2e-nightly-34x.yml, .github/workflows/e2e-nightly-35x.yml, .github/workflows/e2e-nightly-master.yml, .github/workflows/e2e.yml, .github/workflows/fuzz-nightly.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/tests.yml, go.mod, go.sum
We are not yet ready to require Go 1.18 in our base module file, since that affects all our downstream users in both library and binary form. The recent Dependabot update to buf pulled in a version bump that does require this, so revert it.
At the same time, our code _should_ build and test correctly with Go 1.18, so also update the versions of the Go toolchain used by CI jobs.
=> Revert buf tools upgrade requiring Go 1.18

internal/p2p/router.go
This should remedy a situation observbed by penumbra where stale peers
from old networks clog up the peer store and make it take longer for
peers/networks to become connected. This doesn't affect correctness
(e.g. we would never establish connections to these peers but we waste time
trying,) and the router/peermanager are very conservative about
removing peers from the database, which I think exacerbates this
issue.
The risk of this PR is that a peer will eventually recover and we will
have removed it from the network, and it will have a hard time
rejoining, but in these situations it will have to be correct, and
should have the same path through rentering the peer databases of
nodes on the network as a new node, which it is for all intents.
=> p2p: shed peers from store from other networks

CHANGELOG.md, CHANGELOG_PENDING.md
Note that the version was already bumped previously, so it is not in this PR.
There were no changelogs so I cribbed from `git log`.
=> Prepare Release v0.35.6

node/setup.go
This PR changes the node setup so that it passes the configured max connections instead of what I assume is accidental constant of 1000. As discussed in #8683, ~~we might want to instead take this opportunity to remove `MaxPeers` or `MaxConnected` from the peer manager options and only use one of those values.~~
Closes #8683
=> p2p: pass maxConns for MaxPeers during node setup

internal/consensus/ticker.go
This timeout message is unclear and as a result is confusing to operators. Operators have the reasonable expectation that timeouts mean a desired input is not received in time. The consensus timeouts do not mean this. Timeouts are one of the main mechanisms by which Tendermint moves between consensus steps. Logging them frequently produces log spam that is not clear or actionable to operators. This PR switches the timeouts to be Debug level and attempts to clarify their phrasing.
Closes: #8639
=> consensus: switch timeout message to be debug and clarify meaning

.github/workflows/check-generated.yml, scripts/mockery_generate.sh
The use of "go install" is deprecated as a way of installing and running the
Mockery binary. Update the runner script to depend on an ambient version of the
tool and ensure that in CI it's installed.
Fixes #8693.
=> Update how Mockery mocks are checked for currency.

docs/roadmap/roadmap.md
The link actually works in context because of the auto-redirect from GitHub,
but the link checker doesn't follow them. Splice out the redirect.
=> Fix a "broken" markdown link.

.github/dependabot.yml, .github/mergify.yml, .github/workflows/e2e-nightly-34x.yml, .github/workflows/e2e-nightly-36x.yml, .github/workflows/e2e-nightly-master.yml
- Add Mergify settings for backport labels.
- Add e2e nightly workflow for v0.36.x.
- Update documentation on e2e workflows.
- Add v0.36.x to the Dependabot configs.
N.B.: This change targets `master` since that is where we keep workflow settings.
=> Set up automation settings for the v0.36.x backport branch.

scripts/confix/testdata/diff-35-36.txt, scripts/confix/testdata/v36-config.toml
This is a trivial update, but also a convenient way to make sure the mergify settings are working.
=> Update config migration test data for v0.36.x

config/toml.go
I missed updating the default config generation script when preparing #6906.
The config settings work fine, but it's hard for users to discover them.
=> Update default config docs for PSQL indexer settings.

internal/mempool/mempool_test.go
Current test case prints out "test error" to console even when it succeeds, and it can mislead.
=> mempool: fix error message check in test

internal/p2p/router.go, internal/p2p/router_test.go
=> p2p: accept should not abort on first error

cmd/tendermint/commands/debug/kill.go
Guards against PID integer overflows by using strconv.Atoi,
then checking for ranges of PID values before passing them to
killProc. This bug was reported via Cosmos' bug bounty program on
HackerOne but the extent of it, even after an overflow is benign
because Go's os.FindProcess(-1) creates a process whose value
when given a .Kill command will return an error per https://go.dev/play/p/wkuHYxgVQpx
=> cmd/tendermint/commands/debug: guard against PID int overflows

docs/tendermint-core/using-tendermint.md
Modify using-tendermint.md to replace unsafe_reset_all to unsafe-reset-all . Closes #8779 .
=> Fix typo in Using Tendermint section

internal/mempool/v0/clist_mempool.go, internal/mempool/v0/clist_mempool_test.go
Should I throw an error in `CheckTx` if I already have that tx in my cache:
v0.34 v0 mempool: yes
v0.35 v0 mempool: no unless from the same peer
v0.35 v1 mempool: yes
master v1 mempool: yes
This pr makes v0.35 v0 mempool consistent with the rest.
I personaly think this shouldn't actually throw an error but a conversation for a different time.
=> mempool: make error throwing for CheckTx consistent

internal/p2p/router.go
The dial routines perform network i/o, which is a blocking call into the kernel. These routines are completely unable to do anything else while the dial occurs, so for most of their lifecycle they are sitting idle waiting for the tcp stack to hand them data. We should increase this value by _a lot_ to enable more concurrent dials. This is unlikely to cause CPU starvation because these routines sit idle most of the time. The current value causes dials to occur _way_ too slowly. 
Below is a graph demonstrating the before and after of this change in a testnetwork with many dead peers. You can observe that the rate that we connect to new, valid peers, is _much_ higher than previously. Change was deployed around the 31 minute mark on the graph.
=> p2p: more dial routines

internal/p2p/mocks/connection.go, internal/p2p/router.go, internal/p2p/router_test.go, internal/p2p/transport.go, internal/p2p/transport_mconn.go, internal/p2p/transport_memory.go, internal/p2p/transport_test.go, node/node.go
These timeouts default to 'do not time out' if they are not set. This times up resources, potentially indefinitely. If node on the other side of the the handshake is up but unresponsive, the [handshake call](https://github.com/tendermint/tendermint/blob/edec79448aa1d62b84683b1b22e12e145dbdda7c/internal/p2p/router.go#L720) will _never_ return.
This change wires up the values from the config file so that they are actually used.
=> p2p: set empty timeouts to config values.(manual backport #8847)

libs/log/default.go
I was digging around in the zero log functions, and the following
functions using the `Fields()` method directly in zerolog, 
- https://github.com/rs/zerolog/blob/v1.27.0/event.go#L161
- https://github.com/rs/zerolog/blob/e9344a8c507b5f25a4962ff022526be0ddab8e72/fields.go#L15
Have meaningfully equivalent semantics and our pre-processing of
values is getting us much (except forcing zerolog to always sort our
keys, and nooping in the case when you miss the last field.)
With this change also, we can pass maps (or, pratically a single map)
to the logger, which might be a less wacky seeming interface.
=> log: do not pre-process log results

node/node.go, node/setup.go
=> node: always start blocksync and avoid misconfiguration

internal/p2p/conn/connection.go
This is just an implementation of https://github.com/tendermint/tendermint/pull/8904 for more recent
branches. Thanks William for spotting the issue and the fix.
=> p2p: stop mconn channel sends without timeout

config/config.go
This sets the default closer to its value in the legacy stack.
=> p2p: set default outgoing connections to about 20% of total connections

internal/p2p/p2ptest/network.go
This test was made flakey by #8839. The cooldown period means that the node in the test will not try to reconnect as quickly as the test expects. This change makes the cooldown shorter in the test so that the node quickly reconnects.
=> p2p: fix flakey test due to disconnect cooldown

internal/p2p/transport_mconn.go
handshakeCtx is the internal context carrying the timeout. Its error should be used for the error return.
=> p2p: use correct context error

CHANGELOG_PENDING.md, internal/state/indexer/indexer_service.go, internal/state/indexer/indexer_service_test.go
Forward port: #8625
Port and refactored the bug fix terra-money#76 to upstream. This is critical for ethermint json-rpc to work.
- prevent duplicate tx index if it succeeded before
- handle duplicate txs within the same block
Co-authored-by: jess jesse@soob.co
ref: #5281
Please add a description of the changes that this PR introduces and the files that
are the most critical to review.
If this PR fixes an open Issue, please include "Closes #XXX" (where "XXX" is the Issue number) 
so that GitHub will automatically close the Issue when this PR is merged.
=> Work around indexing problem for duplicate transactions (forward port: #8625)

internal/mempool/v1/mempool_test.go
- Add a test for time-based (TTL) expiration.
- Add a test for eviction priority.
=> Add more unit tests for the priority mempool.

internal/p2p/router.go
Once these channels are closed, we should not continue to service them, as they
will never again deliver nonzero values.
Fixes #8978.
=> p2p: ensure closed channels stop receiving service

internal/mempool/v1/mempool.go
We use the default callback for rechecks, but because it is the default it will
be called for other message types too. These can be safely ignored to reduce
log spam. We should, however, log in the explicit (initial) callback.
=> mempool: don't log message type mismatch in the default callback

internal/mempool/v1/mempool.go
The way this was originally structured, we reacquired the lock after issuing
the initial ABCI CheckTx call, only to immediately release it. Restructure the
code so that this redundant acquire is no longer necessary.
=> mempool: reduce lock contention during CheckTx (cleanup)

internal/mempool/v1/mempool.go
This case is symmetric to what we did for CheckTx calls, where we release the
mempool mutex to ensure callbacks can fire during call setup.  We also need
this behaviour for application flush, for the same reason: The caller holds the
lock by contract from the Mempool interface.
=> mempool: release lock during app connection flush

internal/mempool/cache.go, internal/mempool/v1/mempool.go, internal/mempool/v1/mempool_test.go
In the original implementation transactions evicted for priority were also
removed from the cache.
Related:
- Add Has method to cache implementations.
- Update tests to exercise this condition.
**Note to reviewers:** The original implementation did _not_ remove transactions from the cache when expiring them for TTL or height. It seems to me like we might want to treat those cases symmetrically, but for now I've left them as they were.
**Edit to add:** Per the discussion below, I've updated the change to remove expired transactions from the cache as well as evicted ones.
=> mempool: ensure evicted transactions are removed from the cache

mempool/cache.go, mempool/v1/mempool.go, mempool/v1/mempool_test.go
This is a manual cherry-pick of commit b94470a6a42e8ffe7e7467521de5f51eb937c454.
In the original implementation transactions evicted for priority were also
removed from the cache. In addition, remove expired transactions from the
cache.
Related:
- Add Has method to cache implementations.
- Update tests to exercise this condition.
=> mempool: ensure evicted transactions are removed from the cache (backport #9000)

abci/client/grpc_client.go, mempool/v1/mempool.go
In the v0.34 line, the socket and gRPC clients require explicit flushes to
ensure that the client and server have received an async request.  Add these
calls explicitly where required in the backport of the priority mempool.
In addition, the gRPC client's flush plumbing was not fully hooked up in the
v0.34 line, so this change includes that update as well.
=> mempool: ensure async requests are flushed to the server

CHANGELOG.md
I have apparently missed a few of these.
=> Forward-port point release changelogs from v0.35.x.

config/toml.go
These got disarranged during a previous cleanup.
=> config: fix the comments on p2p.queue-type

internal/mempool/v1/mempool.go
The priority mempool has a stricter synchronization requirement than the legacy
mempool. Under sufficiently-heavy load, exclusive access can lead to deadlocks
when processing a large batch of transaction rechecks through an out-of-process
application using the socket client.
By design, a socket client stalls when its send buffer fills, during which time
it holds a lock shared with the receive thread.  While blocked in this state, a
response read by the receive thread waits for the shared lock so the callback
can be invoked.
If we're lucky, the server will then read the next request and make enough room
in the buffer for the sender to proceed. If not however (e.g., if the next
request is bigger than the one just consumed), the receive thread is blocked:
It is waiting on the lock and cannot …
=> mempool: rework lock discipline to mitigate callback deadlocks

cmd/tendermint/commands/reset.go, cmd/tendermint/commands/root.go
Ref. #9102 
close #9102
`tendermint unsafe-reset-all` command should clear client's home directory
but this command is not working with default home flags.
Ad described #9102, `unsafe-reset-all` command try to clear `#HOME/data` directory by default
where is not client's home.
To resolve this issue, `ParseConfig` function explicitly get client's home
and set it into config.
=> Fix unsafe-reset-all for working with default home

cmd/tendermint/commands/rollback_test.go, internal/consensus/byzantine_test.go, internal/consensus/reactor_test.go, internal/consensus/replay_test.go, internal/mempool/mempool_test.go, internal/p2p/conn/connection_test.go, internal/p2p/peermanager_test.go, internal/p2p/router_test.go, internal/p2p/transport_mconn_test.go, internal/statesync/block_queue_test.go, internal/statesync/reactor_test.go, internal/statesync/syncer_test.go, light/detector_test.go, light/example_test.go, light/light_test.go, light/provider/http/http_test.go, node/node_test.go, rpc/client/examples_test.go, rpc/client/helpers_test.go, rpc/client/rpc_test.go, rpc/jsonrpc/client/ws_client_test.go, rpc/jsonrpc/jsonrpc_test.go, types/part_set_test.go, types/validator_set_test.go
As a small developer quality of life improvement, I found many individual unit tests that take longer than around a second to complete, and set them to skip when run under `go test -short`.
On my machine, the wall timings for tests (with `go test -count=1 ./...` and optionally `-short` and `-race`) are roughly:
- Long tests, no race detector: about 1m42s
- Short tests, no race detector: about 17s
- Long tests, race detector enabled: about 2m1s
- Short tests, race detector enabled: about 28s
This PR is split into many commits each touching a single package, with commit messages detailing the approximate timing change per package.
=> Improve handling of -short flag in tests

.github/CODEOWNERS
Updates the `CODEOWNERS` file to use the @tendermint/tendermint-engineering and @tendermint/tendermint-research teams as opposed to adding people one by one. This makes repository administration somewhat easier to manage, especially when onboarding/offboarding people.
=> Update CODEOWNERS to use teams

CHANGELOG_PENDING.md, cmd/tendermint/commands/run_node.go
Closes #9035
Add the `p2p.external-address` command line argument to configure the node external address.
=> cli: set node p2p external address with cmd flag

blockchain/reactor_test.go, consensus/replay_file.go, consensus/replay_stubs.go, consensus/replay_test.go, consensus/wal_generator.go, docs/tendermint-core/metrics.md, node/node.go, node/node_test.go, proxy/app_conn.go, proxy/metrics.go, proxy/multi_app_conn.go, proxy/multi_app_conn_test.go, state/execution_test.go, state/helpers_test.go
This PR adds an initial set of metrics for use ABCI. The initial metrics enable the calculation of timing histograms and call counts for each of the ABCI methods. The metrics are also labeled as either 'sync' or 'async' to determine if the method call was performed using ABCI's `*Async` methods.
An example of these metrics is included here for reference:
```
tendermint_abci_connection_method_timing_seconds_bucket{chain_id="ci",method="commit",type="sync",le="0.0001"} 0
tendermint_abci_connection_method_timing_seconds_bucket{chain_id="ci",method="commit",type="sync",le="0.0004"} 5
tendermint_abci_connection_method_timing_seconds_bucket{chain_id="ci",method="commit",type="sync",le="0.002"} 12
tendermint_abci_connection_method_timing_seconds_bucket{chain_id="ci",method="commit",type="sync",le …
```
=> proxy: add initial set of abci metrics (port of #7115)

consensus/metrics.go, consensus/state.go, docs/tendermint-core/metrics.md
This change introduces an additional set of metrics aimed at helping operators understand the timing for consensus.
This change adds the following metrics:
```
tendermint_consensus_round_duration_seconds_bucket{chain_id="test-chain-IrF74Y",le="0.1"} 29
tendermint_consensus_round_duration_seconds_bucket{chain_id="test-chain-IrF74Y",le="0.2682695795279726"} 29
tendermint_consensus_round_duration_seconds_bucket{chain_id="test-chain-IrF74Y",le="0.7196856730011522"} 29
tendermint_consensus_round_duration_seconds_bucket{chain_id="test-chain-IrF74Y",le="1.9306977288832508"} 29
tendermint_consensus_round_duration_seconds_bucket{chain_id="test-chain-IrF74Y",le="5.1794746792312125"} 29
tendermint_consensus_round_duration_seconds_bucket{chain_id="test-chain-IrF74Y",le="13.894954943731381"} 29 …
```
=> consensus: additional timing metrics (port of #7849)

.github/workflows/e2e-nightly-34x.yml, .github/workflows/e2e-nightly-main.yml, .github/workflows/fuzz-nightly.yml
Updates our nightly E2E notifications to use the [incoming webhook approach](https://github.com/slackapi/slack-github-action#technique-3-slack-incoming-webhook), targeting our engineering team channel.
=> ci: Update nightly E2E notifications

.github/workflows/e2e-nightly-34x.yml, .github/workflows/e2e-nightly-main.yml, .github/workflows/fuzz-nightly.yml
A follow-up to #9177.
This updates the nightly E2E workflows to fix the notifications for the `v0.34.x` branch while also simplifying the messages and making them a little more readable.
I've tested these notifications out in a private repo, sending them directly to myself, and they appear to work now.
---
=> ci: Fix nightly E2E notifications and improve readability

.github/workflows/e2e-nightly-34x.yml
The v0.34.x tests have been failing (or reporting failures, I don't
believe that this is a real failure,) because the CI configuration has
been out of sync with itself, likely due to a mistake during
backporting configs from the `master` branch.
The entire 0.34.x e2e test suite takes 26 minutes to run, plus about 7
minutes to build the docker image. Each split has to build the same
docker image, (and is therefore a cap on the amount of parallelism we
can get at the moment.) Having more groups, just seems like we'll be
burning money building the docker image with no really meaningful
difference in throughput. For a nightly test that people don't really
wait on, the current latency (time-to-completion) of roughly 19
minutes, isn't causing in friction.
=> e2e: fix out of sync configuration

CHANGELOG_PENDING.md, UPGRADING.md, abci/types/messages.go, spec/abci/client-server.md
=> abci: Make ABCI and P2P wire-level length delimiters consistent 

.github/CODEOWNERS
Relates to #9245 and #9243
We should strongly consider dropping our documentation support for v0.33.x once we release v0.37.
---
=> chore: Sync `CODEOWNERS` on `v0.33.x` branch with `main`

.github/CODEOWNERS
Synchronizes the `CODEOWNERS` file on the `v0.34.x` branch with `main`.
There's no spec on the `v0.34.x` branch, so we don't need the research team-related restriction on this branch.
---
=> chore: Sync `CODEOWNERS` on `v0.34.x` branch with `main`

cmd/tendermint/main.go
I noticed today that this wasn't enabled.
---
=> cli: Enable reindex-event cmd

cmd/tendermint/commands/rollback.go, config/config.go, config/toml.go, node/node.go, test/maverick/node/node.go
Closes #9274 
Docs and `CHANGELOG_PENDING` entry will be added in #9267.
---
=> config: Move `discard_abci_responses` flag into its own storage section

.github/workflows/e2e-nightly-main.yml, libs/pubsub/pubsub.go, libs/pubsub/subscription.go
Closes #9277
This PR aligns the .github configuration in `feature/abci++ppp` with the one in `main` to avoid problems when carrying out the final merge of the feature branch back into `main`
---
=> Restore e2e nightly workflow on feature/abci++ppp branch

LICENSE
Our license can't be picked up by automated systems because of a couple of odd tweaks to the `LICENSE` file that don't really seem to add any value.
---
=> docs: Apply standard Apache 2.0 license

test/e2e/generator/generate.go
Small change in the e2e generator code that wasn't ported across
=> e2e: fix generation by considering evidence age in retain height

CHANGELOG_PENDING.md, CONTRIBUTING.md, UPGRADING.md, rpc/openapi/openapi.yaml
Closes #9304 
This is a documentation PR.
* `CHANGELOG_PENDING.md` now contains entries reflecting the changes coming from `feature/abci++ppp`
* `UPGRADING.md` has been compared to its version in `v0.35.x`, `v0.36.x` and `master` and all relevant differences have been included
* In particular #5404 has been cherry-picked
---
=> Added `PrepareProposal` and `ProcessProposal` data `CHANGELOG_PENDING.md`. Reworked `UPGRADING.md`

spec/p2p/v0.34/addressbook.md, spec/p2p/v0.34/peer_manager.md, spec/p2p/v0.34/pex-protocol.md, spec/p2p/v0.34/pex.md, spec/p2p/v0.34/switch.md, spec/p2p/v0.34/transport.md, spec/p2p/v0.34/types.md
Addresses #9089.
Description of the implementation of the p2p layer in v0.34. This is a work in progress.
=> spec: overview of the p2p implementation in v0.34

.github/dependabot.yml, .github/mergify.yml, .github/workflows/e2e-nightly-37x.yml
Depends on #9337.
Prepare the CI to handle the v0.37 development processes, as per our [release guidelines](https://github.com/tendermint/tendermint/blob/main/RELEASES.md#creating-a-backport-branch).
---
=> ci: Prepare for v0.37 release branch

.goreleaser.yml
This is by no means a signal that we offer any additional guarantees with our software. This warning seems somewhat pointless given that:
1. Our open source license clearly states that we offer no warranties with this software.
2. We are clearly still pre-1.0.
It also doesn't make sense to append "(WARNING: BETA SOFTWARE)" to pre-releases such as alpha releases, which are to be considered _more_ unstable than beta releases.
---
=> ci: Remove "(WARNING: BETA SOFTWARE)" tagline from all upcoming releases

docs/.vuepress/redirects
Small issue, https://tendermint.com/core/ pointing to /master/tutorials/go.html rather than /v0.34/tutorials/go.html
=> Add redirect link for tutorial

test/loadtime/cmd/load/main.go
the `NewClient` method is called by the load test framework for each connection. This means that if multiple connections are instantiated, each connection will erroneously have its own UUID. This PR changes the UUID generation to happen at the _beginning_ of the script instead of on client creation so that each experimental run shares a UUID.
Caught while preparing the script for production readiness.
=> test: generate uuid on startup for load tool

consensus/byzantine_test.go, consensus/state.go, node/node_test.go, state/execution.go, state/execution_test.go
Contributes to #9053 
The way this code is structured will minimize conflicts when backporting vote extensions to `main`.
However, on `v0.37.x`, there is no point in having the `votes` parameter, which is not used.
---
=> ABCI: Removed unused `votes` param

.github/dependabot.yml
As per discussion with @sergio-mena, this should disable all automated dependency updates that are not security-related. We should make this part of our standard practice when cutting new major releases, given that our QA process for major releases is expensive at present and we cannot re-run it for every dependency update.
Once we have cut a final major release, we can consider re-enabling automated dependency updates here that can be rolled out in minor releases.
---
=> ci: Only allow automated security-related updates until v0.37.0 release

RELEASES.md
After discussion with @marbar3778, it seems that this process of creating `*-dev` tags interferes with the use of our pre-releases.
Also, it's not clear what value this really brings. Who needs these `-dev` tags and why? If nobody, we should really just remove this part of the process. If it's actually necessary, we should find a different tag naming scheme that doesn't interfere with use of our pre-releases.
---
=> docs: Remove dev base tagging from release branch creation process

state/store.go
Error message was incorrectly changed in https://github.com/tendermint/tendermint/pull/9286. This restores it to the previous one.
=> state: restore previous error message

spec/abci/abci++_methods.md
Contributes to #9201
As per title, fixed paragraph that was stating the contrary.
---
=> Fix ABCI specification (TXs added in `PrepareProposal` are not added to the mempool)

README.md
[Rendered](https://github.com/tendermint/tendermint/blob/thane/readme-release-badge/README.md)
The release tag currently shows `dev-v0.38.0`, which isn't useful to anyone.
---
=> docs: Use release badge in README instead of latest tag

config/toml.go
In looking at adding support for the new `[storage]` section in tendermint-rs, I see that in #9275 I forgot to add the section to our TOML template that's used when generating new configuration files :facepalm: 
This doesn't affect users whose configuration files include the new `[storage]` section in any way: this just ensures that we generate the config file correctly when the user runs `tendermint init`.
This should go into `main`, `v0.37.x` and `v0.34.x` and won't affect the results of our v0.37 QA.
---
=> config: Add missing storage section when generating config

.github/workflows/e2e-nightly-34x.yml, .github/workflows/e2e-nightly-37x.yml, .github/workflows/e2e-nightly-main.yml
As discussed in the team, let's only be notified when there's a failure in the nightly E2E tests. All of them for `main`, `v0.34.x` and `v0.37.x` seem to be passing pretty consistently at present.
---
=> ci: Only notify on nightly E2E failures

blocksync/msgs_test.go, blocksync/reactor.go, blocksync/reactor_test.go, node/doc.go, node/node.go, node/node_test.go
this is a follow up on an earlier PR renaming fast sync to block sync. It appears there were a few cases missing.
=> blocksync: rename blockchain to blocksync in certain areas

test/loadtime/payload/payload.go
Closes #9539
This PR changes the way the payload is encoded and decoded in the `loadtime` tool.
To make sure only one "=" character appears in the transaction's payload, we:
* First we use protobufs to encode the `Payload` structure
* Then we encode those bytes in (uppercase) hex
As this encoding is less efficient, we need to adjust the padding length in order to obtain the desired transaction length.
The tradeoff here is that the minimum transaction payload is doubled (the space required to store a transaction without padding); but we are not likely to hit this limit anytime soon.
---
=> Fix TX payload for DO testnets

.github/workflows/e2e-nightly-34x.yml, .github/workflows/e2e-nightly-37x.yml, .github/workflows/e2e-nightly-main.yml
It's mostly not true that a particular commit _caused_ a failure, so I've changed the wording here.
---
=> ci: Update Slack nightly failure messages

CHANGELOG.md
Adds the changelog entry from #9583 to the changelog on `main`.
---
=> Update changelog with v0.34.22 entry

abci/types/types.pb.go, proto/tendermint/blocksync/types.pb.go, proto/tendermint/consensus/types.pb.go, proto/tendermint/consensus/wal.pb.go, proto/tendermint/crypto/keys.pb.go, proto/tendermint/crypto/proof.pb.go, proto/tendermint/libs/bits/types.pb.go, proto/tendermint/mempool/types.pb.go, proto/tendermint/p2p/conn.pb.go, proto/tendermint/p2p/pex.pb.go, proto/tendermint/p2p/types.pb.go, proto/tendermint/privval/types.pb.go, proto/tendermint/rpc/grpc/types.pb.go, proto/tendermint/state/types.pb.go, proto/tendermint/statesync/types.pb.go, proto/tendermint/store/types.pb.go, proto/tendermint/types/block.pb.go, proto/tendermint/types/canonical.pb.go, proto/tendermint/types/events.pb.go, proto/tendermint/types/evidence.pb.go, proto/tendermint/types/params.pb.go, proto/tendermint/types/types.pb.go, proto/tendermint/types/validator.pb.go, proto/tendermint/version/types.pb.go, rpc/grpc/types.pb.go
Looks like `make proto-gen` is changing the dependencies in the auto-generated code, which is causing problem in CI.
This temporary fix reverts the `make proto-gen` introduced by #9590
This is temporary: we need to find out why `make proto-gen` is introducing those dependency changes.
---
=> Revert `make proto-gen` in #9590

.github/workflows/markdown-links.yml, .md-link-check.json
The Markdown link checker takes ages to run, and often fails spuriously with many false positives. This makes it run nightly for `main` and the `v0.37.x` and `v0.34.x` branches.
This does not enable Slack notifications. Let me know if anyone wants Slack notifications for this, otherwise we'll just end up getting GitHub notifications for failures.
Also, we could consider reducing this to run only once per week if it's too noisy. Let me know if anyone has any preferences.
---
=> ci: Run Markdown link checker nightly

spec/abci/abci++_methods.md
A reference to `Finalize block` was left when referring to the `AppHash` returned via `Info`. In 0.34 and 0.37, the `AppHash` is updated during `Commit` and returned within the `Data` field of `ResponseCommit`.
=> spec/abci: Removed reference to Finalize block

rpc/client/event_test.go, rpc/client/helpers.go
For the full description, see https://github.com/tendermint/tendermint/pull/7986
---
=> backport:  rewrite the WaitForOneEvent helper for rpc/client (#7986)

blockchain/v0/reactor.go, blockchain/v0/reactor_test.go, blockchain/v1/reactor.go, blockchain/v1/reactor_test.go, blockchain/v2/reactor.go, blockchain/v2/reactor_test.go, consensus/reactor.go, consensus/reactor_test.go, evidence/reactor.go, evidence/reactor_test.go, mempool/v0/reactor.go, mempool/v0/reactor_test.go, mempool/v1/reactor.go, mempool/v1/reactor_test.go, p2p/pex/pex_reactor.go, p2p/pex/pex_reactor_test.go, p2p/switch_test.go, statesync/reactor.go, statesync/reactor_test.go, test/maverick/consensus/reactor.go
When implementing this, I had assumed that proto.Unmarshal would allocate for the top-level struct if only a pointer was passed. This assumption was incorrect, we have to explicitly allocate the value to pass to the unmarshal call.
---
=> add allocate in Receive calls

abci/client/local_client.go, abci/client/unsync_local_client.go, proxy/client.go, test/e2e/app/app.go, test/e2e/app/sync_app.go, test/e2e/generator/generate.go, test/e2e/networks/ci.toml, test/e2e/node/config.go, test/e2e/node/main.go, test/e2e/pkg/manifest.go, test/e2e/pkg/testnet.go, test/e2e/runner/setup.go
Closes #7073.
Adds an unsynchronized local client without changing the existing local client behaviour, so API consumers can switch at their leisure and we can roll this out in a non-breaking update from v0.34 onwards.
Also adds a "synchronized" version of the E2E application that can be used with the unsynchronized client, and modifies the E2E tests to randomly choose either a synchronized or unsynchronized application for full nodes and validators whose ABCI protocol is chosen as "builtin".
A manual full E2E run (like the nightly run) seems to show that this works: https://github.com/tendermint/tendermint/actions/runs/3385473966/jobs/5623656412
The CI E2E tests have also been updated to ensure that one validator (`validator04`) always uses the sync version of the app with the …
=> abci: Add unsynchronized local client

README.md
Our version support policy is outdated, and we should be explicit about which versions we currently support.
[Rendered](https://github.com/tendermint/tendermint/blob/thane/docs-supported-versions/README.md#supported-versions)
---
=> docs: Add supported versions to README

.github/workflows/pre-release.yml, .github/workflows/release.yml
=> ci: Sync v0.37.x release workflows with main

CHANGELOG_PENDING.md, UPGRADING.md, cmd/tendermint/commands/run_node.go, config/config.go, config/toml.go, node/node.go, spec/p2p/config.md, spec/p2p/v0.34/configuration.md
This PR adds a new config field: bootstrap peers, a comma separated string of addresses to be added to the addressbook upon node startup. Currently, some node operators misuse persistent peers as a way of adding addresses to dial. Persistent peers has the characteristic of always redialing that peer to keep a consistent connection (designed for sentries) which might not be what node operators intended for. 
This feature is ported across from v0.35.x
---
=> config: add bootstrap peers

spec/abci/abci++_basic_concepts.md
The current text gives margin to committing changes to the app state during EndBlock, but it should only happen during Commit. Also, PrepareProposal is not allowed to modify transactions, but only the transaction set.
---
=> Disambiguates wording in EndBlock

.github/CODEOWNERS
Backports #9697 to `v0.34.x`.
---
=> v0.34.x: Update codeowners to include Adi and Lásaro

.github/CODEOWNERS
Backports #9697 to `v0.37.x`.
---
=> v0.37.x: Update codeowners to include Adi and Lásaro (backport #9697)

CHANGELOG_PENDING.md, UPGRADING.md, rpc/jsonrpc/server/http_server.go, rpc/jsonrpc/server/http_server_test.go, rpc/jsonrpc/server/ws_handler.go
Not sure why Mergify failed to open the automatic backport of #9720 to `v0.34.x`, so I just cherry-picked the commit manually.
---
=> Remove useless whitespace in Websocket output (backport #9720)

config/config.go
I believe we forgot to remove this warning (it's not present in `main`) after patching the priority mempool.
=> v1 mempool: remove memory leak warning

docs/pre.sh
Stacked on top of #9674.
The pre-processing script was copying the entire `rpc/openapi` folder into `docs/.vuepress/public`, instead of just copying the `openapi.yaml` file.
---
=> docs: Fix OpenAPI pre-processing script

scripts/estream/estream.go
For the full description, see https://github.com/tendermint/tendermint/pull/8015
---
=> backport: add command-line tool to manually subscribe to an event stream. (#8015)

docs/.vuepress/config.js
Updates the Algolia search config so that our search will actually work with an appropriate index. Needs to be backported to v0.37 and v0.34.
---
=> docs: Fix search configuration

.github/workflows/docs-deployment.yml
I see our docs build is failing: https://github.com/tendermint/tendermint/actions/runs/3570216583/jobs/6000981820
The cause seems related to [this issue](https://stackoverflow.com/questions/70582072/npm-run-fails-with-err-ossl-evp-unsupported). Running this workflow manually with this fix solves it: https://github.com/tendermint/tendermint/actions/runs/3570298021
The longer-term solution is to get away from using NodeJS entirely in our docs build process.
---
=> ci: Configure docs build workflow to use legacy OpenSSL provider

rpc/openapi/openapi.yaml
Builds on #9674, adding more of the description from https://github.com/tendermint/tendermint/blob/4290ad29829fde50d8a32ef8e11295c4d28c481b/rpc/core/types/responses.go#L26-L29
No need to backport this, I'll add this to #9791 and #9792 before merging them.
---
=> docs: Expand on genesis_chunked description

docs/pre.sh
Our documentation build process is rather finicky. I noticed yet another build failure that doesn't actually cause the docs site build to fail - see https://github.com/tendermint/tendermint/actions/runs/3578638807/jobs/6019002654
Basically the `docs/post.sh` script deletes the `.vuepress/public/rpc` directory after generating the docs for a specific version of Tendermint, and then the `docs/pre.sh` script attempts to copy the next version's OpenAPI script into `.vuepress/public/rpc` but that directory doesn't exist.
For some reason this doesn't cause the npm build process to fail - it just results in the OpenAPI doc not being available.
This is hard to test locally because our docs build process currently relies on checking out specific branches to do the full docs site build: …
=> docs: Fix pre-build script

test/e2e/networks/simple.toml, test/e2e/pkg/manifest.go, test/e2e/pkg/testnet.go, test/e2e/runner/load.go, test/e2e/runner/main.go
This pull request updates the e2e test to use the `loadtime` transaction format and updates the configuration to allow for parity with the `loadtime` load generation.
`load_tx_size_bytes`: This size, in bytes, of each generated transaction. Defaults to 1024 bytes.
`load_tx_batch_size`: How many transactions to generate every 1 second.
`load_tx_connections`: How many connections to make to each node.
`node.no_send_load`: Whether or not to send load to this node.
Note that there is a slight difference between this configuration scheme and the scheme used in the `loadtime` tool. The `loadtime` tool generates `batch_size` _per connection_ per second. This code generates a total of `load_tx_batch_size` total every second. To mimic the behavior of the `loadtime` tool simply multiply by the …
=> e2e: test runner generates loadtime formatted transactions.

test/e2e/pkg/manifest.go, test/e2e/runner/main.go
The "toml" annotation of "send no load" had a typo (`send_no_laod`).
This is suspected to have caused failures in e2e, however I couldn't reproduce the error locally, so not sure this will fix it. Still, the typo needs to be fixed in any case.
---
=> Fix typo in new option in e2e manifest node

docs/tutorials/go-built-in.md, docs/tutorials/go.md
Updates the discussion of prepareProposal in the go tutorials to mention tx_max_bytes limitation to transaction set size.
---
=> Mention tx_max_bytes in the tutorials

test/e2e/runner/load.go
Fixes the issue observed in an [e2e test run](https://github.com/tendermint/tendermint/actions/runs/3588927225). The issue arises when the e2e runner process cannot connect to the remote node. In the previous version of this code, the runner would simply skip the transaction if the client couldn't connect. This pull request resurrects that behavior.
---
=> e2e: create client when sending transaction

.github/workflows/docker.yml, .github/workflows/e2e-nightly-34x.yml, .github/workflows/e2e-nightly-37x.yml, .github/workflows/e2e-nightly-main.yml, .github/workflows/fuzz-nightly.yml
The primary aim of this PR is to improve the failure messages we get a little. Seeing the latest commit is often useless, and it's probably better to just get a direct link to a list of commits for that specific branch so we can see what's been committed since the previous nightly run.
This PR also makes one minor improvement in the use of the now-deprecated `set-output` syntax for workflows, upgrading it to use the new approach as per https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
---
=> ci: Better Slack failures

test/e2e/runner/load.go
Aimed at fixing: https://github.com/tendermint/tendermint/actions/runs/3598326181/jobs/6060978982
The issue is that if the context in the `createBatch` function is canceled before all of the transactions are generated, we will hit the return in the `ctx.Done()` case of the select and the `wg.Done()` will never be called, causing the `createBatch` function to never return and therefore never allow more transactions to be generated.
To test this, I passed a context with very short timeout into the `createBatch` function and observed that, after the initial set of transactions fail because the connection is not yet established to the node, the `ctx.Done()` case is hit and no more transactions are ever created, leading to the same failure we see in the e2e nightly.
A sample of output from …
=> e2e: add defer to ensure waitgroup is finished.

test/e2e/generator/generate.go, test/e2e/generator/main.go, test/e2e/generator/random.go
This pull request should be the last changes made directly to the Go e2e code. This adds a `multi-version` flag to the e2e test generator. When set with `--multi-version <version-number>` the e2e generator will create manifests with with `<version-number>` specified as the node version. 
The final piece of this group of changes will be setting this flag in the `v0.34.x` branch's invocation of the `generator` tool. The flag will be set dynamically by querying git for the latest `v0.34.*` tag.
=> e2e: add multiversion flag to generator

docs/architecture/adr-075-rpc-subscription.md, rpc/client/eventstream/eventstream_test.go, rpc/core/events.go
For the full description, see https://github.com/tendermint/tendermint/pull/8050
---
=> backport: set a minimum long-polling interval for Events in rpc (#8050)

config/config.go
This is the last backport for adr 075, for the full description, see https://github.com/tendermint/tendermint/pull/8572
---
=> backport: enable the ADR 075 event log by default in new configs in rpc (#8572)

.github/workflows/testapp-docker.yml
The docker image was mistakenly named `testapp`, whereas the correct name is `e2e-node`. This is the name used by the docker-compose file referenced in the e2e tests:
https://github.com/tendermint/tendermint/blob/3324f49fb7e7b40189726746493e83b82a61b558/test/e2e/pkg/infra/docker/docker.go#L60
---
=> workflow: correct the name for the e2e app in the workflow

light/proxy/routes.go
The PR #9759 relies on `match.events` to appear first in the query. It was not fixed for the light client RPC queries.
=> kvindexer: Fixing order or keywords in light client rpc

node/setup.go
Seems as if the logger was never wired up to the mempool reactor so logs weren't being published by that reactor.
This PR wires it up correctly. I've validated this by running the e2e tests afterwards and checking that the logs actually publish mempool reactor info.
This should also be backported to v0.34.x
=> node: wire up logger to mempool reactor

blocksync/pool.go, blocksync/reactor_test.go, internal/test/params.go, privval/file.go, proto/tendermint/abci/types.proto, proto/tendermint/types/canonical.proto, proto/tendermint/types/types.proto, proxy/app_conn.go, state/execution.go, store/store.go, types/block_test.go, types/vote_set.go
Contributes to #9887
These are the obvious divergences (including bugs) between #9620 and `feature/abci++vef`
For more info, check #9887
---
=> Divergences in comparison with #9620. Part 1: easy/obvious

test/e2e/networks/ci.toml
=> e2e: Remove extraneous abci_protocol params in CI test

p2p/peer.go
`TrySendEnvelopeShim` is a temporary function introduced in `v0.34.23` to make the new `Envelope`-based infra for sending/broadcasting messages over p2p compatible with the existing releases in the `v0.34.x` branch.
This function does not exist in any further release branch (`v0.37.x`, etc)
`TrySendEnvelopeShim` is supposed to be non-blocking, and should therefore call `TrySendEnvelope` rather than `SendEnvelope`
---
=> Fix function `TrySendEnvelopeShim`

blocksync/reactor.go, blocksync/reactor_test.go, types/params.go, types/vote.go
Contributes to #9887
This PR fixes and tests the problems found in the blocksync reactor when comparing the cherry-picked branch with #9620 (diff-of-diffs).
The newly added UT will panic if the fix in the blocksync reactor is removed.
---
=> Divergences in comparison with #9620. Part 3: Fix problems found in blocksync reactor

CHANGELOG_PENDING.md, consensus/reactor.go
Reverts tendermint/tendermint#9775 to remove from v0.37.0.
We'll reapply this to v0.37.1.
=> Revert "consensus: correctly save reference to previous height precommits (backport #9760)"

consensus/state.go, light/trust_options.go, mempool/v1/mempool_test.go, state/validation_test.go, types/block.go, types/test_util.go, types/vote.go
Contributes to #9887
This PR contains other minor differences spotted between #9620 and the cherry-picked vote extension branch.
After this PR, all differences between these two branches (#9620 and the cherry-picked)  will now be integrated in branch `feature/abci++vef`
These are the differences included in this PR (can be reviewed independently by selecting the right commit):
* Restore `IsZero` method at the places it was removed when solving cherry-pick conflicts
* Improve the level of checks when signing votes in production, by moving the checks introduced in #9895 to production (rather than test)
* Fixed timing of some v1 mempool UTs to make them less flaky
* Other simple changes spotted during the diff-of-diffs
---
=> Divergences in comparison with #9620. Part 4: Other changes spotted
