tendermint/tendermint

- node/node.go
> getter for blockstore in Node

- rpc/server/handlers.go
An empty request to `myhost:46657/` will return an html page with a list of links to the http endpoints
> rpc endpoint / lists available endpoints

- binary/reflect.go
- blockchain/pool.go
- blockchain/reactor.go
- common/repeat_timer.go
- common/service.go
- consensus/reactor.go
- consensus/state.go
- events/events.go
- events/log.go
- mempool/reactor.go
- node/node.go
- p2p/addrbook.go
- p2p/connection.go
- p2p/listener.go
- p2p/peer.go
- p2p/pex_reactor.go
- p2p/switch.go
- p2p/switch_test.go
- p2p/upnp/upnp.go
- rpc/server/handlers.go
- state/permissions_test.go
- vm/test/log_event_test.go
- vm/test/vm_test.go
- vm/types.go
Created BaseService/QuitService/BaseReactor struct types that handle idempotent Start() and Stop() for implementors.
After polishing the code to make it simple and succinct, it turns out the result looks and functions much like classical inheritance.
> Base service + Base reactor

- state/block_cache.go
- state/state_test.go
- vm/vm.go
This PR fixes the code handling removed accounts (suicides). Previously, suicides caused panic (eg. https://github.com/tendermint/tendermint/issues/131). Test included as well.
> fix suicide

- rpc/test/tests.go
- state/execution.go
- state/state_test.go
- types/names.go
- types/tx.go
closes https://github.com/tendermint/tendermint/issues/141
> update namereg with longer names, more allowed chars

- mempool/reactor.go
https://github.com/tendermint/tendermint/issues/156
> check peerMempoolChan for nil on Reset

- proxy/log.go
- proxy/remote_app_context.go
fix race condition where didRecv runs before didSend by running didSend (now willSend) before writing to the connection
> didSend -> willSend

- blockchain/reactor.go
- consensus/common_test.go
- consensus/reactor.go
- consensus/state.go
- consensus/state_test.go
- events/events.go
- mempool/reactor.go
- node/node.go
- rpc/server/handlers.go
- state/state.go
- types/block.go
- types/events.go
> Consensus refactor

- cmd/tendermint/reset_priv_validator.go
- consensus/common_test.go
- consensus/reactor.go
- consensus/replay.go
- consensus/replay_test.go
- consensus/state.go
- consensus/wal.go
- types/priv_validator.go
Coupled with the replay-WAL, this should prevent us from ever halting due to "losing a sig and not wanting to double sign".
> types: privVal.LastSignature. closes #247

- mempool/mempool.go
> Fix mistake in Mempool Reap documentation

- README.md
- circle.yml
- test/run_test.sh
- test/test.sh
- test/test_cover.sh
Properly compute code coverage, add other badges to readme.
> Codecov and badges

- rpc/test/client_test.go
And the test that went missing in the refactor...
> Add test for proper tx event

- consensus/mempool_test.go
- mempool/mempool.go
- mempool/mempool_test.go
Reference:
* https://tendermint.slack.com/archives/support/p1475625676000526
* https://github.com/tendermint/tendermint/pull/288
@srmo, can you check that this works?
> Fix race condition; Refactor out txCache

- .codecov.yml
Status will still be success if coverage drops by up to 1%
> add codecov.yml to lower threshold

- blockchain/reactor.go
- blockchain/store.go
- consensus/byzantine_test.go
- consensus/common.go
- consensus/common_test.go
- consensus/reactor.go
- consensus/reactor_test.go
- consensus/state.go
- glide.lock
- node/node.go
- rpc/test/client_test.go
- state/execution.go
- state/execution_test.go
- state/state.go
- test/app/dummy_test.sh
- types/block.go
- types/protobuf.go
- types/validator.go
- types/validator_set_test.go
Very simple approach to validator set changes.
Still needs testing. Also will need more work for proper light client validation.
> Validator Set Changes

- README.md
- blockchain/pool.go
- cmd/tendermint/flags.go
- config/tendermint/config.go
- config/tendermint_test/config.go
- glide.lock
- glide.yaml
- node/node.go
- rpc/core/blocks.go
- rpc/core/net.go
- rpc/core/routes.go
- scripts/glide/parse.sh
- test/test_libs.sh
Small release to enable the peer exchange reactor behind a feature flag
> Release 0.7.4: feature flag: pex reactor

- version/version.go
https://www.youtube.com/watch?v=8Ux3DKxxFoM
> shame: version bump 0.7.4

- types/block.go
- types/canonical_json.go
- types/part_set.go
- types/proposal.go
- types/proposal_test.go
- types/vote.go
- types/vote_set_test.go
Use canonical forms of structs for WriteSignBytes
https://github.com/tendermint/tendermint/issues/315
> Sign bytes

- Vagrantfile
I am in favor of docker, but people say that running docker containers
inside another container is bad.
Things included in provision:
- docker (latest)
- jq
- curl
- shellcheck
- golang 1.7
- glide
> Feature: Update Vagrant setup

- cmd/tendermint/main.go
- cmd/tendermint/run_node.go
- node/node.go
- node/node_test.go
- rpc/test/helpers.go
Refactor needed to make Basecoin+Tendermint integration simple.
> Refactor Node; Node is a simple BaseService

- scripts/dist.sh
- scripts/dist_build.sh
> permissions error during make dist

- Makefile
- circle.yml
- test/test.sh
- test/test_cover.sh
- test/test_libs.sh
> Improve CircleCI setup (WIP)

- DOCKER/Dockerfile
813Mb => 29.5Mb 😋 
Re(push) image:
```
docker build -t "tendermint/tendermint" -t "tendermint/tendermint:0.8.0" -t "tendermint/tendermint:0.8" .
docker login
docker push "tendermint/tendermint" "tendermint/tendermint:0.8.0" "tendermint/tendermint:0.8"
```
> [docker] move to alpine base image

- .gitignore
- Vagrantfile
- circle.yml
- test/p2p/peer.sh
- test/p2p/test.sh
- test/test.sh
How: 1) we start syslog docker container 2) all other containers use
syslog logging driver to ship their logs to that container
Refs #387
> collect and add docker logs to CircleCI artifacts (Refs #387)

- cmd/tendermint/init.go
> do not overwrite existing files when doing `tendermint init`

- blockchain/reactor.go
- consensus/byzantine_test.go
- consensus/reactor.go
- mempool/reactor.go
See #174 for the issue & discussion.
> Check `peer.Send` failures

- blockchain/pool.go
- config/tendermint/config.go
- config/tendermint_test/config.go
- consensus/replay.go
- consensus/replay_file.go
- consensus/state.go
- consensus/ticker.go
- consensus/wal.go
- node/node.go
- proxy/multi_app_conn.go
Fix https://github.com/tendermint/tendermint/issues/436
Handshake replay logic did not account for need to catch up by fast sync!
> consensus: timeout on replayLastBlock

- rpc/server/handlers.go
- rpc/server/http_server.go
https://github.com/tendermint/tendermint/issues/457
> rpc: use HTTP error codes

- Makefile
- version/version.go
> Use ld flags to set git hash instead of "revision_file"

- types/tx.go
What are the other Objects whose String reprs we can improve? @melekes
> Add Tx String representation

- consensus/byzantine_test.go
- consensus/common_test.go
- consensus/reactor_test.go
- glide.lock
(Refs #492)
DEPENDS ON https://github.com/tendermint/tmlibs/pull/14
> Color code different consensus instances in consensus tests

- rpc/lib/server/handlers.go
- rpc/lib/server/http_server.go
- types/validator_set.go
Adjust naming of a few fields (lower case), and pretty print the rpc output for nice viewing
> Clean up json output

- rpc/lib/client/http_client.go
Also, no longer panics but instead return an error.
> httpDialer accepts no prefix or http:// as tcp://

- cmd/tendermint/commands/root.go
DEPENDS ON https://github.com/tendermint/tmlibs/pull/21
> tracing logger (Refs #506)

- cmd/tendermint/commands/root.go
- cmd/tendermint/commands/run_node.go
- types/genesis.go
Fix issue #554 to make it easier to maintain consistency between stand-alone tendermint, and tendermint embedded in basecoin.
This should make it into 0.10.1
> #554 embed commands

- DOCKER/Dockerfile
- DOCKER/Dockerfile.develop
- DOCKER/Makefile
- DOCKER/README.md
- DOCKER/build.sh
- DOCKER/push.sh
- scripts/tendermint-builder/Dockerfile
- test/docker/Dockerfile
Refs https://github.com/tendermint/tools/issues/35
> Docker build automation

- blockchain/reactor.go
- consensus/reactor.go
- node/node.go
- rpc/core/pipe.go
- rpc/core/status.go
Related to https://github.com/tendermint/tendermint/pull/579
Replace `blockchainReactor` by `consensusReactor` to get fast-sync status
/cc @adrianbrink
> fast sync status

- README.md
Changed the blog links to Medium.
Updated Tendermint website links.
> Update website links on README.md

- docs/getting-started/#02-first-app.md
- docs/getting-started/#03-deploy-testnet.md
- docs/getting-started/#04-next-steps.md
- docs/guides/abci-cli.md
- docs/guides/app-architecture.md
- docs/guides/app-development.md
- docs/guides/using-tendermint.md
fix/clarify a bunch of things
closes:
- https://github.com/zramsay/tendermint/issues/3
- https://github.com/zramsay/tendermint/issues/5
> docs fixes throughout

- consensus/reactor.go
- consensus/state.go
Bug fix: dont panic on a bad vote type
Improvement: recover from panics on consensus state and hang
> Dont panic

- benchmarks/simu/counter.go
- glide.lock
- glide.yaml
- node/node.go
- rpc/client/httpclient.go
- rpc/lib/client/ws_client.go
- rpc/lib/client/ws_client_test.go
- rpc/lib/rpc_test.go
- rpc/lib/server/handlers.go
- rpc/lib/test/integration_test.sh
- rpc/lib/types/types.go
What's new:
- auto reconnect
- ping/pong
- colored tests
- latency timer embedded in WS client
> Biff up RPC WSClient

- cmd/tendermint/commands/root.go
https://github.com/tendermint/tendermint/issues/620
> cmd: don't load config for version command. closes #620

- consensus/replay.go
- rpc/client/httpclient.go
- rpc/client/interface.go
- rpc/client/localclient.go
- rpc/client/mock/client.go
- rpc/client/rpc_test.go
- rpc/core/blocks.go
- rpc/core/consensus.go
- rpc/core/pipe.go
- rpc/core/routes.go
- state/errors.go
- state/execution.go
- state/state.go
- state/state_test.go
https://github.com/tendermint/tendermint/issues/590
> Historical validators

- state/state.go
- state/state_test.go
I've capped the line length because otherwise, it is annoying to have split screen vim/emacs on a 13" screen.
Also, I've extracted common setup in the test file.
> Upgrade state_test.go

- blockchain/reactor.go
- consensus/byzantine_test.go
- consensus/common_test.go
- consensus/reactor.go
- mempool/reactor.go
- p2p/peer.go
- p2p/peer_set.go
- p2p/peer_set_test.go
- p2p/peer_test.go
- p2p/pex_reactor.go
- p2p/pex_reactor_test.go
- p2p/switch.go
- p2p/switch_test.go
- rpc/core/consensus.go
- rpc/core/net.go
https://github.com/tendermint/tendermint/issues/631
> peer interface

- CHANGELOG.md
- rpc/core/events.go
- rpc/lib/client/http_client.go
- rpc/lib/client/ws_client.go
- rpc/lib/server/handlers.go
- rpc/lib/server/http_server.go
- rpc/lib/types/types.go
- rpc/lib/types/types_test.go
- test/app/counter_test.sh
Port of https://github.com/tendermint/go-rpc/pull/19
link to spec: http://www.jsonrpc.org/specification
> updated json response to match spec by @davebryson

- CONTRIBUTING.md
- README.md
- docs/ecosystem.rst
- docs/install.rst
> update readme and other files

- glide.lock
- glide.yaml
- node/node.go
- p2p/listener.go
- rpc/lib/types/types.go
> p2p: allow listener with no external connection

- rpc/grpc/types.proto
Fix protoc complaining about broken import
> Fix broken reference to ABCI

- Makefile
- scripts/publish.sh
- scripts/release.sh
Untested, but should be working.
> Bash script for releasing Tendermint

- docs/using-tendermint.rst
configutation -> configuration
> Fix typo in using-tendermint.rst

- docs/index.rst
- docs/specification/configuration.rst
- docs/using-tendermint.rst
> document no empty blocks

- .gitignore
- docs/how-to-read-logs.rst
- docs/index.rst
- mempool/mempool.go
> How To Read Logs guide

- consensus/common_test.go
- consensus/reactor.go
- consensus/state.go
- consensus/state_test.go
- consensus/types/height_vote_set.go
- consensus/types/height_vote_set_test.go
- consensus/types/reactor.go
- consensus/types/state.go
- rpc/core/consensus.go
- rpc/core/pipe.go
- rpc/core/types/responses.go
- rpc/lib/doc.go
- rpc/lib/server/handlers.go
- rpc/lib/types/types.go
> Leaving out params crashes tm rpc

- rpc/client/httpclient.go
- rpc/client/interface.go
- rpc/client/localclient.go
- rpc/client/mock/abci.go
- rpc/client/mock/abci_test.go
- rpc/client/mock/client.go
- rpc/client/rpc_test.go
- rpc/client/types.go
- rpc/core/abci.go
- rpc/core/routes.go
> support historical abci queries

- docs/_static/custom_collapsible_code.css
- docs/_static/custom_collapsible_code.js
- docs/_templates/layout.html
- docs/app-development.rst
[docs] added new code to allow creation of collapsible code blocks
[docs] added a java example for each go example in app development section
> 701 add dev docs in java

- docs/ecosystem.rst
- docs/getting-started.rst
- docs/using-tendermint.rst
> add tm-migrator to docs

- mempool/mempool.go
> WIP: only notify when there are some txs (Refs #753)

- CHANGELOG.md
- mempool/mempool.go
- rpc/lib/client/http_client.go
- state/state.go
- state/state_test.go
- state/txindex/indexer.go
- state/txindex/kv/kv.go
- state/txindex/null/null.go
- types/block.go
This cleans up some of the code in the state package
> Cleanup of code and code docs

- docs/abci-cli.rst
- docs/getting-started.rst
links to https://github.com/tendermint/abci/pull/117
> docs: update abci example details

- blockchain/pool.go
- blockchain/reactor.go
- blockchain/reactor_test.go
- p2p/pex_reactor.go
> blockchain reactor timeout

- CHANGELOG.md
- cmd/tendermint/commands/testnet.go
- cmd/tendermint/main.go
- config/config.go
- config/toml.go
- config/toml_test.go
- consensus/test_data/build.sh
- docs/deploy-testnets.rst
- docs/specification/configuration.rst
- docs/specification/genesis.rst
- docs/specification/rpc.rst
- docs/using-tendermint.rst
- rpc/core/doc.go
- scripts/debora/unsafe_reset_net.sh
> config: split data and config directories

- blockchain/pool.go
- blockchain/reactor.go
- consensus/byzantine_test.go
- consensus/reactor.go
- consensus/reactor_test.go
- consensus/state.go
Addresses https://github.com/tendermint/tendermint/issues/740
Not thrilled about it though. Anyone have better ideas?
> dont catchupReplay on wal if we fast synced

- p2p/switch.go
> fix comment typos

- consensus/reactor.go
I don't know a good way to test this yet other than manually :(
> consensus: ensure prs.ProposalBlockParts is initialized. fixes #810

- consensus/mempool_test.go
- node/node_test.go
- p2p/pex_reactor_test.go
- p2p/switch_test.go
> prefer tickers to time.Sleep

- p2p/switch.go
- p2p/switch_test.go
> MakeConnectedSwitches: connect first switch to others

- consensus/reactor.go
- p2p/peer.go
- test/p2p/atomic_broadcast/test.sh
- test/p2p/peer.sh
- test/test.sh
> Enable logs by default

- p2p/peer.go
Noticed while auditing the code that we aren't respecting
(*net.Conn) SetDeadline errors which return after
a connection has been killed and is simultaneously
being used.
For example given program, without SetDeadline error checks
```go
package main
import (
"log"
"net"
"time"
)
func main() {
conn, err := net.Dial("tcp", "tendermint.com:443")
if err != nil {
log.Fatal(err)
}
go func() {
<-time.After(400 * time.Millisecond)
conn.Close()
}()
for i := 0; i < 5; i++ {
if err := conn.SetDeadline(time.Now().Add(time.Duration(10 * time.Second))); err != nil {
log.Fatalf("set deadline #%d, err: %v", i, err)
}
log.Printf("Successfully set deadline #%d", i)
<-time.After(150 * time.Millisecond)
}
}
```
erraneously gives
```shell
2017/11/14 17:46:28 Successfully set deadline #0
2017/11/14 17:46:29 …
```
> p2p: peer should respect errors from SetDeadline

- CHANGELOG.md
- p2p/switch.go
- p2p/trust/trustmetric.go
- rpc/lib/types/types.go
@melekes can you review this changelog and add/correct anything that's missing please
> Small things

- docs/specification/block-structure.rst
- docs/specification/merkle.rst
> docs: fix links

- p2p/switch.go
Fixes https://github.com/tendermint/tendermint/issues/875
Ensure that every DialSeeds call uses a new PRNG seeded from
tendermint/tmlibs/common.RandInt which internally uses
crypto/rand to seed its source.
> p2p: make Switch.DialSeeds use a new PRNG per call

- INSTALL.md
> remove unused file

- docs/getting-started.rst
fixes broken link to introduction.html
> Update getting-started.rst to fix broken link

- glide.lock
- p2p/connection.go
Just remade the branch and new PR for cleanliness.
> normalize priority and id and remove pointers in ChannelDescriptor

- .codecov.yml
see: https://docs.codecov.io/v4.3.6/docs/ignoring-paths
> codecov: ignore docs files

- p2p/netaddress.go
- p2p/netaddress_test.go
- p2p/switch.go
> tolerate unresolvable seeds

- cmd/tendermint/commands/root_test.go
- config/config.go
- config/toml.go
- config/toml_test.go
- docs/specification/configuration.rst
- rpc/core/status.go
> default moniker to the host name

- Makefile
- Vagrantfile
Note default username changed from vagrant to ubuntu in the base image.
> Update Vagrantfile to xenial (16.04 LTS)

- docs/architecture/adr-007-trust-metric-usage.md
Draft of the trust metric usage guide proposal
> Adding the Trust Metric Usage Guide

- CHANGELOG.md
- glide.lock
- glide.yaml
- node/node.go
- rpc/client/helpers.go
- rpc/client/httpclient.go
- rpc/client/interface.go
- rpc/client/localclient.go
- rpc/core/events.go
- rpc/lib/server/handlers.go
- rpc/lib/types/types.go
- types/event_bus.go
- types/events.go
Requires https://github.com/tendermint/tmlibs/pull/96
> bring back transparent websocket (Refs #945)

- CHANGELOG.md
- consensus/wal.go
- consensus/wal_generator.go
- rpc/test/helpers.go
> [consensus] remove WAL separator

- Makefile
- circle.yml
See commit description for details.
> Remove get_deps, update_deps and list_deps from Makefile

- p2p/trust/config.go
- p2p/trust/metric.go
- p2p/trust/metric_test.go
- p2p/trust/store.go
- p2p/trust/store_test.go
- p2p/trust/ticker.go
https://github.com/tendermint/tendermint/issues/916
> Fixed the problems identified in issue #916

- CHANGELOG.md
- cmd/tendermint/commands/run_node.go
- config/config.go
- p2p/pex_reactor.go
Note this is actually breaking because https://github.com/tendermint/tendermint/issues/957
> activate PEX reactor by default

- blockchain/reactor_test.go
- consensus/mempool_test.go
- consensus/state.go
- lite/helpers.go
- state/execution.go
- state/execution_test.go
- state/state.go
- types/block.go
- types/block_test.go
Addresses one part of issue #952
- Add extra field to header
- Make NumTx also an int64 for consistency.
- Update state to keep track of this info.
- Change function args as needed.
> Add TotalTx to block header

- types/block_test.go
> add missing Timestamp to Vote

- consensus/replay.go
- state/execution.go
- state/execution_test.go
> Send absent validators

- consensus/replay.go
- consensus/replay_test.go
- consensus/wal.go
- consensus/wal_fuzz.go
- consensus/wal_generator.go
- consensus/wal_test.go
- docs/specification/corruption.rst
> Handle corrupt WAL file

- config/config.go
- consensus/mempool_test.go
- consensus/reactor.go
- consensus/reactor_test.go
- consensus/replay_test.go
- consensus/state.go
- consensus/wal_generator.go
- glide.lock
- p2p/connection.go
- p2p/peer.go
- p2p/peer_set_test.go
- p2p/pex_reactor.go
- p2p/pex_reactor_test.go
- p2p/switch.go
- test/p2p/kill_all/check_peers.sh
Trying to hunt non-determinism on Circle. 
We've been using CircleCI's version of docker v1.10.0, which is nearly 2 years old. Perhaps it  had a bug in the networking layer ?!
> Circle testing

- consensus/wal_generator.go
> enable logging for wal_generator and set timeout to 1 min

- p2p/listener.go
- p2p/netaddress.go
- p2p/netaddress_test.go
> strip protocol if defined

- types/priv_validator.go
- types/priv_validator_test.go
since now we have time in the msgs and we might crash between writing
the priv val and writing to wal.
Refs #984
> priv validator returns last sign bytes if h/r/s matches

- Makefile
- glide.lock
- p2p/connection.go
- test/docker/Dockerfile
- test/run_test.sh
Related: https://github.com/tendermint/abci/pull/168
> Cleaned up makefile

- types/vote_test.go
Improve test coverage of `types/vote.go`
> Add more tests to types/vote.go

- consensus/common_test.go
- consensus/reactor_test.go
- docs/app-development.rst
- docs/specification/light-client-protocol.rst
- state/execution.go
- state/state_test.go
> enforce <1/3 validator updates

- lite/memprovider.go
Fixes #1006
```
goroutine 230 [runnable]:
github.com/cosmos/gaia/vendor/golang.org/x/crypto/ripemd160.(*digest).Sum(0xc420ac2af0, 0x0, 0x0, 0x0, 0xc420c01360, 0xc420c01378, 0x20)
/Users/mappum/go/src/github.com/cosmos/gaia/vendor/golang.org/x/crypto/ripemd160/ripemd160.go:119 +0x2c9
github.com/cosmos/gaia/vendor/github.com/tendermint/tmlibs/merkle.KVPair.Hash(0x49447e8, 0x7, 0x47ff760, 0xc420048d50, 0xc420aba9a0, 0x14, 0x20)
/Users/mappum/go/src/github.com/cosmos/gaia/vendor/github.com/tendermint/tmlibs/merkle/simple_tree.go:122 +0x200
github.com/cosmos/gaia/vendor/github.com/tendermint/tmlibs/merkle.(*KVPair).Hash(0xc4200f7ae0, 0xc420aba9a0, 0x14, 0x20)
<autogenerated>:1 +0x57
github.com/cosmos/gaia/vendor/github.com/tendermint/tmlibs/merkle.SimpleHashFromHashables(0xc420111900, 0x9, …
```
> protect memStoreProvider#byHash map by mutex

- consensus/wal_generator.go
> change directory for each call, not only for each test

- Makefile
- docs/install.rst
- scripts/dist_build.sh
Reverts tendermint/tendermint#1053
Too many issues, reverting.  Please comment on the original PR, if it makes sense to.
@ebuchman @Greg-Szabo
> Revert "Changes to achieve a standardized build process and deterministic builds"

- lite/inquirer.go
- lite/inquirer_test.go
- lite/proxy/certifier.go
> NewInquiring returns error instead of swallowing it

- types/validator_set.go
- types/validator_set_test.go
> check for overflow and underflow while choosing proposer

- docs/using-tendermint.rst
> document the maximum supported voting power due to overflow [ci skip]

- docs/using-tendermint.rst
> document tx formats

- rpc/core/events.go
> document event subscriptions

- Makefile
- cmd/tendermint/commands/root.go
- cmd/tendermint/commands/root_test.go
- config/config.go
- config/toml.go
- consensus/common_test.go
- consensus/mempool_test.go
- consensus/reactor_test.go
- consensus/replay_test.go
- consensus/state_test.go
- consensus/wal_test.go
- glide.lock
- glide.yaml
- mempool/mempool.go
- mempool/mempool_test.go
- node/node.go
- p2p/test_util.go
- test/run_test.sh
Tweak test config to make tests run 2-3x faster :).
Sorry I didn't come up with this months ago ...
> Consensus tests

- mempool/docs/README.md
- mempool/docs/concurrency.md
- mempool/docs/config.md
- mempool/docs/functionality.md
- mempool/docs/messages.md
Writing a public specification of the mempool module.
* Include overview and configuration options.
> WIP: Mempool specification

- docs/specification/new-spec/consensus-reactor.md
This is the first version of several important part of consensus reactor.
> Add consensus reactor doc

- circle.yml
> mercy for developers with slow Internet

- blockchain/pool.go
- blockchain/reactor.go
- blockchain/reactor_test.go
- consensus/reactor.go
- consensus/state.go
- consensus/types/height_vote_set.go
- mempool/reactor.go
- p2p/switch.go
- state/execution.go
- types/validator_set.go
- types/vote_set.go
Implement a few of the "punish peer" TODOs.
There's still lots more but these were low-hanging fruit.
Others may require some design/conversation.
> StopPeerForError in blockchain and consensus

- node/node.go
- p2p/node_info.go
- p2p/peer.go
- p2p/peer_test.go
- p2p/test_util.go
Solves https://github.com/tendermint/tendermint/issues/957
> p2p: add Channels to NodeInfo and don't send for unknown channels

- p2p/conn/connection.go
I don't think we've seen issues related to these breaks before, but its possible the blocking on c.pong is related to https://github.com/cosmos/gaia/issues/112 and  https://github.com/tendermint/tendermint/issues/938 and https://github.com/tendermint/tendermint/pull/1151
> p2p/conn: fix blocking on pong during quit and break out of loops

- types/vote_set.go
> improve error message

- docs/specification/new-spec/bft-time.md
@ebuchman @melekes @ethanfrey Please check if this makes sense so I can proceed to implementation.
> Add BFT time spec

- CHANGELOG.md
- cmd/tendermint/commands/run_node.go
- config/config.go
- config/toml.go
- docs/specification/configuration.rst
- node/node.go
> add seed_mode flag (`--p2p.seed_mode`)

- p2p/base_reactor.go
- p2p/conn/connection.go
> WIP: TestReactorValidatorSetChanges fails non deterministically

- blockchain/pool.go
Refs #1177
Note on labels:
KB - 1024
kB - 1000
https://ux.stackexchange.com/questions/13815/files-size-units-kib-vs-kb-vs-kb
> improve "curRate too low" message

- p2p/conn/connection.go
- p2p/conn/connection_test.go
- p2p/conn/secret_connection_test.go
- p2p/switch.go
- p2p/switch_test.go
Refs #804
Original PR: https://github.com/tendermint/tendermint/pull/832
> [p2p] Pong Timeout

- blockchain/pool.go
- blockchain/reactor.go
- blockchain/reactor_test.go
- consensus/reactor.go
- consensus/state.go
- consensus/ticker.go
- evidence/reactor.go
- glide.lock
- glide.yaml
- mempool/reactor.go
- node/node_test.go
- p2p/conn/connection.go
- p2p/peer.go
- p2p/pex/addrbook.go
- p2p/pex/pex_reactor.go
- p2p/pex/pex_reactor_test.go
- p2p/trust/metric.go
- p2p/trust/store.go
- rpc/client/httpclient.go
- rpc/lib/client/ws_client.go
- rpc/lib/client/ws_client_test.go
- rpc/lib/server/handlers.go
Issue https://github.com/tendermint/tendermint/issues/1205
DEPENDS ON:
1. https://github.com/tendermint/tmlibs/pull/150
2. https://github.com/tendermint/abci/pull/191
> Fixes for p2p memory leak and pong

- CHANGELOG.md
- proxy/client.go
> return back dummy & persistent_dummy as options for proxy_app

- p2p/pex/pex_reactor.go
- p2p/pex/pex_reactor_test.go
We dial persistent_peers right away, but it takes a while to dial seeds for the first time. If we have no peers, we should dial seeds right away
> p2p: if we have no peers we should dial seeds right away

- codecov.yml
- docs/abci-cli.rst
- docs/conf.py
- docs/ecosystem.rst
- docs/index.rst
- docs/specification.rst
- docs/specification/new-spec/README.md
- docs/specification/new-spec/reactors/consensus/consensus-reactor.md
- docs/specification/new-spec/reactors/consensus/consensus.md
ref: #1261 
@srmo & @Chjango you can test this with:
```
cd docs
make html
xdg-open _build/html/index.html
```
on Mac you can drop the `xdg-` prefix
> fix docs links & stuff

- rpc/lib/server/handlers.go
> Make RPC handler protocol agnostic

- cmd/tendermint/commands/run_node.go
- config/config.go
- docs/architecture/adr-008-priv-validator.md
- node/node.go
- types/priv_validator.go
PrivValidator follow up re https://github.com/tendermint/tendermint/issues/1255
> PrivValidatorAddr -> PrivValidatorListenAddr. Update ADR008

- node/node.go
- types/priv_validator/json.go
- types/priv_validator/socket.go
- types/priv_validator/socket_test.go
Incorporates feedback from #1203 and is part of #1255.
> Follow-ups to PrivValidator

- .github/ISSUE_TEMPLATE
- Makefile
> add 2 more points to ISSUE_TEMPLATE

- p2p/pex/addrbook.go
- p2p/pex/addrbook_test.go
- p2p/pex/pex_reactor.go
- p2p/pex/pex_reactor_test.go
- rpc/lib/client/ws_client.go
> exponential backoff for addrs in the address book

- cmd/tendermint/commands/lite.go
Noticed while investigating
https://github.com/tendermint/tendermint/issues/970
As reported by @zramsay, we'd get the warning
from tendermint/rpc/lib because we were passing in
scheme-less addresses, so by default use "tcp".
Also by default, "node" (nodeAddr) has been set to:
"tcp://localhost:46657"
instead of the bare:
"localhost:46657"
This change is just to clean up such warnings as
they spuriously would spook users for a package "lite"
that claims to be secure.
> cmd/tendermint/commands/lite: add tcp scheme to address URLs

- cmd/priv_val_server/main.go
- types/priv_validator/socket.go
- types/priv_validator/socket_test.go
Follow-up to #1255 aligning with the expectation that the external signing process connects to the node. The SocketClient will block on start until one connection has been established, support for multiple signers connected simultaneously is a planned future extension.
* SocketClient accepts connection
* PrivValSocketServer renamed to RemoteSigner
* extend tests
> Invert privVal socket communication

- blockchain/pool.go
- blockchain/pool_test.go
- blockchain/reactor.go
- blockchain/store.go
- consensus/byzantine_test.go
- consensus/reactor.go
- consensus/state.go
- consensus/types/height_vote_set.go
- consensus/types/height_vote_set_test.go
- evidence/reactor.go
- mempool/reactor.go
- node/node.go
- p2p/peer.go
- p2p/pex/pex_reactor.go
- p2p/switch.go
- types/vote.go
> Using MarkGood and StopPeerForError

- cmd/tendermint/commands/testnet.go
- types/priv_validator.go
Closes https://github.com/tendermint/tendermint/issues/1290
Replaces https://github.com/tendermint/tendermint/pull/1303
> testnet cmd: ensure config dir exists. closes #1290

- blockchain/reactor.go
- consensus/reactor.go
- consensus/reactor_test.go
- p2p/dummy/peer.go
- p2p/peer.go
> consensus: fix tracking for MarkGood

- .gitignore
- docs/specification/rpc.rst
- node/node.go
- rpc/core/doc.go
- rpc/core/health.go
- rpc/core/pipe.go
- rpc/core/routes.go
- rpc/core/types/responses.go
- types/heartbeat.go
- types/validator.go
> Add `\health` rpc endpoint

- CHANGELOG.md
- rpc/client/httpclient.go
- rpc/client/interface.go
- rpc/client/localclient.go
- rpc/client/rpc_test.go
- rpc/core/health.go
> Follow up for /health endpoint

- types/block.go
- types/block_test.go
Fixes https://github.com/tendermint/tendermint/issues/1298
Fixes https://github.com/tendermint/tendermint/issues/1299
Found while writing tests in https://github.com/tendermint/tendermint/pull/1300
> types: Hash invoked for nil Data and Header should not panic

- docs/examples/getting-started.md
- docs/examples/install_tendermint.sh
> docs/examples: update quick start guide

- docs/specification/new-spec/reactors/pex/pex.md
- p2p/pex/pex_reactor.go
- p2p/pex/pex_reactor_test.go
> Exponential backoff follow up

- cmd/tendermint/commands/run_node.go
Changed to make line break easier to read
> Fix comment

- CHANGELOG.md
- rpc/client/rpc_test.go
- rpc/core/tx.go
- rpc/core/types/responses.go
> Tx search response should include tx hash

- cmd/tendermint/commands/lite.go
> Fixed listen address

- Gopkg.lock
- Gopkg.toml
- p2p/conn/connection.go
- p2p/conn/secret_connection.go
- p2p/conn/secret_connection_test.go
- p2p/peer.go
https://github.com/tendermint/tmlibs/pull/181
Fixes #1368
> [rpc] unsubscribe does not work

- rpc/lib/server/http_server.go
Needed for https://github.com/cosmos/cosmos-sdk/pull/601
> Add a method for creating an https server

- rpc/lib/server/http_server.go
Refs https://github.com/tendermint/tendermint/pull/1403
> HTTPS server follow up

- .gitignore
- docs/conf.py
- docs/index.rst
ref: https://github.com/tendermint/tools/pull/79
old:
new:
* [N/A] Wrote tests
* [N/A] Updated CHANGELOG.md
> docs: build updates

- CHANGELOG.md
- types/event_bus.go
- types/event_bus_test.go
> subscribe does not work for a custom tag

- docs/specification/new-spec/light-client.md
> Add light client spec

- consensus/reactor.go
https://github.com/tendermint/tendermint/issues/1372
> consensus: check for closed subscription channels and exit routine

- CHANGELOG.md
- consensus/state.go
- rpc/core/status.go
- rpc/core/types/responses.go
- types/validator_set.go
Refs #581 
```
{
"jsonrpc": "2.0",
"id": "",
"result": {
....
"latest_block_height": 1149,
"latest_block_time": "2018-03-29T11:35:43.112Z",
"syncing": false,
"validator_status": {
"voting_power": 10
}
}
}
```
> Include validator power in /status

- CHANGELOG.md
- p2p/pex/addrbook.go
- p2p/pex/addrbook_test.go
- p2p/pex/pex_reactor.go
> p2p seed mode follow up

- CHANGELOG.md
- p2p/listener.go
- p2p/netaddress.go
- p2p/netaddress_test.go
> p2p: require all addresses come with an ID no matter what

- CHANGELOG.md
- node/node.go
- p2p/node_info.go
- p2p/pex/addrbook.go
- p2p/pex/addrbook_test.go
- p2p/pex/pex_reactor.go
- p2p/pex/pex_reactor_test.go
- p2p/switch.go
- p2p/switch_test.go
> p2p: loopbacks should be detected and ignored instead of dialling self infinitely

- cmd/tendermint/commands/init.go
- cmd/tendermint/commands/testnet.go
- config/toml.go
* allow non-validators
* configurable prefix
* populating of persistent peers
> improve testnet cmd

- docs/specification/genesis.rst
> [docs/spec] update msg type and Tendermint behavior

- Gopkg.lock
- Gopkg.toml
- consensus/replay_file.go
- consensus/types/state.go
- docs/specification/new-spec/encoding.md
- types/genesis.go
- types/priv_validator/priv_validator.go
- types/validator_set.go
- use MarshalJSONIndent for genesis and priv val (closes #1506)
- always use two-spaces for indents in strings and JSONIndent
> JSON Indent and some docs

- consensus/types/height_vote_set.go
- consensus/types/wire.go
- node/node.go
- p2p/node_info.go
- rpc/core/status.go
- rpc/core/types/responses.go
- types/part_set.go
- types/vote_set.go
Fixes:
- https://github.com/tendermint/tendermint/issues/1481
- https://github.com/tendermint/tendermint/issues/1480
- https://github.com/tendermint/tendermint/issues/1310
- https://github.com/tendermint/tendermint/issues/1199 (?)
> Various RPC fixes

- cmd/tendermint/commands/init.go
> set GenesisTime to now during `tendermint init`

- Gopkg.lock
- Gopkg.toml
- consensus/reactor.go
- p2p/node_info.go
- rpc/client/interface.go
- rpc/client/rpc_test.go
- rpc/core/consensus.go
- rpc/core/types/responses.go
Also requires ASCII sanitized moniker & other NodeInfo fields.
> Expose peer stats for dump_consensus_state

- benchmarks/codec_test.go
- cmd/tendermint/commands/show_node_id.go
- cmd/tendermint/commands/show_validator.go
- consensus/reactor.go
- consensus/state.go
- consensus/types/round_state.go
- rpc/client/helpers_test.go
- types/block.go
- types/genesis_test.go
- types/vote_set.go
rebased version of https://github.com/tendermint/tendermint/pull/1475/files
Conflict was the json tags in consensus/types/round_state.go
> Fix validBlock rule

- Makefile
- Vagrantfile
- config/config.go
- mempool/mempool.go
- node/node.go
- state/execution.go
- state/txindex/indexer.go
- state/txindex/indexer_service.go
- state/txindex/kv/kv_test.go
https://gist.github.com/melekes/ed2da8bc9f7d0723a723e262c6722bc1
Refs https://github.com/tendermint/tools/issues/61
> Performance improvements

- docs/deploy-testnets.rst
- docs/terraform-and-ansible.rst
> document testnet command & other little doc fixes

- docs/conf.py
- docs/index.rst
- docs/install.rst
- docs/transactional-semantics.rst
#1580 and a few fixes
* [N/A] Updated all code comments where relevant
* [N/A] Wrote tests
* [N/A] Updated CHANGELOG.md
> docs improvements

- p2p/conn/connection.go
> nice output for msgBytes

- CHANGELOG.md
- rpc/client/httpclient.go
- rpc/client/interface.go
- rpc/client/localclient.go
- rpc/client/rpc_test.go
- rpc/core/README.md
- rpc/core/mempool.go
- rpc/core/pipe.go
- rpc/core/pipe_test.go
- rpc/core/routes.go
- rpc/core/tx.go
- rpc/core/types/responses.go
> limit /tx_search output

- DOCKER/README.md
- docs/spec/p2p/node.md
- docs/spec/p2p/peer.md
- p2p/README.md
> fix dead links & other doc updates

- blockchain/reactor_test.go
- consensus/byzantine_test.go
- p2p/dummy/peer.go
- p2p/errors.go
- p2p/peer.go
- p2p/peer_set.go
- p2p/peer_set_test.go
- p2p/peer_test.go
- p2p/pex/pex_reactor_test.go
- p2p/switch.go
- p2p/switch_test.go
- p2p/test_util.go
#1264 
TODO: fix and write tests
> p2p: prevent connections from same ip

- CHANGELOG.md
- consensus/wal.go
- p2p/peer.go
- p2p/pex/pex_reactor.go
- p2p/pex/pex_reactor_test.go
- p2p/switch.go
- p2p/switch_test.go
I was not able to reproduce #1600, but I did fix one possible panic and improved `SearchEndHeight` behaviour (see commit messages for details).
> [wal] small fixes in SearchEndHeight & replay logic

- CHANGELOG.md
- libs/pubsub/example_test.go
- libs/pubsub/pubsub.go
- libs/pubsub/pubsub_test.go
- libs/pubsub/query/empty_test.go
- libs/pubsub/query/query.go
- libs/pubsub/query/query_test.go
- state/state_test.go
- types/event_bus.go
- types/event_bus_test.go
> expect all tags to be strings

- docs/abci-cli.rst
ref: https://github.com/tendermint/abci/pull/249
> docs: update ABCI output

- docs/index.rst
- docs/indexing-transactions.rst
- docs/subscribing-to-events-via-websocket.rst
> [docs] indexing transactions and subscribing to events

- docs/spec/blockchain/encoding.md
see https://github.com/tendermint/go-crypto/pull/110 
we might update this according to https://github.com/tendermint/go-amino/pull/163
> WIP: simplify & update documentation, fix typo

- mempool/mempool.go
Looking into the reports from #1642, #1394, #1661 .
Running `tm-bench` against a local node will sometimes time out at the RPC level.
Seems occasionally it will also deadlock - the RPC becomes unresponsive when trying to get `/status` or `/consensus_state`.
Passing `SIGABRT` to the tendermint process (`killall -6 <pid>`) dumps the go-routines. Upon inspection, I found all my HTTP request routines blocked on getting the consensus state lock.
Also found consensus blocked trying to Reap from the mempool, and the mempool resCb blocked trying to send on txsAvailable.
Seems the send on txsAvailable could happen multiple times despite the boolean guard. Actually looks like that boolean may have been racy. We just saw a similar kind of thing in the blockchain reactor: …
> fix possible mempool deadlock

- mempool/mempool.go
> recheck only if there are txs left in the mempool

- rpc/core/pipe.go
- rpc/core/pipe_test.go
- rpc/core/tx.go
plus an additional check just in case
Closes #1688
> validate per_page before page

- Gopkg.lock
- Gopkg.toml
- consensus/wal.go
- p2p/pex/pex_reactor_test.go
Refs #1659
Refs tendermint/tmlibs#217
> Flush cs.wal on stop

- docs/install.rst
- scripts/install_tendermint.sh
shared a gist with @jolesbi that did what this script does for the SDK (in https://github.com/cosmos/cosmos-sdk/pull/1097), he had postive feedback; it works out of the box and installation is still an issue for folks (e.g., #1660)
> quick install script

- cmd/tendermint/commands/reset_priv_validator.go
This closes https://github.com/cosmos/cosmos-sdk/issues/1152, in order to make whats going on more clear in the CLI.
> alter unsafe reset all msg

- Gopkg.lock
- Gopkg.toml
- consensus/byzantine_test.go
- consensus/reactor_test.go
- consensus/replay.go
- consensus/replay_file.go
- consensus/replay_test.go
- consensus/wal_generator.go
- node/node.go
- state/execution.go
- state/execution_test.go
- state/state_test.go
- state/store.go
- state/validation.go
- state/validation_test.go
- types/evidence.go
- types/evidence_test.go
- types/protobuf.go
Update to the latest ABCI with new:
- PubKey
- RequestBeginBlock
- RequestInitChain
Still a couple TODOs left
> Update ABCI for new PubKey type and changes to BeginBlock and InitChain

- docs/running-in-production.md
> [docs] write about addr_book_strict in production notes

- CHANGELOG.md
- consensus/state_test.go
- rpc/client/httpclient.go
- rpc/client/localclient.go
- state/txindex/indexer.go
- state/txindex/null/null.go
- types/event_bus.go
- types/event_bus_test.go
Run 'gofmt -w .' from project root.
* [n/a] Updated all relevant documentation in docs
* [n/a] Updated all code comments where relevant
* [n/a] Wrote tests
> all: gofmt

- .github/CODEOWNERS
> add xla as codeowner

- CHANGELOG.md
- libs/pubsub/pubsub.go
- rpc/lib/server/handlers.go
- rpc/lib/server/handlers_test.go
- rpc/lib/types/types.go
- types/event_bus.go
Refs #1755 
**please do not squash commits upon merging**
> Memory leak in Websocket

- crypto/hkdfchacha20poly1305/hkdfchachapoly_test.go
> crypto/hkdfchachapoly: Add testing seal to the test vector

- .gitignore
- docs/abci-cli.md
- docs/abci-spec.md
- docs/app-architecture.md
- docs/app-development.md
- docs/conf.py
- docs/determinism.md
- docs/getting-started.md
- docs/how-to-read-logs.md
- docs/introduction.md
- docs/spec/software/abci.md
- docs/specification/block-structure.rst
- docs/specification/validators.rst
- docs/using-tendermint.md
> docs: update abci links

- rpc/core/status.go
- rpc/core/types/responses.go
> Rename sync_info.syncing to sync_info.catching_up

- networks/remote/README.md
> proper link to a docs module

- consensus/state.go
- mempool/mempool.go
- mempool/reactor.go
> Consensus halt fix & logging improvements

- CHANGELOG.md
- cmd/tendermint/commands/run_node.go
- config/config.go
- config/toml.go
- docs/specification/configuration.md
- node/node.go
- p2p/listener.go
- p2p/listener_test.go
- p2p/pex/pex_reactor_test.go
Change default option to enable upnp.
Closes #1806
> config: rename skip_upnp to upnp

- README.md
> Broken link to docs/terraform-and-ansible corrected

- node/node.go
- p2p/listener.go
Adding IPv6 support to the p2p layer.  Tested between two IPv6 nodes.
> Adding IPv6 support to peering

- .github/ISSUE_TEMPLATE
> Update ISSUE_TEMPLATE to mention using pastebin

- CONTRIBUTING.md
just a couple lil' guys - feel free to just push to this branch if something incorrect
> contributing guide typos

- p2p/peer_set.go
- p2p/pex/pex_reactor.go
Fixes #1830
remember that PeerSet#Get can return nil
> fix nil pointer panic by checking if peer is nil

- privval/priv_validator.go
> overwrite pubkey and address for convenience

- state/store.go
> fix wrong field access in LoadConsensusParams

- consensus/reactor.go
- consensus/state.go
> Properly shutdown consensus WAL

- state/execution.go
- state/execution_test.go
> state: err if 0 power validator is added to the validator set

- .gitignore
- docs/DOCS_README.md
> add docs/DOCS_README.md 

- rpc/lib/server/handlers.go
- rpc/lib/server/http_params.go
- rpc/lib/server/parse_test.go
@ebuchman has more context....
> WIP RPC HTTP does not require quotes around int64/int/uint64/uint types

- CHANGELOG.md
- docs/tendermint-core/running-in-production.md
> Add missing changelog entry

- abci/client/socket_client_test.go
Refs https://github.com/tendermint/tendermint/pull/1891#discussion_r201339918
> remove print statements

- consensus/reactor.go
Addresses https://github.com/tendermint/tendermint/issues/1839
> consensus: wait on stop if not fastsync

- libs/pubsub/pubsub.go
- node/node.go
- node/node_test.go
- types/event_bus.go
> fix stopping pubsub

- Makefile
> makefile: fix protoc_libs

- p2p/node_info.go
> Version check: delete redundant code

- blockchain/reactor_test.go
- p2p/dummy/peer.go
- p2p/peer.go
- p2p/pex/pex_reactor_test.go
- p2p/switch.go
> preserve original address and dial it instead of self-reported address

- blockchain/pool_test.go
- blockchain/store_test.go
- consensus/types/round_state_test.go
- lite/proxy/block.go
- lite/proxy/validate_test.go
- rpc/core/blocks.go
- state/execution.go
- state/state_test.go
- tools/tm-monitor/monitor/node.go
- tools/tm-monitor/monitor/node_test.go
- types/block.go
- types/block_meta.go
- types/events.go
make BlockMeta Header a non-pointer
Refs #693
This is "Ensure all funcs in types pkg are well guarded (Part 2)". First PR is [here](https://github.com/tendermint/tendermint/pull/1936)
> make Block Header and Data non-pointers

- crypto/armor/armor.go
- crypto/armor/armor_test.go
- crypto/encoding/amino/amino.go
- crypto/encoding/amino/encode_test.go
- crypto/xsalsa20symmetric/symmetric.go
- crypto/xsalsa20symmetric/symmetric_test.go
My bad. I totally forgot this is something you have to do when refactoring. (I think its because this code wasn't used anywhere in tendermint) If possible, can we merge this in for next release?
> crypto: Fix package imports from the refactor

- node/node.go
- rpc/test/helpers.go
also, make running Prometheus server optional.
Closes #2019
* ~~[ ] Wrote tests~~
* ~~[ ] Updated CHANGELOG.md~~
> do not overwrite metrics provider in node#NewNode

- CHANGELOG.md
- CHANGELOG_PENDING.md
- privval/socket.go
before: 1.000000003s
after: 3.000000000s
Refs #2027
> fix acceptDeadline

- .github/PULL_REQUEST_TEMPLATE.md
> github: update PR template to indicate changing pending changelog.

- .gitignore
- Makefile
- rpc/core/README.md
- rpc/core/slate_header.txt
> rpc: improve slate for Jenkins

- libs/common/bit_array.go
> libs: update BitArray go docs

- blockchain/reactor.go
- consensus/reactor.go
- evidence/reactor.go
- p2p/pex/pex_reactor.go
> Removed unnecessary onStart call

- README.md
The paper is such a useful resource to anyone building on Tendermint. It should be linked in the ReadMe.
> Link to "The latest gossip on BFT consensus"

- docs/spec/blockchain/blockchain.md
- docs/spec/blockchain/state.md
> Modify blockchain spec to reflect validator set changes

- abci/README.md
> abci: Update readme for building protoc

- docs/architecture/adr-015-crypto-encoding.md
> [ADR] Encoding for cryptography at launch

- CHANGELOG_PENDING.md
- consensus/state.go
- libs/autofile/autofile.go
- libs/autofile/group.go
- libs/autofile/group_test.go
- libs/autofile/sighup_watcher.go
- p2p/pex/addrbook.go
> consensus: non-responsive to CTRL-C if consensus state panics

- docs/architecture/adr-013-symmetric-crypto.md
- docs/architecture/adr-015-symmetric-crypto.md
Ref #2023, makes a way to do #1955
> [ADR] Proposal for encoding symmetric cryptography

- CHANGELOG.md
- CHANGELOG_PENDING.md
- Makefile
- abci/example/example_test.go
- consensus/types/round_state_test.go
- crypto/README.md
- crypto/crypto.go
- crypto/ed25519/ed25519.go
- crypto/ed25519/ed25519_test.go
- crypto/encoding/amino/amino.go
- crypto/encoding/amino/encode_test.go
- crypto/secp256k1/secp256k1.go
- crypto/secp256k1/secpk256k1_test.go
- node/id.go
- p2p/conn/secret_connection.go
- p2p/pex/pex_reactor.go
- privval/priv_validator.go
- privval/priv_validator_test.go
- types/heartbeat.go
- types/heartbeat_test.go
- types/proposal.go
- types/proposal_test.go
- types/protobuf_test.go
- types/vote.go
- types/vote_set.go
- version/version.go
Merge the release/v0.23.0 branch back to develop
> Bucky/merge 0.23.0 to develop

- abci/example/example_test.go
- libs/clist/clist_test.go
- p2p/conn/connection_test.go
Remove some slowness from tests. Ref https://github.com/tendermint/tendermint/issues/2038
> speed up some tests. ref #2038

- .github/CODEOWNERS
i don't need to be on the codeowners file for this repo - the docs are in good hands @zramsay.
> remove JB from codeowners file

- crypto/multisig/compact_bit_array.go
- crypto/multisig/compact_bit_array_test.go
This is in a separate PR from the rest of the multisig code for ease of review.
> crypto: Add compact bit array for intended usage in the multisig

- blockchain/reactor.go
> blockchain: fix register concrete name.

- .gitignore
- abci/types/application.go
- types/genesis.go
- types/genesis_test.go
* [X ] Updated all code comments where relevant
Here is a fix for issue #2015 
Note: for testing this issue I used my local testnet with 4 nodes. you can find out a copy of it here: https://github.com/b00f/tm-testnet
I manually changed the genesis file in new node and removed all validators. Then I updated the BaseApplication (InitChain phase) for updating the state. It worked properly.
> Issue 2015

- Gopkg.lock
- docs/app-dev/subscribing-to-events-via-websocket.md
- state/execution.go
- state/execution_test.go
- types/event_bus.go
- types/event_bus_test.go
- types/events.go
- types/nop_event_bus.go
Refs #1916
**REBASE AGAINST DEVELOP ONCE #2159 MERGED**
> send ValidatorSetUpdates event when validator set changes

- CHANGELOG_PENDING.md
- config/config.go
- config/toml.go
- docs/spec/reactors/pex/pex.md
- docs/tendermint-core/configuration.md
- p2p/pex/pex_reactor.go
- p2p/switch.go
> [p2p/pex] connect to more than 10 peers

- CHANGELOG_PENDING.md
- consensus/types/round_state_test.go
- crypto/ed25519/ed25519.go
- crypto/multisig/compact_bit_array_test.go
- crypto/multisig/wire.go
- crypto/secp256k1/secp256k1.go
*REBASE ONTO DEVELOP ONCE #2164 IS MERGED*
> crypto: Remove unnecessary prefixes from amino route variable names

- abci/cmd/abci-cli/abci-cli.go
> // TODO: Print out all the sub-commands available

- docs/tendermint-core/using-tendermint.md
> Fix addressbook_strict typo

- docs/introduction/introduction.md
> docs: fix image links

- libs/common/math.go
Remove all unused functions in common/math.go,
the only used functions are:` MaxInt`, `MaxInt64`, `MinInt`, `MinInt64`
requested in #2273.
> Reduce code in common/math

- CHANGELOG_PENDING.md
- config/toml.go
- docs/tendermint-core/configuration.md
Issue reported downstream: cosmos/cosmos-sdk#1712
> Replace db_path with db_dir in default configuration

- docs/config.js
ref: https://github.com/cosmos/cosmos-sdk/pull/2161
> HOTFIX make docs automated again

- CHANGELOG.md
- libs/autofile/autofile.go
- libs/autofile/group.go
- version/version.go
Merge master back to develop
* libs/autofile: bring back loops
* changelog, version
> libs/autofile: bring back loops (#2261)

- config/config.go
- config/toml.go
- docs/spec/README.md
- docs/spec/blockchain/blockchain.md
- docs/spec/blockchain/encoding.md
- docs/spec/blockchain/state.md
- docs/spec/reactors/block_sync/impl.md
- docs/tendermint-core/configuration.md
- docs/tendermint-core/running-in-production.md
- docs/tendermint-core/secure-p2p.md
- addresses a few points in #2143
- removes most TODO's from spec for better readability. documented in #1152 #1749 #2329
> Several minor docs & spec cleanup

- docs/config.js
The CI for the website is failing because this file doesn't exist (yet) on master in this repo. It's required as part of the build pipeline
> fix failing website build

- config/config.go
- config/toml.go
- docs/app-dev/indexing-transactions.md
- docs/tendermint-core/configuration.md
- rpc/client/rpc_test.go
- rpc/test/helpers.go
Follow up on https://github.com/tendermint/tendermint/pull/2324
> Update indexing docs & write a test cast

- config/config.go
- config/toml.go
> Add priv_validator_laddr to config.toml

- CHANGELOG_PENDING.md
- p2p/pex/pex_reactor.go
- p2p/switch.go
> ignore existing peers in DialPeersAsync

- CHANGELOG_PENDING.md
- abci/README.md
- docs/app-dev/ecosystem.json
- docs/spec/blockchain/blockchain.md
- docs/tendermint-core/using-tendermint.md
Explicitly mention external contributors!
> name drop external contribs in changelog

- scripts/linkify_changelog.py
> add script to add links in changelog

- .gitignore
- docs/DOCS_README.md
- docs/app-dev/getting-started.md
- docs/networks/deploy-testnets.md
- docs/research/transactional-semantics.md
- docs/spec/blockchain/encoding.md
- docs/spec/consensus/consensus.md
- docs/tendermint-core/how-to-read-logs.md
- docs/tendermint-core/light-client-protocol.md
- docs/tendermint-core/using-tendermint.md
- docs/tendermint-core/validators.md
> fix docs error links

- docs/spec/abci/abci.md
- docs/spec/abci/apps.md
https://github.com/tendermint/tendermint/issues/1179
> docs/spec/abci: improve docs on AppHash

- libs/common/service.go
- rpc/lib/client/ws_client.go
also, return ErrNotStarted when trying to stop a not-running service
> [common] revert started flag when service already stopped

- tools/tm-bench/main.go
- tools/tm-bench/transacter_test.go
> tools/tmbench: Bounds checking for txSize.

- libs/autofile/autofile.go
- libs/autofile/autofile_test.go
- libs/db/fsdb.go
- libs/errors/errors.go
> Enforce file permissions

- CHANGELOG_PENDING.md
- benchmarks/codec_test.go
- docs/spec/p2p/peer.md
- node/node.go
- p2p/node_info.go
- p2p/test_util.go
- rpc/core/status.go
- rpc/core/types/responses.go
- rpc/core/types/responses_test.go
> [rpc] transform /status result.node_info.other into map

- CHANGELOG_PENDING.md
- cmd/tendermint/commands/init.go
- cmd/tendermint/commands/testnet.go
- state/execution_test.go
- types/genesis.go
- types/genesis_test.go
> [types] add Address to GenesisValidator

- docs/app-dev/indexing-transactions.md
Fix inconsistent documents and code
> minor note in indexing-transactions.md (#2443)

- node/node.go
- p2p/node_info.go
- remove second AminoVersion from
https://github.com/tendermint/tendermint/pull/2426/files#diff-f2fefc7a06ea0d1e0a910196901e50aaR86
Refs #2433
> add missing RPCAddress to NodeInfoOther.String() func

- CHANGELOG_PENDING.md
- libs/db/db.go
https://github.com/tendermint/tendermint/pull/2411 follow-up
> add missing changelog entry and comment

- Makefile
- docs/introduction/install.md
- docs/spec/abci/abci.md
- docs/spec/abci/apps.md
- docs/tendermint-core/running-in-production.md
- mempool/mempool.go
Improve documentation, including what's noted in https://github.com/tendermint/tendermint/pull/2467#issuecomment-423682294 and various issues.
> Update abci/app docs

- rpc/core/abci.go
- rpc/core/blocks.go
- rpc/core/consensus.go
- rpc/core/doc.go
- rpc/core/mempool.go
- rpc/core/net.go
- rpc/core/tx.go
- rpc/lib/doc.go
> rpc: doc updates

- CHANGELOG_PENDING.md
- cmd/tendermint/commands/root.go
- config/config.go
- config/config_test.go
- config/toml.go
- consensus/mempool_test.go
- consensus/reactor.go
- consensus/state.go
- consensus/state_test.go
- docs/tendermint-core/configuration.md
**DO NOT SQUASH BEFORE MERGING**
> config: Add ValidateBasic

- docs/DOCS_README.md
- docs/README.md
goes with https://github.com/tendermint/tendermint.com/pull/239
> docs: Add version

- CHANGELOG_PENDING.md
- README.md
- config/config.go
- crypto/merkle/proof.go
- crypto/merkle/proof_key_path.go
- crypto/merkle/proof_simple_value.go
- libs/common/types.pb.go
- lite/doc.go
- lite/dynamic_verifier.go
Addresses some of https://github.com/tendermint/tendermint/issues/2509
> General Merkle Follow Up

- types/block_test.go
> Make block_test.go more table driven

- CHANGELOG_PENDING.md
- evidence/store.go
> fix evidence db iter leak

- rpc/core/routes.go
- types/block_test.go
> [rpc] fix /abci_query: trusted was renamed to prove

- docs/architecture/adr-025-commit.md
> [ADR][DRAFT] 025: Commit Simplifications

- libs/autofile/group.go
There's a time window after we call RotateFile() where autofile#index+1 does
not exist. It will be created during the next call to Write(). BUT if
somebody calls NewReader(...) before Write(), it will fail with "open
/tmp/walXXXXXXXXX/wal: no such file or directory"
We must create file (either by calling gr.Head.openFile() or directly)
during NewReader() to ensure read calls succeed.
Closes #2538
> [libs/autofile] fix DATA RACE by removing openFile() call

- docs/architecture/adr-024-sign-bytes.md
- docs/architecture/adr-02x-sign-bytes.md
Work in progress: Quick fledged draft summarizing https://github.com/tendermint/tendermint/issues/1622
If time allows, please review for overall sanity (not typos/nitpicks):
https://github.com/tendermint/tendermint/blob/5d46a2d49dba4da726463ba43058c6b230e3d24a/docs/architecture/adr-02x-sign-bytes.md
> [ADR][DRAFT] 024: SignBytes and validator types in privval

- docs/architecture/adr-030-consensus-refactor.md
> [ADR][DRAFT] 030: Consensus refactor

- docs/.vuepress/config.js
- docs/spec/abci/README.md
> add spec/abci/readme to sidebar

- docs/architecture/adr-026-general-merkle-proof.md
> ADR-026 General Merkle Proof

- CHANGELOG_PENDING.md
- p2p/switch.go
> fix p2p switch FlushThrottle value

- .circleci/config.yml
- Makefile
- test/p2p/circleci.sh
closes #2554 
then clicking on `messages` leads to:
https://27748-19799491-gh.circle-artifacts.com/0/home/circleci/project/test/p2p/logs/messages
> circle: save p2p logs as artifacts

- config/config.go
- tools/tm-bench/main.go
also specify time unit for FlushThrottleTimeout in TestP2PConfig
> tools: Refactor tm-bench

- CHANGELOG_PENDING.md
- crypto/random.go
- crypto/random_test.go
Ref #2099, does not close the issue. There are more points there that should be addressed.
> crypto/random: Use chacha20, add forward secrecy

- consensus/reactor_test.go
- consensus/types/wire.go
- evidence/pool_test.go
- evidence/reactor_test.go
- types/block_test.go
- types/evidence.go
- types/wire.go
> separate mock evidence from real evidence

- libs/db/common_test.go
Fixes: https://github.com/tendermint/tendermint/issues/2573
> test(db): fix #2573

- crypto/encoding/amino/amino.go
- crypto/encoding/amino/encode_test.go
This is intended for use in a future PR for #2414
> crypto: Add a way to go from pubkey to route

- tools/tm-bench/Dockerfile
- tools/tm-bench/Makefile
- tools/tm-bench/README.md
- tools/tm-monitor/Dockerfile
- tools/tm-monitor/Makefile
- tools/tm-monitor/README.md
> tools: update docs & fix build-docker Makefile target

- crypto/encoding/amino/amino.go
- crypto/encoding/amino/encode_test.go
ref: https://github.com/tendermint/tendermint/pull/2574#discussion_r223777650
This method will probably be removed once we have an upstream amino update for this. (Perhaps postlaunch though)
> crypto/amino: Address anton's comment on PubkeyAminoRoute

- consensus/metrics.go
- consensus/reactor.go
- docs/tendermint-core/metrics.md
- mempool/mempool.go
- mempool/metrics.go
- node/node.go
- p2p/metrics.go
- state/execution.go
- state/metrics.go
Continues addressing https://github.com/cosmos/cosmos-sdk/issues/2169.
> Add additional metrics

- CHANGELOG_PENDING.md
Refs https://github.com/tendermint/tendermint/pull/2506#issuecomment-428458974
> fix contributor's name in CHANGELOG_PENDING

- docs/networks/deploy-testnets.md
[X] Updated all relevant documentation in docs
[N/A] Updated all code comments where relevant
[N/A] Wrote tests
[N/A] Updated CHANGELOG_PENDING.md
> Minor doc fix regarding testnet on non-linux OS

- CHANGELOG_PENDING.md
- cmd/tendermint/commands/lite.go
- config/toml.go
- consensus/state_test.go
- docs/spec/blockchain/blockchain.md
- p2p/netaddress.go
- state/state.go
- state/validation.go
- state/validation_test.go
- types/block.go
- types/block_test.go
> state: require block.Time of the fist block to be genesis time

- crypto/ed25519/ed25519.go
> Comment about ed25519 private key format on Sign

- consensus/replay.go
> set next validators along with validators while replay

- consensus/common_test.go
- consensus/reactor.go
- consensus/state.go
- consensus/state_test.go
- p2p/metrics.go
- types/evidence_test.go
Fix https://github.com/tendermint/tendermint/issues/2529 and https://github.com/tendermint/tendermint/issues/2625.
> Align propose phase with spec

- types/block.go
> [R4R] Standardize header.Hash() for Merklizing

- docs/spec/blockchain/blockchain.md
- types/params.go
- types/params_test.go
> [R4R] Unmerklize ConsensusParams.Hash()

- libs/pubsub/pubsub.go
Refs https://github.com/tendermint/tendermint/issues/1811#issuecomment-427825250
> [pubsub] document design shortcomings

- scripts/install/install_tendermint_ubuntu.sh
Install script changes for installing in ubuntu. See #2372
>  Ubuntu bash installation root permission requirement.

- consensus/state_test.go
- scripts/install/install_tendermint_bsd.sh
- scripts/install/install_tendermint_ubuntu.sh
- upgrading OS is out of scope of installation scripts
> install scripts: update go version, remove upgrade cmd

- docs/app-dev/ecosystem.json
It utilises async IO -> greater performance.
> docs/ecosystem: add tm-abci python ABCI server (fork of py-abci)

- docs/architecture/adr-016-protocol-versions.md
Ref https://github.com/tendermint/tendermint/issues/2468
> adr-016: update int64->uint64; add version to ConsensusParams

- docs/spec/blockchain/encoding.md
- types/canonical.go
- types/vote_test.go
> types: remove Version from CanonicalXxx

- crypto/random.go
> crypto: use stdlib crypto/rand. ref #2099

- CHANGELOG_PENDING.md
- README.md
> update changelog pending and readme

- Gopkg.lock
- Gopkg.toml
- consensus/state.go
- libs/fail/fail.go
- state/execution.go
> one less dependency

- Gopkg.lock
- docs/spec/blockchain/blockchain.md
- types/proposal.go
- types/proposal_test.go
- types/vote.go
- types/vote_test.go
> Align Vote/Proposal fields with canonical order and fields

- consensus/reactor.go
- docs/spec/reactors/consensus/consensus-reactor.md
- docs/spec/reactors/consensus/consensus.md
> 2646 fix spec

- blockchain/reactor.go
- consensus/reactor.go
- consensus/types/round_state.go
- types/block.go
- types/block_test.go
- types/proposal.go
- types/validation.go
- types/vote.go
Just addressing my own ongoing review of #2711. Still going through it.
> some ValidateBasic updates

- evidence/reactor_test.go
- types/evidence_test.go
- types/heartbeat_test.go
- types/part_set_test.go
- types/proposal_test.go
- types/vote_test.go
> Add tests for ValidateBasic methods

- CHANGELOG_PENDING.md
- consensus/wal.go
- libs/autofile/autofile.go
- libs/autofile/autofile_test.go
- libs/autofile/group.go
> libs/autofile/group: don't panic when checking Head size

- .circleci/config.yml
- Makefile
- scripts/install/install_tendermint_arm.sh
> arm: add install script, fix Makefile

- docs/tendermint-core/using-tendermint.md
- types/genesis.go
> docs: update genesis info

- docs/app-dev/ecosystem.json
- docs/app-dev/ecosystem.md
> cleanup ecosystem

- CHANGELOG_PENDING.md
- Gopkg.lock
- Gopkg.toml
- config/config.go
- config/config_test.go
- config/toml.go
- node/node.go
- rpc/client/rpc_test.go
- rpc/core/doc.go
- rpc/lib/server/http_server.go
- rpc/test/helpers.go
ref https://github.com/tendermint/tendermint/issues/2582
> 2582 Enable CORS on RPC API 

- state/store.go
Signed-off-by: Zeyu Zhu <zhuzeyu0409@gmail.com>
> Optimize: using parameters in func

- CHANGELOG_PENDING.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- SECURITY.md
Still need to fix up the CONTRIBUTING.md a bit more (add notes on how changelog should look)
> update some top-level markdown files

- CHANGELOG.md
- CHANGELOG_PENDING.md
- version/version.go
> changelog, versionbump

- docs/README.md
solution to mysterious bug that truncates the filename after the `_`
> use a github link

- CHANGELOG_PENDING.md
- cmd/tendermint/commands/init.go
- cmd/tendermint/commands/root.go
- config/config.go
- config/toml.go
- docs/tendermint-core/configuration.md
> Config option for JSON output formatter

- abci/client/grpc_client.go
- abci/client/socket_client.go
> More verbose error log

- CHANGELOG_PENDING.md
- node/node.go
- p2p/peer.go
- p2p/switch.go
- p2p/test_util.go
- p2p/transport.go
- p2p/transport_test.go
Fix https://github.com/tendermint/tendermint/issues/2842
Also removes some unused config fields.
> p2p: NewMultiplexTransport takes an MConnConfig

- CHANGELOG_PENDING.md
- config/toml.go
- docs/tendermint-core/configuration.md
> #2877 include BlockTimeIota should be included in default config toml

- CHANGELOG_PENDING.md
- state/state.go
- state/state_test.go
- state/store.go
- types/validator_set.go
- types/validator_set_test.go
This isn't a big deal, but good to fix nevertheless.
* [n/a] Updated all relevant documentation in docs
> RPC validators calls IncrementAccum if necessary

- CHANGELOG_PENDING.md
- docs/architecture/adr-008-priv-validator.md
- node/node.go
- node/node_test.go
Ref #2827 
(I have since seen #2847 which is a fix for the same issue; this PR has tests and docs too ;) )
> allow IPCVal to be instantiated from config

- CHANGELOG_PENDING.md
- libs/cli/flags/log_level_test.go
- libs/log/filter.go
Fixes #2868 where module=main setting overrides all others
> return back initially allowed level if we encounter allowed key

- CHANGELOG_PENDING.md
- state/txindex/kv/kv.go
- state/txindex/kv/kv_test.go
> don't return false positives when searching for a prefix of a tag value

- CHANGELOG.md
- CHANGELOG_PENDING.md
- version/version.go
> Prepare v0.26.4 changelog

- state/execution.go
- state/execution_test.go
- state/state_test.go
> Refactor updateState #2865

- docs/app-dev/getting-started.md
- closes #2931, also required https://github.com/tendermint/js-abci/pull/25
> docs: fix js-abci example

- rpc/core/abci.go
- rpc/core/blocks.go
- rpc/core/consensus.go
- rpc/core/events.go
- rpc/core/health.go
- rpc/core/mempool.go
- rpc/core/net.go
- rpc/core/status.go
- rpc/core/tx.go
follow-up on https://github.com/tendermint/tendermint/pull/2936
> docs: add client#Start/Stop to examples in RPC docs

- CHANGELOG.md
- CHANGELOG_PENDING.md
- UPGRADING.md
> update changelog and upgrading

- docs/app-dev/ecosystem.json
- docs/spec/README.md
> docs links fix

- cmd/tendermint/commands/testnet.go
previously, we're turning it off only if `--populate-persistent-peers`
flag was used, which is obviously incorrect.
Fixes https://github.com/cosmos/cosmos-sdk/issues/2983
> tendermint testnet: always turn off strict routability

- libs/log/testing_logger.go
I'm making this PR for @jackzampolin, since he doesn't have TM branching perms.
> Make testing logger that doesn't write to stdout

- CHANGELOG_PENDING.md
- rpc/client/httpclient.go
- rpc/client/interface.go
- rpc/client/localclient.go
- rpc/client/rpc_test.go
> Add missing endpoints to HTTPClient and LocalClient

- docs/.vuepress/config.js
Woot Woot https://github.com/tendermint/devops/issues/117
it's only a search API so it's not a secret (approved by Jessy). Fixed the "Last Updated" feature which uses git and refers to each individual file
> full-text docs search

- CHANGELOG_PENDING.md
- mempool/mempool.go
> Fix overflow issue when summing mempool gas wanteds

- .circleci/config.yml
- CHANGELOG_PENDING.md
> New CircleCI job

- docs/.vuepress/config.js
- adds "Edit on GH" link to all files, at bottom of each file
- adds GH link to top right of docs navbar
> improve docs configuration

- Makefile
- docs/networks/docker-compose.md
> docs: networks/docker-compose: small fixes

- CHANGELOG_PENDING.md
- abci/cmd/abci-cli/abci-cli.go
- cmd/tendermint/commands/run_node.go
- docs/tendermint-core/using-tendermint.md
- proxy/client.go
> fix docs / proxy app

- docs/.vuepress/config.js
> add rpc link to docs navbar and re-org sidebar

- .circleci/config.yml
> security update, image is finally availble

- consensus/state.go
Suggested fix for https://github.com/tendermint/tendermint/issues/3038
> 3038 prettify logging on ignored Votes

- CHANGELOG_PENDING.md
- crypto/ed25519/ed25519.go
- crypto/encoding/amino/amino.go
- crypto/encoding/amino/encode_test.go
- crypto/multisig/threshold_pubkey.go
- crypto/multisig/threshold_pubkey_test.go
- crypto/multisig/wire.go
- crypto/secp256k1/secp256k1.go
- types/params.go
- types/protobuf.go
> Don't use pointer receivers for PubKeyMultisigThreshold

- p2p/README.md
* [N/A] Updated all code comments where relevant
* [N/A ] Wrote tests
* [N/A] Updated CHANGELOG_PENDING.md
> docs: fix p2p readme links

- docs/architecture/adr-030-consensus-refactor.md
- libs/common/errors_test.go
- types/evidence_test.go
> [WIP] Fill in consensus core details in ADR 030

- state/state_test.go
> More ProposerPriority tests 

- cmd/priv_val_server/main.go
- node/node.go
- privval/client.go
Thanks @melekes for review in https://github.com/tendermint/tendermint/pull/2923#pullrequestreview-192065694
> fixes from review

- docs/app-dev/app-architecture.md
> Updated the reference link for Tendermint RPC Docs

- CHANGELOG.md
> fix changelog fmt

- crypto/merkle/simple_tree.go
> Add comment to simple_merkle get_split_point

- docs/networks/docker-compose.md
> Url link not found

- docs/app-dev/indexing-transactions.md
> docs: fix RPC links

- CHANGELOG_PENDING.md
- Gopkg.lock
- Gopkg.toml
Fix https://github.com/tendermint/tendermint/issues/3130
> update btcd fork for v0.1.1

- CHANGELOG_PENDING.md
- lite/base_verifier.go
- lite/commit.go
- lite/dbprovider.go
- lite/doc.go
- lite/dynamic_verifier.go
- lite/dynamic_verifier_test.go
- lite/errors/errors.go
- lite/multiprovider.go
- lite/provider.go
- types/block.go
- types/validator_set.go
Fixes https://github.com/tendermint/tendermint/issues/2862
> fix DynamicVerifier for large validator set changes

- CHANGELOG.md
- CHANGELOG_PENDING.md
- UPGRADING.md
- docs/spec/abci/apps.md
- version/version.go
> Prepare v0.29.0

- CHANGELOG.md
- types/validator_set.go
> fix changelog indent

- .circleci/config.yml
- CHANGELOG_PENDING.md
- p2p/conn_set.go
- p2p/dummy/peer.go
- p2p/peer.go
- p2p/peer_set_test.go
- p2p/peer_test.go
- p2p/pex/pex_reactor_test.go
- p2p/switch.go
- p2p/switch_test.go
- p2p/test_util.go
- p2p/transport.go
> p2p: file descriptor leaks

- lite/doc.go
I removed the Markdown parts and replaced them with godoc equivalents if possible. 
This was done for issue #3180
> Updated Doc for issue #3180

- CHANGELOG_PENDING.md
- p2p/pex/pex_reactor.go
> only log "Reached max attempts to dial" once

- consensus/state.go
- consensus/state_test.go
- consensus/types/round_state.go
> fix halting issue

- docs/architecture/adr-033-pubsub.md
Couldn't resist to edit this while reading through it. Feel free to close if deemed unnecessary or parts will be re-written etc.
> Some minor improvements while reading through adr 33:

- PHILOSOPHY.md
These are the core values that should determine what PRs are merged, and how we think about design choices.
> add design philosophy doc

- privval/socket_test.go
> refactor TestListenerConnectDeadlines to avoid data races

- docs/.vuepress/config.js
> fix docs navbar rpc link

- mempool/mempool.go
> fix log issue in recheck callback

- libs/pubsub/pubsub.go
- libs/pubsub/pubsub_test.go
in https://github.com/tendermint/tendermint/pull/3209
> pubsub: fixes after Ethan's review

- libs/common/net.go
- p2p/test_util.go
- rpc/test/helpers.go
> cmn: GetFreePort

- p2p/pex/addrbook_test.go
Fixes https://circleci.com/gh/tendermint/tendermint/44901
> addrbook_test: preallocate memory for bookSizes

- CHANGELOG.md
- README.md
- crypto/random.go
- crypto/xsalsa20symmetric/symmetric.go
- crypto/xsalsa20symmetric/symmetric_test.go
Ref #2099 and security audits. This was unused and just wasted reviewer time.
> remove MixEntropy

- crypto/secp256k1/secp256k1_nocgo.go
minor change that addresses: https://github.com/tendermint/tendermint/pull/3234#discussion_r254977954
> secp256k1: use btcec exposed N 

- CHANGELOG.md
- CHANGELOG_PENDING.md
- UPGRADING.md
- version/version.go
> Prepare v0.30.0

- state/state_test.go
> fix failure in TestProposerFrequency

- .golangci.yml
- abci/client/grpc_client.go
- abci/cmd/abci-cli/abci-cli.go
- blockchain/reactor.go
- cmd/tendermint/commands/run_node.go
- consensus/common_test.go
- consensus/reactor.go
- consensus/replay.go
- consensus/replay_file.go
- consensus/state.go
- consensus/types/height_vote_set_test.go
- crypto/encoding/amino/encode_test.go
- crypto/secp256k1/secp256k1_nocgo.go
- libs/common/bit_array.go
- p2p/conn/secret_connection_test.go
- privval/file.go
- privval/server.go
- rpc/client/mock/abci.go
- rpc/client/rpc_test.go
- rpc/core/abci.go
- rpc/core/blocks.go
- rpc/core/consensus.go
- rpc/core/events.go
- rpc/core/mempool.go
- rpc/core/net.go
- state/execution.go
- tools/tm-monitor/monitor/node.go
> make govet linter pass

- docs/spec/abci/apps.md
- types/validator_set_test.go
Minor follow up to #3222.
It's actually already very well tested! I just separated out some of the error cases into independent tests to make it easier to add more and modify. Pretty minor. Everything is passing :)
> types: validator set update tests

- CHANGELOG.md
- CHANGELOG_PENDING.md
- consensus/wal.go
Should fix #3295 
Also partial fix of #3043
> consensus: flush wal on stop

- CHANGELOG_PENDING.md
- cmd/tendermint/commands/show_node_id.go
- cmd/tendermint/commands/show_validator.go
> Return an error on `show_validator`

- types/vote_test.go
Resolves #3311
ref: #2455  #2508
> Fix signBytes test vectors

- CHANGELOG_PENDING.md
- consensus/common_test.go
- consensus/state.go
- consensus/state_test.go
- profile.out
Fixes https://github.com/tendermint/tendermint/issues/3302.
> reset triggered timeout precommit

- rpc/core/tx.go
> Fix rpc Tx() docs

- consensus/wal.go
Follow-up to https://github.com/tendermint/tendermint/pull/3300
> cs: update wal comments

- CHANGELOG_PENDING.md
- abci/cmd/abci-cli/abci-cli.go
- cmd/priv_val_server/main.go
- cmd/tendermint/commands/lite.go
- cmd/tendermint/commands/run_node.go
- docs/app-dev/abci-cli.md
- libs/autofile/cmd/logjack.go
- libs/common/os.go
- libs/common/os_test.go
- rpc/lib/test/main.go
- tools/tm-bench/main.go
- tools/tm-monitor/main.go
> Unclean shutdown on SIGINT / SIGTERM

- p2p/conn/secret_connection.go
Just a minor followup on the review if #3347: Fixes a comment. https://github.com/tendermint/tendermint/pull/3347#discussion_r259582330
> Folloup on review/3347

- CHANGELOG_PENDING.md
- libs/db/c_level_db.go
- libs/db/c_level_db_test.go
Fixes: https://github.com/tendermint/tendermint/issues/3378
> Add cleveldb.Stats()

- .circleci/config.yml
- Makefile
- README.md
- Vagrantfile
- networks/remote/integration.sh
- scripts/install/install_tendermint_arm.sh
- scripts/install/install_tendermint_bsd.sh
- scripts/install/install_tendermint_ubuntu.sh
- tools/build/Makefile
- update docker image on circleci
- remove GOCACHE=off from Makefile (see: https://tip.golang.org/doc/go1.12#gocache)
> Update to golang/1.12.0

- .golangci.yml
- Makefile
- libs/db/db_test.go
- rpc/client/event_test.go
> make dupl linter pass

- docs/spec/blockchain/encoding.md
PR just to fix one word in the doc.
> Fix the reverse of meaning in spec doc

- Gopkg.lock
Update Gopkg.lock via `dep ensure --update golang.org/x/crypto`
see https://github.com/tendermint/tendermint/issues/3391#issuecomment-470630079 (nothing to review here really).
> dep ensure --update golang.org/x/crypto

- .circleci/config.yml
- CHANGELOG_PENDING.md
Closes https://github.com/tendermint/devops/issues/198
Successful test [here](https://circleci.com/gh/tendermint/tendermint/49493)
> R4R: Removed complexity from docs deployment job 

- CHANGELOG_PENDING.md
- p2p/switch.go
- p2p/switch_test.go
- p2p/transport.go
> p2p: do not panic when filter times out

- scripts/install/install_tendermint_arm.sh
- scripts/install/install_tendermint_bsd.sh
- scripts/install/install_tendermint_ubuntu.sh
there is no such file https://storage.googleapis.com/golang/go1.12.0.linux-amd64.tar.gz
Fixes #3405
> fix GO_VERSION in installation scripts

- CHANGELOG_PENDING.md
- libs/db/remotedb/grpcdb/server.go
Fixes #3402
Maybe in the future. Code is unused right now.
> grpcdb: close Iterator/ReverseIterator after use

- CHANGELOG.md
- UPGRADING.md
- version/version.go
> Minor changes / fixes to release 0.31.0

- CHANGELOG.md
Address review comments:
https://github.com/tendermint/tendermint/pull/3417#discussion_r265524960
https://github.com/tendermint/tendermint/pull/3417#discussion_r265526898
> Ismail/more review fixes/release/v0.31.0

- CHANGELOG.md
- UPGRADING.md
Great work preparing the v0.31.0 @Liamsi and @melekes !
I made a number of updates though, please take a look:
- Fix indenting so the breaking changes sub categories are properly formatted (this seems to bite us all the time)
- Improve language in release summary
- Reference the bug bounty
- Reference the milestone (new!)
- Add some missing changes
- Rework modules and change category for some existing changes
- Re-order alphabetically within each change category
- Update UPGRADING.md with more structure and tips
> Update v0.31.0 release notes

- CHANGELOG.md
- CHANGELOG_PENDING.md
- consensus/replay.go
- docker-compose.yml
- libs/db/remotedb/grpcdb/server.go
- types/protobuf.go
- types/protobuf_test.go
**Don't squash! We need those commits in the release branch.**
Did not include #3442 in the Changelog as this likely to be removed via #3448
> Merge develop into release/0.31.0

- crypto/doc.go
- crypto/example_test.go
- crypto/hash.go
> crypto: delete unused code

- docs/spec/blockchain/blockchain.md
- rpc/core/consensus.go
- types/validator_set.go
Ref: https://github.com/tendermint/tendermint/issues/3073
> comments on validator ordering

- consensus/replay.go
- types/protobuf.go
- types/protobuf_test.go
> replace PB2TM.ConsensusParams with a call to params#Update

- README.md
> V0.0.1 release

- CHANGELOG_PENDING.md
- config/config.go
- config/toml.go
- docs/tendermint-core/configuration.md
- node/node.go
related to https://github.com/tendermint/tendermint/issues/3419
support rpc based on tls.
> rpc: support tls rpc

- CHANGELOG.md
> Address review comments 

- .circleci/config.yml
> Deployment test

- .circleci/config.yml
> Docker push fix, SHASUM upload fix

- .circleci/config.yml
> Docker release fix

- .circleci/config.yml
> Docker release fix 2

- CHANGELOG.md
- docs/networks/docker-compose.md
- docs/spec/blockchain/blockchain.md
- docs/spec/blockchain/encoding.md
- docs/spec/consensus/abci.md
- docs/spec/consensus/wal.md
**Do not squash** to include commit: https://github.com/tendermint/tendermint/pull/3491/commits/6a45379cdf7cde8654ba6524ed408b7e9d8fa7cd
> Update release/v0.31.1 to include #3488

- CHANGELOG.md
> minor changelog updates

- CHANGELOG_PENDING.md
- docs/spec/abci/abci.md
- docs/spec/blockchain/blockchain.md
It's not proposer local time anymore, but a weighted median
Fixes #3514
> docs: fix block.Header.Time description

- p2p/pex/addrbook.go
- p2p/pex/errors.go
- p2p/switch.go
Should replace https://github.com/tendermint/tendermint/pull/3463
> p2p: do not log err if peer is private

- CHANGELOG.md
- mention ADR in release summary
- remove [p2p] api changes
- amend v0.31.3 log to contain note about breaking change
> release/v0.31.4: address review comments

- docs/architecture/adr-039-peer-behaviour.md
Respond to a wonderful round of feedback in #3539 and align the ADR numbering with #2313
> [ADR] PeerBehaviour updates

- .gitignore
Add `.vendor-new/`to .gitignore
_skip below checklist because trivial changes_
> Add .vendor-new/ to gitignore list

- libs/common/cmap.go
> CMap: slight optimization in Keys() and Values().

- libs/README.md
> Fix typo in readme

- CHANGELOG_PENDING.md
- consensus/replay.go
- consensus/replay_test.go
Fixes #3460
Not really needed, but it would detect if the app changed in a way it
shouldn't have.
> cs/replay: check appHash for each block

- CHANGELOG_PENDING.md
- cmd/tendermint/commands/testnet.go
Option to explicitly provide the `-config` in the `testnet` command, closing #3160.
> testnet cmd: add config option

- CHANGELOG_PENDING.md
- consensus/common_test.go
- consensus/state_test.go
Should fix #3451, #2723 and #3317.
> Consensus: Fix nondeterministic tests

- CONTRIBUTING.md
Minor updates to reflect squash merging and how to prepare releases
> docs: Update contributing guideliens

- CHANGELOG_PENDING.md
- p2p/conn/secret_connection.go
Adds checking if nonce would overflow by next increasing. Panics if true
Refs #3531
> p2p: Session should terminate on nonce wrapping (#3531)

- abci/types/types.pb.go
- abci/types/types.proto
> abci/types: update comment

- docs/spec/abci/apps.md
> docs: update apps.md

- docs/architecture/adr-037-deliver-block.md
- docs/architecture/adr-038-deliver-block.md
> ADR-037: DeliverBlock

- docs/architecture/adr-036-validator-set-by-app.md
> [WIP] [ADR] ADR-36: Giving the app control over proposer selection

- docs/architecture/adr-037-deliver-block.md
- docs/architecture/adr-041-proposer-selection-via-abci.md
Minor fixes to match https://github.com/tendermint/tendermint/issues/2313
> adr renames

- Gopkg.lock
- Gopkg.toml
- libs/db/boltdb.go
- libs/db/boltdb_test.go
- libs/db/common_test.go
- libs/db/db.go
- libs/db/fsdb.go
- libs/db/go_level_db_test.go
- libs/db/mem_db.go
- libs/db/util_test.go
Original description:
> add boltdb implement for db interface.
> 
> The boltdb is safe and high performence embedded KV database. It is based on B+tree and Mmap.
> Now it is maintained by etcd-io org. https://github.com/etcd-io/bbolt
> It is much better than LSM tree (levelDB) when RANDOM and SCAN read.
Replaced https://github.com/tendermint/tendermint/pull/3604
Refs https://github.com/tendermint/tendermint/issues/1835
> bbolt (etcd's fork of bolt)

- libs/db/boltdb.go
Refs https://github.com/tendermint/tendermint/pull/3610#discussion_r281201274
If we do not close, other txs will be stuck forever.
> close boltDBIterator

- CHANGELOG_PENDING.md
- Makefile
- config/config.go
- config/toml.go
- docs/introduction/install.md
- docs/tendermint-core/configuration.md
- libs/db/backend_test.go
- libs/db/boltdb.go
- libs/db/boltdb_test.go
- libs/db/c_level_db.go
- libs/db/c_level_db_test.go
- libs/db/db.go
- libs/db/go_level_db.go
- libs/db/remotedb/remotedb_test.go
- lite/proxy/verifier.go
Fixes https://github.com/tendermint/tendermint/issues/3611
> libs/db: conditional compilation

- libs/db/boltdb.go
for storing batch keys and values in boltDBBatch.
NOTE: batch does not have to be safe for concurrent access. Delete may
be slow, but given it should not be used often, it's ok.
Fixes #3631
> libs/db: boltdb: use slice instead of sync.Map

- libs/common/json_sort.go
- libs/common/json_sort_test.go
- types/genesis.go
~~* [ ] Updated CHANGELOG_PENDING.md~~(doesn't apply, see orig PR: #3638)
> 3638: Move helpers to libs/common and add tests

- CHANGELOG_PENDING.md
- lite/proxy/proxy.go
Ref: https://github.com/tendermint/tendermint/issues/3669
> [R4R] Fix missing context parameter in proxy

- CHANGELOG_PENDING.md
- docs/networks/terraform-and-ansible.md
- networks/remote/integration.sh
> fix ansible integration script

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
> update PULL_REQUEST_TEMPLATE and CONTRIBUTING

- docs/app-dev/subscribing-to-events-via-websocket.md
> typo in docs

- scripts/release_management/bump-semver.py
Attempts to prevent #3698 from happening again.
The aim here is to cause the `prepare_build` job to fail if we're attempting to do a release and the `TMCoreSemVer` variable in the code doesn't line up with our anticipated next release number.
> Add check for version/version.go TMCoreSemVer

- CHANGELOG.md
- CHANGELOG_PENDING.md
- version/version.go
> changelog and version

- rpc/core/events.go
> docs: update RPC docs for /subscribe & /unsubscribe

- CHANGELOG_PENDING.md
- rpc/core/blocks.go
- state/store.go
> docs: update /block_results RPC docs

- CHANGELOG_PENDING.md
- node/node.go
- p2p/netaddress.go
- p2p/netaddress_test.go
- p2p/pex/pex_reactor.go
- p2p/transport_test.go
> p2p: remove NewNetAddressStringWithOptionalID

- CHANGELOG_PENDING.md
- libs/db/boltdb.go
These changes fix #3717 and #3718.
> Fix fundemental BoltDB backend correctness issues.

- CHANGELOG_PENDING.md
- types/event_bus.go
- update changelog
- do not ignore errors returned by `PublishWithEvents`
Refs #3643
> Follow up to 3643

- node/node.go
- p2p/switch.go
This PR fixed `TODO: gracefully disconnect from peers.` in `p2p/switch.go`.
> p2p: Stop peers gracefully when stopping switch

- docs/.vuepress/config.js
- docs/app-dev/app-development.md
- docs/spec/abci/abci.md
- docs/spec/blockchain/encoding.md
- docs/spec/blockchain/state.md
- docs/tendermint-core/using-tendermint.md
> docs/ fix some language issues and deprecated link

- CHANGELOG_PENDING.md
- abci/client/local_client.go
- abci/example/counter/counter.go
- abci/example/kvstore/kvstore.go
- abci/example/kvstore/kvstore_test.go
- abci/example/kvstore/persistent_kvstore.go
- abci/server/socket_server.go
- abci/types/application.go
- blockchain/reactor_test.go
- consensus/mempool_test.go
- consensus/replay.go
- docs/app-dev/app-development.md
- docs/app-dev/indexing-transactions.md
- mempool/clist_mempool_test.go
- rpc/client/mock/abci.go
- state/execution_test.go
> abci: Refactor ABCI CheckTx and DeliverTx signatures

- .golangci.yml
- benchmarks/codec_test.go
- blockchain/reactor_test.go
- consensus/byzantine_test.go
- consensus/common_test.go
- consensus/reactor.go
- consensus/state_test.go
- consensus/types/height_vote_set_test.go
- evidence/pool_test.go
- go.sum
- node/node_test.go
- p2p/upnp/upnp.go
- privval/file_test.go
- state/execution_test.go
- state/state_test.go
- state/tx_filter_test.go
- state/txindex/indexer_service_test.go
- types/block.go
- types/protobuf_test.go
- Govet issues fixed
- 1 gosec issue solved using nolint
Refs #3262
> Changes to files that had linting issue

- CONTRIBUTING.md
- README.md
Signed-off-by: Ismail Khoffi <Ismail.Khoffi@gmail.com>
> Prepare nuking develop

- CHANGELOG_PENDING.md
- node/node.go
Fixes #3741
Introduced in: 7b162f5c54267d716ef2e66912d59a0bd993a84f
> node: run whole func in goroutine, not just logger.Error fn

- rpc/core/mempool.go
> docs: (rpc/broadcast_tx_*) write expectations for a client

- docs/introduction/install.md
- added disclaimer for `-s -w`
> Added a disclaimer so the user is aware of binary

- CONTRIBUTING.md
- Add in section for Draft PR, instead of WIP
- Add make lint as part of the commit process.
> Update to contributing.md

- CHANGELOG_PENDING.md
- config/config.go
- config/config_test.go
- config/toml.go
- docs/tendermint-core/configuration.md
> rpc: make possible to set absolute paths for TLS cert and key

- CHANGELOG_PENDING.md
- behaviour/peer_behaviour.go
> [behaviour] fix in struct returned in  messagOutOfOrder PeerBehaviour

- docs/spec/abci/abci.md
- docs/spec/abci/apps.md
As per comments [here](https://github.com/tendermint/tendermint/pull/3744#discussion_r302821587) and [here](https://github.com/tendermint/tendermint/pull/3744#discussion_r302821620).
> abci: Fix documentation regarding CheckTx type update

- go.mod
- go.sum
Upgrade goleveldb dependency to commit: `c3a204f8e96543bb0cc090385c001078f184fc46`
> Upgrade levelDB

- CHANGELOG_PENDING.md
- libs/fail/fail.go
- Clean up fail.go
- Remove unneeded Func `FailRand()`
closes #2729
> Clean up `fail.go`

- CHANGELOG_PENDING.md
Refs https://github.com/tendermint/tendermint/pull/3758#issuecomment-510738955
> add a changelog entry

- CHANGELOG.md
> pr comments

- CHANGELOG_PENDING.md
- abci/server/socket_server.go
> abci/server: recover from app panics in socket server

- docs/.vuepress/config.js
> add guides to docs

- .golangci.yml
- abci/client/grpc_client.go
- abci/example/example_test.go
- blockchain/v0/reactor.go
- blockchain/v1/reactor.go
- consensus/mempool_test.go
- consensus/reactor_test.go
- consensus/state.go
- consensus/state_test.go
- go.sum
- libs/common/async.go
- libs/common/async_test.go
- libs/pubsub/pubsub_test.go
- lite/proxy/query_test.go
- mempool/clist_mempool.go
- p2p/conn/connection_test.go
- p2p/conn/secret_connection_test.go
- p2p/switch_test.go
- privval/signer_validator_endpoint_test.go
- rpc/grpc/client_server.go
- rpc/lib/client/ws_client.go
- rpc/lib/client/ws_client_test.go
- state/state_test.go
- tools/tm-monitor/mock/eventmeter.go
- types/genesis_test.go
- types/validator_set.go
cleanup to add linter
- grpc change:
- https://godoc.org/google.golang.org/grpc#WithContextDialer
- https://godoc.org/google.golang.org/grpc#WithDialer
- grpc/grpc-go#2627
- prometheous change:
- due to UninstrumentedHandler, being deprecated in the future
- empty branch = empty if or else statement
- didn't delete them entirely but commented
- couldn't find a reason to have them
- could not replicate the issue #3406
- but if want to keep it commented then we should comment out the if statement as well
> Add staticcheck linting

- docs/guides/go-built-in.md
- docs/guides/go.md
> docs: add a footer to guides

- docs/guides/kotlin.md
> docs: "Writing a Tendermint Core application in Kotlin (gRPC)" guide

- go.mod
- go.sum
> version tmdb

- CHANGELOG.md
> Update log v0.32.2

- .golangci.yml
- abci/cmd/abci-cli/abci-cli.go
- abci/example/kvstore/kvstore_test.go
- blockchain/v0/pool.go
- consensus/replay.go
- consensus/replay_test.go
- consensus/state.go
- crypto/merkle/simple_proof.go
- go.mod
- go.sum
- libs/autofile/group.go
- libs/common/async_test.go
- libs/common/errors.go
- libs/log/tmfmt_logger.go
- mempool/clist_mempool_test.go
- node/node.go
- p2p/fuzz.go
- p2p/netaddress.go
- p2p/node_info_test.go
- p2p/switch.go
- rpc/lib/client/http_client.go
- rpc/lib/server/handlers.go
- state/execution.go
- state/txindex/kv/kv.go
- tools/tm-monitor/monitor/network.go
- types/validator.go
- folow up to complete gocritic (1/2)
> Add gocritic (2/2)

- docs/guides/java.md
- docs/guides/kotlin.md
> docs: "Writing a Tendermint Core application in Java (gRPC)" guide

- CHANGELOG_PENDING.md
- store/codec.go
Fixes https://github.com/tendermint/tendermint/issues/3893
> store: register block amino, not just crypto

- scripts/gitian-build.sh
- scripts/gitian-descriptors/gitian-darwin.yml
- scripts/gitian-descriptors/gitian-linux.yml
- scripts/gitian-descriptors/gitian-windows.yml
> Update reproducible builds to build with Go 1.12.8

- .circleci/config.yml
- CONTRIBUTING.md
- docs/spec/rpc/swagger.yaml
- scripts/get_nodejs.sh
Testing Nodejs image
follow up to come comments from #3903 
> Test nodejs image

- .golangci.yml
- types/vote_set.go
This should've been a part of
https://github.com/tendermint/tendermint/pull/3960, but I forgot about
it while reviewing.
A good programmer is someone who always looks both ways before crossing
a one-way street. - Doug Linder
> enable unconvert, goconst and nakedret linters

- .golangci.yml
- CHANGELOG_PENDING.md
- rpc/client/interface.go
- rpc/client/mock/client.go
- types/vote.go
closes #3984
- add mempoolclient interface to client interface
> Add MempoolClient to Client Interface

- abci/types/types.pb.go
- abci/types/typespb_test.go
- crypto/merkle/merkle.pb.go
- libs/common/types.pb.go
- libs/common/typespb_test.go
- rpc/grpc/types.pb.go
- rpc/grpc/typespb_test.go
- types/proto3/block.pb.go
protoc 3.7.0
gogo v1.3.0
Replaces https://github.com/tendermint/tendermint/pull/3997
> regenerate protobuf files with newer gogo version

- .golangci.yml
- blockchain/v2/reactor.go
- blockchain/v2/routine.go
- blockchain/v2/routine_test.go
- Release candidate for v0.32.4
once this is finalized, will branch off and create the release branch and we can close this.
- waiting on release of tm-db
> RC1 - 0.32.4

- CHANGELOG.md
> Address PR comments in PR #4002

- .circleci/config.yml
- README.md
- UPGRADING.md
- docs/guides/go-built-in.md
- docs/guides/go.md
- docs/guides/java.md
- docs/guides/kotlin.md
- Some places still had develop instead of master.
closes #4107
> Develop -> Master

- .golangci.yml
> Add Dogsled to linting

- CHANGELOG.md
- CHANGELOG_PENDING.md
also 
- replace TODO placeholder with the actual issue in v0.32.5
**SQUASH**
> changelog: add v0.31.9 and v0.31.8 updates

- config/toml.go
- docs/spec/reactors/mempool/config.md
- docs/tendermint-core/configuration.md
> docs: any path can be absolute or relative

- docs/DEV_SESSIONS.md
> Add Previous dev sessions

- .golangci.yml
- abci/tests/test_app/main.go
- config/config.go
- consensus/reactor_test.go
- consensus/types/peer_round_state.go
- consensus/types/round_state.go
- libs/flowrate/flowrate.go
- libs/flowrate/io_test.go
- node/node.go
- p2p/pex/addrbook.go
- p2p/pex/pex_reactor.go
- p2p/switch_test.go
- rpc/core/pipe.go
- rpc/lib/client/ws_client.go
- rpc/lib/server/handlers_test.go
- state/state_test.go
- tools/tm-bench/transacter.go
> New lint version upgrade

- docs/.vuepress/config.js
- docs/package-lock.json
- docs/package.json
- docs/ru/readme.md
Update to the latest version of the `vuepress-theme-cosmos`.
Features:
* Animation when expanding/collapsing directories
* By default auto-sidebar is not limited to two levels of directories (it's recursive!).
* Add directory trees in `sidebar` in `config.js` by using a `directory: true` property. This will be useful for Cosmos SDK modules section.
* To link to a static file in `.vuepress/public` use `static: true` property.
To check it out run: `cd docs && rm -rf node_modules && npm install && npm run serve`.
> Docs: animated sidebar and nested directories

- scripts/gitian-build.sh
- scripts/gitian-descriptors/gitian-darwin.yml
- scripts/gitian-descriptors/gitian-linux.yml
- scripts/gitian-descriptors/gitian-windows.yml
> Fix reproducible builds

- Makefile
- docs/versions
> Update docs build job

- .gitignore
- docs/.vuepress/config.js
- docs/introduction/quick-start.md
- docs/package-lock.json
- docs/package.json
- docs/versions
> Latest version of the theme

- CHANGELOG.md
> Fix trivial typo

- docs/app-dev/app-architecture.md
- docs/spec/blockchain/encoding.md
> Doc link fixes

- .circleci/config.yml
> remove source code cache restore

- .circleci/config.yml
> remove source code cache restore (again)

- .circleci/config.yml
- Makefile
> Added staging build

- rpc/swagger/swagger.yaml
- closes #4138
- added numtxs to blockmeta swagger type
> Add numtxs to swagger blockmeta
