- rpc/core_client/client.go
- rpc/core_client/client_methods.go
- rpc/test/client_ws_test.go
- rpc/test/helpers.go
- rpc/test/tests.go
- rpc/test/ws_helpers.go
- types/tx_utils.go
Felt an overwhelming urge to do this. Simplifies some of the functions, makes it more extensible, uses the client functions in tx_utils (I was inspired by starting to write the tests for namereg ...)
> cleanup rpc tests, use tx_utils

- blockchain/pool.go
- blockchain/reactor.go
- config/tendermint_test/config.go
- consensus/reactor.go
- node/node.go
Addresses a bug in consensus state where a validator would proceed with consensus rounds even if he was still fast syncing.  Also cleans up some methods and variable names, and fixes a sleep bug in the blockpool.
> Blockchain

- Dockerfile
This PR adds gmp to the docker build process which is required by the Tendermint VM to perform `ecrecover` properly.
> add gmp so that docker images build correctly

- p2p/switch.go
eg. on /net_info my docker nodes were showing eachothers internal docker ips, not their real ones. will also prevent spoofing
> don't trust peer's node info

- account/pub_key.go
- config/tendermint_test/config.go
- ReadFull hangs forever unless we set a timeout on the conn (not sure this matters for sconn.Read(), but it does for shareEphPubKey
- sconn.Read was missing a bounds check such that a malicious `chunkLength` would crash the node
- there's also a question in there about the size of the buffer used for `shareAuthSignature`
Unfortunately, I couldn't think of an easy way to implement tests for my fixes (I tested both manually).
> add handshakeTimeout, bound chunkLength, comments

- cmd/tendermint/main.go
- config/tendermint/config.go
- config/tendermint_test/config.go
- node/node.go
- node/version.go
- p2p/switch_test.go
- p2p/version.go
- rpc/version.go
- types/node.go
- wire/version.go
Add versions to the p2p, rpc, and wire. This is mostly for sake of other consumers/clients. The main tendermint version encapsulates state/consensus/blockchain.
> more versioning

- Makefile
- config/tendermint/config.go
- config/tendermint_test/config.go
- node/node.go
- p2p/netaddress.go
- vm/config.go
- vm/vm.go
- one commit hash per revision file, but also keep a revision_history
- enable profile server from config
- toggle vm output from config
- enable local routing from config (for running multiple nodes from one machine, for debugging)
> more config options

- node/node.go
- state/permissions_test.go
- vm/snative.go
All permissions snatives accessed through a single "permissions_contract" contract interface using solidity abi function ids for switching.
> consolidate snatives and use abi func id

- DOCKER/docker.sh
- cmd/tendermint/main.go
- config/tendermint/config.go
- config/tendermint_test/config.go
- consensus/common_test.go
- consensus/reactor.go
- consensus/replay.go
- consensus/replay_test.go
- consensus/state.go
- consensus/state_test.go
- consensus/wal.go
- consensus/wal_test.go
- node/node.go
- proxy/remote_app_conn.go
- types/events.go
This PR introduces a write ahead log (WAL) into the consensus state so that all messages received in the receiveRoutine are written to disk before they are processed, in order that consensus state is not corrupted in the event of a crash. 
TestReplayCatchup simulates a case where the node crashed after precommitting but before committing. Without being able to rerun msgs from the WAL, it would halt forever. Could potentially be saved by network input, but there are cases eg. in a 4 node net, with one node down, if another node crashed and restarted at the right point, the network could halt.
The WAL can also be used for deterministic accountability and analysis. The PR includes simple tools to rerun an entire WAL against the consensus state, and to do so interactively with commands for …
> consensus: write ahead logging, recovery, replay

- blockchain/pool.go
- blockchain/pool_test.go
- config/tendermint/config.go
- config/tendermint_test/config.go
- consensus/reactor.go
- consensus/replay.go
- consensus/replay_test.go
- consensus/state.go
- consensus/state_test.go
- consensus/wal.go
- consensus/wal_test.go
- glide.lock
- mempool/mempool.go
- mempool/mempool_test.go
- mempool/reactor.go
- node/node.go
- rpc/core/mempool.go
- rpc/core/routes.go
- rpc/core/status.go
- rpc/core/types/responses.go
- rpc/test/client_test.go
Changes and fixes resulting from the benchmarking effort (https://github.com/tendermint/network_testing)
- Now configurable from config.yaml: consensus timeouts, block size (including -1 to ignore mempool txs when proposing), recheck tx, mempool broadcasting 
- cswal fixes and light mode (doesn't record block parts). closes https://github.com/tendermint/tendermint/issues/186 and https://github.com/tendermint/tendermint/issues/184
- unsafe_set_config rpc command. used especially to toggle block_size so blocks don't include txs until we want them to. note not all config values can be changed this way depending on if they are assigned to variables (maybe we change this on a case by case basis. currently consensus timeouts are not updateable but maybe we want them to be)
- fix bug where peer …
> configurable params, other fixes

- cmd/tendermint/flags.go
- config/tendermint/config.go
- config/tendermint_test/config.go
- mempool/mempool.go
- node/node.go
- proxy/remote_app_conn.go
- proxy/remote_app_conn_test.go
- rpc/core/mempool.go
- state/execution.go
- protobuf messages use oneof
- support for grpc (`tendermint node -tmsp=grpc`)
Complements https://github.com/tendermint/tmsp/pull/13
> Protobuf + GRPC

- rpc/core/events.go
Currently unsubscribe is broken because it is using the event name instead of the listener to unsubscribe. This restores it to the functionality provided by:
https://github.com/eris-ltd/eris-db/blob/master/Godeps/_workspace/src/github.com/tendermint/tendermint/rpc/server/handlers.go#L359
As a side note the current code only allows one websocket subscription for the same remote address to the same event. This is probably a bad limitation to have. See my remark in: https://github.com/eris-ltd/eris-db/pull/235.
> Fix unsubscribe

- consensus/replay.go
- consensus/state.go
- consensus/state_test.go
Don't warn about signing errors during replay.
Fix race condition between scheduleRound0 and receiveRoutine processing queued messages from replay.
Fix race condition in consensus test where votes are updated before they can be validated.
> consensus: no sign err in replay; fix a race

- node/node.go
- proxy/client.go
- proxy/multi_app_conn.go
- test/app/test.sh
- version/version.go
mustConnect was accidentally set to true when it should have been false. This means tendermint would panic if the app wasn't already running. fixed, and added a test for it
> Hotfix 1.7.2

- blockchain/reactor.go
- consensus/common.go
- consensus/common_test.go
- consensus/reactor.go
- consensus/replay_test.go
- consensus/state.go
- consensus/state_test.go
- glide.lock
- mempool/reactor.go
- node/node.go
- rpc/core/events.go
- rpc/core/mempool.go
- rpc/core/pipe.go
- scripts/glide/status.sh
- scripts/glide/update.sh
- state/execution.go
- types/events.go
- Remove all dependence on `github.com/tendermint/go-events` except through `types/events.go`
- Use proxy `FireEvent` functions in `types/events.go` to enforce data types and instances of `types.TMEventData`
Depends on https://github.com/tendermint/go-rpc/pull/3 and https://github.com/tendermint/go-events/pull/7
> Type safe fire event

- consensus/height_vote_set.go
lock on hvs.StringIndented() see https://github.com/tendermint/tendermint/issues/284
> consensus: hvs.StringIndented() was missing a lock. addresses #284

- .editorconfig
- .gitignore
- Makefile
- scripts/dist.sh
- scripts/dist_build.sh
- scripts/tendermint-builder/Dockerfile
- version/version.go
Preface: if we want to engage more people (not just hardcore devs), I believe we must provide statically compiled binaries for each release. Besides, this could be easily done with Golang. 
Story: as a dev, if I just want to try Tendermint (or I am planning to write my app in Java), I don't want to install Golang, I just want `brew install tendermint` or similar (btw, what do you think about adding Tendermint to `brew`).
This will fix many issues (https://tendermint.com/intro/getting-started/install):
1. user don't have to install Golang
2. user don't have to learn Golang tools (go get)
3. user won't be having any problems with updated dependencies
Usage
=====
```
$ make dist
```
will create binaries for almost all platforms and will package them for distribution. It will also create a …
> `make dist` for creating binaries and packaging them for distribution

- cmd/tendermint/main.go
I find it very confusing when I am going through the tutorial (https://tendermint.com/intro/getting-started/install) and **do not see `init` in the list of available commands**.
Also, now we just dump all the flags, even whose not relevant to the given command:
```
./build/tendermint replay wal --gee
unknown flag: --gee
Usage of main:
--abci string         Specify abci transport (socket | grpc) (default "socket")
--fast_sync           Fast blockchain syncing (default true)
--grpc_laddr string   GRPC listen address (BroadcastTx only). Port required
--help                Print this help message.
--log_level string    Log level (default "notice")
--moniker string      Node Name (default "anonymous")
--node_laddr string   Node listen address. (0.0.0.0:0 means any interface, anyport) (default …
```
> Output all tendermint commands

- DOCKER/README.md
- Makefile
- Vagrantfile
- test/net/start.sh
The main reason is people usually expect docker image to have the same name as the repo. Plus, `tendermint` is cleaner than `tmbase`.
`tmbase` would make sense if we had multiple docker images within `tendermint`, but we don't.
> Rename docker image to tendermint

- Vagrantfile
- cmd/tendermint/gen_validator.go
Refs #396 
so we can pipe result to a file:
```
tendermint gen_validator > example.json
```
before this we had to cut first 3 lines:
```
tendermint gen_validator | sed 1,3d > example.json
```
> [cli] cleanup gen_validator output

- blockchain/reactor.go
- consensus/replay.go
- consensus/replay_test.go
- consensus/state.go
- consensus/test_data/build.sh
- consensus/test_data/empty_block.cswal
- consensus/test_data/many_blocks.cswal
- consensus/test_data/small_block1.cswal
- consensus/test_data/small_block2.cswal
- consensus/wal.go
- glide.lock
- state/execution.go
- state/state.go
- state/state_test.go
https://github.com/tendermint/tendermint/issues/448
- WAL #HEIGHT -> #ENDHEIGHT 
- NOTE: This is not backwards compatible, so we also check WAL for #HEIGHT until 0.10.0. This should cover most (all ?) cases for upgrading.
- ABCIResponses struct persisted before Commit
- ApplyBlock does everything, from ExecBlock to state.Save
- Handshake uses ApplyBlock, not ConsensusState/WAL
TODO
- How to handle NewBlock event - if we crash before firing we might never fire it. If we fire it during Handshake, the RPC isn't active yet so app might not receive it - so do we also fire on cs.Start() if the WAL for the block is empty (and thus possibly fire twice). Or is it fine to never fire for a block if we crashed while processing it ?
> Fix replay

- blockchain/pool.go
On removePeer, we were incrementing numPending for every requester associated with that peer (even those that weren't pending), causing us to exceed the MaxNumPending and stop making progress. Now we only increment for blocks that weren't already pending (ie. blocks we had received from the peer).
Question: should we really reset a requester and re-request a block just because the peer disconnected ?
> blockpool: fix removePeer bug

- p2p/netaddress_test.go
The cause is the dns resolver on osx resolves `127.0.0` successfully to `127.0.0.0` instead of returning an error.  Different behavior on linux.
Commenting out this test case means I actually can run the test suite on my macbook.  I had the same problem under vagrant as well, which seems to use the native dns resolver....
> One silly tests passes on osx, fails on linux... 

- CHANGELOG.md
- cmd/tendermint/commands/flags/log_level.go
- cmd/tendermint/commands/run_node.go
- config/config.go
- config/toml.go
- node/node.go
- rpc/client/rpc_test.go
- rpc/core/blocks.go
- rpc/core/routes.go
- rpc/test/helpers.go
- state/execution.go
- test/app/test.sh
- test/p2p/data/core/init.sh
- test/p2p/fast_sync/test_peer.sh
- test/p2p/local_testnet_start.sh
- test/p2p/pex/test_addrbook.sh
- test/persist/test_failure_indices.sh
- types/priv_validator.go
- version/version.go
https://github.com/tendermint/tendermint/issues/510
Adds some fixes, and some breaking changes to the rc1
BREAKING:
- `node_laddr -> p2p.laddr`
- new `rpc` subconfig
- unsafe rpc calls disabled by default, can be enabled with `--rpc.unsafe`
Fixes
- use `state:info,*:error` for logging, and log the height and number of txs on committing state
- limit `/blockchain_info` to return max 20 blocks
- compute and overwrite the pubkey and address when loading priv_validator.json
> fixes to changelog, config, default logging

- state/execution.go
The log info in 109 line of `state/execution.go` didn't output:
```
logger.Info("Executed block", "height", block.Height, "valid txs", validTxs, "invalid txs", invalidTxs)
```
the keys `valid txs` and `invalid txs` contain a **blank space**  that leads the logger not output log.
after fixing, this line of log can output as follows:
```
I[06-14|06:52:07.015] Finalizing commit of block with 0 txs        module=consensus height=7899 hash=33E0C0E2F22379E71A24493939D28027014B2C11 root=0000000000000001
I[06-14|06:52:07.015] Block{
Header{
ChainID:        test-chain-KbzJQK
Height:         7899
Time:           2017-06-14 14:52:07.008 +0800 CST
NumTxs:         0
LastBlockID:    6AE7197A2C5D1E637428A1249EDBFF7150379539:1:E96236C517BA
LastCommit:     A9B155817550B4957FC19E748793493555FB2E9D
Data: …
```
> logger key doesn't support blank space

- Makefile
- blockchain/pool.go
- blockchain/reactor.go
- cmd/tendermint/commands/root.go
- consensus/byzantine_test.go
- consensus/common_test.go
- consensus/height_vote_set_test.go
- consensus/reactor.go
- consensus/replay.go
- consensus/replay_test.go
- consensus/state.go
- consensus/state_test.go
- p2p/addrbook.go
- p2p/connection.go
- p2p/listener.go
- p2p/netaddress.go
- p2p/pex_reactor.go
- p2p/secret_connection.go
- p2p/upnp/probe.go
- p2p/upnp/upnp.go
- rpc/test/client_test.go
- state/execution.go
- state/state.go
- state/txindex/kv/kv_test.go
- types/block.go
- types/validator_set.go
- this PR applies the `megacheck` tool, which itself applies the `unused`, `gosimple`, and `staticcheck` golang code vetting/improvement tools. See https://github.com/dominikh/go-tools for more information.
- a few fixes caught by the tool were left as-is due to insufficient context for what the best fix ought to be. These will be addressed in a follow-up PR after discussion with @ebuchman
> core: apply megacheck vet tool (unused, gosimple, staticcheck)

- cmd/tendermint/commands/root_test.go
I was having some weird test errors locally...
Turned out having TM_HOME set in my shell was messing with all the commands tests in tendermint.  Let's make it less fragile to being run in an active dev system...
> Do some cleanup in the test, so it doesn't fail in my shell

- CHANGELOG.md
- cmd/tendermint/commands/run_node.go
- config/config.go
- consensus/byzantine_test.go
- consensus/common_test.go
- consensus/mempool_test.go
- consensus/reactor.go
- consensus/replay.go
- consensus/state.go
- mempool/mempool.go
- mempool/mempool_test.go
- node/node.go
- types/canonical_json.go
- types/events.go
- types/heartbeat.go
- types/priv_validator.go
- types/services.go
- option to prevent empty blocks. disabled by default. perhaps we enable by default for 0.11 ?
Note this is a breaking change to the `types.Mempool` interface since it adds a couple methods. As discussed in slack, we will make explicit which packages/types/funcs are covered by semver.
> No empty blocks

- docs/specs/block-structure.md
- docs/specs/byzantine-consensus-algorithm.md
- docs/specs/fast-sync.md
- docs/specs/genesis.md
- docs/specs/light-client-protocol.md
- docs/specs/tendermint-types.md
- closes https://github.com/zramsay/tendermint/issues/1
- cleans up any other links required for longevity in the face of changing code.
> fix dead tendermint types links in specs

- cmd/hsm/main.go
- types/priv_validator.go
This change allows the default privValidator to use a custom Signer implementation with no reliance on the default Signer implementation.
Due to the existing naming of methods (and not wishing to break backwards compatibility), the downside of my change is that we lose logging information. There was no natural place to insert a logger object.
> Remove reliance on default Signer

- p2p/peer_set.go
- p2p/peer_set_test.go
* Full test PeerSet and check its concurrent guarantees
* Improve the doc for PeerSet.Has and remove unnecessary
defer for a path that sets a variable, make it fast anyways.
* Parallelize PeerSet tests with t.Parallel()
> p2p: fully test PeerSet

- cmd/hsm/main.go
- types/priv_validator.go
Prior to this change, a custom Signer would have no knowledge of the private
key stored in the configuration file. This changes introduces a generator
function, which creates a Signer based on the private key. This provides an
opportunity for customer Signers to adjust behaviour based on the key
contents. (E.g. imagine key contents are a key label, rather than the key
itself).
This is just one possible way of solving the issue.
> Allow Signer to be generated with priv key

- consensus/state.go
- background: #595 (closes issue)
- user reports that this changed fixed their problem on windows. Using `filepath` is (AFAIK) recommended for Linux and other OSs.
> use filepath for windows compatibility

- README.md
This adds passchain to the 'applications' part of the toplevel README.md file.
Passchain is a distributed password sharing system built on top of tendermint.
See [Passchain Repository](https://github.com/trusch/passchain)
> [README] added passchain to application list;

- docs/ecosystem.rst
This adds passchain to the correct doc location and not in the toplevel README.md file since it is outdated.
> docs: added passchain to the ecosystem.rst in the applications section

- rpc/client/httpclient.go
- rpc/lib/client/ws_client.go
- rpc/lib/client/ws_client_test.go
When connection is lost with server, client does not re-subscribe so client is not notified anymore.
> rpc: subscribe on reconnection

- rpc/lib/server/handlers.go
Since version 0.10.2, ping/pong between server and client are broken. Server is not notified that client is alive because pong message was not handled.
Each 30 seconds, log "Failed to read request" appeared.
> rpc: fix client websocket timeout

- docs/getting-started.rst
Since 0.10.0, RPC does not require all args (default values will be used).
> remove unnecessary args in abci_query call in getting-started [ci skip]

- docs/app-development.rst
Refs #695 
Questions:
1) Can we embed code directly from Github? something like `https://github.com/tendermint/abci/blob/master/example/dummy/persistent_dummy.go#L10-20`
2) I think we need examples in another language(s). Java?
3) persistent-dummy may not be the best example. Other suggestions?
> Improve app dev docs

- rpc/lib/doc.go
I don't want to lose any documentation. Correct me if I am wrong, but we
don't have this docs anywhere else.
> restore rpc/lib readme as doc.go (Refs #710) [ci skip]

- types/heartbeat.go
- types/heartbeat_test.go
Updates https://github.com/tendermint/tendermint/issues/693
* Adjusted Heartbeat.Copy to return nil on
trying to copy a nil value instead of panicking.
* Also documented that WriteSignBytes panics
if the Heartbeat is nil.
> types/heartbeat: test all Heartbeat functions

- rpc/lib/client/http_client.go
- rpc/lib/client/ws_client.go
- rpc/lib/types/types.go
- rpc/lib/types/types_test.go
Currently the RPC clients swallow useful nested error data, this PR surfaces that and makes RPCError implement the Go error interface.
> Make RPCError an actual error and don't swallow its companion data

- types/genesis_test.go
- types/params.go
- types/params_test.go
Fixes https://github.com/tendermint/tendermint/issues/747
Updates https://github.com/tendermint/tendermint/issues/693
* Document the unmentioned limits for ConsensusParams.Validate()
* Make the limit for ConsensusParams.BlockSizeParams.MaxBytes
clear at 100MiB
> types: ConsensusParams test + document the ranges/limits

- consensus/state.go
Change log level to Info when proposal block hashing fails due to partially complete block
Closes #769
> Change log level to Info when proposal block hashing fails 

- consensus/replay_test.go
- glide.lock
Refs #782 
```
-bash-4.2$ tendermint show_validators
panic: failed to determine gopath: exec: "go": executable file not found in $PATH
goroutine 1 [running]:
github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common.gopath(0xc4200632c0, 0x18)
/var/lib/jenkins/workspace/03.Build.Package/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common/os.go:26 +0x1b5
github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common.init()
/var/lib/jenkins/workspace/03.Build.Package/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common/os.go:17 +0x13c
github.com/tendermint/tendermint/vendor/github.com/tendermint/go-wire.init()
/var/lib/jenkins/workspace/03.Build.Package/go/src/github.com/tendermint/tendermint/vendor/gi …
```
> fix panic: failed to determine gopath: exec: "go"

- benchmarks/simu/counter.go
- rpc/client/httpclient.go
- rpc/lib/client/ws_client.go
- rpc/lib/client/ws_client_test.go
- rpc/lib/rpc_test.go
In `WSClient` when `readRoutine` reads a message it blocks sending it to `ResultsCh`. When you call `Stop()` on the `WSClient` this cause it to block indefinitely. This is because `readRoutine` never calls `Done()` on the wait group in `WSClient` because it is blocking on sending to `ResultsCh` and `Stop()` calls `c.wg.Wait()`.
This fixes it by introducing a back channel `writeRoutineQuit` which works in a similar way to the existing `readRoutineQuit`. In both cases the close idiom is used so that any subsequent reads will immediately return which should eliminate any issues if both routines are trying to close each other. We need another channel (rather than using 'readRoutineQuit' for both) because only one goroutine can be responsible for closing a channel without there being a race.
> Fix WSClient deadlock in the readRoutine after Stop() is called

- Makefile
- rpc/lib/client/integration_test.go
- rpc/lib/client/ws_client.go
- rpc/lib/client/ws_client_test.go
Fixes https://github.com/tendermint/tendermint/issues/751.
Adds jitter to our exponential backoff to mitigate a self DDOS
vector. The jitter is a randomly picked percentage of a second
whose purpose is to ensure that each exponential backoff retry
occurs within (1<<attempts) == 2**attempts, but with the delay
each client will have a random buffer time before it tries to
reconnect instead of all at once reconnections that might even
bring back the previous conditions that might have caused the
dial to the WSServer to have failed e.g
* Network outage
* File descriptor exhaustion
* False positives from firewalls
etc
> rpc/lib/client: add jitter for exponential backoff of WSClient

- config/config.go
- config/toml.go
- config/toml_test.go
- docs/specification/configuration.rst
- rpc/lib/doc.go
closes #705 
links to:  #709, #636
Running `tendermint init` used to produce the following `config.toml`:
```
proxy_app = "tcp://127.0.0.1:46658"
moniker = "anonymous"
fast_sync = true
db_backend = "leveldb"
log_level = "state:info,*:error"
[rpc]
laddr = "tcp://0.0.0.0:46657"
[p2p]
laddr = "tcp://0.0.0.0:46656"
seeds = ""
```
which did not provide all that much information about the many config options. Now, the `config.toml` looks like:
```
proxy_app = "tcp://127.0.0.1:46658"
moniker = "anonymous"
fast_sync = true
db_backend = "leveldb"
db_path = "data"
log_level = "state:info,*:error"
chain_id = ""
genesis_file = "genesis.json"
priv_validator_file = "priv_validator.json"
abci = "socket"
prof_laddr = ""
filter_peers = false
tx_index = "kv"
[rpc]
laddr = "tcp://0.0.0.0:46657"
grpc_laddr = …
```
> write config.toml with all defaults & improve config doc 

- p2p/netaddress_test.go
A test assumes that `"a"` is not a valid hostname however it is in fact one of the most common because it is so short so this test is likely to cause spurious errors. It fails on my LAN here:
```
ok  	github.com/tendermint/tendermint/consensus	46.703s
ok  	github.com/tendermint/tendermint/consensus/types	0.039s
ok  	github.com/tendermint/tendermint/mempool	4.073s
ok  	github.com/tendermint/tendermint/node	2.017s
--- FAIL: TestNewNetAddressString (0.00s)
Error Trace:    netaddress_test.go:48
Error:      	Expected value not to be nil.
Messages:   	a:8080
FAIL
FAIL	github.com/tendermint/tendermint/p2p	7.341s
?   	github.com/tendermint/tendermint/p2p/upnp	[no test files]
```
With this PR this test and all tests pass on my system.
> fix test using uncommon names

- rpc/lib/server/handlers.go
- rpc/lib/server/handlers_test.go
Follow up of PR https://github.com/tendermint/tendermint/pull/724
For https://github.com/tendermint/tendermint/issues/708
Reported initially in #708, this bug was reconfirmed
by the fuzzer.
This fix ensures that:
* if the user doesn't pass in `"id"` that we send them back
a message in an error telling them to send `"id"`. Previously
we let the handler return a 200 with nothing.
* passing in nil `params` doesn't crash
* not passing in `params` doesn't crash
* passing in non-JSON parseable data to `params` doesn't crash
> rpc/lib/server: add handlers tests for params inclusion

- consensus/state.go
https://github.com/tendermint/tendermint/issues/243#issuecomment-339924812
Tendermint should die if app hash does so OS can handle restarts
> Kill Tendermint when App dies

- p2p/addrbook.go
Just noticed while auditing the code in p2p/addrbook.go,
wg.Add(1) but no subsequent defer.
@jaekwon and I had a discussion offline and we agreed to
comment about why the code was that way and why
we shouldn't move the wg.Add(1) into .saveRoutine() because
if go a.saveRoutine() isn't started before anyone invokes
a.Wait(), then we'd have raced a.saveRoutine().
> p2p: comment on the wg.Add before go saveRoutine()

- consensus/reactor_test.go
```
panic: interface conversion: interface {} is nil, not types.TMEventData
goroutine 7690 [running]:
github.com/tendermint/tendermint/consensus.waitForAndValidateBlock.func1(0xc427727620, 0x3)
/go/src/github.com/tendermint/tendermint/consensus/reactor_test.go:292 +0x62b
created by github.com/tendermint/tendermint/consensus.timeoutWaitGroup
/go/src/github.com/tendermint/tendermint/consensus/reactor_test.go:349 +0xa4
exit status 2
FAIL    github.com/tendermint/tendermint/consensus      38.614s
```
> Fix nondeterministic tests failures related to pubsub

- consensus/state_test.go
- test/p2p/peer.sh
```
==================
WARNING: DATA RACE
Write at 0x00c42d7605f0 by goroutine 844:
github.com/tendermint/tendermint/consensus.(*ConsensusState).updateToState()
/home/vagrant/go/src/github.com/tendermint/tendermint/consensus/state.go:465 +0x59e
I[11-14|22:37:28.781] Added to prevote                             vote="Vote{0:646753DCE124 1/02/1(Prevote) E9B19636DCDB {/CAD5FA805E8C.../}}" prevotes="VoteSet{H:1 R:2 T:1 +2/3:<nil> BA{2:X_} map[]}"
github.com/tendermint/tendermint/consensus.(*ConsensusState).finalizeCommit()
/home/vagrant/go/src/github.com/tendermint/tendermint/consensus/state.go:1229 +0x16a9
github.com/tendermint/tendermint/consensus.(*ConsensusState).tryFinalizeCommit()
/home/vagrant/go/src/github.com/tendermint/tendermint/consensus/state.go:1135 +0x721 …
```
> fix TestFullRound1 race (Refs #846)

- p2p/conn_go110.go
- p2p/connection_test.go
- p2p/switch.go
- p2p/switch_test.go
Fixes https://github.com/tendermint/tendermint/issues/851
Go1.9 and below's net.Pipe did not implement the SetDeadline
method so after commit
https://github.com/golang/go/commit/e2dd8ca946be884bb877e074a21727f1a685a706
this problem was exposed since now we check for errors.
To counter this problem, implement a simple composition for
net.Conn that always returns nil on SetDeadline instead of
tripping out.
Added build tags so that anyone using go1.10 when it is released
will be able to automatically use net.Pipe's net.Conns
> p2p: use fake net.Pipe since only >=Go1.10 implements SetDeadline

- p2p/conn_notgo110.go
- p2p/switch.go
Follow up of 283544c7f3ada24378fd6e0ac2f82cd927bc95e6
putting <Go1.10 implementation of netPipe in its own
file and protect it with its separate build tag.
> p2p: netPipe for <Go1.10 in own file with own build tag

- p2p/secret_connection.go
Updates https://github.com/tendermint/tendermint/issues/850
My security alarms falsely blarred when I skimmed and noticed
keys being compared with `==`, without the proper context
so I mistakenly filed an issue, yet the purpose of that
comparison was to check if the local ephemeral public key
was just the least, sorted lexicographically.
Anyways, let's use the proper bytes.Equal check, to save future labor.
> p2p: use bytes.Equal for key comparison

- glide.lock
- glide.yaml
- p2p/connection.go
In conjunction with https://github.com/tendermint/go-wire/pull/47 to initially reduce `io.Writer` dependence and eventually refactor, split, improve and replace about half of `go-wire` and `MConnection`. This PR just does the first smallest step in that direction and is not ready to be merged yet but may become viable for merging once more reflection and tests are in place. This PR introduces the `legacy` namespace prefix to identify and mark the areas to adjust for refactoring while minimizing chance of disruption. Once we have marked all the areas we want to refactor then we can mechanically change each case to our ideal interface in a systematic, consistent, and hopefully more accurate way as a team.
> WIP: begin parallel refactoring: go-wire Write methods and MConnection

- mempool/mempool.go
- mempool/mempool_test.go
Fixes https://github.com/tendermint/tendermint/issues/890
Add a Stop metho to Mempool to close the underlying
WAL file and then discard it so that further writes
to it will have no effect.
> mempool: implement Mempool.CloseWAL

- docs/ecosystem.rst
> docs:clarify py-abci/py-tendermint

- .editorconfig
- Makefile
- scripts/dist_build.sh
- test/docker/Dockerfile
- version/version.go
The problem is that in homebrew GOPATH is set to /tmp and it is not in PATH. So metalinter fails with:
```
brew install tendermint --HEAD
==> Installing tendermint from tendermint/tendermint
==> Cloning https://github.com/tendermint/tendermint.git
Cloning into '/Users/antonk/Library/Caches/Homebrew/tendermint--git'...
remote: Counting objects: 437, done.
remote: Compressing objects: 100% (412/412), done.
remote: Total 437 (delta 7), reused 129 (delta 2), pack-reused 0
Receiving objects: 100% (437/437), 3.04 MiB | 1006.00 KiB/s, done.
Resolving deltas: 100% (7/7), done.
==> Checking out branch develop
==> make get_vendor_deps
Last 15 lines from /Users/antonk/Library/Logs/Homebrew/tendermint/01.make:
2017-12-04 14:54:54 -0600
make
get_vendor_deps
go get github.com/mitchellh/gox …
```
> Enable homebrew installation from source

- Makefile
It was writing to stdlib packages net, x/crypto, etc. and failing when it didn't have write access to them (which it often shouldn't)
Fixes issue #941 
Explained in golang issue: https://github.com/golang/go/issues/18981 (fixed in develop/1.10)
> From CGO_ENABLED=0 from make install

- consensus/ticker.go
While reading the code I've found a typo in the documentation.
> consensus: Fix typo on ticker.go documentation

- consensus/wal_generator.go
Fixes:
```
--- FAIL: TestHandshakeReplaySome (12.40s)
replay_test.go:332: waited too long for tendermint to produce 6 blocks
```
> wait 5 sec for a block on CircleCI

- CHANGELOG.md
- cmd/tendermint/commands/lite.go
- cmd/tendermint/main.go
- lite/proxy/block.go
- lite/proxy/certifier.go
- lite/proxy/errors.go
- lite/proxy/errors_test.go
- lite/proxy/proxy.go
- lite/proxy/query.go
- lite/proxy/query_test.go
- lite/proxy/wrapper.go
Copy-paste of relevant files from cosmos-sdk so we can have `tendermint lite` server that proxies the tendermint RPC and does light client verification.
Haven't implemented `tendermint lite init` piece yet which is necessary for security, and deactivated some tests. Someone should clean/fix this up sometime when it's a little higher priority, but going to merge now since this was what motivated the "transparent websockets" fix and it will be useful for demoing eg. LotionJS
We should also make sure everything is nice and cleaned and ultimately put it under semver so that Cosmos-SDK can use `lite/proxy` where necessary
> initial port of cosmos-sdk basecli proxy

- consensus/common_test.go
- consensus/state.go
- consensus/types/height_vote_set_test.go
- lite/helpers.go
- types/block.go
- types/canonical_json.go
- types/priv_validator_test.go
- types/proposal.go
- types/proposal_test.go
- types/vote.go
- types/vote_set_test.go
- types/vote_test.go
Fixes issue #929
Store it as time.Timestamp locally, encode it as RFC3339 with milliseconds
before signing the canonical form.
> Add Timestamp to Proposal/Vote

- blockchain/store_test.go
Fixes:
```
panic: Panicked on a Sanity Check: can't encode times below 1970 [recovered]
panic: Panicked on a Sanity Check: can't encode times below 1970
goroutine 2042 [running]:
testing.tRunner.func1(0xc420e8c0f0)
/usr/local/go/src/testing/testing.go:711 +0x5d9
panic(0xcd9e20, 0xc420c8c270)
/usr/local/go/src/runtime/panic.go:491 +0x2a2
github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common.PanicSanity(0xcd9e20, 0xf8ddd0)
/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common/errors.go:26 +0x120
github.com/tendermint/tendermint/vendor/github.com/tendermint/go-wire.WriteTime(0x0, 0x0, 0x0, 0x1306440, 0xc4201607e0, 0xc420e31658, 0xc420e31680)
/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/go-wire/time.go:19 +0x11e …
```
> add missing Timestamp to Votes

- cmd/tendermint/commands/init.go
Fixes #989.
The original initialization sequence started to inexplicably
fail
```shell
tendermint unsafe_reset_all
tendermint init
tendermint node --proxy_app=dummy
```
used to fail with
```shell
ERROR: Failed to create node: Couldn't read GenesisDoc file: open
/Users/emmanuelodeke/.tendermint/genesis.json: no such file or directory
```
because the initialization sequence always assumed that the
genesisDoc would only be set if the privValidator was generated.
However, `tendermint unsafe_reset_all` only created the
`priv_validator.json` file which would mean that then running
`tendermint init` would never create the `genesis.json` file
which if following the recommended sequence would then fail
since the `genesis.json` was absent.
> cmd/tendermint: fix initialization file creation checks

- consensus/replay.go
- consensus/replay_test.go
- lite/dynamic_test.go
- lite/files/commit_test.go
- lite/files/provider_test.go
- lite/helpers.go
- lite/inquirer_test.go
- lite/performance_test.go
- lite/provider_test.go
- lite/static_test.go
- rpc/client/httpclient.go
- rpc/client/interface.go
- rpc/client/localclient.go
- rpc/client/rpc_test.go
- rpc/core/blocks.go
- rpc/core/consensus.go
- rpc/core/routes.go
- rpc/core/types/responses.go
- state/errors.go
- state/execution.go
- state/execution_test.go
- state/state.go
- state/state_test.go
- types/block.go
- types/results.go
- types/results_test.go
Address issue #952 
This is now maintained in state and save to the db.
TODO:
> Add results hash to header

- scripts/dist_build.sh
before:
0.14.0-'88f5f21d'
after:
0.14.0-88f5f21d
Fixes #1023
> remove quotes from `tendermint version`

- CHANGELOG.md
- blockchain/reactor.go
- blockchain/reactor_test.go
- consensus/common_test.go
- consensus/reactor.go
- consensus/replay.go
- consensus/replay_file.go
- consensus/replay_test.go
- consensus/state.go
- consensus/wal_generator.go
- evidence/pool.go
- evidence/pool_test.go
- evidence/reactor_test.go
- evidence/store_test.go
- node/node.go
- rpc/core/blocks.go
- rpc/core/consensus.go
- rpc/core/pipe.go
- state/db.go
- state/execution.go
- state/execution_test.go
- state/state.go
- state/state_test.go
- state/store.go
- state/validation.go
- state/validation_test.go
- types/events.go
- types/services.go
State is no longer mutable.
Move all methods mutating methods to be functions that return a new State.
Introduce `BlockExecutor` to handle `ApplyBlock`
> state: move methods to funcs

- README.md
Solidify in writing, the minimum Go version that
we support, as Go1.9.
> README: document the minimum Go version

- docs/ecosystem.rst
related to https://github.com/tendermint/aib-data/pull/16
instead of trying to force a pretty table in the ecosystem docs, we point to the site that has the ecosystem page and is rendered from this file: https://github.com/tendermint/aib-data/blob/master/json/ecosystem.json
> docs: update ecosystem.rst

- p2p/pex_reactor.go
- p2p/pex_reactor_test.go
Instead of counting msgs per peer, only accept Addr msgs if we requested them, and only accept new Request msgs every ensurePeersPeriod / 3 (divided by 3 to be more than lenient with time keeping)
> better abuse handling in pex

- mempool/mempool.go
- state/execution.go
- types/services.go
if we call it after, we might receive a "fresh" transaction from
`broadcast_tx_sync` before old transactions (which were not
committed).
Refs #1091
```
Commit is called with a lock on the mempool, meaning no calls to CheckTx
can start. However, since CheckTx is called async in the mempool
connection, some CheckTx might have already "sailed", when the lock is
released in the mempool and Commit proceeds.
Then, that spurious CheckTx has not yet "begun" in the ABCI app (stuck
in transport?). Instead, ABCI app manages to start to process the
Commit. Next, the spurious, "sailed" CheckTx happens in the wrong place.
```
> call FlushSync before calling CommitSync

- .gitignore
- CONTRIBUTING.md
- Vagrantfile
If you get an error, please run `vagrant box update`.
According to Vagrant policies the user should be `vagrant` and if a box uses a different user it is a shitty box. It seems that the ubuntu box was upgraded in the 2018 version to use `vagrant`.
So if `vagrant box list` gives you something with 2017, you should run `vagrant box update` and it should work.
> Fix Vagrantfile

- types/event_buffer.go
Fixes https://github.com/tendermint/tendermint/issues/1189
For every TxEventBuffer.Flush() invoking, we were invoking
a:
b.events = make([]EventDataTx, 0, b.capacity)
whose intention is to innocently clear the events slice but
maintain the underlying capacity.
However, unfortunately this is memory and garbage collection intensive
which is linear in the number of events added. If an attack had access
to our code somehow, invoking .Flush() in tight loops would be a sure
way to cause huge GC pressure, and say if they added about 1e9
events maliciously, every Flush() would take at least 3.2seconds
which is enough to now control our application.
The new using of the capacity preserving slice clearing idiom
takes a constant time regardless of the number of elements with zero
allocations so we …
> types: TxEventBuffer.Flush now uses capacity preserving slice clearing idiom

- cmd/tendermint/commands/root.go
- config/config.go
Also, we should allow "main" module to log INFO messages like
```
I[02-07|07:57:25.074] Found private validator                      module=main path=/home/vagrant/.tendermint/config/priv_validator.json
I[02-07|07:57:25.076] Found genesis file                           module=main path=/home/vagrant/.tendermint/config/genesis.json
```
Refs https://github.com/cosmos/gaia/issues/118
**BEFORE**:
```
$ tendermint init
```
**AFTER**:
```
$ tendermint init
I[02-07|07:57:25.074] Found private validator                      module=main path=/home/vagrant/.tendermint/config/priv_validator.json
I[02-07|07:57:25.076] Found genesis file                           module=main path=/home/vagrant/.tendermint/config/genesis.json
```
> With must be called on log.filter, otherwise "main" entries get filtered

- blockchain/reactor_test.go
- glide.lock
- glide.yaml
- mempool/mempool.go
- mempool/reactor.go
- mempool/reactor_test.go
- p2p/peer.go
- p2p/pex/pex_reactor_test.go
Leaking goroutine:
```
114 @ 0x42f2bc 0x42f3ae 0x440794 0x4403b9 0x468002 0x9fe32d 0x9ff78f 0xa025ed 0x45e571
```
Explanation:
it blocks on an empty clist forever. so unless theres txs coming in,
this go routine will just sit there, holding onto the peer too.
if we're constantly reconnecting to some peer, old instances are not
garbage collected, leading to memory leak.
Fixes https://github.com/cosmos/gaia/issues/108
Previous attempt https://github.com/tendermint/tendermint/pull/1156
> fix memory leak in mempool reactor

- lite/helpers.go
- lite/memprovider.go
- lite/performance_test.go
- lite/provider_test.go
Updates #1021
* Implement a GetHeightBinarySearch method that looks for
the height using the binary search algorithm guaranteeing
worst case iteration time of O(log2(n))
whereas
worst case iteration time of O(n) for the current linear search
So if n we had 500 commits stored by height and sorted, to
trigger the worst case scenario for each, pass in
the most negative height you can find e.g. -1
Linear search: 500 iterations
Binary search: 9 iterations
with n=1000, qHeight = -1
Linear search: 1000 iterations
Binary search: 10 iterations
with n=1e6, qHeight = -1
Linear search: 1e6 iterations
Binary search: 20 iterations
Of course there are realistic expectations e.g. a max of
commits that may be saved so linear search might be useful
for very small size set because it has less preparing …
> lite: memStoreProvider GetHeightBinarySearch method + fix ValKeys.signHeaders

- cmd/tendermint/commands/run_node.go
- config/config.go
- node/node.go
- types/priv_validator/socket.go
- types/priv_validator/socket_test.go
Following ADDR 008 the node will connect to an external process to handle signing requests. Operation of the external process is left to the user.
* introduce alias for PrivValidator interface on socket client
* integrate socket client in node
* structure tests
***
Follow-up to #1204 against #1203.
> privVal: Integrate socket client

- Makefile
Hi !
I prepared a pull request with minimalistic variant of tool that you described.
Deps analysis is similar to the one from Hackernoon article. Makefile recipe for it produces text file with list of dependencies and their sizes. They are sorted by size (the biggest at the top).
Resolves #1208
> adding recipe for minimalistic deps analysis

- consensus/state.go
- consensus/types/state.go
With this PR, the idea is to only cover the simplest scenario where having ValidBlock will help with the termination issue. The goal is having the following property assured: during synchronous period (after GST), in a round with a correct proposer, if some correct process locks a block v in round r, at the end of the round r, all correct processes will have lockedBlock = v or lockedBlock = nil, and validBlock = v. This ensures that in the following round, a (correct) proposer will be able to only propose v, and all correct processes will Prevote for v, and hopefully later commit a block. 
Please take a look @ebuchman @melekes. I will add tests after.
> Add support for ValidBlock mechanism for the simplest case

- docs/determinism.rst
- docs/index.rst
This is, admittedly, a half-measure but it gets the ball rolling on having a place to discuss determinism.
closes https://github.com/tendermint/abci/issues/56
> docs: add 'On Determinism'

- Gopkg.lock
- Gopkg.toml
- cmd/priv_val_server/main.go
- node/node.go
- types/priv_validator/socket.go
- types/priv_validator/socket_tcp.go
- types/priv_validator/socket_tcp_test.go
- types/priv_validator/socket_test.go
Follow-up to feedback from #1286, this change simplifies the connection handling in the SocketClient and makes the communication via TCP more robust. It introduces the tcpTimeoutListener to encapsulate accept and i/o timeout handling as well as connection keep-alive, this type could likely be upgraded to handle more fine-grained tuning of the tcp stack (linger, nodelay, etc.) according to the properties we desire. The same methods should be applied to the RemoteSigner which will be overhauled when the priv_val_server is fleshed out.
* require private key
* simplify connect logic
* break out conn upgrades to `tcpTimeoutListener`
* extend test coverage and simplify component setup
***
Belongs to #1255 with the original issue being #1307
> privVal: Improve SocketClient network code

- docs/specification/byzantine-consensus-algorithm.rst
Problems rendering the special characters for fraction in PDF.
> Documentation: The character for 1/3 fraction could not be rendered in PDF on readthedocs.

- consensus/mempool_test.go
- consensus/state.go
Prompted by thinking about https://github.com/tendermint/tendermint/issues/1281 and creating https://github.com/tendermint/tendermint/issues/1327
addVote had big if-blocks and returned errors at the end. Code is much clearer and less indented if we just return error right away
> addVote readability

- p2p/peer_test.go
We observed non-deterministic test failures in one of our switch tests, which would happen if the GC would run between iterations of the accept loop. As we don't hold any reference to the connection the setup finalizer might get triggered and therefore the file handle closed. For the curious check the references on finalizers and the variable scoping in the spec:
https://groups.google.com/forum/#!topic/golang-nuts/xWkhGJ5PY6c
https://groups.google.com/forum/#!topic/golang-nuts/d8aF4rAob7U/discussion
https://golang.org/ref/spec#Declarations_and_scope
Fixes #1266
> p2p: Keep reference to connections in test peer

- docs/specification/new-spec/bft-time.md
Clarify the BFT time spec to emphasise that the median is taking into account the voting power of the processes.
> Improve BFT time spec

- types/validator.go
It's a simple patch.
bytes.Compare(v.Address, other.Address) doesn't need to be called two times.
> Remove unnecessary bytes.Compare() call

- state/txindex/kv/kv.go
- state/txindex/kv/kv_test.go
Refs #1366
Also found and fixed a bug where we don't return multiple transactions (if range condition is being used). See commit msg for details.
> Tx Search should return txs in order by default

- types/block.go
Found a typo in block header while the tendermint node was streaming blocks.
This is my first commit, so please let me know if there is anything else I should do.
> fix typo on block header

- Makefile
Fix for #1395 - forces CGO to be disabled, hence enabling the compiler to automatically link statically.
> CGO_ENABLED=0 added for static linking

- lite/proxy/block.go
- lite/proxy/validate_test.go
- types/block.go
Updates https://github.com/tendermint/tendermint/issues/1017
Ensure that the Validate* functions in proxy are tests
and cover the case of sneakish bugs that have been encountered
a few times from nil dereferences. The lite package should
theoretically never panic with a nil dereference. It is meant
to contain the certifiers hence it should never panic with such.
Requires the following bugs to be fixed first;
* https://github.com/tendermint/tendermint/issues/1298
* https://github.com/tendermint/tendermint/issues/1299
> lite/proxy: Validation* tests and hardening for nil dereferences

- DOCKER/Dockerfile
- DOCKER/Dockerfile.develop
- DOCKER/README.md
Docker fails with:
```
./bin/tendermint
bash: ./bin/tendermint: No such file or directory
```
**DO NOT SQUASH**
> Update dockerfile and readme

- rpc/core/net.go
- rpc/core/types/responses.go
It is extremely helpful for network debugging to cross-reference between /net_info and dump_consensus_state. We switched from using ip addresses to describe peers to ID()s but we should have the necessary info the responses to cross-reference
> Net_info should print the ID of peers

- consensus/reactor.go
Fixes #1414
DATA RACE:
```
Read at 0x00c4214ee940 by goroutine 146:
github.com/tendermint/tendermint/consensus.(*peerStateStats).String()
<autogenerated>:1 +0x57
fmt.(*pp).handleMethods()
/usr/local/go/src/fmt/print.go:596 +0x3f4
fmt.(*pp).printArg()
/usr/local/go/src/fmt/print.go:679 +0x11f
fmt.(*pp).doPrintf()
/usr/local/go/src/fmt/print.go:996 +0x319
fmt.Sprintf()
/usr/local/go/src/fmt/print.go:196 +0x73
github.com/tendermint/tendermint/consensus.(*PeerState).StringIndented()
github.com/tendermint/tendermint/consensus/_test/_obj_test/reactor.go:1426 +0x573
github.com/tendermint/tendermint/consensus.(*PeerState).String()
github.com/tendermint/tendermint/consensus/_test/_obj_test/reactor.go:1419 +0x66
github.com/go-logfmt/logfmt.safeString() …
```
> protect Record* peerStateStats functions by mutex

- consensus/reactor.go
- consensus/state.go
- consensus/types/state.go
- rpc/core/consensus.go
- rpc/core/pipe.go
- rpc/core/types/responses.go
Closes #1442
```
WARNING: DATA RACE
Write at 0x00c4209de7c8 by goroutine 23:
github.com/tendermint/tendermint/types.(*Block).fillHeader()
/home/vagrant/go/src/github.com/tendermint/tendermint/types/block.go:88 +0x157
github.com/tendermint/tendermint/types.(*Block).Hash()
/home/vagrant/go/src/github.com/tendermint/tendermint/types/block.go:104 +0x121
github.com/tendermint/tendermint/types.(*Block).HashesTo()
/home/vagrant/go/src/github.com/tendermint/tendermint/types/block.go:135 +0x4f
github.com/tendermint/tendermint/consensus.(*ConsensusState).enterPrecommit()
/home/vagrant/go/src/github.com/tendermint/tendermint/consensus/state.go:1037 +0x182d
github.com/tendermint/tendermint/consensus.(*ConsensusState).addVote()
/home/vagrant/go/src/github.com/tendermint/tendermint/consensus/state.go:14 …
```
> fix data race

- cmd/tendermint/commands/show_node_id.go
- p2p/key.go
This is a simple fix, followed the discussion about this [issue](https://github.com/tendermint/tendermint/issues/1393) , the `show_node_id` function will  check the existence of related file first.
> improve `show_node_id`

- CHANGELOG.md
- p2p/CHANGELOG.md
- p2p/peer.go
- p2p/switch.go
- p2p/switch_test.go
> p2p: persistent - redial if first dial fails

- networks/local/localnode/Dockerfile
This is to avoid "ERROR: unknown flag: --proxy_app dummy" message when kicking "docker-compose up"
> Split CMD's param on space

- CHANGELOG.md
- docs/specification/new-spec/p2p/node.md
- docs/specification/new-spec/p2p/peer.md
- docs/specification/new-spec/reactors/pex/pex.md
- node/node.go
- p2p/errors.go
- p2p/netaddress.go
- p2p/node_info.go
- p2p/pex/addrbook.go
- p2p/pex/errors.go
- p2p/pex/known_address.go
- p2p/pex/params.go
- p2p/pex/pex_reactor.go
- p2p/switch.go
- p2p/test_util.go
- rpc/core/net.go
- rpc/core/types/responses.go
Replaces https://github.com/tendermint/tendermint/pull/1344
- reduce max pex msg size
- validate nodeInfo.ListenAddr
- clarify maxNumPeers (closes #1501) and update pex spec
- remove trust metric
- more explicit errors for addrbook.AddAddress and NewNetAddressFromString
- give NetAddress json tags in prep for using it in NodeInfo
- allow nodes to differ by minor version
- some cleanup
- a bunch of new comments/notes/todos
- a little #1476
> Cleanup P2P

- consensus/reactor.go
- consensus/state.go
- consensus/types/state.go
This sends votes even when the peer is in prevoteWait.  We could also get more intelligent and only send if we have 2/3, maybe.  In that case we'll need separate clauses for <= prevote and <= prevoteWait because if <= prevote, then we always went to send prevotes.
The same applies for precommits as for prevotes above.
> Suggested changes to consensus/reactor.go

- .github/ISSUE_TEMPLATE
- CHANGELOG.md
- consensus/replay_test.go
- consensus/state.go
- consensus/wal.go
- consensus/wal_generator.go
- node/node_test.go
Fixes https://github.com/tendermint/tendermint/issues/1589
Note this means it is possible to lose votes we have seen from the network before they result in us signing and sending a message. This wouldn't result in any corruption or safety issue, but it does introduce a dependence on the network for retransmission of messages we've already seen.
> consensus: only fsync wal after internal msgs

- types/validator_set.go
In the for loop of ValidatorSet.IncrementAccum(), Heap.Update() call is unnecessary when i == times - 1.
All tests of validator_set_test.go have passed.
> remove Heap.Update() call when setting Proposer field

- config/config.go
- p2p/peer_set.go
- p2p/peer_set_test.go
- p2p/pex/pex_reactor_test.go
- p2p/switch.go
- p2p/test_util.go
In some scenarios like tests we want to disable the guard which prevents peers connecting from the same ip.
> Introduce option to skip duplicate ip check

- .circleci/config.yml
- docs/app-architecture.rst
Motivated by https://github.com/tendermint/tendermint/pull/1577#discussion_r189188468 and other recent comments/work on the docs. This file seemed like it could be much reduced and improved ...
This would eliminate the nice diagram from https://tendermint.readthedocs.io/en/master/app-architecture.html#, but I'm not sure we should recommend that approach since we want people to find the LCD and the Interchain Standards sooner.
Should we bring the fancy network image into the repo, or is that link stable @nylira ?
Note it links to some open PRs and should be updated when theyre merged.
P.S Tendermint docs might be way better if they were organized into higher level sections:
- install
- tendermint core (CLI, RPC, config, genesis, running in production, spec, etc.)
- tendermint networks …
> gut docs/app-arch

- .circleci/config.yml
For post-mortem introspection it is helpful to have the full logs of test runs available for download.
> Store CI test logs

- CHANGELOG.md
- config/config.go
- config/toml.go
- docs/examples/node0/config/config.toml
- docs/examples/node1/config/config.toml
- docs/examples/node2/config/config.toml
- docs/examples/node3/config/config.toml
- docs/spec/p2p/peer.md
- docs/specification/configuration.rst
- docs/specification/secure-p2p.rst
- node/node.go
- p2p/peer.go
- p2p/peer_test.go
- p2p/switch.go
As we didn't hear any voices requesting this feature, we removed the
option to disable it and always have peer connection auth encrypted.
closes #1518
follow-up #1325
> Remove auth_enc config option

- .circleci/config.yml
It's currently breaking for unknown reasons, until fixed we going to
disable it, to not block on it for unrelated PRs.
> Disable slate step in CI workflow

- p2p/pex/pex_reactor_test.go
Ref [https://github.com/tendermint/tendermint/issues/1621](https://github.com/tendermint/tendermint/issues/1621)
Removed assertions in TestPEXReactorAddRemovePeer() in pex_reactor_test.go to avoid confusions, please check the above link to see the discussion on Riot channel.
> removed assertion to avoid confusion

- rpc/lib/server/handlers.go
- rpc/lib/server/handlers_test.go
Closes #1531 
Since the path "/" matches all paths not registered by other handlers I implemented a middleware to check whether the path is indeed "/" and otherwise return a 404 error.
Reference: https://golang.org/pkg/net/http/#ServeMux
> Return 404 for unknown RPC endpoints

- config/config.go
- p2p/conn/connection.go
- p2p/fuzz.go
- p2p/peer.go
- p2p/peer_test.go
- p2p/pex/pex_reactor_test.go
- p2p/switch.go
- p2p/switch_test.go
- p2p/test_util.go
As both configs are concerned with the p2p packaage and PeerConfig is only used inside of the package there is no good reason to keep the couple of fields separate, therefore it is collapsed into the more general P2PConifg. This is a stepping stone towards a setup where the components inside of p2p do not have any knowledge about the config.
follow-up to #1325
> Collapse PeerConfig into P2PConfig

- consensus/byzantine_test.go
This should fix the non-deterministic failures with this test.
Problem was the byzantine proposer would send the proposals before the others switched to consensus, so they ignored it (expected during fast sync), but then once they switched to consensus, they never receive anything, so halt forever.
With this change, everyone should be in consensus mode before the byz validator sends his messages
> fix byz-test

- config/config.go
- p2p/peer.go
- p2p/peer_test.go
- p2p/switch.go
Instead of mutating the passed in MConnConfig part of P2PConfig we just use the default and override the values, the same as before as it was always the default version. This is yet another good reason to not embed information and access to config structs in our components and will go away with the ongoing refactoring in #1325.
> Fix race when mutating MConnConfig

- docs/using-tendermint.md
Adds a description of seed and persistent peer nodes. There was some confusion about this when setting these for the latest testnet.
> Update description of seed and persistent peer nodes

- config/toml.go
Closes #1423
I changed the config template to use JS escaping for paths which is compatible with TOML. This replaces `\` with `\\` as backslashes need to be escaped in TOML.
This fixes config generation and parsing on windows.
> Escape paths in config template

- p2p/upnp/upnp.go
```
I[06-08|11:51:57.234] Getting UPNP external address                module=p2p
I[06-08|11:51:58.867] Got UPNP external address                    module=p2p address=
```
Fixes #1717
```
I[06-08|11:51:56.952] Starting multiAppConn                        module=proxy impl=multiAppConn
I[06-08|11:51:56.952] Starting localClient                         module=abci-client connection=query impl=localClient
I[06-08|11:51:56.952] Starting localClient                         module=abci-client connection=mempool impl=localClient
I[06-08|11:51:56.952] Starting localClient                         module=abci-client connection=consensus impl=localClient
I[06-08|11:51:56.952] ABCI Handshake                               module=consensus appHeight=0 appHash=
I[06-08|11:51:56.952] ABCI Replay Blocks …
```
> return an error if we fail to parse external IP

- cmd/tendermint/commands/reset_priv_validator.go
When executing `unsafe_reset_all` it also clear all IP addresses from
addrbook.json. This is the expected behaviour of `unsafe_reset_all`.
closes #1713
> `unsafe_reset_all` also resets addrbook.json

- CHANGELOG.md
- Gopkg.lock
- Gopkg.toml
- config/config.go
- config/toml.go
- docs/metrics.md
- docs/running-in-production.md
- docs/specification/configuration.md
- lite/proxy/proxy.go
- node/node.go
- rpc/grpc/client_server.go
- rpc/lib/rpc_test.go
- rpc/lib/server/http_server.go
- rpc/lib/server/http_server_test.go
- rpc/lib/test/main.go
Refs #1740
also, expose limit option for number concurrent streams for gRPC
(unlimited by default)
> limit number of open connections

- p2p/trust/metric.go
- p2p/trust/metric_test.go
Fix the following issue: https://github.com/tendermint/tendermint/issues/1765
> p2p/trust: Fix nil pointer error on TrustMetric Copy()

- CHANGELOG.md
- crypto/pub_key.go
- crypto/signature.go
* Created PubKeyEd25519Size as 32
* Created PubkeySecp256k1Size as 33
* Created SignatureEd25519Size as 64
Closes https://github.com/tendermint/go-crypto/issues/81
Note, I am not updating secret connection in this PR, in favor of https://github.com/tendermint/tendermint/pull/1563 being settled first.
> crypto: Abstract pubkey / signature size when known to constants

- blockchain/reactor.go
- consensus/reactor.go
- evidence/reactor.go
- mempool/reactor.go
- p2p/pex/pex_reactor.go
- p2p/pex/pex_reactor_test.go
Closes #646 
"let's unexport all of them and ensure their inputs aren't empty (even though reactors should guarantee the input is not empty)"
the second part is now handled by Amino.
> Unexport DecodeMessage

- CHANGELOG.md
- Gopkg.lock
- Gopkg.toml
- config/config.go
- config/toml.go
- docs/tendermint-core/configuration.md
- node/node.go
Closes #1804
Default to 1 because usually there's just one collector.
> limit the number of requests in flights for Prometheus server

- tools/tm-bench/main.go
This achieved by creating a new flagset. 
This should check-off `Remove testing flags from usage docs` in #1940
> tools/tm-bench: Remove testing flags from help

- CHANGELOG.md
- abci/client/socket_client.go
- abci/client/socket_client_test.go
Addressing issue #1890
Reproduced the errant behavior, and pushing to demo that.
Working on a solution.
> abciClient.BeginBlockSync should not hang on crashed server 

- scripts/install/install_tendermint_osx.sh
This PR adds an OSX install script. Instead of installing `golang` and other deps from scratch it prompts users to do so if they have not done so already.
closes #1931
> Add OSX install script

- tools/tm-bench/main.go
- tools/tm-bench/statistics.go
This PR moves statistics to its own file, seperates getBlockMetas
into its own function, and removes the timeEnd parameter from
calculate statistics. The ending time is now computed directly from
the start time and the duration, to enforce that we only collect
data for the provided duration.
The purpose of refactoring this is to reduce the amount of code in `main.go`, and to package the statistics related code together.
> tools/tmbench: Move statistics to a seperate file

- CHANGELOG.md
- config/config.go
- docs/tendermint-core/configuration.md
This increases the default send/recv rate from 512 kB/s to 5.12 mB/s
Closes #1752
> config: 10x default send/recv rate

- CHANGELOG.md
- libs/common/random.go
- libs/common/random_test.go
We were computing these functions incorrectly. I'm not sure what distribution
these numbers are, but it isn't the normal definition of exponential distribution. (We're making
the probability of getting a number of a particular bitlength equal, but the number in 
that bitlength thats gets chosen is uniformly chosen)
We weren't using these functions anywhere in our codebase, and they
had a nomenclature error. (There aren't exponentially distributed
integers, instead they would be geometrically distributed) While they were
implicitly part of RandTime, and rand.Time, neither of those functions were
used anywhere.
> common/rand: Remove exponential distribution functions

- blockchain/pool_test.go
- libs/clist/clist_test.go
- libs/common/os_test.go
- libs/common/repeat_timer_test.go
- libs/events/events_test.go
- lite/performance_test.go
- p2p/peer_set_test.go
- p2p/pex/addrbook_test.go
- rpc/lib/rpc_test.go
- types/event_bus_test.go
This commit switches all usage of math/rand to cmn's rand. The only
exceptions are within the random file itself, the tools package, and the
crypto package. In tools/tm-bench you don't want it to lock between the go-routines.
The crypto package doesn't use it so the crypto package has no other
dependencies within tendermint/tendermint for easier portability.
Crypto/rand usage is unadjusted.
Closes #1343
> Switch usage of math/rand to cmn's rand

- CHANGELOG.md
- libs/common/random.go
- libs/common/random_test.go
The godocs fell out of sync with the code here. Additionally we had
warning that these randomness functions weren't for cryptographic
use on every function. However these warnings are confusing, since
there was no implication that they would be secure there, and a
single warning on the actual Rand type suffices. (This is what
is done in golang's math/rand godoc) These warnings being present
seemed to imply that there was a method that was suitable for cryptographic
usage.
Additionally we indicated that rand.Bytes() was reading OS randomness
but in fact that had been changed.
> libs/common/rand: Update godocs

- README.md
To address the relocation of terraform-and-ansible.md under networks/, as per https://github.com/tendermint/tendermint/commit/e54c0f804faa3d4a6c0c1ada0288c07d2a49ce50
> A link fixed

- .circleci/config.yml
- Makefile
- test/test_cover.sh
This was used in conjunction with `go list <path>`, however `go list`
already ignores the vendor directory. (It appears that this wasn't always the case, haven't been able to track down which version of go introduced this) This makes the `grep -v` redundant.
> tools: Remove redundant grep -v vendors/

- config/config.go
- config/toml.go
- docs/tendermint-core/configuration.md
- node/node.go
- p2p/pex/addrbook.go
- p2p/pex/addrbook_test.go
- p2p/pex/errors.go
- p2p/pex/pex_reactor.go
- p2p/pex/pex_reactor_test.go
Fixes #1705 by tracking private peer IDs in the AddrBook, and blocking when AddAddress is called.
> Add private peer ID tracking to AddrBook

- crypto/ed25519/ed25519.go
- crypto/ed25519/ed25519_test.go
This commit updates the godocs for the package, and adds an optimization
to the privkey.Pubkey() method.
The optimization is that in golang, the private key (due to interface
compatibility reasons) has a copy of the public key stored inside of it.
Therefore if this copy has already been computed, there is no need to
recompute it.
> crypto/ed25519: Update the godocs

- crypto/ed25519/ed25519.go
- crypto/ed25519/ed25519_test.go
The privkey.Generate method here was a custom-made method for deriving
a private key from another private key. This function is currently
not used anywhere in our codebase, and has not been reviewed enough
that it would be secure to use. This removes that method. We should
adopt the official ed25519 HD derivation once that has been standardized,
in order to fulfill this need.
closes #2000
> crypto/ed25519: Remove privkey.Generate method

- rpc/core/status.go
- rpc/core/status_test.go
Refs #1772 
validator power is `0` when consensus halts
don't think we should do the same for /dump_consensus_state or /consensus_state endpoints cause their entire output depends on consensus state, which we can't get due to mutex.
> make `/status` RPC endpoint resistant to consensus halt

- rpc/core/status.go
Haven't been able to replicate https://github.com/tendermint/tendermint/issues/1772 and don't want to lose sight of what might be going on there so at least adding this log line
> rpc: log error when we timeout getting validators from consensus

- .circleci/config.yml
- CHANGELOG_PENDING.md
- Gopkg.lock
- Gopkg.toml
- Makefile
- test/docker/Dockerfile
This adds a new makefile command, which is used in CI linting, `make check_dep`.
This ensures the toml is in sync with the lock, and that were not pinning to a
branch in any repository.
This also adapts `make get_vendor_deps` to check the lock, in addition to
populating the vendor directory. This removes the need for `make ensure_deps`.
This makes `make get_vendor_deps` consistent between tendermint and the sdk.
This would stop problems like #2053 from happening.
> makefile: Add `make check_dep` and remove `make ensure_deps`

- crypto/ed25519/bench_test.go
- crypto/ed25519/ed25519.go
- crypto/internal/benchmarking/bench.go
- crypto/secp256k1/bench_test.go
- crypto/secp256k1/secp256k1.go
This does a slight refactor for the key generation code. It now calls a
seperate unexported method to allow generation from a reader. I think this
will actually reduce time in generation, due to no longer initializing an
extra slice. This was needed in order to enable benchmarking.
This uses an internal package for the benchmarking code, so that this can
be standardized without being exported in the public API. The benchmarking
code is derived from agl/ed25519's benchmarking code, and has copied the
license over.
Closes #1984
> crypto: Add benchmarking code for signature schemes

- CHANGELOG.md
- CHANGELOG_PENDING.md
- Gopkg.lock
- docs/spec/p2p/peer.md
- p2p/conn/secret_connection.go
This PR updates secret connection to remove the ripemd primitive, and the salsa primitive. This gives us a resulting secret connection that looks alot more `noise` like. 
This switches the sender and receiver to use different keys, similar to what noise does. We now use a single hkdf-sha2 invocation on the diffie hellman secret to generate the two keys and a challenge. 
Closes #2039
> secret connection update

- CHANGELOG.md
- blockchain/wire.go
- consensus/types/wire.go
- consensus/wire.go
- lite/files/wire.go
- rpc/core/types/wire.go
- types/wire.go
- version/version.go
Register codecs more properly, refactor/dry code to prevent issues in the future.
> HotFix for 0.22.7, bump to 0.22.8

- CHANGELOG_PENDING.md
- libs/common/bit_array.go
This now makes bit array functions which take in a second bit array, thread
safe. Previously there was a warning on bitarray.Update to be lock the
second parameter externally if thread safety wasrequired.
This was not done within the codebase, so it was fine to change here.
Closes #2080
> libs: Make bitarray functions lock parameters that aren't the caller

- consensus/common_test.go
- consensus/reactor_test.go
Previous evidence test rushed into v0.22.7 was broken for a couple of reasons, including because of the way it had to overwrite the evidence pool in the default ConsensusState set up by the tests.
Also discovered:
- you can't use `require` in go-routines
- we're overwriting the stateDB in `newConsensusStateWithConfigAndBlockStore`
The stateDB issue hasn't mattered because until now because the consensus tests have not depended on the state. But to validate evidence you have to look up a validator set in the state, so we need a proper stateDB.
Here we unroll the test setup function so we can make sure we have a single coherent stateDB and a properly injected evidence pool. 
We're probably overdue for a review and cleanup of these test functions ...
> consensus: Fix test for blocks with evidence

- libs/autofile/group_test.go
Previously we logged `Testing for i <i>` for all i in [0,100).
This was unnecessary. This changes it to just log the value for i on
error messages, to reduce the unnecessary verbosity in the circle log files for testing.
> libs/autofile/group_test: Remove unnecessary logging

- .circleci/config.yml
This commit makes it such that circle CI only shows the module whose
tests it is currently running in the log, unless a test fails. For each
failing test, it will display the name of all failing tests, along with
their log output. This is done to make
our log output far more scrollable. We lose no information in debugging.
An example with `go test`:
I added t.Log("test name") and t.Fail() to the bottom of two tests, and then ran go test, the following log output appeared:
```
go test
--- FAIL: TestErrorPanic (0.00s)
errors_test.go:30: TESTERRORPANIC
--- FAIL: TestErrorNewErrorWithTrace (0.00s)
errors_test.go:97: TestErrorNewErrorWithTrace
```
(This test code is not in the commit, its just meant to show how it works)
Take a look at the CI logs!
> ci: Reduce log output in test_cover

- docs/app-dev/app-development.md
> [docs] validator's address can be skipped in ResponseEndBlock

- consensus/common_test.go
- libs/autofile/autofile_test.go
- libs/common/tempfile.go
- libs/db/backend_test.go
- libs/db/common_test.go
- privval/priv_validator_test.go
Our Tempfile was just a wrapper on ioutil that panicked instead of error.
Our Tempdir was a less safe variant of ioutil's Tempdir.
They have both been removed in favor of ioutil. If my other write file atomic PR is merged first, please rebase this onto develop.
Ref https://github.com/tendermint/tendermint/pull/2113#discussion_r206333777
> libs/cmn: Remove Tempfile, Tempdir, switch to ioutil variants

- CHANGELOG_PENDING.md
- consensus/common_test.go
- libs/autofile/autofile_test.go
- libs/common/os.go
- libs/common/os_test.go
- libs/common/tempfile.go
- libs/common/tempfile_test.go
- libs/db/backend_test.go
- libs/db/common_test.go
- privval/priv_validator_test.go
This uses the stdlib's method of creating a tempfile in our write
file atomimc method, with a few modifications. We use a 64 bit number
rather than 32 bit, and therefore a corresponding LCG. This is to
reduce collision probability. (Note we currently use 24 bytes of entropy,
so switching to 32 bits is a significant change. 
We can move from 64 bits to 32 bits in the future)
We handle reseeding the LCG in such a way that multiple threads are
even less likely to reuse the same seed. 
Before if two processes were spawned that needed write file atomics at the same time, then there is a decent chance of seed collision. This is now less likely.
I'm working on writing a test case to demonstrate all the behaviors are working correctly.
Closes #2109
> libs: AtomicWriteFile filename collision fixes

- CHANGELOG_PENDING.md
- p2p/pex/pex_reactor.go
- p2p/pex/pex_reactor_test.go
This is to reduce wait times when initially connecting. This still runs checks
such as whether you still want additional peers.
A test case has been created, which fails if this change is not included.
This is to reduce wait times when initially connecting. This still runs checks
such as whether you still want additional peers.
A test case has been created, which fails if this change is not included.
Closes #2093
> p2p/pex: Connect to peers from a seed node immediately

- docs/architecture/adr-018-ABCI-Validators.md
Some minor changes to improve the usability of the ABCI, and to properly include the round number.
See markdown at: https://github.com/tendermint/tendermint/blob/279259ec8efb75d4dd2ebd5095c06892ff327804/docs/architecture/adr-018-ABCI-Validators.md
> [ADR] ABCI Validators

- docs/architecture/adr-016-protocol-versions.md
Partial replacement for https://github.com/tendermint/tendermint/pull/1983
- Reduced Scope
- Remove limits on p2p compatibility to simplify syncing old nodes (from different versions)
- Address some TODOs
- use ResponseEndBlock fields to update versions
Still need a decision re p2p-handshake versioning (in case we need to change something about the auth-encryption !)
Adopted 016
> adr: protocol versioning

- docs/architecture/adr-017-chain-versions.md
Partial replacement for #1983. Just copied over this file directly from there. It's still a WIP.
ADR-016 (https://github.com/tendermint/tendermint/pull/2144) should come first. It's targetting the #2144 branch but once that's merged we can change to develop
> adr: chain-versions

- mempool/mempool.go
Hi there.
I think it should be fixed to specify capacity of `txsMap` for performance improvement.
> fix map capacity

- docs/architecture/adr-012-ABCI-propose-tx.md
This adds an ADR entry addressing the implementation of a `ProposeTx`
method in the ABCI proposed in #1776. Fundamentally, this proposal gives
some control of block proposals to the application. The initial use case is
to support the Minimal Viable Plasma specification.
cc @ebuchman
> [ADR] ProposeTx

- CHANGELOG_PENDING.md
- mempool/mempool.go
- mempool/mempool_test.go
This removes bugs with the linked list being full, but hashmap empty.
Ref #2180
> mempool: Keep cache hashmap and linked list in sync

- libs/common/cmap.go
- libs/common/cmap_test.go
All functions in cmap have just one code path. Thus there is not a reason
to use defer statements. (Only having one code path makes what is going on quite clear)
Before:
```
BenchmarkCMapHas-8   	20000000	        73.9 ns/op	       0 B/op	       0 allocs/op
```
After:
```
BenchmarkCMapHas-8   	50000000	        36.9 ns/op	       0 B/op	       0 allocs/op
```
> libs/common/cmap: Remove defers

- libs/clist/bench_test.go
- libs/clist/clist.go
We used unnecessary function calls, defers, and extra mutexes.
These are not our friends for writing fast code in our libs.
`defer()` was removed because these functions only had one or two code paths, so the minute increase in code complexity seems justified to me. I do think defers should be used outside of libs or in libs whenever there are several code paths. 
Before:
```
BenchmarkDetaching-8   	 5000000	       263 ns/op	       0 B/op	       0 allocs/op
BenchmarkRemoved-8     	20000000	        98.8 ns/op	       0 B/op	       0 allocs/op
BenchmarkPushBack-8    	 2000000	       637 ns/op	     328 B/op	       5 allocs/op
```
After:
```
BenchmarkDetaching-8   	20000000	       111 ns/op	       0 B/op	       0 allocs/op
BenchmarkRemoved-8     	20000000	        61.4 ns/op	       0 B/op …
```
> clist: Speedup functions

- p2p/conn/secret_connection.go
Minor change that implements #2263.
Looks like circelci fails because this comes from a fork?
> update secret connection to use a little endian encoded nonce

- CHANGELOG_PENDING.md
- libs/db/go_level_db.go
- libs/db/go_level_db_test.go
This is meant to allow Cosmos SDK to create and handle read-only leveldb instances.
Closes: #2292
> New NewGoLevelDBWithOpts() to pass opts down to goleveldb

- .circleci/codecov.sh
- .circleci/config.yml
CircleCI `upload_codecov` step sometimes fails with:
```
#!/bin/bash -eo pipefail
bash <(curl -s https://codecov.io/bash) -f coverage.txt
/dev/fd/63: line 1: html: No such file or directory
/dev/fd/63: line 2: syntax error near unexpected token `<'
'
Exited with code 2
```
We should cache the codecov bash script to avoid downloading it every time.
> cache codecov script

- CHANGELOG_PENDING.md
- config/config.go
- consensus/mempool_test.go
This reduces the mempool size from 100k to 5k. Note that each secp256k1 sig
takes .5ms to compute. Therefore an adversary could previously delay every
node on the network's computation time upon receiving a block by 50 seconds.
This now reduces that ability to being able to only delay each node by 2.5
seconds. This change should be reverted once ABCI recheck is implemented.
ref #2127 
I think this should be included next release, to improve network resiliency.
> config: reduce default mempool size

- CHANGELOG.md
- libs/autofile/autofile.go
- libs/autofile/group.go
- version/version.go
Trying to understand why https://github.com/tendermint/tendermint/issues/2259 is happening.
Looks like could be due to the changes in https://github.com/tendermint/tendermint/pull/2135, where we may have accidentally removed these loops.
> libs/autofile: bring back loops

- abci/README.md
Previously https://github.com/tendermint/tendermint/pull/2301
> update outdated abci-cli install instructions

- CHANGELOG_PENDING.md
- state/txindex/kv/kv.go
Partially fixed https://github.com/tendermint/tendermint/issues/2051 to make rest api request like http://127.0.0.1:8080/txs?tag=tx.height=1330 work
This is tested against our ABCI application which relies on cosmos default Send msg tx.
To make sure this change works, I:
0. change config.toml file: `index_all_tags=true` and `timeout_commit=30000` (so that 2 transactions issued manually can be included in same block
1. started local test net in 4 docker container
2. restored two accounts for different home (so that I can run 2 gaiacli to make transaction at the same time)
3. transfer coins "at the same time"
4. start a node rest api-server and check **http://127.0.0.1:8080/txs?tag=tx.height=1330**
I can get json response like:
```
[  
{  
hash:"798E4CE82A5CFEB65E9DECD3F4D00F9753509FE7", …
```
> #2051 Make kv index for tx.height

- CHANGELOG_PENDING.md
- config/config.go
- node/node.go
- node/node_test.go
Refs https://github.com/tendermint/tendermint/issues/2294
> Delay starting node until Genesis time

- docs/spec/p2p/peer.md
- p2p/node_info.go
and fix formatting
Refs https://github.com/tendermint/tendermint/pull/2417#discussion_r218080500
> [spec] add missing field to NodeInfoOther

- consensus/replay_file.go
- consensus/replay_test.go
- consensus/wal_generator.go
- node/node.go
- proxy/multi_app_conn.go
- state/execution_test.go
Handshaker was removed from proxy package so it can be called
independently of starting the abci app connections and can return a
result to the caller.
Ref https://github.com/tendermint/tendermint/issues/2436
> proxy: remove Handshaker from proxy pkg

- docs/architecture/adr-021-abci-events.md
Follow up to https://github.com/tendermint/tendermint/pull/2314
Realized we could get "events" from a single list of tags by just including a "special" tag that separates groups of tags constituting an event.
@melekes @cwgoes @ValarDragon faboweb thoughts?
> adr-021: note about tag spacers

- rpc/core/consensus.go
- rpc/core/routes.go
- rpc/core/types/responses.go
> Added /consensus_params endpoint 

- CHANGELOG_PENDING.md
- rpc/lib/server/http_server.go
- rpc/lib/server/http_server_test.go
When http.ServeTLS() fails, StartHTTPAndTLSServer() logs the error then hangs for ever.
It should instead pass the error back to the caller.
Closes: #2460
> Pass http.ServeTLS() errors back to the caller

- CHANGELOG_PENDING.md
- config/config.go
- docs/tendermint-core/running-in-production.md
This should reduce file IO and disk space. For those, who want better guarantees, a note in https://tendermint.com/docs/tendermint-core/running-in-production.html is left of how to enable mempool WAL. In the future, we may want to provide better support and tooling for the mempool WAL recover procedure.
Not sure the measurements below are correct, but that's better than having no pictures 😃 These were taken using `iostat -yd 5` while tendermint (kvstore) & tm-bench were running in parallel inside my virtual box.
> mempool: Disable WAL by default

- libs/common/bit_array.go
- libs/common/bit_array_test.go
This is original code:
if bA.Bits > o.Bits {
c := bA.copy()
for i := 0; i < len(o.Elems)-1; i++ {
c.Elems[i] &= ^c.Elems[i]
}
i := len(o.Elems) - 1
if i >= 0 {
for idx := i * 64; idx < o.Bits; idx++ {
c.setIndex(idx, c.getIndex(idx) && !o.getIndex(idx))
}
}
return c
}
this part,
c := bA.copy()
for i := 0; i < len(o.Elems)-1; i++ {
c.Elems[i] &= ^c.Elems[i]
}
I don't understand, is it wrong?
> Is there a bug in bit_array's sub function?

- CHANGELOG_PENDING.md
- libs/common/bit_array.go
- libs/common/bit_array_test.go
This significantly simplifies subtraction logic. I suspect it also significantly speeds it up due to defer removal.
> bit_array: Simplify subtraction

- CHANGELOG_PENDING.md
- libs/common/bit_array.go
- libs/common/bit_array_test.go
Previously it was very biased. 63 "_" followed by a single "x" had
much greater odds of being chosen. Additionally, the last element was
skewed. This fixes that by first preproccessing the set of all true
indices, and then randomly selecting a single element from there.
This commit also makes the code here significantly simpler, and
improves test cases.
> Fix random distribution in bitArray.PickRandom

- p2p/netaddress.go
- p2p/netaddress_test.go
fix #2071
Signed-off-by: phymbert <pierrick.hymbert@gmail.com>
> [p2p] Malformed external address causes SIGSEGV (if URL has empty host)

- libs/events/events_test.go
> libs: Test deadlock from listener removal inside callback

- CHANGELOG_PENDING.md
- crypto/merkle/simple_map.go
- crypto/merkle/simple_map_test.go
- crypto/merkle/simple_proof.go
- crypto/merkle/simple_tree.go
- crypto/merkle/simple_tree_test.go
- crypto/merkle/types.go
- types/block.go
- types/encoding_helper.go
- types/evidence.go
- types/params.go
- types/part_set.go
- types/results.go
- types/tx.go
- types/validator.go
- types/validator_set.go
This PR is fully backwards compatible in terms of function output!
(The Go API differs though) The only test case changes was to refactor
it to be table driven.
> crypto/merkle: Remove byter in favor of plain byte slices

- privval/socket.go
This is a quick-fix for https://github.com/tendermint/tendermint/issues/2027.
The problem is that we set the deadline once, but need to reset each time we want to read, else the first deadline will expire at some random later read.
Also note this is using the default. It seems the ability to use the options has been eliminated? We probably want to bring that back, and actually use an internal, configured value for the read deadline rather than the default.
> privval: set deadline in readMsg

- CHANGELOG_PENDING.md
- state/state.go
- state/state_test.go
> [R4R] Pass nil to NewValidatorSet() when genesis file's Validators field is nil

- crypto/merkle/simple_tree.go
This also saves allocating the hashes array.
> merkle: Remove unnecessary layer of indirection

- CHANGELOG_PENDING.md
- crypto/merkle/simple_proof.go
- crypto/merkle/simple_tree.go
- types/block.go
- types/evidence.go
- types/tx.go
This is a performance regression, but will also spare the types directory
from knowing about RFC 6962, which is a more correct abstraction. For txs
this performance hit will be fixed soon with #2603. For evidence, the
performance impact is negligible due to it being capped at a small number.
Closes #2612
> Make txs and evidencelist use merkle.SimpleHashFromBytes to create hash

- docs/.vuepress/config.js
We need Google Analytics to start measuring how many developers are viewing our documentation. That way we can gauge how successful and useful various pages are. VuePress supports GA and all we have to provide is the tracking code.
This PR also renames the static docs site to "Tendermint Documentation", which is a better representation of the contents than only "Tendermint Core".
> add Google Analytics for documentation pages

- CHANGELOG_PENDING.md
- docs/spec/blockchain/encoding.md
- types/block.go
Closes #1841 
We should try to write a test for this, probably using reflect so we can ensure that if the order of fields in the header changes, the test will fail. 
We should probably look to remove SimpleHashFromMap altogether, but that will need buy-in from the SDK.
> types: dont use SimpleHashFromMap for header. closes #1841

- benchmarks/codec_test.go
- node/node.go
- p2p/node_info.go
- p2p/peer_test.go
- p2p/test_util.go
- state/state.go
- types/protobuf_test.go
Set the protocol versions in the NodeInfo from the state, not from the globals.
Also avoid use of some Validator literals
> Set protocol versions in NodeInfo from state

- rpc/lib/server/http_server.go
This PR is for suppressing warning log.
> fix `RecoverAndLogHandler` not to call multiple writeheader

- CHANGELOG_PENDING.md
- docs/architecture/adr-001-logging.md
- libs/log/tmfmt_logger.go
According to https://github.com/tendermint/tendermint/issues/2706, I encountered a problem about log format collecting logs to ELK stack for lacking year in timestamp.
Our log format before is:
```
NOTE[04-25|14:45:08] ABCI Replay Blocks                       module=consensus appHeight=0 storeHeight=0 stateHeight=0
```
I want to change it to 
```
NOTE[2017-04-25|14:45:08] ABCI Replay Blocks                       module=consensus appHeight=0 storeHeight=0 stateHeight=0
```
It will help a lot to analyze logs for us.
> [R4R] libs/log: add year to log format

- CHANGELOG_PENDING.md
- crypto/merkle/proof.go
- crypto/merkle/proof_test.go
General Merkle ProofOperator was iterating over the keys in the wrong order.  The keypath should start with the last operation to run (e.g. the top-level root hash operation), not end with it.
NOTE: This is related to https://github.com/cosmos/cosmos-sdk/pull/2633/files
> Fix general merkle keypath to start w/ last op's key

- crypto/crypto.go
- crypto/ed25519/ed25519.go
- crypto/merkle/simple_map_test.go
- crypto/tmhash/hash.go
- crypto/tmhash/hash_test.go
- docs/spec/blockchain/blockchain.md
- docs/spec/blockchain/encoding.md
- docs/spec/blockchain/state.md
- p2p/key.go
- state/validation.go
- types/block.go
- types/block_test.go
- types/evidence.go
- types/validator.go
- types/vote.go
- types/vote_test.go
Closes #1990 
Change TMHASH to 32-bytes.
Include TMHASHTruncated as TMHASH[:20]
Add `crypto.AddressSize = TMHASHTruncated.Size`
> TMHASH is 32 bytes. Closes #1990

- docs/architecture/adr-033-pubsub.md
- docs/architecture/adr-template.md
> [ADR] [DRAFT] pubsub 2.0

- mempool/mempool.go
- mempool/mempool_test.go
We weren't returning error when failing PreCheck before.
> mempool: ErrPreCheck and more log info

- CHANGELOG_PENDING.md
- config/config.go
- mempool/mempool.go
- mempool/mempool_test.go
- node/node.go
> Mempool WAL is still created by default in home directory, leads to permission errors

- CHANGELOG_PENDING.md
- p2p/peer.go
Seems to have been overlooked when introduced in https://github.com/tendermint/tendermint/pull/2425
Is the cause of https://github.com/tendermint/tendermint/issues/2766 (tested manually).
Opened https://github.com/tendermint/tendermint/issues/2770 so we catch this in tests next time!
> p2p: peer-id -> peer_id

- CHANGELOG.md
- p2p/netaddress.go
- p2p/node_info.go
- p2p/pex/addrbook.go
- p2p/pex/errors.go
- p2p/pex/pex_reactor.go
- p2p/switch.go
This solves an issue of having peers without IDs in the address book.
It also fixes #2773, which was a likely cause of there being peers without IDs in the address book in the first place.
It also includes a temporary hack fix for #2092.
> HOTFIX: AddressBook requires addresses to have IDs; Do not close conn immediately after sending pex addrs in seed mode

- consensus/reactor.go
> check the result of `PeerState.peer.Send` before calling `PeerState.setHasVote`

- CHANGELOG.md
- docs/architecture/adr-034-priv-validator-file-structure.md
03-11-2018: Initial Draft
For now, the PrivValidator file `priv_validator.json` contains mutable and immutable parts. 
Even in an insecure mode which does not encrypt private key on disk, it is reasonable to separate 
the mutable part and immutable part.
References:
[#1181](https://github.com/tendermint/tendermint/issues/1181)
[#2657](https://github.com/tendermint/tendermint/issues/2657)
[#2313](https://github.com/tendermint/tendermint/issues/2313)
We can split mutable and immutable parts with two structs:
```go
// PVKey stores the immutable part of PrivValidator
type PVKey struct {
Address types.Address  `json:"address"`
PubKey  crypto.PubKey  `json:"pub_key"`
PrivKey crypto.PrivKey `json:"priv_key"`
filePath string
mtx      sync.Mutex
}
// PVState stores the mutable part of …
```
> [R4R] Add adr-034: PrivValidator file structure

- Gopkg.lock
- Gopkg.toml
fixes int overflow that prevent `tendermint` from building on RPi
> update to amino 0.14.1

- Gopkg.lock
- Gopkg.toml
(at least those with releases)
because
- they are locked in .lock file already
- individual dependencies can be updated with `dep ensure -update XXX`
- review process (and ^^^) should help us prevent accidental updates
Closes #2798
> do not pin deps to exact versions

- CHANGELOG_PENDING.md
- p2p/conn/connection.go
Addresses https://github.com/tendermint/tendermint/issues/1817
It's the responsibility of callers to check if the send failed and act appropriately.
> p2p: log 'Send failed' on Debug

- CHANGELOG_PENDING.md
- mempool/mempool.go
- mempool/mempool_test.go
> mempool: add txs from Update to cache

- CHANGELOG_PENDING.md
- mempool/mempool.go
Within every tx in the mempool, we store a 64 bit counter,
as an index for when it was inserted into the mempool.
This counter doesn't really serve any purpose.
It was likely added for debugging at one point,
Removing the counter reclaims memory,
which enables greater mempool sizes / mitigates resources at the same size.
Closes #2835
> Remove counter from every mempoolTx

- consensus/types/peer_round_state.go
- consensus/types/round_state.go
- p2p/node_info.go
- types/block.go
- types/block_meta.go
Reffer to #2705 
* updated the comment for marshal and unmarshal methods which was created to make protobuf 
compatible.
* Added the marshal,unmarshal,size and MarshalTo methods  for nodeinfo.go
> Updated Marshal and unmarshal methods to make compatible with protobuf

- CHANGELOG_PENDING.md
- libs/db/backend_test.go
- libs/db/c_level_db.go
- libs/db/fsdb.go
- libs/db/go_level_db.go
- libs/db/mem_db.go
- libs/db/prefix_db.go
- libs/db/prefix_db_test.go
- libs/db/types.go
- libs/db/util.go
- lite/dbprovider.go
This makes dbm.DB.ReverseIterator have the same API as the cosmos sdk's store.Store.ReverseIterator (they share the same interface, as that was the intent).
It turns out that the CosmosSDK's store.Store.ReverseIterator API as currently implemented is both different and better than what we have now in tendermint/libs/db.
* In the CosmosSDK's version, start/end have the same semantics as the forward Iterator.
* This not only makes it easier to switch between forward and reverse iteration given the same range, but it also makes it possible to reverse-iterate on a prefix easily, whereas the current tendermint/libs/db.DB.ReverseIterator requires more finangling to make it iterate over a prefix, namely skipping the first item.  This is reflected in the code change here as code simplification.
* …
> R4R: Swap start/end in ReverseIterator

- rpc/core/events.go
If we trying to use examples from [WS RPC docs](https://tendermint.com/rpc/#subscribe), we getting such panic: 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x1643589]
goroutine 1 [running]:
github.com/daniildulin/rpc-test/vendor/github.com/tendermint/tendermint/rpc/lib/client.(*WSClient).Call(0x0, 0x1a1e480, 0xc000012f00, 0x183227a, 0x9, 0xc000817c30, 0x20, 0x18)
```
This happens because we need to start client service before using WS methods like `Subscribe`/`Unsubscribe`.
> Add client.Start() to RPC WS docs

- CHANGELOG_PENDING.md
- types/validator_set.go
- types/validator_set_test.go
Fixes regression in v0.26.4 https://github.com/tendermint/tendermint/issues/2937
We should backport this to v0.26.5 as well.
We should also write a test for the case where the genesis has no validators (allowed, since they can be set by InitChain), since this is what the SDK and more advanced apps will do ...
> types: NewValidatorSet doesn't panic on empty valz list

- consensus/replay_test.go
- p2p/key.go
- p2p/peer_test.go
- p2p/pex/addrbook.go
- p2p/pex/pex_reactor_test.go
- p2p/test_util.go
- rpc/core/pipe.go
- rpc/core/types/responses.go
- tools/tm-monitor/monitor/node.go
This is non-breaking, we just missed a few spots when previously merging the repos.
> remove unnecessary "crypto" import alias

- types/validator_set.go
- types/validator_set_test.go
This PR adds two basic tests for `IncrementProposerPriority` (formerly IncrementAccum). It would have caught what Jae described in #2809:
> IncrementAccum() was written to efficiently calculate the accum as if IncrementAccum(1) was called times times, but clipping as implemented breaks this invariant.
Additionally, it fixes a `randValidator_()` and `randValidatorSet()` which are used in tests and would cause non-deteministic panics.
Part of #2942. Tests which test the whole turnaround in `state` in a follow-up PR.
> Add some ProposerPriority tests 

- types/validator_set.go
explicitly type `MaxTotalVotingPower` to `int64`
fixes #2952 
Tested build in 32 bit ubuntu docker image. Some tests still use ints interchangeably with int64 (e.g. `types/block_test.go:259:39: constant 9223372036854775807 overflows int`) but the build will succeed...
> Fix 32-bit builds

- CHANGELOG_PENDING.md
- rpc/core/mempool.go
`deliverTxResCh`, like any other eventBus (pubsub) channel, is closed when eventBus is stopped. We must check if the channel is still open. The alternative approach is to not close any channels, which seems a bit odd.
Fixes #2408
> rpc: broadcastTxCommit: check if deliverTxResCh is still open, return an err otherwise

- node/node.go
This allows the node to start even if the latest block protocol version for the node is ahead of that found in the state. This means the node has code for a newer block protocol version than the blockchain it's running on. Unless the logic for the new version is written carefully, this could lead the node to fall out of consensus. 
The only change from block protocol `7` to `8` was validation based on PubKeyTypes. So if the only type being used was ED25519, the change won't cause any problems.
To make the change from 7 to 8 fully backwards compatible, the code that validates against PubKeyTypes should only be run if the `state.Version.Consensus.Block==8` . This way the software would support both versions 7 and 8.
> Minor log changes

- CHANGELOG.md
- p2p/switch.go
Addresses #2823. Currently, the acceptRoutine exits if the transport returns
an error trying to accept a new connection. Once this happens, the node
can't accept any new connections. So here, we panic instead. While we
could potentially be more intelligent by rerunning the acceptRoutine, the
error may indicate something more fundamental (eg. file desriptor limit)
that requires a restart anyways. We can leave it to process managers to
handle that restart, and notify operators about the panic.
> p2p: panic on transport error

- CHANGELOG.md
- p2p/peer_set.go
- p2p/peer_set_test.go
- p2p/switch.go
- p2p/switch_test.go
- p2p/test_util.go
Ref #2332 
Here, the metric will be decremented twice, because multiple calls to StopPeerForError are being made. I can't figure out how to write a real test because I can't get access to the underlying value of the gauge metric, since it seems to be hidden by the go-kit wrapper. Is this correct? 
Fixing it is simple - peerSet.Remove() should return a bool, and then we only decrement the counter if that's true. I can push that fix here as well.
> p2p: fix peer count mismatch #2332

- state/txindex/kv/kv.go
- state/txindex/kv/kv_test.go
to avoid including false positives
Refs #2908
> kv indexer: add separator to start key when matching ranges

- consensus/replay.go
Fixes #2951
Integration test passed with log:
ERROR: Failed to create node: Error during handshake: Error on replay: Validator set is nil in genesis and still empty after InitChain
> Fix panic if validator set is empty(#2951)

- mempool/mempool.go
This is only one part of #2989.
We also need to fix the cosmos-sdk application, and add rules to consensus to ensure this. (eventually we ought to just to convert abci.GasWanted to uint64) I think those can be done in separate PR's though. 
(I'm not changing ABCI now, though it would be simpler and correct, because theres a push for non-breaking changes atm, and I don't want the PR to take 5 weeks to be merged)
> Make mempool fail txs with negative gas wanted

- CHANGELOG.md
- CHANGELOG_PENDING.md
- node/node.go
- version/version.go
In https://github.com/tendermint/tendermint/pull/3025 makeNodeInfo calls nodeInfo.Validate and panics on error. Instead it should return the error up the stack.
This also prepares changelog/version for v0.27.2
> makeNodeInfo returns error

- CHANGELOG.md
- CHANGELOG_PENDING.md
- Gopkg.lock
- Gopkg.toml
- crypto/armor/armor.go
- crypto/ed25519/ed25519.go
- crypto/hash.go
- crypto/secp256k1/secp256k1.go
- crypto/xchacha20poly1305/xchachapoly.go
- crypto/xsalsa20symmetric/symmetric.go
- crypto/xsalsa20symmetric/symmetric_test.go
- p2p/conn/secret_connection.go
- version/version.go
We used to use a fork for a modified bcrypt so we could pass our own
randomness but this was largely unecessary, unused, and a burden.
So now we just use the mainline Go crypto lib.
cc https://github.com/tendermint/crypto/commit/3764759f34a542a3aef74d6b02e35be7ab893bba#commitcomment-31685132
> crypto: revert to mainline Go crypto lib

- mempool/mempool.go
because we pop txs from the front if the cache is full
Refs #3035
> mempool: move tx to back, not front on cache hit

- p2p/node_info.go
1024kb  means 1024k bit not Byte, but actually it should be Byte. 
Reference code :https://github.com/tendermint/go-amino/blob/master/amino.go#L276
> node_info : bit -> Byte

- docs/spec/blockchain/blockchain.md
- docs/spec/consensus/signing.md
Ref https://github.com/tendermint/tendermint/issues/2820
Spec for those implementing validator signers.
> add signing spec

- DOCKER/build.sh
- DOCKER/push.sh
- scripts/dist.sh
- scripts/publish.sh
- scripts/release.sh
Search for the right variable when introspecting Go code. `Version` was
renamed to `TMCoreSemVer`.
This is regression introduced in
b95ac688af14d130e6ad0b580ed9a8181f6c487c
> fix build scripts

- CHANGELOG_PENDING.md
- crypto/multisig/threshold_pubkey.go
- crypto/multisig/threshold_pubkey_test.go
Use crypto.AddressHash() to avoid returning 32-byte long address.
Closes: #3102
> Ensure multisig keys have 20-byte address

- CHANGELOG_PENDING.md
- libs/log/tmfmt_logger.go
year should be 2006 not 2016 https://golang.org/pkg/time/#Time.Format
Refs #3060
> [log] fix year format

- Makefile
cd does not work because it's executed in a subprocess
so it has to be either chained by && or ;
See https://stackoverflow.com/q/1789594/820520
for more details.
Fixes #3058
> makefile: fix build-docker-localnode target

- privval/socket_test.go
As per #3115, adds simple Unix socket connect/accept deadline tests in
pretty much the same way as the TCP connect/accept deadline tests work.
> Adds tests for Unix sockets

- privval/client_test.go
- privval/remote_signer_test.go
- privval/server.go
- privval/socket.go
- privval/socket_test.go
This PR attempts to complete #3115, where these commits add code (where relevant) to test the client over Unix domain sockets. Two tests in particular (now named `TestSocketPVDeadlineTCPOnly` and `TestRemoteSignerRetryTCPOnly`) are only relevant to the TCP version of the client (the OS knows both sides of a Unix domain socket instantaneously, and so these tests are not relevant to such connections).
> Expanding tests to cover Unix sockets version of client

- docs/app-dev/ecosystem.json
Adding the OrderStream network client (alpha), [ParadigmCore](https://github.com/ParadigmFoundation/ParadigmCore), to the `ecosystem.json` file.
> [Ecosystem] Add ParadigmCore to ecosystem.json

- state/state_test.go
- types/validator_set.go
Add test to check that proposers are selected at the frequency we expect.
The following fixes needed to be made:
- take absolute value of the priorities diff
- normalize repeatedly until the diff is less than the threshold
> test proposer frequencies

- CHANGELOG_PENDING.md
- docs/spec/blockchain/blockchain.md
- docs/spec/blockchain/encoding.md
- docs/spec/blockchain/state.md
- types/params.go
Addresses https://github.com/tendermint/tendermint/issues/3152
Also adds some fixes to the spec.
> [types] hash of ConsensusParams includes only a subset of fields

- CHANGELOG_PENDING.md
- docs/spec/blockchain/blockchain.md
- docs/spec/blockchain/encoding.md
- docs/spec/blockchain/state.md
- types/results.go
- types/results_test.go
- types/validator.go
Addresses everything from https://github.com/tendermint/tendermint/issues/3120
Note that now the only object that is hashed before merkle tree is txs, while others (validators, evidence, results, commit votes) are not.
> update spec for Merkle RFC 6962

- docs/networks/docker-compose.md
Solves #3192.
I am overriding the command in the docker file of the localnet to make it work. Though it seems like a hack, it works. Is this fine or do you suggest some other way @ebuchman ?
> Update doc support for abci containers on localnet

- config/toml.go
Added another helper function which works identical with `ResetTestRoot` except it takes additional `chainID` parameter
https://github.com/HaoyangLiu/cosmos-sdk/pull/13#issuecomment-455880847
> R4R: Config TestRoot modification for LCD test

- CHANGELOG_PENDING.md
- Makefile
- scripts/get_tools.sh
Run it with `make test_with_deadlock`. After it's done, use Git to
cleanup `git checkout .`
Link: https://github.com/sasha-s/go-deadlock/
Replaces https://github.com/tendermint/tendermint/pull/3148
> add go-deadlock tool to help detect deadlocks

- docs/tendermint-core/rpc.md
- docs/tools/benchmarking.md
- docs/tools/monitoring.md
- tools/tm-bench/README.md
- tools/tm-monitor/README.md
There are a few links in the docs that aren't hyperlinks, so I just fixed these quick.
Plus, the `tm-bench` utility's docs were still pointing to the deprecated tools repo.
> Minor fixes to non-hyperlinked links in docs

- CHANGELOG_PENDING.md
- blockchain/reactor_test.go
- blockchain/store_test.go
- consensus/replay_test.go
- consensus/state.go
- consensus/types/round_state_test.go
- lite/helpers.go
- state/execution.go
- state/execution_test.go
- types/block.go
- types/block_test.go
- types/validator_set.go
- types/validator_set_test.go
- types/vote.go
- types/vote_set.go
- types/vote_test.go
This is some precursor work towards #1648. Ultimately we want to replace Vote in Commit with a struct that has only the signature and timestamp. Here we take some steps towards that by clarifying when we really need to get a vote from the commit.
> Introduce CommitSig alias for Vote in Commit

- Makefile
- p2p/conn/connection.go
Test TestPEXReactorSeedModeFlushStop is non-deterministically failing with timeout. Note before we were holding the stopMtx while waiting for the sendRoutine to finish. Here we change it to not do that. It was also possible before to exit out of the sendRoutine due to error without ever closing the doneSendRoutine, so here we also ensure that doneSendRoutine is closed at the end of the sendRoutine!
> p2p/conn: don't hold stopMtx while waiting

- .circleci/config.yml
- .golangci.yml
- Makefile
- Vagrantfile
- blockchain/pool.go
- consensus/byzantine_test.go
- consensus/common_test.go
- consensus/state.go
- consensus/state_test.go
- crypto/merkle/proof.go
- crypto/merkle/proof_test.go
- libs/clist/clist_test.go
- libs/common/colors.go
- libs/events/events.go
- libs/test.sh
- lite/proxy/query_test.go
- p2p/conn/secret_connection_test.go
- p2p/pex/pex_reactor.go
- p2p/switch.go
- p2p/trust/metric_test.go
- scripts/get_tools.sh
- state/state_test.go
This reverts commit 1cf6712a36e8ecc843a68aa373748e89e0afecba.
Plus, switch from gometalinter to golangci-lint https://github.com/golangci/golangci-lint for speed and better support.
> Revert "quick fix for CircleCI (#2279)"

- crypto/secp256k1/secp256k1_cgo.go
- crypto/secp256k1/secp256k1_nocgo.go
- crypto/secp256k1/secp256k1_nocgo_test.go
Change the build tag to be specific to the lib so we don't always try to build any time CGO is enabled. 
Ref #3273
> secp256k1: change build tags

- CHANGELOG_PENDING.md
- consensus/reactor_test.go
- evidence/pool.go
- evidence/pool_test.go
- evidence/reactor_test.go
- evidence/store.go
- evidence/store_test.go
- node/node.go
- node/node_test.go
- state/execution.go
- state/services.go
- state/validation.go
- state/validation_test.go
Bug reported in bug bounty, approved/patched in security repo. Merging in here for inclusion in v0.30.0
> Fixes for duplicate evidence

- blockchain/reactor_test.go
- blockchain/store_test.go
- cmd/tendermint/commands/reset_priv_validator.go
- consensus/replay_test.go
- consensus/state.go
- consensus/types/round_state_test.go
- lite/helpers.go
- lite/proxy/validate_test.go
- node/node_test.go
- state/execution_test.go
- types/block.go
- types/validator_set_test.go
- types/vote_set.go
> types.NewCommit

- CHANGELOG_PENDING.md
- rpc/core/net.go
- rpc/core/types/responses.go
Before:
"AAAAAAAAAAAAAP//rB8ktw=="
which is amino-encoded net.IP byte slice
After:
"192.0.2.1"
Fixes #3251
> rpc/net_info: change RemoteIP type from net.IP to String

- CHANGELOG_PENDING.md
- blockchain/reactor_test.go
- blockchain/store_test.go
- config/toml.go
- config/toml_test.go
- consensus/byzantine_test.go
- consensus/common_test.go
- consensus/mempool_test.go
- consensus/reactor_test.go
- consensus/replay_test.go
- consensus/state_test.go
- consensus/types/height_vote_set_test.go
- consensus/wal_generator.go
- consensus/wal_test.go
- lite/client/provider_test.go
- lite/proxy/query_test.go
- mempool/bench_test.go
- mempool/mempool_test.go
- mempool/reactor_test.go
- node/node_test.go
- rpc/client/main_test.go
- rpc/grpc/grpc_test.go
- rpc/test/helpers.go
- state/state_test.go
Rely on ioutil.TempDir() to create test root directories and ensure
multiple same-chain id test cases can run in parallel.
> R4R: improve ResetTestRootWithChainID() concurrency safety

- CHANGELOG_PENDING.md
- p2p/transport.go
- p2p/transport_test.go
ref: https://github.com/tendermint/tendermint/issues/3010#issuecomment-464287627
> I tried searching for code where we authenticate a peer against its NetAddress.ID and couldn't find it. I don't see a reason to switch to Noise, but a need to ensure that the node's ID is authenticated e.g. after dialing from the address book.
> Fix p2p id check

- consensus/wal_test.go
The test was sometimes failing due to processFlushTicks being called too
early. The solution is to call wal#Start later in the test.
> fix TestWALPeriodicSync

- CHANGELOG_PENDING.md
- p2p/conn/secret_connection.go
- p2p/conn/secret_connection_test.go
Additionally, to the blacklist of lower order points, check if the shared secret is all zeros.
This mitigates #3010 until we have https://github.com/tendermint/tendermint/issues/3315 and switch to noise (which will also solve this and other issues).
ref: https://github.com/tendermint/tendermint/pull/3040#issuecomment-461978628
ref: https://github.com/tendermint/tendermint/issues/3010 in particular https://github.com/tendermint/tendermint/issues/3010#issuecomment-447123959
> secret connection check all zeroes

- consensus/replay_test.go
- consensus/state.go
- consensus/wal.go
- consensus/wal_generator.go
- consensus/wal_test.go
- libs/autofile/cmd/logjack.go
- libs/autofile/group.go
- libs/autofile/group_test.go
- rename auto#Flush to auto#FlushAndSync
- cleanup WAL interface to not leak implementation details!
* remove Group()
* return io.ReadCloser instead of *auto.Group in SearchForEndHeight()
- add interface assertions
Refs #3337
> rename WAL#Flush to WAL#FlushAndSync

- libs/pubsub/pubsub.go
- p2p/switch.go
- p2p/switch_test.go
Fix reconnection report duplicate id error.
startInitPeer before PeerSet add the peer,
once mconnection start and Receive of one
Reactor faild, will try to remove it from PeerSet
while PeerSet still not contain the peer. Fix
this by change the order.
> fix dirty data in peerset,resolve #3304

- blockchain/pool.go
resolve issue #3353 
When remove peer, block pool simple remove bpPeer,
but do not stop timer, that cause stopError for recorrected
peers. Stop timer when remove from pool.
> fix pool timer leak bug, resolve#3353

- cmd/tendermint/commands/lite.go
- lite/proxy/proxy.go
- lite/proxy/query.go
- lite/proxy/wrapper.go
Resolve #3363
1."abci_query": rpcserver.NewRPCFunc(c.ABCIQuery, "path,data,prove")
"validators": rpcserver.NewRPCFunc(c.Validators, "height"),
the parameters and function do not match, cause index out of range error.
2. the prove of query is forced to be true, while default option is false.
3. fix the wrong key of merkle
> make lightd availbe,resolve #3363

- consensus/types/round_state.go
- types/events.go
Before we're using it to get a round state in tests. Now it can be done
by calling csX.GetRoundState(?) We will need to rewrite
TestStateSlashingPrevotes and TestStateSlashingPrecommits, which are
commented right now, to not rely on EventDataRoundState#RoundState
field.
Refs #1527
> remove RoundState from EventDataRoundState

- Gopkg.toml
We're pinning repos without releases because it's very easy to upgrade all the dependencies by executing `dep ensure --upgrade`. Instead, we should just never run this command directly, only `dep ensure --upgrade <some repo>`. And we can defend that in PRs.
Refs https://github.com/tendermint/tendermint/pull/3374
The problem with pinning to exact revisions: people who import Tendermint as a library (e.g. `abci/types`) are stuck with these revisions even though the code they import may not even use them.
> do not pin repos without releases to exact revisions

- Gopkg.lock
- Gopkg.toml
Although the version we were pinning to is from Nov. 2016 there were no substantial changes:
-  https://github.com/jmhodges/levigo/commit/2b8c778f79d26d89cd5fd82accd3946374774c15 added go-modules support (no code changes)
- https://github.com/jmhodges/levigo/commit/853d788c5c416eaaee5b044570784a96c7a26975 added a badge to the readme
closes #3381
> update levigo to 1.0.0

- .golangci.yml
- consensus/state.go
- lite/dbprovider.go
- lite/dynamic_verifier_test.go
- lite/proxy/query_test.go
- p2p/conn/connection_test.go
- rpc/core/status.go
- state/execution_test.go
- state/state_test.go
> make ineffassign linter pass

- libs/db/c_level_db.go
- libs/db/debug_db.go
- libs/db/go_level_db.go
- libs/db/mem_batch.go
- libs/db/prefix_db.go
- libs/db/remotedb/grpcdb/server.go
- libs/db/remotedb/remotedb.go
- libs/db/types.go
- lite/dbprovider.go
- state/txindex/kv/kv.go
ClevelDB requires closing when WriteBatch is no longer needed, https://godoc.org/github.com/jmhodges/levigo#WriteBatch.Close
> Close WriteBatch to prevent memory leak.

- types/validator_set_test.go
Addresses issue #3383
When scaling and averaging is invoked, it is possible to have validators with close priorities ending up with same priority. This makes it hard, with the current code, to verify the priority orders before and after updates (in test TestValSetUpdatePriorityOrderTests).
> Remove check for priority order of existing validators (#3383)

- consensus/state.go
See https://github.com/tendermint/tendermint/pull/3386#discussion_r263254903 for original discussion. Back then I thought #3386 has nothing to do with the TestReactorValidatorSetChanges test timeout, but now it's more or less clear. I still don't understand how/why log.Error statement is causing it. Note before #3386 we're not calling log.Error because of the shadowing.
[build_49553_step_105_container_3.txt.zip](https://github.com/tendermint/tendermint/files/2951514/build_49553_step_105_container_3.txt.zip)
> cs: remove log.Error to avoid TestReactorValidatorSetChanges timing out

- docker-compose.yml
Fixes #3421
Before: it was creating a file named ${LOG:-tendermint.log} in .build/nodeX
After: it creates a file named tendermint.log
> localnet: fix $LOG variable

- consensus/replay.go
- types/protobuf.go
- types/protobuf_test.go
Fixes #3432
Thanks to @ebuchman for suggesting it!
> types: refactor PB2TM.ConsensusParams to take BlockTimeIota as an arg

- rpc/lib/client/http_client.go
By default, the http go client support Gzip-compressed Http response. 
The cli and light binary does not disable this support via the DisableCompression
property of the HTTPTransport object. As soon as it send a Http Request to a user-controlled
server, it become possible to cause a Denial of Service via a GZIP bomb.
Steps To Reproduce:
Code:
```
<?php
header("Content-Encoding: gzip");
echo file_get_contents("hello.gz")
?>
```
file： hello.gz
the file is 9MB in size but will expand to 9GB as soon as it decompressed.
start lightd or cli with --node to this server, the process will crash.
> rpc: client disable compression

- tools/tm-signer-harness/internal/test_harness.go
In order to re-enable the test harness for the KMS (see tendermint/kms#227), we need some marginally more realistic proposals and votes. This is because the KMS does some additional sanity checks now to ensure the height and round are increasing over time.
> Update height and round for tm-signer-harness

- mempool/reactor.go
Ref: #3306, https://github.com/irisnet/tendermint/pull/44/commits/fdbb67655db45726173895fd4ca6458180a8fc11
I ran an irishub validator. After the validator node ran several days, I dump the whole goroutine stack. I found that there were hundreds of broadcastTxRoutine. However, the connected peer quantity was less than 30. So I belive that there must be broadcastTxRoutine leakage issue.
According to my analysis, I think the root cause of this issue locate in below code:
```
select {
case <-next.NextWaitChan():
// see the start of the for loop for nil check
next = next.Next()
case <-peer.Quit():
return
case <-memR.Quit():
return
}
```
As we know, if multiple paths are avaliable in the same time, then a random path will be selected. Suppose that `next.NextWaitChan()` and `peer.Quit()` are …
> R4R: Resolve broadcastTxRoutine leakage issue

- CHANGELOG_PENDING.md
- rpc/client/httpclient.go
- rpc/client/interface.go
- rpc/client/localclient.go
- rpc/client/mock/client.go
I think it's nice when the `Client` interface has all the methods. If someone does not need a particular method/set of methods, she can use individual interfaces (e.g. NetworkClient, MempoolClient) or write her own interface.
**technically breaking**
Fixes #3458
> rpc/client: include NetworkClient interface into Client interface

- p2p/pex/addrbook.go
- p2p/pex/addrbook_test.go
Why submit this pr:
1.  we have suffered from `infinite loop in addrbook` bug which takes us a long time to find out why process become a  zombie peer. It have been fixed in https://github.com/tendermint/tendermint/pull/3232. But the `ADDRS_LOOP ` is still there, risk of infinite loop is still exist.
2. The algorithm that to random pick a bucket is not stable, which means the peer may unluckily always choose the wrong bucket for a long time, the time and cpu cost is meaningless.
A simple improvement:
shuffle `bucketsNew ` and `bucketsOld`, and pick necessary number of address from them. A stable
algorithm.
> refactor GetSelectionWithBias for addressbook

- CHANGELOG_PENDING.md
- docs/networks/docker-compose.md
- docs/spec/blockchain/blockchain.md
- docs/spec/blockchain/encoding.md
- docs/spec/consensus/abci.md
- docs/spec/consensus/wal.md
A bunch of links were broken in the documentation, they included the `docs` prefix. 
Fixes #3482
> docs: Fix broken links (#3482)

- blockchain/pool_test.go
This comments out a line that triggered the golang race detector. This is OK because:
- the commented line is only in test-code and we usually do not need the log output
- the blockchain reactor will undergo a major refactoring and the lines will probably become obsolete & be deleted anyways
- until the refactoring we can keep the commented line in case we need to debug sth. (@ancazamfir @milosevic)
"resolves" and close #3390
> blockchain: Comment out logger in test code that causes a race condition

- .circleci/config.yml
- CHANGELOG_PENDING.md
- DOCKER/Dockerfile
- Makefile
- scripts/release_management/README.md
- scripts/release_management/bump-semver.py
- scripts/release_management/github-draft.py
- scripts/release_management/github-openpr.py
- scripts/release_management/github-public-newbranch.bash
- scripts/release_management/github-publish.py
- scripts/release_management/github-upload.py
- scripts/release_management/sha-files.py
- scripts/release_management/zip-file.py
This PR is the first step for backporting and security releases deployed using CircleCI. It moves the current Jenkins-based release management over to CircleCI and introduces the vX.X branching model. This step does not support security releases yet. The architecture of security releases is still under discussion.
* Removed golang versions from CircleCI builds. This ensures that we always use the latest Golang version provided by CircleCI. (They update it faster than we do.)
* Minor changes to the `Makefile` so the binary name of the build can be configured. This is necessary because of the parallel builds of multiple architectures.
* New CircleCI release management steps: prepare, build, release (to GitHub), release to Docker.
* The prepare and build steps run on every branch, so when …
> Release management using CircleCI

- scripts/release_management/github-draft.py
The Python script creating the release was always targeting the `master` branch for the release tag. This PR fixes that and rightfully redirects it to the release branch instead of `master`.
> Fix for wrong version tag

- scripts/release_management/github-draft.py
Still part of the release_management update. The release message CHANGELOG link was incorrect, this fixes it.
> Release message changelog link fix

- docs/spec/abci/apps.md
Copied from https://stackoverflow.com/questions/55383199/explain-tendermint-deadlock-in-the-docs
> docs: abci#Commit: better explain the possible deadlock

- CHANGELOG_PENDING.md
- state/store.go
- state/store_test.go
/validators rpc response time grow with time.
Steps To Reproduce:
start a new node from hight 1
2.time curl 127.0.0.1:26657/validators, it takes 0.005s
let the chain run for serveral days, and change no validators.in my scenario the height is : 1584840
time curl 127.0.0.1:26857/validators, it takes 1.25s
The api consumes cpu resouces, in the long run, a small scale of DDOS can make the node
a zombie process.
Acturally the logic to do IncrementProposerPriority by height - valInfo.LastHeightChanged times will not replay the exactly ProposerPriority once there are two or more round.
Replaces https://github.com/tendermint/tendermint/pull/3438
> rpc: Fix response time grow over time

- p2p/node_info.go
- p2p/pex/addrbook.go
- p2p/pex/addrbook_test.go
- p2p/pex/pex_reactor.go
- p2p/pex/pex_reactor_test.go
- p2p/switch.go
- p2p/switch_test.go
- p2p/test_util.go
A prior change to address accidental DNS lookups introduced the SocketAddr on peer, which was then used to add it to the addressbook. Which in turn swallowed the self reported port of the peer, which is important on a reconnect. This change revives the NetAddress on NodeInfo which the Peer carries, but now returns an error to avoid nil dereferencing another issue observed in the past. Additionally we could potentially address #3532, yet the original problem statemenf of that issue stands.
As a drive-by optimisation `MarkAsGood` now takes only a `p2p.ID` which makes it interface a bit stricter and leaner.
> p2p: Bring back NodeInfo NetAddress form the dead

- docs/architecture/adr-037-peer-behaviour.md
> [ADR] ADR-037: Peer Behaviour

- p2p/transport.go
The secREKT is the most annoying one, as it turns up in log output a lot. ;-)
> Fix a couple of typos

- CHANGELOG_PENDING.md
- state/store.go
- state/store_test.go
What happened:
New code v0.31.4 was supposed to fall back to last height changed when/if it
fails to find validators at checkpoint height (to make release
non-breaking).
But because we did not check if validator set is empty (only checking if we have
an info is not enough, we save info for every block), the fall back
logic was never executed => resulting in LoadValidators returning an
empty validator set for cases where `lastStoredHeight` is checkpoint
height (i.e. almost all heights if the application does not change
validator set often).
How it was found:
one of our users - @sunboshan reported a bug here
https://github.com/tendermint/tendermint/pull/3537#issuecomment-482711833
> state: Use last height changed if validator set is empty

- blockchain/pool.go
- blockchain/reactor.go
- libs/common/throttle_timer_test.go
- libs/db/mem_batch.go
Fix issue https://github.com/tendermint/tendermint/issues/3457
> p2p: blockchain dismiss request channel delay

- CHANGELOG_PENDING.md
- p2p/pex/pex_reactor.go
- p2p/pex/pex_reactor_test.go
> p2p: (seed mode) limit the number of attempts to connect to a peer

- libs/clist/clist_test.go
Very simple bandaid for #2227
I think the errors are caused from a race condition in the test, not the actual `clist` data structure
> bandaid for non-deterministic clist test

- crypto/merkle/simple_tree.go
- crypto/merkle/simple_tree_test.go
(#2611) had suggested that an iterative version of
SimpleHashFromByteSlice would be faster, presumably because
we can envision some overhead accumulating from stack
frames and function calls. Additionally, a recursive algorithm risks
hitting the stack limit and causing a stack overflow should the tree
be too large.
Provided here is an iterative alternative, a simple test to assert
correctness and a benchmark. On the performance side, there appears to
be no overall difference:
```
BenchmarkSimpleHashAlternatives/recursive-4                20000 77677 ns/op
BenchmarkSimpleHashAlternatives/iterative-4                20000 76802 ns/op
```
On the surface it might seem that the additional overhead is due to
the different allocation patterns of the implementations. The recursive
version uses a …
> crypto: Proof of Concept for iterative version of SimpleHashFromByteSlices (#2611)

- privval/socket_listeners_test.go
This should fix https://github.com/tendermint/tendermint/issues/3576 (ran it many times locally but only time will tell). The test actually only checked for the opcode of the error. From the name of the test we actually want to test if we see a timeout after a pre-defined time.
> test: Increase timeout to mitigate non-deterministic test failure

- CHANGELOG_PENDING.md
- blockchain/store.go
- config/toml.go
- consensus/reactor.go
- consensus/state.go
- consensus/types/height_vote_set.go
- crypto/xsalsa20symmetric/symmetric.go
- libs/common/errors.go
- libs/common/random.go
- libs/common/service.go
- libs/db/go_level_db.go
- node/node.go
- p2p/conn/connection.go
- p2p/netaddress.go
- p2p/pex/file.go
- p2p/switch.go
- p2p/trust/store.go
- types/part_set.go
- types/validator.go
- types/vote.go
- types/vote_set.go
As per discussion over [here](https://github.com/tendermint/tendermint/pull/3456#discussion_r278423492), we need to remove these `PanicXXX` functions and eliminate our dependence on them. In this PR, each and every `PanicXXX` function call is replaced with a simple `panic` call.
> Remove deprecated PanicXXX functions from codebase

- CHANGELOG_PENDING.md
- p2p/pex/pex_reactor.go
If we are low on addresses for peering, we need to discover more peers. The
previous behavior would query existing peers; however, if an existing peer
does not participate in peer exchange, then our node will not discover more peers.
This change consults both existing peers as well as seeds when there is a deficit
in address book addresses. This allows for discovering peers though existing channels
as well as via seeds if existing peers do not share addresses.
---
> pex: dial seeds when address book needs more addresses

- CHANGELOG_PENDING.md
- cmd/tendermint/commands/reset_priv_validator.go
Adds `--keep-addr-book` flag to `unsafe_reset_all` command allowing not to clear address book
> cli: Add option to not clear address book with unsafe reset

- CHANGELOG_PENDING.md
- docs/spec/p2p/config.md
- node/node.go
- p2p/pex/pex_reactor.go
- p2p/pex/pex_reactor_test.go
- p2p/switch.go
- p2p/switch_test.go
- p2p/transport.go
- rpc/core/net.go
- rpc/core/net_test.go
- rpc/core/pipe.go
Previously only outbound peers can be persistent. 
Now, even if the peer is inbound, if it's marked as persistent, when/if conn is lost,
Tendermint will try to reconnect. **This part is actually optional and can be reverted.**
Plus, seed won't disconnect from inbound peer if it's marked as
persistent. Fixes #3362
> make persistent prop independent of conn direction

- libs/db/boltdb.go
`[]byte` is unhashable and needs to be casted to a string.
See https://github.com/tendermint/tendermint/pull/3610#discussion_r280995538
Ref https://github.com/tendermint/tendermint/issues/3626
CC @melekes @Liamsi
> libs/db: fix boltdb batching

- node/node.go
- p2p/pex/pex_reactor_test.go
- p2p/switch.go
- p2p/switch_test.go
- rpc/core/net.go
also
- handle errors from DialPeersAsync
- remove nil addr from log msg
- fix TestPEXReactorDoesNotDisconnectFromPersistentPeerInSeedMode
This is a follow-up from
https://github.com/tendermint/tendermint/pull/3593#pullrequestreview-233556909
Fixes most of the https://github.com/tendermint/tendermint/issues/3617, except https://github.com/tendermint/tendermint/pull/3593#discussion_r280841401
> rpc: /dial_peers: only mark peers as persistent if flag is on

- CHANGELOG_PENDING.md
- mempool/cache_test.go
- mempool/clist_mempool.go
- mempool/clist_mempool_test.go
- mempool/mempool.go
- mock/mempool.go
- state/execution.go
so evil proposers can't drop valid txs in Commit stage.
Also remove invalid (Code!=0) txs from the cache so they can be
resubmitted.
Fixes #3322
@rickyyangz:
In the end of commit stage, we will update mempool to remove all the txs
in current block.
```go
// Update mempool.
err = blockExec.mempool.Update(
block.Height,
block.Txs,
TxPreCheck(state),
TxPostCheck(state),
)
```
Assum an account has 3 transactions in the mempool, the sequences are
100, 101 and 102 separately, So an evil proposal can only package the
101 and 102 transactions into its proposal block, and leave 100 still in
mempool, then the two txs will be removed from all validators' mempool
when commit. So the account lost the two valid txs.
@ebuchman:
In the longer term we may want to do something like #2639 so we can
validate …
> mempool: remove only valid (Code==0) txs on Update

- p2p/pex/pex_reactor.go
This changeset alters the startup behavior for crawlPeersRoutine. Previously
the routine would crawl a random selection of peers on startup. For a
new seed node, there are no peers. As a result, new seed nodes are unable
to bootstrap themselves with a list of peers until another node with a list
of peers connects to the seed. If this node relies on the seed node for peers,
then the two will not discover more peers.
This changeset makes the startup behavior for crawlPeersRoutine connect to
any seed nodes. Upon connecting, a request for peers will be sent to the seed node
thus helping bootstrap our seed node.
> p2p/pex: consult seeds in crawlPeersRoutine

- crypto/multisig/multisignature.go
- crypto/multisig/threshold_pubkey_test.go
Improve error message returned from `AddSignatureFromPubKey` and cleanup a unit test. I don't think this is worthy of a pending log but I'd be happy to add one if desired.
closes: #3672
----
> Improve error message returned from AddSignatureFromPubKey

- CHANGELOG_PENDING.md
- cmd/tendermint/commands/testnet.go
This attempts to address issue #3660. It adds two additional flags to the `tendermint testnet` command:
1. `--hostname-suffix` - to automatically append a suffix to each and every generated (non-IP) hostname
2. `--hostname` - a [StringArray](https://godoc.org/github.com/spf13/pflag#StringArrayVar) parameter to manually override all peer hostnames. Using this flag causes `tendermint testnet` to completely ignore the `--hostname-prefix`, `--hostname-suffix` and `--starting-ip-address` fields.
**Example 1 with `--hostname-suffix`:**
```bash
> tendermint testnet --v 4 --n 0 --o /tmp/testnet \
--hostname-prefix mynode \
--hostname-suffix .xyz.com
> cat /tmp/testnet/node0/config/config.toml | grep persistent_peers
persistent_peers = "42311234da9693ff1affa073f7ef9984a0674582@mynode0.xyz.com:26656 …
```
> tendermint testnet: Allow for better hostname control

- p2p/peer_behaviour_test.go
Peer behaviour test tweaks towards #3653.
Address the remaining test issues mentioned in #3552 notably:
* switch to p2p_test package
* Use `Error` instead of `Errorf` when not using formatting
* Add expected/got errors to
* `TestMockPeerBehaviourReporterConcurrency` test
Also addresses a bug in `equalBehaviours` in which only the lengths of the behaviours was being tested and not the actual contents.
> [p2p] Peer behaviour test tweaks

- CHANGELOG_PENDING.md
- mempool/clist_mempool.go
- mempool/clist_mempool_test.go
Otherwise, we'll be trying to include them in each consecutive block.
The downside is that evil proposers will be able to drop valid
transactions (see #3322).
Reverts https://github.com/tendermint/tendermint/pull/3625
Fixes #3699
> remove invalid transactions from the mempool

- CHANGELOG_PENDING.md
- docs/tendermint-core/metrics.md
- p2p/metrics.go
- p2p/peer.go
Reactors  run in parallel exchanging messages with peers across channels. To understand the behaviour of the system as a whole, it would be helpful that have visibility into the per channel (and thus per reactor) message exchange. With per channel metrics, we can observe when a given reactor has stopped sending/receiving and correlate cpu usage with potential thread saturation.
Cf. #3666
> p2p: Per channel metrics (#3666)

- behaviour/peer_behaviour.go
- behaviour/peer_behaviour_test.go
- behaviour/reporter.go
- behaviour/reporter_test.go
This PR implements some of the changes previously mentioned in (#3653) and in comment of (#3552) 
to address a few key questions:
The current implementation places reactor specific terms/concepts in the p2p package. In the ideal, the `p2p` package would be as domain agnostic as possible.
This PR creates a new package `behaviour` to  intermediate the relationship between the p2p package and reactors. PeerBehaviours are decidedly simple, containing only an explanation string. The handling of PeerBehaviour is centralized within the `behaviour` package providing clear separation between the reactors and the responsibility of managing peers based on domain knowledge.
The original PR #3552 had each PeerBehaviour as an integer. This meant that passing `3` to `Report` could potentially stop a …
> p2p: Peerbehaviour follow up (#3653)

- docs/app-dev/getting-started.md
In Python 3 the command outlined in this doc `import codecs; codecs.decode("YWJjZA==", 'base64').decode('ascii')` throws an error:
TypeError: decoding with 'base64' codec failed (TypeError: expected bytes-like object, not str), needs to add 'b' before the encoded string
`import codecs; codecs.decode(b"YWJjZA==", 'base64').decode('ascii')` to make it work
> Missing 'b' in python 3 command

- CHANGELOG_PENDING.md
- node/node.go
Solution
`AddOurAddress` when we know it
`sw.NetAddress` is `nil` in `createAddrBookAndSetOnSwitch`
it's set by `n.transport.Listen` function, which is called during start
Fixes #3716
> node: fix a bug where `nil` is recorded as node's address

- .circleci/config.yml
- Circel CI and Golangci were doing linting jobs, removed circleci
This cannot be merged until it is removed from circleci.
@mircea-c can you remove it from circleci?
> Remove double lint

- tools/tm-monitor/Makefile
Makefile `build-docker` target updated to use `go mod`:
- go111module on
- switch from `golang:alpine` to `golang:1.12` to have git
> tm-monitor Makefile updated

- tools/tm-monitor/rpc.go
Add Context in `NewRPCFunc` tm-monitor routes callbacks
Locally solves: https://github.com/tendermint/tendermint/issues/3791
But does not guarantee `e.(error)` is always an error in other places
`rpc.NewRPCFunc` callbacks now accept `rpctypes.Context` as first parameter.
> tm-monitor: Add Context to RPC handlers

- Makefile
- abci/client/grpc_client.go
closes #357
- Remove go func(){}() that caused race condiditon
- To reproduce
- add -race in make file to `install_abci`
- Remove `CGO_ENABLED=0` & add -race to `install`
> Remove go func from finishAsyncCall()

- CHANGELOG_PENDING.md
- config/config.go
- config/toml.go
- docs/tendermint-core/configuration.md
- mempool/clist_mempool.go
- mempool/clist_mempool_test.go
- mempool/errors.go
- mempool/reactor.go
https://github.com/tendermint/tendermint/issues/3817
In connection with this issue, I have found that the size limit of TxMessage in mempool also needs to be configurable. 
This PR fixes hard-coded `maxMsgSize` to be configurable through `MempoolConfig`.
> mempool: make max_msg_bytes configurable

- CHANGELOG_PENDING.md
- p2p/pex/pex_reactor.go
I'm setting up all peers dynamically by calling `dial_peers`, so `p2p.seeds` in configs is empty, and I'm seeing error log a lot in logs.
> Do not write 'Couldn't connect to any seeds' if there are no seeds

- CHANGELOG_PENDING.md
- node/doc.go
- node/node.go
- node/node_test.go
- p2p/switch.go
using [`CustomReactors` option](https://godoc.org/github.com/tendermint/tendermint/node#CustomReactors).
Warning: beware of accidental name clashes. Here is the list of existing
reactors: MEMPOOL, BLOCKCHAIN, CONSENSUS, EVIDENCE, PEX.
>  node: allow replacing existing p2p.Reactor(s) 

- CHANGELOG_PENDING.md
- config/toml.go
- docs/tendermint-core/configuration.md
It was incorrectly placed in fastsync section during
https://github.com/tendermint/tendermint/commit/4d7cd8055b4083376b788239207f72f423e6ce07#diff-092cdc48047eeb4c0bca311a2e1b8ae6
merge.
Fixes #3868
> config: move max_msg_bytes into mempool section

- blockchain/v0/reactor_test.go
- blockchain/v1/reactor_test.go
- crypto/merkle/proof.go
- crypto/merkle/proof_key_path.go
- crypto/merkle/proof_simple_value.go
- crypto/merkle/proof_test.go
- p2p/switch.go
- p2p/test_util.go
- privval/messages.go
- store/store.go
- store/store_test.go
- types/block.go
- types/genesis.go
ref #3862
- step one in removing instances of errors.go in favor of github.com/pkg/errors
> (1/2) of replace errors.go with github.com/pkg/errors

- cmd/tendermint/commands/lite.go
- crypto/merkle/simple_proof.go
- lite/base_verifier.go
- lite/errors/errors.go
- lite/proxy/errors.go
- lite/proxy/query.go
- lite/proxy/verifier.go
- p2p/conn/connection.go
- p2p/peer_test.go
- privval/socket_dialers_test.go
- privval/utils.go
- privval/utils_test.go
- types/params.go
- types/validator_set.go
Replace usage of cmnError and errorWrap
- will keep `errors.go` until the SDK removes the use of it. 
- ref #3862
>  Remove instances of cmn.Error (2/2)

- CHANGELOG_PENDING.md
- rpc/client/httpclient.go
When using the RPC client in my test suite (with `-race` enabled), I do a lot of Subscribe/Unsubscribe operations, at some point (randomly) the race detector returns the following warning:
```
WARNING: DATA RACE
Read at 0x00c0009dbe30 by goroutine 31:
runtime.mapiterinit()
/usr/local/go/src/runtime/map.go:804 +0x0
github.com/tendermint/tendermint/rpc/client.(*WSEvents).redoSubscriptionsAfter()
/go/pkg/mod/github.com/tendermint/tendermint@v0.31.5/rpc/client/httpclient.go:364 +0xc0
github.com/tendermint/tendermint/rpc/client.(*WSEvents).eventListener()
/go/pkg/mod/github.com/tendermint/tendermint@v0.31.5/rpc/client/httpclient.go:393 +0x3c6 
```
Turns out that the `redoSubscriptionAfter` is not protecting the access to subscriptions.
The following change protects the read access to the …
> [RPC] protect subscription access from race condition

- CHANGELOG.md
- docs/spec/abci/apps.md
Fixes some typos in the docs.
Fixes the classification of some changelog items re `Features` vs. `Improvements`
> Fix some typos and changelog entries

- docs/spec/rpc/swagger.yaml
- rpc/core/mempool.go
- switch the data that was represented in `/unconfirmed_txs` and `num_unconfirmed_txs`
> Quick fix to swagger docs

- .circleci/config.yml
- config/config.go
- go.mod
- go.sum
- scripts/get_tools.sh
Also 
- errcheck from v1.1.0 to v1.2.0
- certstrap to e27060a3643e814151e65b9807b6b06d169580a7
- golangci-lint from v0.13.2 to v1.17.1
- gox to v1.0.1
See full diff in
- https://github.com/gogo/protobuf/compare/v1.2.1...v1.3.0 (melekes: ✅)
- https://github.com/kisielk/errcheck/compare/v1.1.0...v1.2.0 (melekes: ✅)
- https://github.com/square/certstrap/compare/e27060a3643e814151e65b9807b6b06d169580a7...338204a88c4349b1c135eac1e8c14c693ad007da (melekes: ✅)
- https://github.com/golangci/golangci-lint/compare/v1.13.2...v1.17.1 (melekes: ✅)
- https://github.com/mitchellh/gox/compare/51ed453898ca5579fea9ad1f08dff6b121d9f2e8...d8caaff5a9dc98f4cfa1fcce6e7265a04689f641 (melekes: ✅)
Changelog:
Tested versions:
go 1.12.9
protoc 3.7.1
Improvements:
plugin/stringer - Handle repeated and/or nullable …
> update gogo/protobuf version from v1.2.1 to v1.3.0

- CHANGELOG_PENDING.md
- mempool/clist_mempool.go
The bug of `atomic` results in `go test` error in the `mempool` module. See #3968 for details.
This is related to `atomic` library's bug: [atomic](https://golang.org/pkg/sync/atomic/#pkg-note-BUG)
> On ARM, x86-32, and 32-bit MIPS, it is the caller's responsibility to arrange for 64-bit alignment of 64-bit words accessed atomically. The first word in a variable or in an allocated struct, array, or slice can be relied upon to be 64-bit aligned.
In `clist_mempool.go`, the following variables are to be loaded by `atomic`'s `LoadInt64`:
```
// Atomic integers
height     int64 // the last block Update()'d to
rechecking int32 // for re-checking filtered txs on Update()
txsBytes   int64 // total size of mempool, in bytes
```
On 32-bit architecture, the memory alignment guarantee of type `int64` …
> Simple Patch for `atomic`'s Bug on 32-bit Machine

- docs/architecture/adr-025-commit.md
Added some more context and reference to issues, and marked it as accepted. We should start moving forward on this and roll out a plan for getting it tested on gaia testnets and ultimately proposed to the cosmos hub for a breaking upgrade (ie. the hub's first breaking upgrade of tendermint itself). cc @zmanian @marbar3778 @milosevic. We can probably include a couple other small block protocol breaking changes, but we shouldn't really block on it.
Summary of the result here:
- Leave the timestamp in the Commit. We need more analysis/review on the proposer timestamp before we can move forward - #2840
- Leave the ValidatorAddress in the Commit. It's super convenient and we still get lots of space savings - Closes #3596 
- Include absent votes explicitly - Closes #3591
- Allow precommits for …
> Update ADR-025 and mark it as Accepted

- DOCKER/Dockerfile.abci
- Vagrantfile
- docs/app-dev/abci-cli.md
- docs/app-dev/getting-started.md
- docs/introduction/install.md
- docs/tools/monitoring.md
- networks/remote/integration.sh
- scripts/dist.sh
- scripts/install/install_tendermint_arm.sh
- scripts/install/install_tendermint_bsd.sh
- scripts/install/install_tendermint_osx.sh
- scripts/install/install_tendermint_ubuntu.sh
- tools/build/Makefile
- tools/tm-bench/Dockerfile.dev
- tools/tm-monitor/Dockerfile.dev
- tools/tm-monitor/README.md
- in the makefile update `get_tools` was changed to just `tools`
> get_tools = tools

- CHANGELOG_PENDING.md
- tools/tm-monitor/monitor/network.go
- tools/tm-monitor/ton.go
Improves `tm-monitor` formatting of start time (RFC1123 without unnecessary precision) and avg tx throughput (three decimal places). The old tx throughput display was confusing during local testing where the tx rate is low and displayed as 0.
Also updates the monitor health whenever the validator number changes. It otherwise starts with moderate health and fails to update this once it discovers the validators, leading to incorrect health reporting and invalid uptime statistics. Let me know if you would like me to submit this as a separate PR.
```
2019-09-29 20:40:00.992834 +0200 CEST m=+0.024057059 up -92030989600.42%
Height: 2518
Avg block time: 1275.496 ms
Avg tx throughput: 0 per sec
Avg block latency: 2.464 ms
Active nodes: 4/4 (health: moderate) Validators: 4
NAME …
```
> Improved tm-monitor formatting

- .github/CODEOWNERS
- .github/stale.yml
- added stale bot to only pull requests for now
- changed codeowner from xla to tessr, no need to clog up xla's GitHub notifications
- https://probot.github.io/apps/stale/
@jackzampolin could you enable this, please.
> Add stale bot

- rpc/swagger/swagger.yaml
- added `/dial_peers` & `dial_seeds` to swagger docs under unsafe tag
closes #4047
> Add unsafe routes to swagger

- behaviour/reporter.go
MockReporeter.Report should return an error to adhere to the `behaviour.Reporter` interface
> [behaviour] Fix mock reporter interface

- CHANGELOG_PENDING.md
- p2p/pex/pex_reactor.go
When dailing connected peer, should log as debug message, instead of Error.
Only log message affected.
> Log as debug msg when address dailling is already connected

- CHANGELOG_PENDING.md
- docs/spec/consensus/fork-accountability.md
- libs/pubsub/pubsub.go
- libs/pubsub/query/empty.go
- libs/pubsub/query/empty_test.go
- libs/pubsub/query/query.go
- libs/pubsub/query/query_test.go
- state/txindex/kv/kv.go
- Some linting/cleanup missed from the initial events refactor
- Don't panic; instead, return `false, error` when matching breaks unexpectedly 
- Strip non-numeric chars from values when attempting to match against query values
- Have the server log during `send` upon error 
----
> Relax Tx Querying

- consensus/wal.go
- crypto/merkle/simple_proof.go
- crypto/merkle/simple_proof_test.go
- docs/spec/blockchain/blockchain.md
- docs/spec/blockchain/encoding.md
- docs/spec/blockchain/state.md
- types/params.go
- types/validator_set.go
- types/vote_set.go
Follow up to the v0.32.7 fixes that introduced some hard-coded limits to help prevent DoS. This makes those limits more explicit in the documentation.
Meanwhile, I've opened an issue about these limits, since it may be worth revisiting the need for them, or how we handle such things in general: https://github.com/tendermint/tendermint/issues/4099
> Add more comments about the hard-coded limits

- CHANGELOG_PENDING.md
- state/txindex/kv/kv.go
Why this pr:
When restarting chain node, sometimes we lost tx index about recent(around 80)blocks, and some client complains that they can't find the tx by RPC call(tx_search) when the tx do exist in the block.
I try to partially fix this issue in a simple way by writing the index data in a sync way. 
There is no performance difference under 1K TPS according to our test.
It is still possible that lost index data after restarting the node, but only 2 block data will lost at most.
I try to totally fix this in https://github.com/tendermint/tendermint/pull/3847/files, but this one is simple and can solve most part of the issue. Please review first, thks.
> [R4R]txindex/kv: Fsync data to disk immediately after receiving it 

- docs/spec/consensus/light-client.md
> typo fix: full nude -> full node

- docs/app-dev/getting-started.md
- docs/introduction/install.md
Currently the documentation on installing tendermint from source references the now-gone repository wiki, which leads to those links being broken. This PR fixes that by just inlining the content that was in the wiki.
Furthermore, building tendermint with just the instructions provided results in the following error:
```
Get Certstrap
go get: warning: modules disabled by GO111MODULE=auto in GOPATH/src;
ignoring go.mod;
see 'go help modules'
go: cannot use path@version syntax in GOPATH mode
make: *** [tools.mk:62: /home/corollari/go/bin/certstrap] Error 1
```
This PR fixes that by also setting the `GO111MODULE` environment variable.
> Fix build instructions

- rpc/core/CONTRIBUTING.md
- rpc/core/abci.go
- rpc/core/blocks.go
- rpc/core/consensus.go
- rpc/core/events.go
- rpc/core/evidence.go
- rpc/core/health.go
- rpc/core/mempool.go
- rpc/core/net.go
- rpc/core/status.go
- rpc/core/tx.go
No need to duplicate information in this case. It a) requires extra
efforts to keep both in sync b) nobody reads godoc documentation
anyways.
> rpc: remove godoc comments in favor of swagger docs

- CHANGELOG_PENDING.md
- consensus/replay.go
- consensus/replay_test.go
- go.sum
- rpc/client/rpc_test.go
- rpc/core/blocks.go
- rpc/core/blocks_test.go
- rpc/core/types/responses.go
- rpc/swagger/swagger.yaml
- state/execution.go
- state/export_test.go
- state/state_test.go
- state/store.go
BREAKING
Example response:
```json
{
"jsonrpc": "2.0",
"id": "",
"result": {
"height": "2109",
"txs_results": null,
"begin_block_events": null,
"end_block_events": null,
"validator_updates": null,
"consensus_param_updates": null
}
}
```
Old result consisted of ABCIResponses struct and height. Exposing
internal ABCI structures (which we store in state package) in RPC seems
bad to me for the following reasons:
1) high risk of breaking the API when somebody changes internal structs
(This has already happened before! We changed the ABCIResponses struct at some point in the past => /block_results response format got updated. There's a high chance we didn't even notice it (~ no changelog entry))
2) RPC is aware of ABCI, which I'm not sure we want
Refs …
> rpc: /block_results fix docs + write test + restructure response

- CHANGELOG.md
- DOCKER/README.md
- README.md
- docs/DOCS_README.md
- docs/guides/go-built-in.md
- docs/guides/go.md
- docs/guides/java.md
- docs/guides/kotlin.md
- networks/remote/README.md
- rpc/swagger/swagger.yaml
- tools/README.md
_Issue_:
The Tendermint documentation domain was updated from 
"https://tendermint.com/docs"  to "https://docs.tendermint.com/master"
Which most of the old links will give the following error message:
> 404
> There's nothing here.
> Take me home.
For example: "https://tendermint.com/docs/introduction" 
_____________________________________________________________________________
_Solution_:
- Updated 34 links in this repository.
> Fixing broken links: 

- docs/tendermint-core/rpc.md
- chane rpc link to master branch rpc docs, current link leads to 404
- closes #4199
> docs: Fix broken rpc link

- abci/README.md
I put it as the awesome repo ecosytem section as this is currently the only place where there is tendermint only ecosystem information.
- closes #4198
> docs: fix broken ecosystem link

- README.md
- docs/guides/go-built-in.md
- docs/guides/go.md
- networks/remote/integration.sh
- scripts/install/install_tendermint_arm.sh
- scripts/install/install_tendermint_bsd.sh
- scripts/install/install_tendermint_ubuntu.sh
- tools/build/Makefile
`github.com/ChainSafe/go-schnorrkel v0.0.0-20191204112926-74e22bf42a85` is required from https://github.com/tendermint/tendermint/pull/4190, but it dependencies `go 1.13`, so we need to update minimum requirements of go version to 1.13
```
../../go/pkg/mod/github.com/!chain!safe/go-schnorrkel@v0.0.0-20191204112926-74e22bf42a85/helpers.go:14:18: syntax error: unexpected b00000111 at end of statement
note: module requires Go 1.13
make: *** [build] Error 2
```
- update README.md (Minimum requirements of Go version and svg badge)
- update relevant docs and install, make scripts
> Update docs and scripts to golang/1.13

- rpc/swagger/swagger.yaml
Fixes #4014
The reason being when you call any endpoint supporting optional height
and use `height=0`, it will return an error. For example:
```
$ curl localhost:2667/consensus_params?height=0
{
"jsonrpc": "2.0",
"id": -1,
"error": {
"code": -32603,
"message": "Internal error",
"data": "height must be greater than 0"
}
}
```
> docs: remove "0 means latest" from swagger docs

- CHANGELOG_PENDING.md
- cmd/tendermint/commands/run_node.go
- config/config.go
- config/toml.go
- docs/tendermint-core/configuration.md
Closes #3831
The support for rocksdb was added a while back in
https://github.com/tendermint/tm-db/pull/12. This commit merely updates
the documentation.
> config: add rocksdb as a db backend option

- cmd/tendermint/commands/debug/kill.go
- testing replacing syscall with os.FindProces
> test: branch for fix of ci

- tools.mk
previous PR seems to have deleted the tools cmd, this adds it back in
> make: add back tools cmd

- CHANGELOG_PENDING.md
- cmd/tendermint/commands/debug/dump.go
- cmd/tendermint/commands/debug/kill.go
- cmd/tendermint/commands/lite.go
- lite/client/provider.go
- lite/client/provider_test.go
- lite2/provider/http/http.go
- lite2/provider/http/http_test.go
- rpc/client/examples_test.go
- rpc/client/httpclient.go
- rpc/client/rpc_test.go
- rpc/lib/client/http_json_client.go
- rpc/lib/client/http_json_client_test.go
- rpc/lib/client/http_uri_client.go
- rpc/lib/client/integration_test.go
- rpc/lib/client/ws_client.go
- rpc/lib/client/ws_client_test.go
- rpc/lib/rpc_test.go
- rpc/test/helpers.go
The `New*` client functions return an error instead
of panicking when the remote address is invalid.
Fixes #3953
> refactor(rpc): return an error on invalid remote (#3953)

- CHANGELOG_PENDING.md
- consensus/reactor.go
Fixes #4069
Backport for v0.32.9 cherry-picked from master at ee6601ad48ca8ae67610e8f94a28341caf30dec4.
> cs: don't panic when block is not found in store (#4163)

- CHANGELOG_PENDING.md
- rpc/lib/client/http_client.go
- rpc/lib/client/http_client_test.go
- rpc/lib/client/ws_client.go
- rpc/lib/client/ws_client_test.go
Enable basic authentication in the RPC client using the https://username:password@node:port format.
Issue #4248 has details about what was refactored/enhanced (it's not as bad as it looks.)
I'm open to suggestions on where/how the documentation should be updated.
Please note that PR #4284 is superseded with this PR. The reason for this is because both PR makes changes to the same code.
> RPC client basic authentication with URL parsing refactored

- CHANGELOG_PENDING.md
- config/config.go
- consensus/wal_generator.go
- p2p/netaddress.go
- rpc/lib/rpc_test.go
- rpc/lib/test/main.go
- rpc/test/helpers.go
The test servers bind to public interfaces by default, triggering about a dozen macOS firewall dialogs that have to be rejected each time tests are run. Binding to the loopback interface instead prevents these warnings.
> tests: bind test servers to 127.0.0.1

- CHANGELOG_PENDING.md
- node/node.go
not MaxOpenConnections
Fixes #4311
Also, set MaxBodyBytes, MaxHeaderBytes and WriteTimeout similar to HTTP
server.
> node: use GRPCMaxOpenConnections when creating the gRPC server

- lite2/client.go
Closes #4350
Checks that the chain ID of the witness and that of the lite client are the same before updating the witness list.
> lite2: filter valid witnesses

- docs/package-lock.json
- docs/package.json
Updates the docs theme to address a security alert in one of _its_ dependencies. 
This update changed the package-lock quite a bit more than I expected; if someone who's more familiar with node/npm could eyeball it and let me know if this is reasonable, that would be wonderful!
> docs: update npm dependencies

- abci/README.md
> abci: fix broken spec link

- lite2/client.go
- lite2/client_test.go
- lite2/example_test.go
- lite2/provider/mock/mock.go
Closes issue #4338 
Uses a wrapper function around both the signedHeader and validatorSet calls to the primary provider which attempts to retrieve the information 5 times before deeming the provider unavailable and replacing the primary provider with the first alternative before trying recursively again (until all alternatives are depleted)
Employs a mutex lock for any operations involving the providers of the light client to ensure no operations occurs whilst the new primary is chosen.
> lite2: replace primary provider with alternative when unavailable

- lite2/client.go
- lite2/client_test.go
- lite2/store/db/db.go
- lite2/store/db/db_test.go
- lite2/store/errors.go
- lite2/store/store.go
- lite2/test_helpers.go
Closes #4328 
When `TrustedHeader(height)` is called, if the height is less than the trusted height but the header is not in the trusted store then a function finds the previous lowest height with a trusted header and performs a forwards sequential verification to the header of the height that was given. If no error is found it updates the trusted store with the header and validator set for that height and can then return them to the user.
> lite2: fetch missing headers

- Makefile
- tests.mk
- tools.mk
The `.PHONY` targets in the `Makefile` are usually placed far away from the actual targets, and thus aren't always updated. Placing the `.PHONY` targets right next to the targets they cover make them more visible and thus more likely to be updated when necessary.
> Makefile: place phony markers after targets

- lite2/client.go
**Minor Edit**
Currently the sequence function always starts from the `trustedHeader` and `trustedNextVals` stored in the lite client. Whereas the bisection one allows the method to be started from any combination of header and validator set. I opened up the sequence verification method to do the same
> lite2: modified sequence method to match bisection

- lite2/client.go
- lite2/verifier.go
- lite2/verifier_test.go
Closes #4398 
Refactored current `Verify` function to `VerifyViaVals` and `VerifyViaSigs`
> lite2: divide verify functions

- blockchain/v0/reactor.go
- blockchain/v1/reactor.go
- blockchain/v1/reactor_test.go
- consensus/reactor.go
Fixes #4416. Since we officially only support 64-bit archs, `int` already implies `int64`, but explicit is better than implicit. Also, we don't need nor want negative numbers, so made it `uint64`.
> Use uint64 for consensus.Reactor.SwitchToConsensus() blocksSynced

- rpc/client/rpc_test.go
Tests are non-deterministic due to shared test fixtures, and occasionally this caused the tx_search tests to submit invalid page numbers.
> rpc: fix txsearch test corner-case

- CHANGELOG_PENDING.md
- p2p/conn/secret_connection.go
Replaces a call to `curve25519.ScalarMult()` with `X25519()`, which fixes the following linter warning towards #4447:
```
p2p/conn/secret_connection.go:365:2: SA1019: curve25519.ScalarMult is deprecated: when provided a low-order point, ScalarMult will set dst to all zeroes, irrespective of the scalar. Instead, use the X25519 function, which will return an error.  (staticcheck)
curve25519.ScalarMult(shrKey, locPrivKey, remPubKey)
^
```
The zero check is now handled by `X25519()`, and can safely be removed.
Technically a breaking change, since we're removing `ErrSharedSecretIsZero`.
> p2p: use curve25519.X25519() instead of ScalarMult()

- lite2/client.go
- lite2/client_test.go
closes #4426
The sequence and bisection methods no longer save the intermediate headers and validator sets that they require to verify a currently untrusted header.
> lite2: don't save intermediate headers

- docs/architecture/adr-046-light-client-implementation.md
- lite2/client.go
- lite2/client_test.go
- lite2/store/db/db.go
- lite2/store/db/db_test.go
- lite2/store/errors.go
- lite2/store/store.go
- lite2/verifier.go
Before we were storing trustedHeader (height=1) and trustedNextVals
(height=2).
After this change, we will be storing trustedHeader (height=1) and
trustedVals (height=1). This a) simplifies the code b) fixes #4399
inconsistent pairing issue c) gives a relayer access to the current
validator set #4470.
The only downside is more jumps during bisection. If validator set
changes between trustedHeader and the next header (by 2/3 or more), the
light client will be forced to download the next header and check that
2/3+ signed the transition. But we don't expect validator set change too
much and too often, so it's an acceptable compromise.
Closes #4470 and #4399
> lite2: store current validator set

- docs/architecture/adr-046-light-client-implementation.md
- lite2/client.go
- lite2/client_test.go
- lite2/example_test.go
- lite2/rpc/client.go
closes: #4455
Verifying backwards checks that the trustedHeader hasn't expired both before and after the loop in case of verifying many headers (a longer operation), but not during the loop itself.
TrustedHeader() no longer checks whether the header saved in the store has expired.
Tests have been updated to reflect the changes
> lite2: remove expiration checks on functions that don't require them

- lite2/client.go
- lite2/client_test.go
- lite2/store/db/db.go
- lite2/store/db/db_test.go
- lite2/store/store.go
closes #4469
Improved speed of cleanup by using `SignedHeaderAfter` instead of `TrustedHeader` to jump from header to header.
`Prune()` is now called when a new header and validator set are saved and is a function dealt by the database itself
> lite2: prune-headers

- blockchain/v0/reactor_test.go
- blockchain/v2/reactor_test.go
- consensus/byzantine_test.go
- consensus/replay_test.go
- libs/math/fraction.go
- state/helpers_test.go
- state/validation_test.go
- types/block.go
- types/block_test.go
- types/priv_validator.go
- types/test_util.go
JSON test file generation requires some changes in the go test files and they are proposed in this PR as below :
- test functions take `time.Time` as a parameter instead of setting the `timestamp` to `tmtime.Now()`. This gives more control over testing the `trusting_period` specifically
- exported `Privkey` (i.e. `MockPV.Privkey`) so that amino can serialize it
- pointers to MockPV were not needed 
- added JSON tags to `Fraction struct`
> JSON tests related changes

- .mergify.yml
Removes unnecessary Mergify conditions, and rely on branch protection instead.
> mergify: remove unnecessary conditions

- CHANGELOG_PENDING.md
- rpc/core/events.go
Closes: #4492
Capture the subscription ID that is set when the subscription begins, so that the emitted events use that same ID.
______
> Keep the original subscription "id" field when new RPCs come in

- CHANGELOG_PENDING.md
- abci/example/kvstore/kvstore.go
- abci/example/kvstore/kvstore_test.go
- abci/tests/test_cli/ex1.abci.out
- docs/app-dev/abci-cli.md
Fixes #4507. I'm assuming we don't consider this a breaking change.
______
> example/kvstore: return ABCI query height

- cmd/tendermint/commands/lite.go
- docs/architecture/adr-046-light-client-implementation.md
- lite2/client.go
- lite2/client_test.go
- lite2/doc.go
- lite2/example_test.go
- lite2/rpc/client.go
We first introduced auto-update as a separate struct `AutoClient`, which
was wrapping `Client` and calling `Update` periodically. 
```go
// AutoClient can auto update itself by fetching headers every N seconds.
type AutoClient struct {
base         *Client
updatePeriod time.Duration
quit         chan struct{}
trustedHeaders chan *types.SignedHeader
errs           chan error
}
// NewAutoClient creates a new client and starts a polling goroutine.
func NewAutoClient(base *Client, updatePeriod time.Duration) *AutoClient {
c := &AutoClient{
base:           base,
updatePeriod:   updatePeriod,
quit:           make(chan struct{}),
trustedHeaders: make(chan *types.SignedHeader),
errs:           make(chan error),
}
go c.autoUpdate()
return c
}
// TrustedHeaders returns a channel onto which new …
```
> lite2: remove auto update

- docs/architecture/adr-042-state-sync.md
- docs/architecture/adr-046-light-client-implementation.md
- lite2/client.go
- lite2/client_test.go
- lite2/example_test.go
`error` itself is not enough since it only signals if there were any
errors. Either (types.SignedHeader) or (success bool) is needed to
indicate the status of the operation. Returning a header is optimal
since most of the clients will want to get a newly verified header
anyway.
______
> lite2: indicate success/failure of Update

- .circleci/config.yml
We've renamed the branch for staging docs from `docs-theme-latest` to `docs-staging`. This makes so that CircleCI uses the correct branch for https://docs.staging-tendermint.com
> Use docs-staging branch for docs preview website

- CHANGELOG_PENDING.md
- rpc/client/event_test.go
- rpc/client/examples_test.go
- rpc/client/httpclient.go
but HTTP client is not running.
`Subscribe`, `Unsubscribe(All)` methods return an error now.
Closes #4568
______
> rpc: fix panic when `Subscribe` is called

- CHANGELOG_PENDING.md
- DOCKER/Dockerfile
Closes: #4569 
This change updates the `Dockerfile` to include defaults for a one-node `kvstore` testnet. It can be overwritten by adding a volume to mount point `/tendermint` as it was available before.
This change is a non-breaking change.
This change allows a developer to run `docker run tendermint/tendermint` and have a locally available one-node testnet at once (without running `init` beforehand).
Note: The `VOLUME` command was moved to the bottom of the file. The reason for this is that any files added to the mount point after this command ran would get lost during the build process. (The files have to be added before this command.)
______
> DOCKER: update with defaults

- DOCKER/Dockerfile
Closes: #4569
This is an extra fix to #4569 . The original solution did not change the RPC port setting from localhost to 0.0.0.0, hence docker was not able to forward it to the host for the user.
This fixes it.
Tested locally.
______
> Docker image port fix

- config/toml.go
- node/node.go
- enable v2 to be set via config paramarters 
______
> blockchain: enable v2 to be set

- CHANGELOG_PENDING.md
- consensus/reactor.go
- evidence/reactor.go
- mempool/reactor.go
- p2p/mock/reactor.go
- p2p/pex/pex_reactor.go
Previously, many reactors were initialized with the name "Reactor," which made it difficult to log which reactor was doing what. This changes those reactors' names to something more descriptive.
______
> all: name reactors when they are initialized

- CHANGELOG_PENDING.md
- CONTRIBUTING.md
- Makefile
- scripts/protocgen.sh
Add command to generate proto stubs with docker. This PR should not be merged till https://github.com/tendermint/images/pull/48 is and it is tested again.
Kept non-docker to generate proto files as some people may not want to run docker non-stop.
closes #4579
______
~~- [] Wrote tests~~
> proto: use docker to generate stubs

- CHANGELOG_PENDING.md
- rpc/client/mock/abci.go
- rpc/core/mempool.go
- rpc/core/types/responses.go
- rpc/swagger/swagger.yaml
Closes: #4606 
Adds a property of `codespace` to `ResultBroadcastTx` and passes it to the application.
- add `codespace` to `ResultBroadcastTx`
- set codespace before returning `ResultBroadcastTx`
- apply abci mock
______
> rpc: add codespace to ResultBroadcastTx

- CHANGELOG_PENDING.md
- docs/architecture/adr-046-light-client-implementation.md
- lite2/client.go
- lite2/client_benchmark_test.go
- lite2/client_test.go
- lite2/errors.go
- lite2/store/db/db.go
- lite2/store/db/db_test.go
- lite2/store/store.go
Closes: #4537 
Uses `SignedHeaderBefore` to find header before unverified header and then bisection to verify the header. Only when header is between first and last trusted header height else if before the first trusted header height then regular backwards verification is used. 
______
> lite2: use bisection for some of backward verification

- CHANGELOG_PENDING.md
- cmd/tendermint/commands/debug/dump.go
- cmd/tendermint/commands/debug/kill.go
- cmd/tendermint/commands/debug/util.go
- cmd/tendermint/commands/lite.go
- lite/client/provider.go
- lite/proxy/query_test.go
- lite2/client_benchmark_test.go
- lite2/client_test.go
- lite2/example_test.go
- lite2/helpers_test.go
- lite2/provider/http/http.go
- lite2/provider/http/http_test.go
- lite2/verifier_test.go
- rpc/client/examples_test.go
- rpc/client/http/http.go
- rpc/client/http/httpclient.go
- rpc/client/local/local.go
- rpc/client/rpc_test.go
- rpc/swagger/swagger.yaml
Fixes #4626:
* Split `rpc/client` implementations into `rpc/client/http` and `rpc/client/local`, and rename constructors.
* Split `lite2` tests into separate `lite_test` package.
* Embed `SignStatusClient` in `http.http` struct, so tests can convert it.
______
> rpc/client: split out client packages

- docs/architecture/adr-053-state-sync-prototype.md
Strengthen and simplify the ADR-053 state sync ABCI interface based on implementation findings. The main changes are:
* Snapshot discovery now includes chunk SHA-256 hashes. If there are any mismatches across nodes, the majority wins. This serves two purposes:
1. In the case of accidental non-determinism in snapshot generation across nodes, we can make sure all fetched chunks are part of the same snapshot such that it can still be restored (subject to `app_hash` verification).
2. An adversary now has to be able to provide the chosen snapshot manifest, and we can use majority-based heuristics to counteract this. Before, it was sufficient for a single adversary to be able to provide a single invalid chunk to cause the entire snapshot restoration to fail.
* Chunks are now exchanged simply as …
> ADR-053: strengthen and simplify the state sync ABCI interface

- CHANGELOG_PENDING.md
- evidence/errors.go
- evidence/pool.go
- evidence/pool_test.go
- evidence/reactor.go
- evidence/store.go
- evidence/store_test.go
- rpc/core/evidence.go
Closes: #4614
Uses the `Has()` function from the DB store interface to first confirm that a piece of received evidence is not already stored before commencing verification
______
> evidence: check evidence hasn't already been stored

- README.md
This has been the convention for a long time (longer than I've been on the team), 
but I wanted to make it explicit.
> README: specify supported versions

- CHANGELOG_PENDING.md
- README.md
- cmd/tendermint/main.go
- libs/cli/helper.go
New `tendermint completion` command to generate Bash/Zsh completion scripts.
How to use it:
```bash
$ . <(tendermint completion)
```
Note that the `completion` command does not show up in the help screen,
though it comes with its own `--help` option.
This is a port of the feature provided by cosmos-sdk.
______
> add command to generate shell completion scripts

- .mergify.yml
The Mergify folks were kind enough to add an option for using the PR title and body as the squash merge commit message (https://github.com/Mergifyio/mergify-engine/pull/939). The GitHub default uses all branch commit messages, which is a bit noisy.
______
> mergify: use PR title and body for squash merge commit

- evidence/pool.go
- evidence/pool_test.go
- evidence/reactor.go
- state/validation.go
Refs https://github.com/tendermint/tendermint/issues/2565#issuecomment-432896645
Refs https://github.com/tendermint/tendermint/issues/2653
spec PR: tendermint/spec#87
for evidence to be considered expired. otherwise, a cabal group can
manipulate block time to make a particular evidence too old.
______
> evidence: both MaxAgeDuration and MaxAgeNumBlocks need to be surpassed

- docs/architecture/adr-054-crypto-encoding-2.md
This pr amend the adr for crypto to only define tendermint's keys and not the sdk's keys.
______
> docs: amend adr-54 with changes made in Cosmos-SDK

- blockchain/v2/io.go
Fixes a bug where the reactor would broadcast a base with height=0.
______
> blockchain/v2: don't broadcast base if height is 0

- libs/service/service.go
The service logging can be a bit unclear. For example, with state sync it would log:
```
I[2020-04-20|08:40:47.366] Starting StateSync     module=statesync impl=Reactor
I[2020-04-20|08:40:47.834] Starting state sync    module=statesync
```
Where the first message is the reactor service startup, and the second message is the start of the actual state sync process. This clarifies the first message by changing it to `Starting StateSync service`.
______
> clarify service logging

- store/store.go
- store/store_test.go
Followup from #4588. Allow the first `SaveBlock()` call in an empty block store to be at any height, to start from a truncated block history. Subsequent `SaveBlock()` calls must be for contiguous blocks.
______
> blockstore: allow initial SaveBlock() at any height

- p2p/pex/pex_reactor_test.go
in TestPEXReactorDialsPeerUpToMaxAttemptsInSeedMode
Closes #4668
______
> p2p/pex: fix DATA RACE

- CHANGELOG_PENDING.md
- lite2/rpc/client.go
- rpc/client/rpc_test.go
- rpc/core/consensus.go
- rpc/core/types/responses.go
- rpc/swagger/swagger.yaml
Closes: #4695
Verify `/block_results` and `/validators` responses from an HTTP client using the light client.
Added `count` and `total` to `/validators` response.
Refs #3113
______
> lite2/rpc: verify block results and validators

- .github/PULL_REQUEST_TEMPLATE.md
- .github/auto-comment.yml
The checklist and message in the default PR description were sometimes getting
included in commit messages. This change moves that text from the PR description
to a comment from a [Probot tool](https://probot.github.io/apps/auto-comment/).
> .github: move checklist from PR description into an auto-comment

- .github/auto-comment.yml
Whoops.
This change should fix that.
> .github: fix whitespace for auto-comment

- go.mod
- go.sum
This is a duplicate of https://github.com/tendermint/tendermint/pull/4757, but with the changes produced by `go mod tidy`
> build(deps): manually bump github.com/prometheus/client_golang from 1.5.1 to 1.6.0

- CHANGELOG_PENDING.md
- state/state.go
This is useful for custom state sync `StateProvider` implementations that need to build new states for bootstrapping the node. It will also be useful when implementing other mechanisms to bootstrap nodes, e.g. #4642 and #3713.
> state: export InitStateVersion

- CHANGELOG_PENDING.md
- p2p/conn/secret_connection.go
remove todo and panic from `signChallenge`
going through conn code for proto and noticed this goody
> p2p: return err on `signChallenge`

- CHANGELOG_PENDING.md
- lite2/client.go
- lite2/verifier.go
- types/evidence.go
- types/validator_set.go
- types/validator_set_test.go
Closes #4783 
It looks like we're validating Commit twice. Also, height and blockID params were coming from the commit, so no need to pass them separately.
> types: simplify VerifyCommitTrusting

- CHANGELOG_PENDING.md
- rpc/lib/server/http_server.go
Fixes #4802. The Go HTTP server has a global panic handler for requests, so it was not as severe as first thought.
This fix can still panic, since we try to send a `500` response - if that happens, the Go HTTP server will terminate the connection. Otherwise, the client will get a 200 response, which we should avoid. I'm sort of torn on whether it's even necessary to include this fix, instead of just letting the HTTP server deal with it.
> rpc: handle panics during panic handling

- consensus/state.go
- consensus/state_test.go
What the test did beforehand:
Round 1:
v1 proposes block A
v1, v2, v3, v4 prevote block A
v1 precommits block A, v2, v3, v4 precommit nil
Round 2:
v2 proposes block B **which is the exact same as A**
v1 relocks onto block A, the others prevote B
all vals precommit B **because B and A are the same**
Now:
Round 1:
v1 proposes block A
v1, v2, v3, v4 prevote block A
v1 precommits block A, v2, v3, v4 precommit nil
Round 2:
v2 proposes block B
v1 is locked so it prevotes block A, 
the others prevote block B
v1 changes lock because of the majority of votes to block B and precommits B
the others precommit B
Closes: #4020
> consensus: fix and rename TestStateLockPOLRelock

- test/docker/Dockerfile
Debian testing caused Docker image build failures:
```
The following packages have unmet dependencies:
libc6-dev : Breaks: libgcc-8-dev (< 8.4.0-2~) but 8.3.0-6 is to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
```
It does not appear that we actually need testing, so removing it.
> test: fix p2p test build breakage caused by Debian testing

- CHANGELOG.md
- CHANGELOG_PENDING.md
- node/node.go
- node/node_test.go
- privval/doc.go
- privval/retry_signer_client.go
returning an error
Closes #4707
> privval: retry GetPubKey/SignVote/SignProposal N times before

- test/docker/Dockerfile
Since we support 1.13 and above, let's use that as a baseline for tests.
> test: revert Go 1.13→1.14 bump

- lite2/client.go
- lite2/client_test.go
previously:
```
pivotHeight := (headerCache[depth].sh.Height + 
trustedHeader.Height) * bisectionNumerator / bisectionDenominator
```
This had the possibility of picking a height that exceeded the range the node is bisecting through
now:
```
pivotHeight := trustedHeader.Height + (headerCache[depth].sh.Height - 
trustedHeader.Height) * bisectionNumerator / bisectionDenominator
```
also added a test to make sure it catches an instance that would have previously returned an error
> lite2: fix pivot height

- CHANGELOG_PENDING.md
- consensus/byzantine_test.go
- consensus/common_test.go
- consensus/replay_test.go
- consensus/state.go
- consensus/state_test.go
- consensus/types/height_vote_set_test.go
- crypto/ed25519/ed25519.go
- lite2/helpers_test.go
- privval/file.go
- privval/file_test.go
- privval/retry_signer_client.go
- privval/signer_client.go
- privval/signer_client_test.go
- privval/signer_requestHandler.go
- rpc/client/evidence_test.go
- state/validation_test.go
- tools/tm-signer-harness/internal/test_harness.go
- types/block.go
- types/canonical.go
- types/evidence.go
- types/evidence_test.go
- types/priv_validator.go
- types/proposal.go
- types/proposal_test.go
- types/test_util.go
- types/validator_set_test.go
- types/vote.go
- types/vote_test.go
have `SignBytes` accept a proto type
Closes: #XXX
> signing: change signbytes 

- .circleci/config.yml
bumping the timeout on test_coverage as the amount of tests have increased causing quite a few timeouts.
Closes: #XXX
> ci: bump the timeout for test_coverage

- blockchain/v1/peer_test.go
TestPeerResetBlockResponseTimer && TestPeerOnErrFuncCalledDueToExpiration was failing because the sleep and timeouts were sent in the magnitude of a few ms this meant that occasionally a timer would timeout when it shouldn't. I have broadened the timing ranges to the range of 20-50 ms and so far haven't seen anything fail.
> blockchain[v1]: increased timing of peer tests to avoid random failures

- CHANGELOG_PENDING.md
- lite/base_verifier_test.go
- lite/dynamic_verifier_test.go
- lite2/client_test.go
- lite2/helpers_test.go
- lite2/verifier_test.go
- types/block.go
- Move core stateless validation of the Header type to a ValidateBasic method.
- Call header.ValidateBasic during a SignedHeader validation.
- Call header.ValidateBasic during a PhantomValidatorEvidence validation.
- Call header.ValidateBasic during a LunaticValidatorEvidence validation.
lite tests are skipped since the package is deprecated, no need to waste time on it
closes: #4572
Co-authored-by: Anton Kaliaev <anton.kalyaev@gmail.com>
> types: implement Header#ValidateBasic (#4638)

- blockchain/v0/reactor_test.go
Mitigates the below data race. The proper fix involves not fiddling with reactor internals, which needs a rewrite of the test and possible additional reactor infrastructure.
```
==================
WARNING: DATA RACE
Write at 0x00c001118e78 by goroutine 187:
github.com/tendermint/tendermint/blockchain/v0.TestBadBlockStopsPeer()
/go/src/github.com/tendermint/tendermint/blockchain/v0/reactor_test.go:234 +0x9d7
testing.tRunner()
/usr/local/go/src/testing/testing.go:992 +0x1eb
Previous read at 0x00c001118e78 by goroutine 326:
[failed to restore the stack]
Goroutine 187 (running) created at:
testing.(*T).Run()
/usr/local/go/src/testing/testing.go:1043 +0x660
testing.runTests.func1()
/usr/local/go/src/testing/testing.go:1285 +0xa6
testing.tRunner()
/usr/local/go/src/testing/testing.go:992 +0x1eb …
```
> test/blockchain/v0: mitigate test data race

- p2p/transport_test.go
Attempt to fix this the below test failure by waiting for the listener to get ready. I am not at all convinced that this is the correct fix - the below indicates that the TCP socket was closed after it was set up - but I'm unable to come up with an actionable hypothesis for what caused it.
```
2020/05/14 17:25:11 Failed to accept conn: accept tcp 127.0.0.1:44737: use of closed network connection
2020/05/14 17:25:11 Failed to accept conn: accept tcp 127.0.0.1:42589: use of closed network connection
2020/05/14 17:25:11 Failed to accept conn: accept tcp 127.0.0.1:40905: use of closed network connection
2020/05/14 17:25:12 Failed to accept conn: accept tcp 127.0.0.1:39847: use of closed network connection
2020/05/14 17:25:12 Failed to accept conn: accept tcp 127.0.0.1:39989: use of closed …
```
> p2p/test: wait for listener to get ready

- lite2/provider/http/http_test.go
Increases the block retention such that it is less likely that the header requested three blocks behind the latest has already been pruned
> lite2/http: fix provider test

- p2p/switch.go
- p2p/switch_test.go
Fixes the following race condition, and also the nil pointer dereferencing it triggered.
```
=== RUN   TestSwitchInitPeerIsNotCalledBeforeRemovePeer
I[2020-05-25|12:39:48.550] Starting P2P Switch service                  switch=1 impl="P2P Switch"
E[2020-05-25|12:39:48.841] Stopping peer for error                      switch=1 peer=null err=test
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0x18c76d4]
goroutine 818 [running]:
github.com/tendermint/tendermint/p2p.(*MultiplexTransport).Cleanup(0xc0004378c0, 0x0, 0x0)
/Users/erik/Projects/tendermint/tendermint/p2p/transport.go:334 +0x34
github.com/tendermint/tendermint/p2p.(*Switch).stopAndRemovePeer(0xc000437e60, 0x0, 0x0, 0x194b380, 0x1c4e1d0) …
```
> p2p/test: fix Switch test race condition

- CHANGELOG_PENDING.md
- libs/os/os.go
- mempool/clist_mempool.go
- mempool/doc.go
- mempool/mempool.go
- mock/mempool.go
- node/node.go
allow ReapX and CheckTx functions to run in parallel, making it not possible to block certain proposers from creating a new block.
Closes: #2972
> mempool: allow ReapX and CheckTx functions to run in parallel

- CHANGELOG_PENDING.md
- abci/example/example_test.go
- types/evidence.go
- types/evidence_test.go
- types/protobuf_test.go
Removed header from phantom validator evidence as it is unnecesasry because each node will need to retrieve their own header at that height in order to verify that there actually was a phantom validator
Closes: #4867
> evidence: remove header from phantom evidence

- consensus/state.go
Refs #3406
cs.Logger is protected by a global mutex, so it cannot be a reason for
the halt in #3401.
> consensus: bring back log.Error statement

- types/validator_set_test.go
These test cases are extremely slow when running with the race detector, often taking more that 2 minutes on my local machine. I can easily see them timing out on the much slower CI machines, causing these failures:
```
panic: test timed out after 5m0s
goroutine 234 [running]:
testing.(*M).startAlarm.func1()
/usr/local/go/src/testing/testing.go:1460 +0x11c
created by time.goFunc
/usr/local/go/src/time/sleep.go:168 +0x52
goroutine 1 [chan receive, 4 minutes]:
testing.(*T).Run(0xc000172c60, 0x107a5a2, 0x22, 0x11bfc68, 0x1)
/usr/local/go/src/testing/testing.go:1044 +0x699
testing.runTests.func1(0xc000172c60)
/usr/local/go/src/testing/testing.go:1285 +0xa7
testing.tRunner(0xc000172c60, 0xc00012bcc8)
/usr/local/go/src/testing/testing.go:992 +0x1ec
testing.runTests(0xc00000e2c0, 0x1901500, …
```
> types/test: remove slow test cases in TestValSetUpdatePriorityOrderTests

- rpc/client/event_test.go
Mitigates race condition causing these test failures:
```
=== RUN   TestTxEventsSentWithBroadcastTxAsync
=== RUN   TestTxEventsSentWithBroadcastTxAsync/*http.HTTP
I[2020-05-25|12:29:08.477] Starting WSEvents service                    impl=WSEvents
TestTxEventsSentWithBroadcastTxAsync/*http.HTTP: event_test.go:124: 
Error Trace:	event_test.go:124
Error:      	Expected nil, but got: &errors.errorString{s:"timed out waiting for event"}
Test:       	TestTxEventsSentWithBroadcastTxAsync/*http.HTTP
Messages:   	0: timed out waiting for event
```
> rpc/test: wait for subscription in TestTxEventsSentWithBroadcastTxAsync

- .github/workflows/lint.yaml
- .github/workflows/net.yml
- .github/workflows/proto.yml
- .github/workflows/tests.yml
Add Timeouts to Github action jobs. The goal of adding timeouts is so if a job is hanging on something it gets killed and the author will get notified. 
I picked these times based on previous circle and Github action times then doubled & in some places tripled the times. 
Closes: #XXX
> ci: add timeouts

- CONTRIBUTING.md
Updates our development and release process to match the process outlined in #4860. 
Also elaborates on a few git/Github conventions that we've discussed in the past.
> CONTRIBUTING: update minor release process

- consensus/common_test.go
- consensus/mempool_test.go
attempt to fix #4270, https://github.com/tendermint/tendermint/issues/3897
TestMempoolProgressAfterCreateEmptyBlocksInterval and other tests which
rely on ensureTimeout
> consensus: increase ensureTimeout

- CHANGELOG_PENDING.md
- lite/proxy/proxy.go
- lite/proxy/wrapper.go
- lite2/proxy/routes.go
- lite2/rpc/client.go
- rpc/client/http/http.go
- rpc/client/interface.go
- rpc/client/local/local.go
- rpc/client/mock/client.go
- rpc/client/rpc_test.go
* Adds [`BlockByHash`](https://docs.tendermint.com/master/rpc/#/Info/block_by_hash) to supported rpc Client methods. 
Ethermint currently has to maintain a map `height`-> `block hash` on the store (see [here](https://github.com/ChainSafe/ethermint/blob/03de80b68eba37da6421b133dec57f4fd0704d78/x/evm/keeper/keeper.go#L58-L81)) as it needs to expose the [`eth_getBlockByHash`](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getblockbyhash) JSON-RPC query for Web3 compatibility. This query is currently not supported by the tendermint RPC client.
> rpc: add BlockByHash to supported methods

- cmd/tendermint/commands/lite.go
- lite2/rpc/client.go
Closes #4837
- `/block_results`
before:
failed to update light client to 7: failed to obtain the header #7: signed header not found
after:
We can't return the latest block results because we won't be able to
prove them. Return the results for the previous block instead.
- /block_results?height=X`
no changes
> lite2: correctly return the results of the "latest" block

- consensus/common_test.go
- consensus/state_test.go
I've taken out the timer aspect and now it just waits on a channel for an event to occur. To be honest I wasn't exactly sure what the test was testing, there seemed to be more involved than making sure that it starts the next height but I found that it wasn't so clearly commented so I tried to add a few extra comments in.  
Closes: #XXX
> consensus: fix startnextheightcorrectly test

- docs/tendermint-core/running-in-production.md
See e.g. https://github.com/tendermint/tendermint/issues/4925#issuecomment-637929251 for people getting hit by this. Should we document it elsewhere as well?
> docs: document open file limit in production guide

- CHANGELOG_PENDING.md
- types/evidence.go
Add json tags to duplicate evidence 
Closes: #4958
> evidence: json tags for DuplicateVoteEvidence

- types/validator_set.go
Removes code duplication when checking `commit.Height` and `commit.BlockID`.
> types: Remove duplicated validation in VerifyCommit

- CHANGELOG_PENDING.md
- light/rpc/client.go
- mempool/clist_mempool.go
- node/node.go
- proxy/app_conn.go
- rpc/client/http/http.go
- rpc/client/interface.go
- rpc/client/local/local.go
- rpc/client/mock/client.go
- rpc/client/rpc_test.go
- rpc/core/env.go
- rpc/core/mempool.go
- rpc/core/routes.go
- rpc/core/types/responses.go
- rpc/swagger/swagger.yaml
`/check_tx?tx=X` checks the transaction without executing it. The transaction won't be added to the mempool either.
Closes #4549
> rpc: add /check_tx endpoint

- .github/workflows/tests.yml
- store/store.go
The binaries are cached using `github.head_ref` as a key; this is e.g. the branch name, so the binary will be built on the first run and then the cached version reused for all subsequent builds. This broke tests on e.g. #5058 since the cached binary has a bug that was fixed in a later commit, but the cached version used for tests still had the bug. Changing to `github.sha` makes sure the cache is only valid for the current commit.
> tests: use github.sha in binary cache key

- abci/example/kvstore/kvstore.go
- abci/example/kvstore/persistent_kvstore.go
- consensus/replay_file.go
- go.mod
- go.sum
- light/store/db/db.go
- node/node.go
- p2p/trust/store_test.go
- state/state_test.go
- state/store.go
- state/store_test.go
- state/tx_filter_test.go
- state/txindex/kv/kv.go
- state/txindex/kv/kv_test.go
- store/store.go
- store/store_test.go
Noticed while working on this that we've disabled the `errcheck` lint, which made it hard to find and fix all the instances since enabling it threw a ton of unrelated warnings. Maybe we should enable it and clean up the code base?
> deps: bump tm-db to 0.6.0

- README.md
- Vagrantfile
- docs/guides/go.md
- go.mod
- test/docker/Dockerfile
since 0.34 is breaking we should bump the go version to 1.14
Closes: #XXX
> bump go version

- README.md
Assuming we don't use Riot anymore.
> README: update chat link with Discord instead of Riot

- evidence/pool.go
Fixes #5098.
Is this out in a public release? If so, I'll add a changelog entry as well, for backporting.
> evidence: fix data race in Pool.updateValToLastHeight()

- docs/app-dev/subscribing-to-events-via-websocket.md
Whilst traipsing around the websocket side of tendermint to try setup an event I felt that this page could include a little more detail into how to set up a websocket connection and subscribe to messages. (Some of this information is duplicated here: https://docs.tendermint.com/master/rpc/)
Also I noticed that we provide a link to all the events that someone can subscribe to but just for the ValidatorSetUpdates do we provide more info - I was wondering if we should do the same for the others?
> docs: added further documentation to the subscribing to events page

- CHANGELOG_PENDING.md
- state/execution.go
- types/event_bus.go
- types/event_bus_test.go
- types/events.go
- types/events_test.go
Closes: #5092 
At the moment it is a simple query tm.event="NewEvidence" to get any new evidence. This is fired when a block is committed and there is evidence in the block. 
Made some unit tests - no full integration tests yet
The event also returns the height that the evidence was committed on the block. I thought this might be helpful but may not be necessary
> evidence: new evidence event subscription

- docs/tendermint-core/light-client-protocol.md
Updates the docs for the website to be a little bit clearer on how to run a light client, which is, I suspect, what most people will be looking for.
> docs: tweak light client documentation

- .github/workflows/lint.yaml
bump version of ci linter. 1.27 is not supported anymore
Closes: #XXX
> ci: bump linter version

- rpc/jsonrpc/server/http_uri_handler.go
this log message was marked as not useful and in the issue it was proposed to move it to debug. I am going with this path for now. After we have refactored the logger we shold go through the codebase in order to clean our log statements. 
Closes: #2101
> jsonrpc: change log to debug

- CHANGELOG_PENDING.md
- rpc/jsonrpc/server/http_json_handler.go
- rpc/jsonrpc/server/http_json_handler_test.go
- rpc/jsonrpc/server/http_server.go
- rpc/jsonrpc/server/http_server_test.go
- rpc/jsonrpc/server/http_uri_handler.go
...rrayHTTP 
Closes #5135
Also, wrote a test for WriteRPCResponseHTTPError and used it with correct status codes according to https://www.jsonrpc.org/historical/json-rpc-over-http.html#response-codes
> rpc/jsonrpc/server: merge WriteRPCResponseHTTP and WriteRPCResponseAr

- version/version.go
Bumps the Tendermint version to 0.34.0, and debumps the P2P and block protocol numbers since 0.33.6 has:
```go
// P2PProtocol versions all p2p behaviour and msgs.
// This includes proposer selection.
P2PProtocol Protocol = 7 
// BlockProtocol versions all block data structures and processing.
// This includes validity of blocks and state updates.
BlockProtocol Protocol = 10
```
> version: bump version numbers

- CHANGELOG.md
Bumps 0.34.0-rc2 - rc1 must be pulled due to premature checksum recorded on sum.golang.org.
> changelog: bump to 0.34.0-rc2

- CHANGELOG_PENDING.md
- UPGRADING.md
- types/protobuf.go
Some of the evidence types weren't updated to match the changes. Such updates included:
- Removing mock evidence (we don't use that anymore)
- Adding amnesia evidence
- Removing potential amnesia evidence (this should never be committed on the chain)
> abci: fix abci evidence types

- evidence/pool.go
- evidence/reactor.go
Currently if adding evidence returns an error we log it and exit out of the Receive message in the evidence reactor. If the evidence sent was faulty we `StopPeerForError`, however, even for other errors like not having the block because we pruned, we still return an error and stop checking the rest of the evidence in the message. This PR changes that.
I've also replaced `ErrInvalidEvidence` because we already have a similar area used in the types package
> evidence: don't stop evidence verification if one fails

- .circleci/config.yml
Added GOARCH: arm64 with GOOS: linux, for releasing Linux/ARM64 binary
release for tendermint.
Signed-off-by: odidev <odidev@puresoftware.com>
Closes: #5157
> Added ARM64 in GOARCH for Linux/ARM64 binary release

- CHANGELOG_PENDING.md
- crypto/secp256k1/secp256k1.go
- crypto/secp256k1/secp256k1_test.go
This Pr changes `GenPrivKeySecp256k1` to `GenPrivKeyFromSecret` to be consistent with the other keys. Also the previous name was not descriptive on what it did.
Closes: #XXX
> crypto: consistent api across keys

- CHANGELOG_PENDING.md
- libs/rand/random.go
changes `Str()` in `libs/rand/random.go` file.
If someone invoke this method with an unexpected argument, e.g. `rand.Str(0)`, an out of memory error occurs.
It takes me hours to finally figure it out, because I write this line in my program:
```
str := rand.Str(rand.Intn(32768))
```
After this pull request, if the argument is less or equals to 0, an empty string will be returned, instead of an out-of-memory error.
> libs/rand: fix "out-of-memory" error on unexpected argument

- CONTRIBUTING.md
When doing a release the former rc branch should be deleted as the content of the branch is now on the release branch. After a release is made a new RC branch should be created. 
Closes: #XXX
> contributing: add steps for adding and removing rc branches

- CHANGELOG_PENDING.md
- node/node.go
- state/state_test.go
- state/store.go
Fixes #5138. I don't have a strong opinion on this, but find it sort of odd that `Load` functions actually save as well.
> state: don't save genesis state in database when loaded

- CHANGELOG_PENDING.md
- UPGRADING.md
- consensus/replay.go
Followup from #5227. Instead of checking `ResponseInitChain.app_hash` against the genesis doc app hash, we instead replace it. We should probably remove the genesis doc app hash completely, and rely solely on the one from `InitChain`, I'll open a separate issue to discuss this.
> consensus: don't check InitChain app hash vs genesis app hash, replace it

- CHANGELOG_PENDING.md
- consensus/state.go
- crypto/crypto.go
- crypto/ed25519/ed25519.go
- crypto/ed25519/ed25519_test.go
- crypto/internal/benchmarking/bench.go
- crypto/secp256k1/secp256k1_cgo.go
- crypto/secp256k1/secp256k1_nocgo.go
- crypto/secp256k1/secp256k1_nocgo_test.go
- crypto/secp256k1/secp256k1_test.go
- crypto/sr25519/pubkey.go
- crypto/sr25519/sr25519_test.go
- p2p/conn/secret_connection.go
- rpc/client/evidence_test.go
- tools/tm-signer-harness/internal/test_harness.go
- types/evidence.go
- types/proposal_test.go
- types/protobuf_test.go
- types/validator_set.go
- types/vote.go
- types/vote_test.go
This PR aims to make the crypto.PubKey interface more intuitive. 
Changes: 
- `VerfiyBytes` -> `VerifySignature`
Before `Bytes()` was amino encoded, now since it is the byte representation should we get rid of it entirely?
EDIT: decided to keep `Bytes()` as it is useful if you are using the interface instead of the concrete key
Closes: #XXX
> crypto: API modifications

- CHANGELOG.md
Wasn't added when the release was made, so adding now.
> changelog: add v0.33.8 from release

- CHANGELOG_PENDING.md
- blockchain/v0/reactor.go
- blockchain/v1/reactor.go
- blockchain/v2/reactor.go
- blockchain/v2/scheduler.go
- blockchain/v2/scheduler_test.go
Blockchain reactors were not updated to handle arbitrary initial height after #5191.
> blockchain: fix fast sync halt with initial height > 1

- .github/workflows/linkchecker.yml
- docs/architecture/adr-047-handling-evidence-from-light-client.md
This update comes from conversations with informal and is derived from their [work](https://github.com/informalsystems/tendermint-rs/tree/master/docs/spec/lightclient/detection).
In addendum, I would also like to move the evidence definitions from this ADR (I think they are a bit too much fat for this ADR)
- Equivocation is already known and should be documented elsewhere (in the spec)
- Lunatic Evidence (is new but should either receive it's own ADR or be in the spec)
- Amnesia Evidence already has it's own ADR - ADR 56
> light: update ADR 47 with light traces

- docs/introduction/architecture.md
This PR makes Tendermint Architectural Overview not visible mainly because there are todos and it duplicates some information. 
Closes: #XXX
> docs: dont display duplicate 

- .github/workflows/net.yml
- DOCKER/README.md
- Makefile
Ci handles localnet-start differently. To remedy the situation, reverting docker cmd updates is the short term situation. We will have to change a few things to make it work as we would like. 
Closes: #XXX
> ci: fix net pipeline

- codecov.yml
Currently, for ci testing, we upload the code coverage reports individually across multiple machines. Once codecov receives one report it sends a notification in the form of a comment on the pull request. This comment does not contain the full report from all the tests therefore causing inaccurate reports. This PR aims at delaying the codecov notification till at least 4 reports have been uploaded, reducing noise.
Closes: #XXX
> ci: delay codecov notification 

- config/config.go
make state sync trust period consistent with the default in the `tendermint light` cmd
Closes: #XXX
> config: trust period consistency

- CHANGELOG_PENDING.md
- light/provider/http/http.go
- types/validator_set.go
- types/validator_set_test.go
Created `ValidatorSetFromExistingValidators` which restores a validator set (without incrementing priorities) from an array of validators.
Closes: #5306
@erikgrinaker is it possible to see if this fixes your problem
> fix validator set proposer priorities in light client provider

- CHANGELOG_PENDING.md
- statesync/stateprovider.go
Fixes #5295. Requires #5307 as well.
> statesync: fix valset off-by-one causing consensus failures

- CHANGELOG_PENDING.md
- UPGRADING.md
- cmd/tendermint/commands/run_node.go
- config/config.go
- config/toml.go
- docs/tendermint-core/configuration.md
- node/node.go
- rpc/core/dev.go
- rpc/core/doc.go
- rpc/core/routes.go
also, remove `/unsafe_start_cpu_profiler`, `/unsafe_stop_cpu_profiler`
and `/unsafe_write_heap_profile` in favor of pprof server functionality.
Closes #5303
> config: rename prof_laddr to pprof_laddr and move it to rpc

- CHANGELOG_PENDING.md
- statesync/reactor.go
On startup, the peer-to-peer stack may have peers connected before the state sync process begins, causing these to not trigger `AddPeer` events and thus not be used for snapshot discovery. Broadcasting a snapshot request to these explicitly makes sure we discover snapshots from existing peers as well.
> statesync: broadcast snapshot request to all peers on startup

- consensus/metrics.go
- consensus/state.go
Part of the issue is to add metrics to the websocket connection. It seems this would require some moving around of things in the node pkg. I opted to not make this change now, and wait for when we do a node pkg refactor. 
If someone disagrees with this appraoch please let me know, I can attempt to get metrics into the rpc layer.
There is not a need to update documentation as it already states this metric is a histogram..
Closes: #1791
> metrics: switch from gauge to histogram

- .github/CODEOWNERS
Per conversation in Slack, we'd like to experiment with a little more rigor before merging PRs. One thing we'll try is by actually utilizing Github's CODEOWNERS featuer. This PR serves as a proposal for changes to _who_ is responsible for _what_.
Note that we intend to eventually require sign-off from code owners on PRs before they're merged. But as a first step, we'll start by just designating code owners for various files and directories, and it will be up to PR authors to check that the expected code owners have been requested for review. 
A few notes on who is responsible for what:
* There are four global codeowners (@ebuchman, @erikgrinaker, @melekes and @tessr) who are the codeowners for any file/directory that isn't more precisely specified. 
* @marbar3778 is an additional …
> CODEOWNERS: specify more precise codeowners

- docs/tendermint-core/using-tendermint.md
Add a sentence on `initial_height`.
There will be a section in the spec repo explaining the genesis more in depth as this is something that will affect both clients
Closes: #XXX
> docs: add more description to initial_height

- docs/rfc/README.md
Hide the RFC section from the docs website. 
Closes: #XXX
> docs: make rfc section disppear

- Makefile
This PR adds support for badgerdb, rocksdb and boltdb within the build options. 
RocksDB builds correctly.
```
make build TENDERMINT_BUILD_OPTIONS=rocksdb    
CGO_ENABLED=1 go build -mod=readonly -ldflags "-X github.com/tendermint/tendermint/version.GitCommit=`git rev-parse --short=8 HEAD` -s -w " -trimpath -tags 'tendermint rocksdb' -o build/tendermint ./cmd/tendermint/
tendermint on  master [$!] via 🐹 v1.15.2 took 19s 
```
Closes: #5355
> makefile: add options for other DBs

- rpc/openapi/openapi.yaml
> rpc: fix openapi spec syntax error

- UPGRADING.md
Adding a section explaining the state store interface change. I wasn't aware this was used externally. Our infamous API strikes again.
Closes: #XXX
> upgrading: state store change

- mempool/reactor_test.go
found out this issue when trying to decouple mempool reactor with its
underlying clist implementation.
according to its comment, the test `TestReactorNoBroadcastToSender` is
intended to make sure that a peer shouldn't send tx back to its origin.
however, the current test forgot to init peer state key, thus the code
will get stuck at waiting for peer to catch up state *instead of* skipping
sending tx back, therefore the test passes by accident:
https://github.com/tendermint/tendermint/blob/b8d08b9ef448365695de19fea0156e1c8611ae7b/mempool/reactor.go#L216-L226
this PR fixes the issue by init peer state key.
> mempool/reactor: fix reactor broadcast test

- .clang-format
- .github/workflows/proto.yml
- .vscode/settings.json
- Makefile
- proto/tendermint/abci/types.proto
- proto/tendermint/evidence/types.proto
- proto/tendermint/types/evidence.proto
- proto/tendermint/types/types.proto
Add a cmd to docker image and use it to format our proto files. This avoids developers the need to install clang-format
Closes: #XXX
> ux: use docker to format proto files

- CHANGELOG_PENDING.md
- abci/client/socket_client.go
This caused the node to crash whenever any state sync-related request was called via the ABCI UNIX socket client.
> abci: fix socket client error for state sync responses

- CHANGELOG_PENDING.md
- config/config.go
- config/toml.go
- node/node.go
- statesync/reactor.go
- statesync/syncer.go
Reduces the state sync discovery time from 20 to 15 seconds, and makes it configurable.
> config: add state sync discovery_time setting

- UPGRADING.md
This change adds some polish to the upgrading instructions for 0.34. The only substantive changes include:
* Calling out ABCI-impacting changes explicitly in the "ABCI Changes" section, even if those changes are also mentioned elsewhere
* Removes `ProofOfTrialPeriod` from consensus params; this change was introduced and then removed.
> UPGRADING: polish upgrading instructions for 0.34

- CHANGELOG.md
- CHANGELOG_PENDING.md
I set the next release on the CHANGELOG_PENDING to rc5, even though I hope our next set of changes goes into 0.34.1.
> CHANGELOG: update for 0.34.0-rc4

- README.md
- cmd/tendermint/commands/debug/debug.go
- cmd/tendermint/commands/debug/dump.go
- cmd/tendermint/commands/lite.go
- cmd/tendermint/commands/reset_priv_validator.go
- cmd/tendermint/commands/root.go
- cmd/tendermint/commands/run_node.go
- cmd/tendermint/commands/testnet.go
- light/detector.go
Minor PR made whilst testing light client. Home directory of the light client is set relative to where the cmd was done whereas the tendermint node cmd uses an absolute home path so made this the same with the light client. In addition, made all the flag descriptions lower-case and lowered the log level of some of the light client calls which were unnecessary.
> cli: light home dir should default to where the full node default is

- blockchain/msgs.go
- blockchain/v0/reactor.go
- blockchain/v1/reactor.go
- blockchain/v2/reactor.go
- blockchain/v2/scheduler.go
- blockchain/v2/scheduler_test.go
- types/validator_set.go
When we run `BlockFromProto()` we also run validate basic on the converted block as part of the output. This is done twice: in `ValidateMsg` and when receiving `BlockResponse`. This PR removes the check in `ValidateMsg`.
> blockchain: remove duplication of validate basic

- mempool/reactor.go
- mempool/reactor_test.go
previously, the second next could return nil, which would be the reason
for panic on line 275:
memTx := next.Value.(*mempoolTx)
Closes #5408
> mempool: fix nil pointer dereference

- CHANGELOG_PENDING.md
- privval/signer_dialer_endpoint.go
Required for #5291 to set timeouts for remote signers.
> privval: allow passing options to NewSignerDialerEndpoint

- CHANGELOG_PENDING.md
- config/toml.go
Required for #5291, to generate configuration files with state sync RPC servers.
> config: set statesync.rpc_servers when generating config file

- .circleci/config.yml
- .github/workflows/docker.yml
Removes docker deployment from circleci and adds it to GA. This also aims to deploy rc tags
how it looks:
> ci: docker remvoe circleci and add github action

- docs/architecture/adr-056-light-client-amnesia-attacks.md
- docs/architecture/adr-056-proving-amnesia-attacks.md
This is to reflect the notion that a more well-thought protocol for amnesia accountability will need to be created in the long term future but for now 0.34 will only include the light detector algorithm and thus will be able to detect but not punish amnesia attacks.
I have also included in the appendix a more detailed description of how an amnesia attack would work.
> docs: revise ADR 56, documenting short term decision around amnesia evidence 

- CHANGELOG.md
I forgot to add the date when we cut 0.33.5. This fixes that. It also fixes a header indentation issue for 0.33.8.
> changelog: add missing date to v0.33.5 release, fix indentation

- test/e2e/tests/app_test.go
- test/e2e/tests/block_test.go
- test/e2e/tests/e2e_test.go
- test/e2e/tests/validator_test.go
Partial fix for #5291.
This adds a basic set of test cases for core network invariants. Although small, it is sufficient to replace and extend the current set of P2P tests. Further test cases can be added later.
> test: add basic end-to-end test cases

- CHANGELOG.md
Backport changelog fixes from #5454 for the RC.
> changelog: add missing date to v0.33.5 release, fix indentation (#5454)

- crypto/encoding/codec.go
In blocks_results we use the proto definition of abciResponses: https://github.com/tendermint/tendermint/blob/2672b91ab099b8b02f3afabae4a0a745acd93c3f/rpc/core/blocks.go#L152-L155, this leads to the use of the proto definition of the pubkey which is an interface in go (oneof). The interface must be registered with the JSON encoder to have it work correctly.
A clearer divide between proto types and native types is needed.
Closes: #XXX
> fix RPC blockresults reutrn

- .github/workflows/e2e.yml
avoid running e2e jobs when not needed
Closes: #XXX
> ci/e2e: avoid running job when no go files are touched

- docs/versions
This PR changes the order of docs versions in order to have master as the default version.
Closes: #5472
> docs: set master as default version

- mempool/clist_mempool.go
- mempool/mempool.go
- types/tx.go
- use append within function parameter instead of passing two parameters
Closes: #XXX
> tx: reduce function to one parameter

- .github/workflows/e2e.yml
Renames the E2E job `e2e-test`, since Github often lists jobs without the workflow name.
> github: rename e2e jobs

- CONTRIBUTING.md
We've been cutting a lot of RCs lately, and I wanted to include our process for that in our flows.
> contributing: include instructions for a release candidate

- CHANGELOG_PENDING.md
- statesync/stateprovider.go
> statesync: check all necessary heights when adding snapshot to pool

- CHANGELOG_PENDING.md
- types/block.go
rename json `parts` to `part_set_header`
Closes: #5522 
this should be backported as well
> types: rename json parts to part_set_header

- CHANGELOG_PENDING.md
- abci/client/grpc_client.go
> abci/grpc: return async responses in order (#5520)

- test/e2e/generator/generate.go
When #5499 and #5530 land, we can re-enable v2 in the E2E testnet generator (and thus the nightly E2E tests).
> test: enable blockchain v2 in E2E testnet generator

- CHANGELOG_PENDING.md
- consensus/state.go
Fixes #5422. That turned out to be a whole lot easier than expected.
> consensus: open target WAL as read/write during autorepair

- test/e2e/generator/generate.go
- test/e2e/networks/ci.toml
When #5536 lands we can re-enable restart/kill perturbations in E2E tests.
> test: enable restart/kill perturbations in E2E tests

- CHANGELOG_PENDING.md
- blockchain/v2/processor.go
- blockchain/v2/reactor.go
- blockchain/v2/routine.go
- blockchain/v2/scheduler.go
- blockchain/v2/scheduler_test.go
When a peer is stopped due to some network issue, the Reactor calls scheduler#handleRemovePeer, which removes the peer from the scheduler. BUT the peer stays in the processor, which sometimes could lead to "duplicate block enqueued by processor" panic WHEN the same block is requested by the scheduler again from a different peer. The solution is to return scPeerError, which will be propagated to the processor. The processor will clean up the blocks associated with the peer in purgePeer.
Closes #5513, #5517
> blockchain/v2: fix "panic: duplicate block enqueued by processor"

- blockchain/v1/reactor.go
- blockchain/v1/reactor_fsm.go
- blockchain/v1/reactor_fsm_test.go
Add simple `NoBlockResponse` handling to blockchain reactor v1. I tested before and after with erik's e2e testing and was not able to reproduce the inability to sync after the changes were applied
Closes: #5394
Backport of #5401.
> blockchain/v1: add noBlockResponse handling  (#5401)

- abci/client/grpc_client.go
Fixes #5540, fixes #2965. This is a hack that patches over the problem, but really the whole async handling in gRPC should be redesigned, as should ReqRes callback dispatch.
> abci/grpc: fix ordering of sync/async callback combinations

- state/tx_filter_test.go
- types/block.go
- types/block_test.go
MaxCommitSigSize should be 109 bytes instead of 77 (Signature is 64 instead of 32)
will back port this also into rc-6
Closes: #5564
> fix max commit sig size

- test/e2e/generator/generate.go
- test/e2e/pkg/testnet.go
- test/e2e/runner/main.go
- test/e2e/runner/start.go
- test/e2e/runner/wait.go
In #5488 the E2E testnet generator changed to setting explicit `StartAt` heights for initial nodes. This broke the runner, which expected all initial nodes to have `StartAt: 0`, as well as validator set scheduling in the generator. Testnet loading now normalizes initial nodes to have `StartAt: 0`.
This also tweaks waiting for misbehavior heights to only use an additional wait if there actually is any misbehavior in the testnet, and to output information when waiting.
> test: fix handling of start height in generated E2E testnets

- test/e2e/generator/generate.go
- test/e2e/networks/ci.toml
Disables misbehaviors in E2E testnets due to failures caused by #5554 and #5560. Should be re-enabled once these are fixed.
> test: disable E2E misbehaviors due to bugs

- types/block.go
- types/test_util.go
MakeBlock was housed in the `test_util.go` file but used in the state package in a production path: https://github.com/tendermint/tendermint/blob/80b9eb8f0f7ee57753534b0ee14cbc22755669b5/state/state.go#L244, this pr moves the function out of test_utils into block.go. While an unneeded change it can cause confusion to why a test_util is used in production. 
Closes: #XXX
> types: move `MakeBlock` to block.go

- CHANGELOG_PENDING.md
- consensus/state.go
- evidence/pool.go
- evidence/pool_test.go
- evidence/reactor.go
- evidence/reactor_test.go
- evidence/verify.go
Backports two commits related to evidence:
- evidence: don't gossip consensus evidence too soon (#5528)
- evidence: don't send committed evidence and ignore inbound evidence that is already committed (#5574)
> evidence: backport evidence fixes regarding gossiping

- docs/architecture/adr-061-p2p-refactor-scope.md
[Rendered](https://github.com/tendermint/tendermint/blob/erik/adr-p2p-refactor/docs/architecture/adr-061-p2p-refactor-scope.md)
This summarizes recent discussions on the scope of the upcoming P2P refactor.
> docs: add ADR on P2P refactor scope

- test/e2e/generator/generate.go
- test/e2e/networks/ci.toml
- test/e2e/pkg/testnet.go
- test/e2e/runner/cleanup.go
- test/e2e/runner/main.go
- test/e2e/runner/start.go
- test/e2e/tests/app_test.go
- test/e2e/tests/block_test.go
- test/e2e/tests/validator_test.go
Backport of #5576.
* Don't use state sync for nodes starting at initial height.
* Also remove stopped containers when cleaning up.
* Start nodes in order of startAt, mode, name to avoid full nodes starting before their seeds.
* Tweak network waiting to avoid halts caused by validator changes and perturbations.
* Disable most tests for seed nodes, which aren't always able to join consensus.
* Disable `blockchain/v2` due to known bugs.
> test: fix various E2E test issues (#5576)

- blockchain/v2/reactor.go
- blockchain/v2/scheduler.go
- blockchain/v2/scheduler_test.go
after they were pruned by the scheduler
Closes #5513
> blockchain/v2: remove peers from the processor  (#5607)

- CHANGELOG.md
- CHANGELOG_PENDING.md
Note that this also deletes everything from CHANGELOG_PENDING that was included in RC6.
> CHANGELOG: update to reflect v0.34.0-rc6

- rpc/core/evidence.go
- rpc/openapi/openapi.yaml
`broadcast_evidence`, like `broadcast_tx`, should not be part of the Info group but should reside in the `Evidence` tab that we especially allocated for it.
NOTE: Not too sure if this is actually the way to fix it
> move broadcast_evidence rpc call from info to evidence

- scripts/linkify_changelog.py
Our changelog entries usually reference PRs rather than issues; this script makes the links default to the more common choice.
> scripts: make linkifier default to 'pull' rather than 'issue'

- CHANGELOG.md
- CHANGELOG_PENDING.md
"Squashes" the changelog from RCs 2-6 into one changelog message for 0.34.0, and adds the changelog pending.
> changelog: squash changelog from 0.34 RCs into one

- .goreleaser.yml
This updates the goreleaser tooling to build the same binaries that were built for the 0.34.0 release.
> .goreleaser: add windows, remove arm (32 bit)

- CHANGELOG_PENDING.md
- blockchain/v1/peer.go
- blockchain/v1/pool.go
- blockchain/v1/reactor_fsm.go
- blockchain/v1/reactor_fsm_test.go
Closes #5444
Now we record the fact that a peer does not have a requested block and later use this information to make a new request for the same block from another peer.
> blockchain/v1: handle peers without blocks

- CHANGELOG_PENDING.md
- crypto/secp256k1/secp256k1.go
This caused stack overflow panics in E2E tests, e.g.:
```
2020-11-24T02:37:17.6085640Z [35mvalidator04    |[0m runtime: goroutine stack exceeds 1000000000-byte limit
2020-11-24T02:37:17.6087818Z [35mvalidator04    |[0m runtime: sp=0xc0234b23c0 stack=[0xc0234b2000, 0xc0434b2000]
2020-11-24T02:37:17.6088920Z [35mvalidator04    |[0m fatal error: stack overflow
2020-11-24T02:37:17.6089776Z [35mvalidator04    |[0m
2020-11-24T02:37:17.6090569Z [35mvalidator04    |[0m runtime stack:
2020-11-24T02:37:17.6091677Z [35mvalidator04    |[0m runtime.throw(0x12dc476, 0xe)
2020-11-24T02:37:17.6093123Z [35mvalidator04    |[0m 	/usr/local/go/src/runtime/panic.go:1116 +0x72
2020-11-24T02:37:17.6094320Z [35mvalidator04    |[0m runtime.newstack()
2020-11-24T02:37:17.6095374Z [35mvalidator04 …
```
> crypto: fix infinite recursion in Secp256k1 string formatting (#5707)

- README.md
The readme was linking to the Cosmos blog, while we post most of our articles in the Tendermint blog.
> README: update link to Tendermint blog

- .github/workflows/coverage.yml
- .github/workflows/docker.yml
- .github/workflows/e2e-nightly.yml
- .github/workflows/e2e.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- consensus/invalid_test.go
- consensus/mempool_test.go
- consensus/replay_test.go
- consensus/wal_test.go
- p2p/conn/connection_test.go
- p2p/conn/secret_connection_test.go
- p2p/pex/addrbook_test.go
- p2p/pex/pex_reactor_test.go
- p2p/trust/store_test.go
Replace defer with t.Cleanup().
Replace the combination of ioutil.TempDir, error checking
and defer os.RemoveAll() with Go testing.T's new TempDir()
helper.
Mark auxiliary functions as test helpers.
> use Cleanup(),TempDir() in test cases

- consensus/replay_test.go
Replace testing.T.Cleanup() with deferred function
calls in test helpers as those cleanup functions
need to be called once the helper returns and not
when the entire test ends.
This reverts a few of the changes introduced in #5723.
Thanks: @erikgrinaker for pointing this out.
Ref: #5732
> consensus: fix flaky tests

- blockchain/v0/reactor.go
- blockchain/v2/reactor.go
- consensus/reactor.go
- mempool/reactor.go
- p2p/pex/pex_reactor.go
- statesync/reactor.go
- test/maverick/consensus/reactor.go
After a reactor has failed to parse an incoming message, it shouldn't output the "bad" data into the logs, as that data is unfiltered and could have anything in it. (We also don't think this information is helpful to have in the logs anyways.)
> reactors: omit incoming message bytes from reactor logs

- go.mod
- go.sum
Bump version to get performance updates:
```
benchmark                    old ns/op     new ns/op     delta
BenchmarkVerification-8      174857        78376         -55.18%
```
Closes: #XXX
> dep: bump ed25519consensus version

- CHANGELOG_PENDING.md
- blockchain/doc.go
- blockchain/v0/pool.go
- blockchain/v0/reactor.go
- blockchain/v2/io.go
- blockchain/v2/reactor.go
Closes: https://github.com/tendermint/tendermint/issues/5718
> blockchain/v0: relax termination conditions and increase sync timeout

- Makefile
`Makefile` used `git branch --show-current` for branch detection. This option was introduced in Git 2.22. However, the current Debian release (Buster), which is used by the `golang:1.15` Docker image, uses Git 2.20. This gives spurious errors e.g. when running the E2E tests:
```
error: unknown option `show-current'
```
This PR changes the branch detection to be compatible with Git 2.20. The behavior appears to be the same as `git branch --show-current`, both when on a branch, on a tag, and on a detached HEAD.
> Makefile: use git 2.20-compatible branch detection

- README.md
Also adds a slightly modified version of the footer text from the docs website.
> readme: add links to job post

- README.md
- docs/.vuepress/config.js
The Discord refactor broke our invite links. This updates them to a link that takes you to the Cosmos lobby, at least; the direct links to channels are not available in the current configuration.
> readme: update discord links

- networks/local/localnode/Dockerfile
When starting a local net the `--proxy-app` flag is incorrect.
The command is outlined here => [run_node.go](https://github.com/tendermint/tendermint/blob/master/cmd/tendermint/commands/run_node.go#L46)
- `make build`
- `make localnet-start`
> localnet: fix node starting issue with --proxy-app flag

- CHANGELOG_PENDING.md
- config/config.go
- config/toml.go
- docs/nodes/configuration.md
- mempool/clist_mempool.go
- mempool/clist_mempool_test.go
When set to `true`, an invalid transaction will be kept in the cache (this may help some applications to protect against spam). 
NOTE: this is a temporary config option. The more correct solution would be to add a TTL to each transaction (i.e. CheckTx may return a TTL in ResponseCheckTx).
Closes: #5751
> mempool: introduce KeepInvalidTxsInCache config option

- CHANGELOG_PENDING.md
- config/config.go
- config/toml.go
- docs/tendermint-core/configuration.md
- mempool/clist_mempool.go
- mempool/clist_mempool_test.go
When set to true, an invalid transaction will be kept in the cache (this may help some applications to protect against spam).
NOTE: this is a temporary config option. The more correct solution would be to add a TTL to each transaction (i.e. CheckTx may return a TTL in ResponseCheckTx).
Closes: #5751
> mempool: introduce KeepInvalidTxsInCache config option (#5813)

- CHANGELOG_PENDING.md
- config/config.go
- config/toml.go
- docs/tendermint-core/configuration.md
- mempool/reactor.go
- mempool/reactor_test.go
@p4u from vocdoni.io reported that the mempool might behave incorrectly under a
high load. The consequences can range from pauses between blocks to the peers
disconnecting from this node.
My current theory is that the flowrate lib we're using to control flow
(multiplex over a single TCP connection) was not designed w/ large blobs
(1MB batch of txs) in mind.
I've tried decreasing the Mempool reactor priority, but that did not
have any visible effect. What actually worked is adding a time.Sleep
into mempool.Reactor#broadcastTxRoutine after an each successful send ==
manual control flow of sort.
As a temporary remedy (until the mempool package
is refactored), the max-batch-bytes was disabled. Transactions will be sent
one by one without batching
Closes #5796
> mempool: disable MaxBatchBytes (#5800)

- .github/workflows/lint.yaml
make timeout 8 minutes for golangci. I need to look into why its taking longer in the cleanup stage. Golangci linting is passing but cancelling due to the timeout. 
Closes: #XXX
> ci: make timeout-minutes 8 for golangci

- CHANGELOG_PENDING.md
- UPGRADING.md
- abci/types/messages.go
Migrate ABCI to use `protoio` (uint64 length delimitation) instead of specific int64 length delimiters.
Closes: #5783
> abci: use protoio for length delimitation

- docker-compose.yml
- networks/local/localnode/config-template.toml
This relates to #5805 and changes the port from :9090 to :27000 as :9090 is the default port that the actual prometheus server runs on. 
In order to do this, I have shifted the rpc and p2p ports of the other three nodes down
> localnet: use 27000 port for prometheus

- p2p/transport_memory.go
- p2p/transport_memory_test.go
This should probably have more tests, but I expect the transport layer to change quite a bit before the P2P refactor is done, so we'll add more later.
> p2p: add MemoryTransport, an in-memory transport for testing

- blockchain/v0/reactor.go
- blockchain/v2/reactor.go
- consensus/reactor.go
- evidence/reactor.go
- statesync/reactor.go
- test/maverick/consensus/reactor.go
blockchain/vX reactor priority was decreased because during the normal operation
(i.e. when the node is not fast syncing) blockchain priority can't be
the same as consensus reactor priority. Otherwise, it's theoretically possible to
slow down consensus by constantly requesting blocks from the node.
NOTE: ideally blockchain/vX reactor priority would be dynamic. e.g. when
the node is fast syncing, the priority is 10 (max), but when it's done
fast syncing - the priority gets decreased to 5 (only to serve blocks
for other nodes). But it's not possible now, therefore I decided to
focus on the normal operation (priority = 5).
evidence and consensus critical messages are more important than
the mempool ones, hence priorities are bumped by 1 (from 5 to 6).
statesync reactor priority was changed …
> modify Reactor priorities

- blockchain/v0/reactor.go
- blockchain/v2/reactor.go
- consensus/reactor.go
- evidence/reactor.go
- statesync/reactor.go
- test/maverick/consensus/reactor.go
blockchain/vX reactor priority was decreased because during the normal operation
(i.e. when the node is not fast syncing) blockchain priority can't be
the same as consensus reactor priority. Otherwise, it's theoretically possible to
slow down consensus by constantly requesting blocks from the node.
NOTE: ideally blockchain/vX reactor priority would be dynamic. e.g. when
the node is fast syncing, the priority is 10 (max), but when it's done
fast syncing - the priority gets decreased to 5 (only to serve blocks
for other nodes). But it's not possible now, therefore I decided to
focus on the normal operation (priority = 5).
evidence and consensus critical messages are more important than
the mempool ones, hence priorities are bumped by 1 (from 5 to 6).
statesync reactor priority was changed …
> modify Reactor priorities (#5826)

- abci/README.md
Proto definitions file was moved and link was broken. Fixed as relative link.
> ABCI: Update readme to fix broken link to proto

- tools/tm-signer-harness/internal/test_harness.go
> tools/tm-signer-harness: fix listener leak in newTestHarnessListener()

- abci/client/grpc_client.go
> abci/grpc: fix invalid mutex handling in StopForError()

- CHANGELOG_PENDING.md
- libs/os/os.go
- libs/os/os_test.go
> libs/os: EnsureDir now returns IO errors and checks file type

- p2p/transport.go
- p2p/transport_mconn.go
The old code naïvely concatenated IP and port, which doesn't work for IPv6 addresses where `:` can be part of the IP as well.
> p2p: fix IPv6 address handling in new transport API

- test/e2e/README.md
This should be useful to understand the overall purpose and structure of the end-to-end tests.
> test/e2e: add conceptual overview

- CHANGELOG_PENDING.md
- abci/types/messages.go
- libs/protoio/io.go
- libs/protoio/io_test.go
- libs/protoio/reader.go
- p2p/conn/connection.go
- p2p/conn/connection_test.go
- p2p/conn/secret_connection.go
- p2p/transport_mconn.go
- privval/secret_connection.go
- privval/signer_endpoint.go
Fixes #5866. Inbound traffic monitoring (and by extension inbound rate limiting) was inadvertently removed in 660e72a12f977a9b52659e263d096406b181b2ba.
> p2p: fix MConnection inbound traffic statistics and rate limiting

- libs/os/os.go
#5852 fixed an issue with error propagation in `os.EnsureDir()`. However, this function is basically identical to `os.MkdirAll()`, and can be replaced entirely with a call to it. We keep the function for backwards compatibility.
> os: simplify EnsureDir()

- test/e2e/tests/validator_test.go
E2E tests often fail due to fast sync stalls causing the validator to miss signing blocks. This increases the tolerance for missed signatures to 2/3 to allow validators to spend more time starting up.
> test/e2e: tolerate up to 2/3 missed signatures for a validator

- CHANGELOG_PENDING.md
- evidence/pool.go
- evidence/pool_test.go
Evidence coming from consensus is stored in a temporary buffer before being flushed to the evidence pool and thus halted until the voting in the height of the evidence is finished before being broadcasted and proposed. This avoids the issue of some nodes verifying and proposing evidence at a height where the block hasn't been committed yet which could cause those peers who never saw the double votes to  panic.
> evidence: buffer evidence from consensus

- CHANGELOG_PENDING.md
- state/store.go
- statesync/stateprovider.go
When state syncing, we currently don't save `state.LastHeightConsensusParamsChanged`. This causes it to be set with a value of 0 when it is saved to the state store. `Bootstap()` the function that is called ignores this value
```go
if err := store.saveConsensusParamsInfo(height, height, state.ConsensusParams); err != nil {
return err
}
```
However, state keeps the 0 value meaning at following heights when state is saved, `LastHeightConsensusParamsChanged` is 0
```go
if err := store.saveConsensusParamsInfo(nextHeight,
state.LastHeightConsensusParamsChanged, state.ConsensusParams); err != nil {
return err
}
```
This means that the state store isn't saving the consensus params rather referencing the consensus params at height 0 which don't exist and causes this error to arise when pruning: …
> state sync: last consensus params height is not set

- CHANGELOG_PENDING.md
- evidence/pool.go
- evidence/pool_test.go
- state/store.go
- statesync/stateprovider.go
Backport of #5889 and #5890. Do not squash merge.
> backport: evidence fix and statesync fix

- .github/CODEOWNERS
- go.mod
- go.sum
Backports changes that landed on `master` before the gogoproto update: #5913, #5902, #5897.
> 0.34.3 backports (pre-gogo proto update)

- p2p/peer.go
- p2p/router.go
- p2p/router_test.go
This improves the prototype peer manager by:
* Exporting `PeerManager`, making it accessible by e.g. reactors.
* Replacing `Router.SubscribePeerUpdates()` with `PeerManager.Subscribe()`.
* Tracking address/peer connection statistics, and retrying dial failures with exponential backoff.
* Prioritizing peers, with persistent peers configuration.
* Limiting simultaneous connections.
* Evicting peers and upgrading to higher-priority peers.
* Tracking peer heights, as a workaround for legacy shared peer state APIs.
This is getting to a point where we need to determine precise semantics and implement tests, so we should figure out whether it's a reasonable abstraction that we want to use. The main questions are around the API model (i.e. synchronous method calls with the router polling the …
> p2p: improve PeerManager prototype
